import {ConflictException,Injectable} from '@nestjs/common';
import {PrismaService} from '@ucell/database';
import {randomUUID} from 'node:crypto';
import {AuditService} from '../../common/audit/audit.service';
import {IdempotencyService} from '../../common/idempotency/idempotency.service';
import {PiiCryptoService} from '../../common/security/pii-crypto.service';

export interface DeliveryProfileInput {recipientName:string;phone:string;countryCode:string;postalCode?:string;region:string;city:string;address:string;}
@Injectable()
export class DeliveryProfileService {
 constructor(private readonly db:PrismaService,private readonly idempotency:IdempotencyService,private readonly audit:AuditService,private readonly pii:PiiCryptoService){}
 async get(personId:string){const row=await this.db.deliveryProfile.findFirst({where:{personId,effectiveTo:null},orderBy:{effectiveFrom:'desc'}});if(!row)return {recipientName:null,phone:null,countryCode:null,postalCode:null,region:null,city:null,address:null,complete:false,updatedAt:null};const contact=this.pii.decrypt<{phone:string}>(row.contactCiphertext,row.keyVersion),address=this.pii.decrypt<{region:string;city:string;address:string}>(row.addressCiphertext,row.keyVersion);return {recipientName:row.recipientName,phone:contact.phone,countryCode:row.countryCode,postalCode:row.postalCode,...address,complete:true,updatedAt:row.effectiveFrom.toISOString()};}
 async update(personId:string,input:DeliveryProfileInput,key:string,requestId:string){try{const result=await this.idempotency.execute(`member:delivery-profile:${personId}`,key,input,async tx=>{const now=new Date(),correlationId=randomUUID();await tx.$queryRaw`SELECT true AS locked FROM (SELECT pg_advisory_xact_lock(hashtextextended(${personId},0))) AS lock_row`;const previous=await tx.deliveryProfile.findFirst({where:{personId,effectiveTo:null},orderBy:{effectiveFrom:'desc'}});if(previous)await tx.deliveryProfile.update({where:{deliveryProfileId:previous.deliveryProfileId},data:{effectiveTo:now}});const contact=this.pii.encrypt({phone:input.phone}),address=this.pii.encrypt({region:input.region,city:input.city,address:input.address});if(contact.keyVersion!==address.keyVersion)throw new Error('PII key version changed during transaction');const profile=await tx.deliveryProfile.create({data:{personId,recipientName:input.recipientName,contactCiphertext:contact.ciphertext,countryCode:input.countryCode,postalCode:input.postalCode||null,addressCiphertext:address.ciphertext,keyVersion:contact.keyVersion,effectiveFrom:now}});await this.audit.write(tx,{actorType:'MEMBER',actorId:personId,action:'DELIVERY_PROFILE_VERSION_CREATED',entityType:'DeliveryProfile',entityId:profile.deliveryProfileId,beforeData:{hadProfile:Boolean(previous)},afterData:{complete:true,changedFields:['recipientName','phone','countryCode','postalCode','region','city','address'],keyVersion:profile.keyVersion},requestId,correlationId});await tx.outboxEvent.create({data:{eventType:'DELIVERY_PROFILE_UPDATED',aggregateType:'Person',aggregateId:personId,payload:{schemaVersion:1,personId,deliveryProfileId:profile.deliveryProfileId,complete:true},correlationId}});return {deliveryProfileId:profile.deliveryProfileId,status:'UPDATED' as const,complete:true,updatedAt:now.toISOString()};});return {...result.value,replayed:result.replayed};}catch(error){if(['P2002','P2034'].includes((error as any).code))throw new ConflictException({code:'RETRYABLE_CONFLICT'});throw error;}}
}
