import {ConflictException,Injectable,NotFoundException,UnprocessableEntityException} from '@nestjs/common';
import {PrismaService} from '@ucell/database';
import {createHash,randomUUID} from 'node:crypto';
import {AuditService} from '../../common/audit/audit.service';
import {IdempotencyService} from '../../common/idempotency/idempotency.service';
import {PiiCryptoService} from '../../common/security/pii-crypto.service';

export type FormalDraftInput={formalContractVersionId:string;legalName:string;gender:string;birthDate:string;nationalId:string;communicationAddress:string;phone:string;email:string;bankCode:string;bankAccount:string;accountHolder:string};
@Injectable()
export class FormalMemberApplicationService {
 constructor(private readonly db:PrismaService,private readonly idempotency:IdempotencyService,private readonly audit:AuditService,private readonly pii:PiiCryptoService){}
 private normalize(input:FormalDraftInput){return {formalContractVersionId:input.formalContractVersionId,legalName:input.legalName.trim(),gender:input.gender.trim(),birthDate:input.birthDate,nationalId:input.nationalId.trim().toUpperCase(),communicationAddress:input.communicationAddress.trim(),phone:input.phone.trim(),email:input.email.trim().toLowerCase(),bankCode:input.bankCode.trim(),bankAccount:input.bankAccount.replace(/\s+/g,''),accountHolder:input.accountHolder.trim()};}
 private view(application:any,payload:any,version:number){return {id:application.formalMemberApplicationId,status:application.status,version,contractVersionId:payload.formalContractVersionId,legalName:payload.legalName,gender:payload.gender,birthDate:payload.birthDate,communicationAddress:payload.communicationAddress,phone:payload.phone,email:payload.email,nationalIdMasked:`***${payload.nationalId.slice(-4)}`,bankCode:payload.bankCode,bankAccountMasked:`***${payload.bankAccount.slice(-4)}`,accountHolder:payload.accountHolder,updatedAt:application.updatedAt.toISOString()};}
 async save(personId:string,input:FormalDraftInput,key:string,requestId:string){const normalized=this.normalize(input),hash=createHash('sha256').update(JSON.stringify(normalized)).digest('hex');try{const result=await this.idempotency.execute(`member:formal-application:save:${personId}`,key,{...normalized,nationalIdHash:createHash('sha256').update(normalized.nationalId).digest('hex'),bankAccountHash:createHash('sha256').update(normalized.bankAccount).digest('hex'),nationalId:undefined,bankAccount:undefined},async tx=>{const person=await tx.person.findUnique({where:{personId}});if(!person||!['NETWORK_MEMBER','FORMAL_PENDING'].includes(person.membershipState??''))throw new ConflictException({code:'FORMAL_APPLICATION_NOT_AVAILABLE'});const now=new Date(),contract=await tx.contractDocumentVersion.findFirst({where:{contractDocumentVersionId:normalized.formalContractVersionId,required:true,audience:{in:['FORMAL_MEMBER','ALL_MEMBERS']},effectiveFrom:{lte:now},OR:[{effectiveTo:null},{effectiveTo:{gt:now}}]},include:{consentEvidence:{where:{personId},take:1}}});if(!contract||!contract.consentEvidence.length)throw new UnprocessableEntityException({code:'FORMAL_CONTRACT_CONSENT_REQUIRED'});const current=await tx.formalMemberApplication.findFirst({where:{personId,status:{in:['DRAFT','SUBMITTED','UNDER_REVIEW','NEEDS_MORE_INFO'] as any}},include:{snapshots:{orderBy:{version:'desc'},take:1}}});if(current&&current.status!=='DRAFT'&&current.status!=='NEEDS_MORE_INFO')throw new ConflictException({code:'FORMAL_APPLICATION_LOCKED'});const encrypted=this.pii.encrypt(normalized),version=(current?.snapshots[0]?.version??0)+1,application=current?await tx.formalMemberApplication.update({where:{formalMemberApplicationId:current.formalMemberApplicationId},data:{currentSnapshotHash:hash,status:'DRAFT'}}):await tx.formalMemberApplication.create({data:{personId,currentSnapshotHash:hash,status:'DRAFT'}});await tx.formalMemberApplicationSnapshot.create({data:{formalMemberApplicationId:application.formalMemberApplicationId,version,payloadCiphertext:encrypted.ciphertext,keyVersion:encrypted.keyVersion,payloadHash:hash}});const correlationId=randomUUID();await this.audit.write(tx,{actorType:'MEMBER',actorId:personId,action:'FORMAL_APPLICATION_DRAFT_SAVED',entityType:'FormalMemberApplication',entityId:application.formalMemberApplicationId,afterData:{version,payloadHash:hash,formalContractVersionId:normalized.formalContractVersionId,fieldsComplete:true},requestId,correlationId});await tx.outboxEvent.create({data:{eventType:'FORMAL_APPLICATION_DRAFT_SAVED',aggregateType:'Person',aggregateId:personId,payload:{schemaVersion:1,personId,applicationId:application.formalMemberApplicationId,applicationVersion:version,payloadHash:hash},correlationId}});return this.view(application,normalized,version);});return {...result.value,replayed:result.replayed};}catch(error){if(['P2002','P2034'].includes((error as any).code))throw new ConflictException({code:'RETRYABLE_CONFLICT'});throw error;}}
 async current(personId:string){const application=await this.db.formalMemberApplication.findFirst({where:{personId,status:{in:['DRAFT','SUBMITTED','UNDER_REVIEW','NEEDS_MORE_INFO'] as any}},include:{snapshots:{orderBy:{version:'desc'},take:1}}});if(!application||!application.snapshots[0])throw new NotFoundException({code:'FORMAL_APPLICATION_NOT_FOUND'});const snapshot=application.snapshots[0],payload=this.pii.decrypt<any>(snapshot.payloadCiphertext,snapshot.keyVersion);return this.view(application,payload,snapshot.version);}
 async adminList(input:{status?:string;take?:number}={}){const take=Math.min(Math.max(input.take??50,1),100);const rows=await this.db.formalMemberApplication.findMany({where:input.status?{status:input.status}:undefined,include:{person:{select:{legalName:true,membershipState:true}},snapshots:{select:{version:true,payloadHash:true},orderBy:{version:'desc'},take:1}},orderBy:{updatedAt:'desc'},take});return rows.map(row=>({id:row.formalMemberApplicationId,personNameMasked:row.person.legalName?`${row.person.legalName.slice(0,1)}${'*'.repeat(Math.max(row.person.legalName.length-1,1))}`:'**',membershipState:row.person.membershipState,status:row.status,version:row.snapshots[0]?.version??null,payloadHash:row.snapshots[0]?.payloadHash??row.currentSnapshotHash,createdAt:row.createdAt.toISOString(),updatedAt:row.updatedAt.toISOString(),submittedAt:row.submittedAt?.toISOString()??null,reviewedAt:row.reviewedAt?.toISOString()??null,decisionReasonCode:row.decisionReasonCode}));}
}
