import {ConflictException,Injectable,NotFoundException,UnprocessableEntityException} from '@nestjs/common';import {PrismaService} from '@ucell/database';import {createHash,randomUUID} from 'node:crypto';import {AuditService} from '../../common/audit/audit.service';import {IdempotencyService} from '../../common/idempotency/idempotency.service';
export type ContentInput={contentType:'VIDEO_EXTERNAL'|'EXTERNAL_LINK';title:string;summary?:string;externalUrl:string;thumbnailUrl?:string;audiencePolicy:'NETWORK_MEMBER';shareable:boolean;publishFrom?:string;publishTo?:string};
@Injectable() export class ContentService{constructor(private db:PrismaService,private idempotency:IdempotencyService,private audit:AuditService){}
 private url(value:string){let url:URL;try{url=new URL(value);}catch{throw new UnprocessableEntityException({code:'CONTENT_URL_INVALID'});}if(url.protocol!=='https:')throw new UnprocessableEntityException({code:'CONTENT_URL_INVALID'});return url.toString();}
 private snapshot(input:ContentInput){const {contentType:_contentType,...versioned}=input;const value={...versioned,externalUrl:this.url(input.externalUrl),thumbnailUrl:input.thumbnailUrl?this.url(input.thumbnailUrl):undefined,publishFrom:input.publishFrom?new Date(input.publishFrom):null,publishTo:input.publishTo?new Date(input.publishTo):null};if(value.publishFrom&&value.publishTo&&value.publishTo<=value.publishFrom)throw new UnprocessableEntityException({code:'CONTENT_PUBLISH_WINDOW_INVALID'});return value;}
 async create(input:ContentInput,key:string,requestId:string,actor:string){return this.idempotency.execute(`admin:content:create:${actor}`,key,input,async tx=>{const data=this.snapshot(input),content=await tx.publishedContent.create({data:{contentType:input.contentType,createdByActor:actor}}),hash=createHash('sha256').update(JSON.stringify(data)).digest('hex'),version=await tx.contentVersion.create({data:{contentId:content.contentId,version:1,...data,contentHash:hash}}),correlationId=randomUUID();await this.audit.write(tx,{actorType:'USER',actorId:actor,action:'CONTENT_CREATED',entityType:'Content',entityId:content.contentId,afterData:{contentType:content.contentType,contentVersionId:version.contentVersionId,contentHash:hash},requestId,correlationId});return {contentId:content.contentId,contentVersionId:version.contentVersionId,version:1,status:'DRAFT'};});}
 async addVersion(contentId:string,input:ContentInput,key:string,requestId:string,actor:string){return this.idempotency.execute(`admin:content:version:${contentId}:${actor}`,key,input,async tx=>{const content=await tx.publishedContent.findUnique({where:{contentId},include:{versions:{orderBy:{version:'desc'},take:1}}});if(!content)throw new NotFoundException({code:'CONTENT_NOT_FOUND'});if(content.contentType!==input.contentType)throw new ConflictException({code:'CONTENT_TYPE_IMMUTABLE'});const data=this.snapshot(input),next=(content.versions[0]?.version??0)+1,hash=createHash('sha256').update(JSON.stringify(data)).digest('hex'),version=await tx.contentVersion.create({data:{contentId,version:next,...data,contentHash:hash}}),correlationId=randomUUID();await this.audit.write(tx,{actorType:'USER',actorId:actor,action:'CONTENT_VERSION_CREATED',entityType:'ContentVersion',entityId:version.contentVersionId,afterData:{contentId,version:next,contentHash:hash},requestId,correlationId});return {contentId,contentVersionId:version.contentVersionId,version:next,status:'DRAFT'};});}
 async publish(contentId:string,versionId:string,approvalReference:string,key:string,requestId:string,actor:string,now=new Date()){return this.idempotency.execute(`admin:content:publish:${versionId}:${actor}`,key,{approvalReference},async tx=>{const row=await tx.contentVersion.findFirst({where:{contentVersionId:versionId,contentId,status:'DRAFT'}});if(!row)throw new ConflictException({code:'CONTENT_VERSION_NOT_PUBLISHABLE'});const published=await tx.contentVersion.update({where:{contentVersionId:versionId},data:{status:'PUBLISHED',approvedAt:now,approvedByActor:actor,approvalReference}});await tx.publishedContent.update({where:{contentId},data:{status:'PUBLISHED'}});const correlationId=randomUUID();await this.audit.write(tx,{actorType:'USER',actorId:actor,action:'CONTENT_PUBLISHED',entityType:'ContentVersion',entityId:versionId,afterData:{contentId,version:published.version,contentHash:published.contentHash,approvalReference},requestId,correlationId});await tx.outboxEvent.create({data:{eventType:'CONTENT_PUBLISHED',aggregateType:'Content',aggregateId:contentId,payload:{schemaVersion:1,contentId,contentVersionId:versionId,contentHash:published.contentHash},correlationId}});return {contentId,contentVersionId:versionId,version:published.version,status:'PUBLISHED',publishedAt:now.toISOString()};});}
 async adminList(){const rows=await this.db.publishedContent.findMany({include:{versions:{orderBy:{version:'desc'}}},orderBy:{createdAt:'desc'},take:100});return rows.map(content=>({id:content.contentId,type:content.contentType,status:content.status,createdAt:content.createdAt.toISOString(),versions:content.versions.map(row=>({id:row.contentVersionId,version:row.version,title:row.title,summary:row.summary,url:row.externalUrl,thumbnailUrl:row.thumbnailUrl,audiencePolicy:row.audiencePolicy,shareable:row.shareable,publishFrom:row.publishFrom?.toISOString()??null,publishTo:row.publishTo?.toISOString()??null,status:row.status,approvalReference:row.approvalReference,approvedAt:row.approvedAt?.toISOString()??null,contentHash:row.contentHash}))}));}
 async list(personId:string,now=new Date()){const person=await this.db.person.findUnique({where:{personId}});if(!person||!['NETWORK_MEMBER','FORMAL_PENDING','FORMAL_MEMBER'].includes(person.membershipState??''))return [];const rows=await this.db.contentVersion.findMany({where:{status:'PUBLISHED',audiencePolicy:'NETWORK_MEMBER',OR:[{publishFrom:null},{publishFrom:{lte:now}}],AND:[{OR:[{publishTo:null},{publishTo:{gt:now}}]}]},include:{content:true},orderBy:[{version:'desc'},{approvedAt:'desc'}],take:500});const seen=new Set<string>();const current=rows.filter(x=>!seen.has(x.contentId)&&Boolean(seen.add(x.contentId))).sort((a,b)=>(b.approvedAt?.getTime()??0)-(a.approvedAt?.getTime()??0)).slice(0,100);return current.map(x=>({id:x.contentId,versionId:x.contentVersionId,type:x.content.contentType,title:x.title,summary:x.summary,url:x.externalUrl,thumbnailUrl:x.thumbnailUrl,shareable:x.shareable,publishedAt:x.approvedAt?.toISOString()}));}
 async get(personId:string,id:string,now=new Date()){const person=await this.db.person.findUnique({where:{personId}});if(!person||!['NETWORK_MEMBER','FORMAL_PENDING','FORMAL_MEMBER'].includes(person.membershipState??''))throw new NotFoundException({code:'CONTENT_NOT_FOUND'});const row=await this.db.contentVersion.findFirst({where:{contentId:id,status:'PUBLISHED',audiencePolicy:'NETWORK_MEMBER',OR:[{publishFrom:null},{publishFrom:{lte:now}}],AND:[{OR:[{publishTo:null},{publishTo:{gt:now}}]}]},include:{content:true},orderBy:{version:'desc'}});if(!row)throw new NotFoundException({code:'CONTENT_NOT_FOUND'});return {id:row.contentId,versionId:row.contentVersionId,type:row.content.contentType,title:row.title,summary:row.summary,url:row.externalUrl,thumbnailUrl:row.thumbnailUrl,shareable:row.shareable,publishedAt:row.approvedAt?.toISOString()};}}





