import { ConflictException, Injectable, NotFoundException, UnprocessableEntityException } from '@nestjs/common';
import { Prisma, PrismaService } from '@ucell/database';
import { createHash, randomUUID } from 'node:crypto';
import { AuditService } from '../../common/audit/audit.service';
import { IdempotencyService } from '../../common/idempotency/idempotency.service';

export type OfferingVersionInput = { channels: string[]; composition?: unknown; selectionRule?: unknown; recognitionProfile?: unknown; approvalReference?: string; effectiveFrom: string; effectiveTo?: string };

@Injectable()
export class CommercialOfferingConfigService {
  constructor(private readonly db: PrismaService, private readonly idempotency: IdempotencyService, private readonly audit: AuditService) {}
  private hash(value: unknown) { return createHash('sha256').update(JSON.stringify(value)).digest('hex'); }
  private validWindow(input: OfferingVersionInput) { const from=new Date(input.effectiveFrom),to=input.effectiveTo?new Date(input.effectiveTo):undefined; if(!Number.isFinite(from.getTime()) || (to&&to<=from)) throw new UnprocessableEntityException({code:'INVALID_COMMERCIAL_OFFERING_WINDOW'}); if(!input.channels.length || new Set(input.channels).size!==input.channels.length || input.channels.some(x=>!/^[A-Z][A-Z0-9_]{1,39}$/.test(x))) throw new UnprocessableEntityException({code:'INVALID_COMMERCIAL_OFFERING_CHANNELS'}); return {from,to}; }
  async adminList() { return this.db.commercialOffering.findMany({include:{versions:{orderBy:{version:'desc'}}},orderBy:{offeringCode:'asc'}}); }
  async createOffering(input:{offeringCode:string;offeringType:any},key:string,requestId:string,actor:string) { const code=input.offeringCode.trim().toUpperCase(); if(!/^[A-Z][A-Z0-9_-]{1,79}$/.test(code)) throw new UnprocessableEntityException({code:'INVALID_COMMERCIAL_OFFERING_CODE'}); return this.idempotency.execute(`admin:commercial-offering:create:${actor}`,key,{...input,offeringCode:code},async tx=>{ const row=await tx.commercialOffering.create({data:{offeringCode:code,offeringType:input.offeringType,status:'ACTIVE'}}); await this.audit.write(tx,{actorType:'USER',actorId:actor,action:'COMMERCIAL_OFFERING_CREATED',entityType:'CommercialOffering',entityId:row.commercialOfferingId,afterData:{offeringCode:row.offeringCode,offeringType:row.offeringType},requestId,correlationId:randomUUID()}); return row; }); }
  async addVersion(offeringId:string,input:OfferingVersionInput,key:string,requestId:string,actor:string) { const {from,to}=this.validWindow(input); return this.idempotency.execute(`admin:commercial-offering-version:create:${offeringId}:${actor}`,key,input,async tx=>{const offering=await tx.commercialOffering.findUnique({where:{commercialOfferingId:offeringId}}); if(!offering)throw new NotFoundException({code:'COMMERCIAL_OFFERING_NOT_FOUND'});const latest=await tx.commercialOfferingVersion.aggregate({where:{commercialOfferingId:offeringId},_max:{version:true}});const version=(latest._max.version??0)+1,snapshotHash=this.hash({offeringCode:offering.offeringCode,offeringType:offering.offeringType,version,channels:input.channels,composition:input.composition??[],selectionRule:input.selectionRule??null,recognitionProfile:input.recognitionProfile??null,effectiveFrom:from.toISOString(),effectiveTo:to?.toISOString()??null});const row=await tx.commercialOfferingVersion.create({data:{commercialOfferingId:offeringId,version,status:'DRAFT',effectiveFrom:from,effectiveTo:to,channels:input.channels,composition:(input.composition??[]) as Prisma.InputJsonValue,selectionRule:input.selectionRule as Prisma.InputJsonValue,recognitionProfile:input.recognitionProfile as Prisma.InputJsonValue,approvalReference:input.approvalReference?.trim()||'PENDING_APPROVAL',snapshotHash}});await this.audit.write(tx,{actorType:'USER',actorId:actor,action:'COMMERCIAL_OFFERING_VERSION_CREATED',entityType:'CommercialOfferingVersion',entityId:row.commercialOfferingVersionId,afterData:{offeringCode:offering.offeringCode,version,status:row.status,snapshotHash},requestId,correlationId:randomUUID()});return row;}); }
  async approve(versionId:string,approvalReference:string,key:string,requestId:string,actor:string) { if(!approvalReference.trim())throw new UnprocessableEntityException({code:'COMMERCIAL_OFFERING_APPROVAL_REFERENCE_REQUIRED'}); return this.idempotency.execute(`admin:commercial-offering-version:approve:${versionId}:${actor}`,key,{approvalReference},async tx=>{const row=await tx.commercialOfferingVersion.updateMany({where:{commercialOfferingVersionId:versionId,status:'DRAFT'},data:{status:'APPROVED',approvalReference:approvalReference.trim()}});if(row.count!==1)throw new ConflictException({code:'COMMERCIAL_OFFERING_VERSION_NOT_APPROVABLE'});const version=await tx.commercialOfferingVersion.findUniqueOrThrow({where:{commercialOfferingVersionId:versionId}});await this.audit.write(tx,{actorType:'USER',actorId:actor,action:'COMMERCIAL_OFFERING_VERSION_APPROVED',entityType:'CommercialOfferingVersion',entityId:versionId,afterData:{version:version.version,approvalReference:version.approvalReference},requestId,correlationId:randomUUID()});return version;}); }
  async activate(versionId:string,key:string,requestId:string,actor:string,now=new Date()) { return this.idempotency.execute(`admin:commercial-offering-version:activate:${versionId}:${actor}`,key,{versionId},async tx=>{const version=await tx.commercialOfferingVersion.findUnique({where:{commercialOfferingVersionId:versionId}});if(!version||version.status!=='APPROVED')throw new ConflictException({code:'COMMERCIAL_OFFERING_VERSION_NOT_ACTIVATABLE'});if(version.effectiveFrom>now||(version.effectiveTo&&version.effectiveTo<=now))throw new ConflictException({code:'COMMERCIAL_OFFERING_VERSION_NOT_EFFECTIVE'});await tx.commercialOfferingVersion.updateMany({where:{commercialOfferingId:version.commercialOfferingId,status:'ACTIVE'},data:{status:'RETIRED',effectiveTo:now}});const row=await tx.commercialOfferingVersion.update({where:{commercialOfferingVersionId:versionId},data:{status:'ACTIVE'}});await this.audit.write(tx,{actorType:'USER',actorId:actor,action:'COMMERCIAL_OFFERING_VERSION_ACTIVATED',entityType:'CommercialOfferingVersion',entityId:versionId,afterData:{version:row.version,snapshotHash:row.snapshotHash},requestId,correlationId:randomUUID()});return row;}); }
  async memberList(channel:string,now=new Date()) { const rows=await this.db.commercialOfferingVersion.findMany({where:{status:'ACTIVE',effectiveFrom:{lte:now},OR:[{effectiveTo:null},{effectiveTo:{gt:now}}],offering:{status:'ACTIVE'}},include:{offering:true},orderBy:[{offering:{offeringCode:'asc'}},{version:'desc'}]});return rows.filter(x=>Array.isArray(x.channels)&&x.channels.includes(channel)).map(x=>({offeringCode:x.offering.offeringCode,offeringType:x.offering.offeringType,version:x.version,commercialOfferingVersionId:x.commercialOfferingVersionId,composition:x.composition,selectionRule:x.selectionRule,recognitionProfile:x.recognitionProfile,snapshotHash:x.snapshotHash,effectiveFrom:x.effectiveFrom.toISOString(),effectiveTo:x.effectiveTo?.toISOString()??null})); }
}