import {Body,Controller,Get,Headers,Param,ParseUUIDPipe,Post,Query,Req,UseGuards} from '@nestjs/common';
import {ApiBearerAuth,ApiHeader,ApiProperty,ApiPropertyOptional,ApiTags} from '@nestjs/swagger';
import {ArrayMaxSize,ArrayMinSize,IsArray,IsEnum,IsISO8601,IsObject,IsOptional,IsString,Matches,MaxLength} from 'class-validator';
import {Roles} from '../auth/roles.decorator';
import {IdempotencyGuard} from '../../common/guards/idempotency.guard';
import {CommercialOfferingConfigService,OfferingVersionInput} from './commercial-offering-config.service';
import {MemberAuthenticationGuard} from '../auth/member-authentication.guard';
class OfferingDto {@ApiProperty() @Matches(/^[A-Z][A-Z0-9_-]{1,79}$/) offeringCode!:string;@ApiProperty({enum:['QUALIFICATION_PACKAGE','REPURCHASE_PLAN','CORE_PRODUCT','RETAIL_PRODUCT','PROMOTIONAL_BUNDLE']}) @IsEnum(['QUALIFICATION_PACKAGE','REPURCHASE_PLAN','CORE_PRODUCT','RETAIL_PRODUCT','PROMOTIONAL_BUNDLE']) offeringType!:any;}
class OfferingVersionDto implements OfferingVersionInput {@ApiProperty({type:[String]}) @IsArray() @ArrayMinSize(1) @ArrayMaxSize(20) @Matches(/^[A-Z][A-Z0-9_]{1,39}$/,{each:true}) channels!:string[];@ApiPropertyOptional() @IsOptional() composition?:unknown;@ApiPropertyOptional() @IsOptional() selectionRule?:unknown;@ApiPropertyOptional() @IsOptional() recognitionProfile?:unknown;@ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(200) approvalReference?:string;@ApiProperty() @IsISO8601() effectiveFrom!:string;@ApiPropertyOptional() @IsOptional() @IsISO8601() effectiveTo?:string;}
class ApprovalDto {@ApiProperty() @IsString() @MaxLength(200) approvalReference!:string;}
@ApiTags('Admin - Commercial Offerings') @ApiBearerAuth('adminBearer') @Roles('SUPER_ADMIN','ORDER_OPS','PACKAGE_CONFIG_MANAGE','PACKAGE_CONFIG_APPROVE','COMPLIANCE_AUDIT') @Controller('admin/commercial-offerings')
export class AdminCommercialOfferingController {constructor(private readonly service:CommercialOfferingConfigService){}@Get() list(){return this.service.adminList();}@Post() @Roles('SUPER_ADMIN','PACKAGE_CONFIG_MANAGE') @UseGuards(IdempotencyGuard) @ApiHeader({name:'Idempotency-Key',required:true}) create(@Body() body:OfferingDto,@Headers('idempotency-key') key:string,@Req() req:any){return this.service.createOffering(body,key,req.requestId,req.user?.personId??req.user?.subject);}@Post(':id/versions') @Roles('SUPER_ADMIN','PACKAGE_CONFIG_MANAGE') @UseGuards(IdempotencyGuard) @ApiHeader({name:'Idempotency-Key',required:true}) version(@Param('id',new ParseUUIDPipe()) id:string,@Body() body:OfferingVersionDto,@Headers('idempotency-key') key:string,@Req() req:any){return this.service.addVersion(id,body,key,req.requestId,req.user?.personId??req.user?.subject);}@Post('versions/:id/approve') @Roles('SUPER_ADMIN','PACKAGE_CONFIG_APPROVE') @UseGuards(IdempotencyGuard) @ApiHeader({name:'Idempotency-Key',required:true}) approve(@Param('id',new ParseUUIDPipe()) id:string,@Body() body:ApprovalDto,@Headers('idempotency-key') key:string,@Req() req:any){return this.service.approve(id,body.approvalReference,key,req.requestId,req.user?.personId??req.user?.subject);}@Post('versions/:id/activate') @Roles('SUPER_ADMIN','PACKAGE_CONFIG_APPROVE') @UseGuards(IdempotencyGuard) @ApiHeader({name:'Idempotency-Key',required:true}) activate(@Param('id',new ParseUUIDPipe()) id:string,@Headers('idempotency-key') key:string,@Req() req:any){return this.service.activate(id,key,req.requestId,req.user?.personId??req.user?.subject);}}
@ApiTags('Member - Commercial Offerings') @ApiBearerAuth('memberBearer') @UseGuards(MemberAuthenticationGuard) @Controller('member/commercial-offerings')
export class MemberCommercialOfferingController {constructor(private readonly service:CommercialOfferingConfigService){}@Get() list(){return {data:this.service.memberList('WEB_MEMBER')};}}