export const nav=[
  ['總覽','/','dashboard'],
  ['會員／自然人','/people','people'],
  ['會員申請','/applications','applications'],
  ['會員資格（球）','/qualifications','qualifications'],
  ['商品參照','/products','products'],
  ['套組與資格商品','/packages','packages'],
  ['訂單與收款','/orders','orders'],
  ['組織／安置','/organization','organization'],
  ['重購訂閱','/subscriptions','subscriptions'],
  ['獎金與結算證據','/bonuses','bonuses'],
  ['退貨／重算','/returns','returns'],
  ['升級／轉讓／退出','/workflows','workflows'],
  ['付款批次與對帳','/payouts','payouts'],
  ['影音／連結內容','/content','content'],
  ['文件／附件','/documents','documents'],
  ['稽核紀錄','/audit','audit'],
  ['報表／完整性','/reports','reports'],
  ['NASL／十二代健康雷達','/analytics','analytics'],
  ['UAT／上線驗證','/uat','uat'],
  ['系統就緒度','/system','system'],
  ['Provider Webhook 營運','/provider-operations','provider-operations'],
] as const;
export const navGroups=[
 {label:'營運中心',paths:['/','/content']},
 {label:'會員與資格',paths:['/people','/qualifications','/applications','/workflows']},
 {label:'商務',paths:['/products','/packages','/orders','/subscriptions','/returns']},
 {label:'組織',paths:['/organization']},
 {label:'獎金財務',paths:['/bonuses','/payouts']},
 {label:'分析中心',paths:['/reports','/analytics']},
 {label:'治理稽核',paths:['/documents','/audit']},
 {label:'系統與發布',paths:['/uat','/system','/provider-operations']},
];
