export const nav=[
  ['總覽','/','dashboard'],
  ['會員／自然人','/people','people'],
  ['會員申請','/applications','applications'],
  ['會員資格（球）','/qualifications','qualifications'],
  ['商品參照','/products','products'],
  ['訂單與收款','/orders','orders'],
  ['組織／安置','/organization','organization'],
  ['重銷方案','/subscriptions','subscriptions'],
  ['獎金／帳本','/bonuses','bonuses'],
  ['退貨／重算','/returns','returns'],
  ['升級／轉讓／退出','/workflows','workflows'],
  ['結算／付款','/payouts','payouts'],
  ['文件／附件','/documents','documents'],
  ['稽核紀錄','/audit','audit'],
  ['報表／完整性','/reports','reports'],
  ['UAT／上線驗證','/uat','uat'],
  ['系統就緒度','/system','system'],
] as const;
