packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': false
  prisma: true
  unrs-resolver: true
overrides:
  fastify: 5.12.4
  prisma: 6.19.3
  '@prisma/client': 6.19.3
  typescript: 5.9.3
  '@types/node': ^24.0.0
