import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';
import {randomUUID} from 'node:crypto';
const require=createRequire(new URL('../package.json',import.meta.url));
const {PrismaClient,Prisma}=require('@prisma/client');
const replay=require('./packages/database/dist/historical-replay.js');
const {EpvService}=require('../backend/apps/api/dist/modules/epv/epv.service.js');
const {EpvMonthService}=require('../backend/apps/api/dist/modules/epv/epv-month.service.js');
const {BonusQueryService}=require('../backend/apps/api/dist/modules/bonus/bonus-query.service.js');
const {RuntimeRuleService}=require('../backend/apps/api/dist/modules/rules/runtime-rule.service.js');
const url=new URL(process.env.DATABASE_URL??'');assert.equal(url.pathname,'/ucell_admin_test');assert.ok(['localhost','127.0.0.1'].includes(url.hostname));
const prisma=new PrismaClient(),results=[],version='PHASE2_TEST_'+randomUUID(),rollback=new Error('ROLLBACK_PHASE2_FIXTURES');
function check(label,actual,expected,stableEvidence){
 assert.deepEqual(actual,expected,label);
 results.push({label,result:'PASS',...(stableEvidence??{actual,expected})});
}
let failure;
try{await prisma.$transaction(async tx=>{
 for(const [name,schema,table] of [['SettlementAdjustmentBatch','ledger','settlement_adjustment_batch'],['SettlementAdjustmentLine','ledger','settlement_adjustment_line'],['QualificationWorkflow','membership','qualification_workflow'],['SettlementReplayRun','ledger','settlement_replay_run'],['SettlementReplayPeriod','ledger','settlement_replay_period'],['BonusCalculationEvidence','ledger','bonus_calculation_evidence']]){
  const model=Prisma.dmmf.datamodel.models.find(model=>model.name===name);assert.ok(model,'generated Prisma model '+name);
  const columns=await tx.$queryRaw`SELECT column_name FROM information_schema.columns WHERE table_schema=${schema} AND table_name=${table} ORDER BY column_name`;
  check('Prisma DB column convergence '+name,columns.map(row=>row.column_name).sort(),model.fields.filter(field=>field.kind!=='object').map(field=>field.dbName??field.name).sort());
 }
 const person=await tx.person.findFirstOrThrow(),product=await tx.productReference.findFirstOrThrow();
 const parameters=await tx.runtimeRuleParameter.findMany({where:{ruleVersionCode:'R1.0B'}});
 for(const row of new Map(parameters.map(r=>[JSON.stringify([r.parameterCode,r.scopeKey]),r])).values()){
   if(['epv.calendar.timezone','accounting.timezone'].includes(row.parameterCode))continue; // Explicit TEST_ONLY UTC below.
   await tx.runtimeRuleParameter.create({data:{ruleVersionCode:version,parameterCode:row.parameterCode,scopeKey:row.scopeKey,valueJson:row.valueJson,effectiveFrom:new Date('2019-01-01')}});
 }
 await tx.runtimeRuleParameter.create({data:{ruleVersionCode:version,parameterCode:'epv.calendar.timezone',valueJson:'UTC',effectiveFrom:new Date('2019-01-01')}});
 await tx.runtimeRuleParameter.create({data:{ruleVersionCode:version,parameterCode:'accounting.timezone',valueJson:'UTC',effectiveFrom:new Date('2019-01-01')}});
 async function qualification(active=true){const q=await tx.qualification.create({data:{currentHolderPersonId:person.personId,planLevelCode:'LEADER',status:'EFFECTIVE',effectiveAt:new Date('2020-01-01')}});await tx.qualificationPlanHistory.create({data:{qualificationId:q.qualificationId,planCode:'LEADER',effectiveFrom:new Date('2020-01-01'),sourceType:'PHASE2_TEST'}});await tx.qualificationStatusHistory.create({data:{qualificationId:q.qualificationId,status:'EFFECTIVE',effectiveFrom:new Date('2020-01-01'),sourceType:'PHASE2_TEST'}});if(active)await tx.activePeriod.create({data:{qualificationId:q.qualificationId,activeFrom:new Date('2020-01-01'),sourceType:'PHASE2_TEST',ruleVersionCode:version}});return q;}
 const self=await qualification(),oldSponsor=await qualification(),inactive=await qualification(false),newSponsor=await qualification();
 const relationship=await tx.sponsorRelationship.create({data:{childQualificationId:self.qualificationId,sponsorQualificationId:oldSponsor.qualificationId,sponsorSequenceNo:1,effectiveFrom:new Date('2020-01-01')}});
 await tx.sponsorRelationship.create({data:{childQualificationId:oldSponsor.qualificationId,sponsorQualificationId:inactive.qualificationId,sponsorSequenceNo:1,effectiveFrom:new Date('2020-01-01')}});
 const order=await tx.order.create({data:{qualificationId:self.qualificationId,purpose:'REPURCHASE',status:'PAID',grossAmount:4800,netAmount:4800,ruleVersionCode:version,paidAt:new Date('2020-01-05'),lines:{create:{productId:product.productId,skuSnapshot:product.sku,productNameSnapshot:'PHASE2 TEST',quantity:3,unitPrice:1600,lineAmount:4800,gpvRateSnapshot:0,gpvAmountSnapshot:0,ruleProfileSnapshot:{testOnly:true}}}},include:{lines:true}});
 const gpv=await tx.pvLedger.create({data:{qualificationId:self.qualificationId,pvType:'GPV',amount:0,eventType:'GPV_CREATED',sourceType:'ORDER',sourceId:order.orderId,sourceLineId:order.lines[0].orderLineId,ruleVersionCode:version,occurredAt:order.paidAt,correlationId:randomUUID()}});await replay.sealGpvEvent(tx,gpv);
 const facade={$transaction:fn=>fn(tx)};
 const service=new EpvService(facade,new RuntimeRuleService(facade),new BonusQueryService(facade),new EpvMonthService());
 check('original EPV 4800 => 1680',(await service.recognizeOrder(order.orderId,version)).epv,'1680');
 const originalAwards=await tx.bonusAward.findMany({where:{sourceQualificationId:self.qualificationId,awardType:'EPV'},orderBy:{bonusAwardId:'asc'}}),originalJson=JSON.stringify(originalAwards);
 const selfAward=originalAwards.find(a=>a.recipientQualificationId===self.qualificationId);
 check('original Active EPV self entitlement',selfAward.payableAmount.toString(),'840');
 check('original inactive EPV Sponsor generation stays zero',originalAwards.find(a=>a.recipientQualificationId===inactive.qualificationId).payableAmount.toString(),'0');
 const epvActiveSelf=await qualification(),epvBinaryOnly=await qualification(),epvChain=[];
 for(let i=0;i<5;i++)epvChain.push(await qualification());
 for(let i=0;i<5;i++){
   await tx.sponsorRelationship.create({data:{childQualificationId:i===0?epvActiveSelf.qualificationId:epvChain[i-1].qualificationId,sponsorQualificationId:epvChain[i].qualificationId,sponsorSequenceNo:1,effectiveFrom:new Date('2020-01-01')}});
   if(i>0)await tx.binaryPlacement.create({data:{childQualificationId:epvChain[i-1].qualificationId,parentQualificationId:epvChain[i].qualificationId,side:'LEFT',effectiveFrom:new Date('2020-01-01')}});
 }
 await tx.binaryPlacement.create({data:{childQualificationId:epvBinaryOnly.qualificationId,parentQualificationId:epvChain[0].qualificationId,side:'LEFT',effectiveFrom:new Date('2020-01-01')}});
 await tx.binaryPlacement.create({data:{childQualificationId:epvActiveSelf.qualificationId,parentQualificationId:epvBinaryOnly.qualificationId,side:'LEFT',effectiveFrom:new Date('2020-01-01')}});
 const epvActiveOrder=await tx.order.create({data:{qualificationId:epvActiveSelf.qualificationId,purpose:'REPURCHASE',status:'PAID',grossAmount:4800,netAmount:4800,ruleVersionCode:version,paidAt:new Date('2020-01-05'),lines:{create:{productId:product.productId,skuSnapshot:product.sku,productNameSnapshot:'TEST_ONLY EPV RECIPIENT ISOLATION',quantity:3,unitPrice:1600,lineAmount:4800,gpvRateSnapshot:0,gpvAmountSnapshot:0,ruleProfileSnapshot:{testOnly:true,pendingFormalPVMapping:true}}}}});
 await service.recognizeOrder(epvActiveOrder.orderId,version);
 const epvActiveAwards=await tx.bonusAward.findMany({where:{sourceQualificationId:epvActiveSelf.qualificationId,awardType:'EPV'}});
 for(let generation=1;generation<=5;generation++)check('Active historical EPV Sponsor G'+generation,epvActiveAwards.find(a=>a.recipientQualificationId===epvChain[generation-1].qualificationId&&a.generationNo===generation).payableAmount.toString(),'100.8');
 check('Binary-only historical EPV ancestor gets no award',epvActiveAwards.filter(a=>a.recipientQualificationId===epvBinaryOnly.qualificationId).length,0);
 const paidEvent=await tx.bonusAwardLifecycleEvent.create({data:{bonusAwardId:selfAward.bonusAwardId,status:'PAID',occurredAt:new Date(),reasonCode:'PHASE2_TEST_PAID'}});
 await tx.sponsorRelationship.update({where:{sponsorRelationshipId:relationship.sponsorRelationshipId},data:{effectiveTo:new Date('2020-01-06')}});
 // Supervised fixture supersede: the current-row guard permits replacement only after closing its interval.
 await tx.sponsorRelationship.update({where:{sponsorRelationshipId:relationship.sponsorRelationshipId},data:{sponsorQualificationId:newSponsor.qualificationId,effectiveFrom:new Date('2020-01-06'),effectiveTo:null}});
 await tx.activePeriod.updateMany({where:{qualificationId:oldSponsor.qualificationId},data:{activeTo:new Date('2020-01-06')}});
 await tx.activePeriod.create({data:{qualificationId:inactive.qualificationId,activeFrom:new Date('2020-01-06'),sourceType:'CHANGED_AFTER_CAPTURE_TEST',ruleVersionCode:version}});
 async function ret(amount=1600){return tx.returnCase.create({data:{orderId:order.orderId,status:'POSTED',reasonCode:'PHASE2_TEST',occurredAt:new Date('2020-01-10'),idempotencyKey:randomUUID(),correlationId:randomUUID(),lines:{create:{orderLineId:order.lines[0].orderLineId,quantity:1,returnAmount:amount,gpvReversalAmount:0}}}});}
 const first=await ret();await replay.processHistoricalReturn(tx,first.returnCaseId);
 const firstPost=await tx.entitlementReplayPosting.findFirstOrThrow({where:{actionKey:'RETURN:'+first.returnCaseId,recipientQualificationId:self.qualificationId}});
 check('partial return historical self delta',firstPost.delta.toString(),'-480');
 check('first effective historical self entitlement',firstPost.recalculatedEntitlement.toString(),'360');
 check('historical sponsor receives adjustment despite current inactive',await tx.entitlementReplayPosting.count({where:{actionKey:'RETURN:'+first.returnCaseId,recipientQualificationId:oldSponsor.qualificationId,delta:{lt:0}}}),1);
 check('current sponsor never receives historical money',await tx.entitlementReplayPosting.count({where:{recipientQualificationId:newSponsor.qualificationId}}),0);
 check('historically inactive recipient stays zero',(await tx.entitlementReplayPosting.findFirstOrThrow({where:{recipientQualificationId:inactive.qualificationId}})).delta.toString(),'0');
 const firstRecoveryCount=await tx.bonusRecoveryEvent.count({where:{returnCaseId:first.returnCaseId}});
 await replay.processHistoricalReturn(tx,first.returnCaseId);check('duplicate return no duplicate recovery',await tx.bonusRecoveryEvent.count({where:{returnCaseId:first.returnCaseId}}),firstRecoveryCount);
 const second=await ret();await replay.processHistoricalReturn(tx,second.returnCaseId);
 const secondPost=await tx.entitlementReplayPosting.findFirstOrThrow({where:{actionKey:'RETURN:'+second.returnCaseId,recipientQualificationId:self.qualificationId}});
 check('multi-return incremental self delta',secondPost.delta.toString(),'-360');
 check('cross-threshold effective entitlement',secondPost.recalculatedEntitlement.toString(),'0');
 check('clawback never exceeds original entitlement',(await tx.bonusRecoveryEvent.aggregate({where:{bonusAwardId:selfAward.bonusAwardId},_sum:{recoveryAmount:true}}))._sum.recoveryAmount.toString(),'840');
 check('original awards are immutable',JSON.stringify(await tx.bonusAward.findMany({where:{sourceQualificationId:self.qualificationId,awardType:'EPV'},orderBy:{bonusAwardId:'asc'}})),originalJson,{actual:'UNCHANGED',expected:'UNCHANGED'});
 check('original PAID history is immutable',await tx.bonusAwardLifecycleEvent.findUniqueOrThrow({where:{lifecycleEventId:paidEvent.lifecycleEventId}}),paidEvent,{actual:'UNCHANGED',expected:'UNCHANGED'});
 check('PAID historical reduction appends one CLAWBACK lifecycle',await tx.bonusAwardLifecycleEvent.count({where:{bonusAwardId:selfAward.bonusAwardId,status:'CLAWBACK',reasonCode:'HISTORICAL_REPLAY'}}),1);
 check('original EPV ledger unchanged',(await tx.pvLedger.findFirstOrThrow({where:{sourceId:order.orderId,pvType:'EPV'}})).amount.toString(),'1680');
 check('effective EPV ledger after two returns',(await tx.pvLedger.aggregate({where:{qualificationId:self.qualificationId,pvType:'EPV'},_sum:{amount:true}}))._sum.amount.toString(),'0');
 check('outstanding recovery tracks PAID clawback',(await tx.bonusRecoveryEvent.aggregate({where:{bonusAwardId:selfAward.bonusAwardId},_sum:{outstandingAmount:true}}))._sum.outstandingAmount.toString(),'840');
 async function rejected(label,operation,code){await tx.$executeRawUnsafe('SAVEPOINT phase2_expected_failure');let caught;try{await operation();}catch(error){caught=error;}await tx.$executeRawUnsafe('ROLLBACK TO SAVEPOINT phase2_expected_failure');assert.ok(caught,label);check(label,String(caught.message).includes(code)||String(caught.getResponse?.().code).includes(code),true);}
 const originalPv=await tx.pvLedger.findUniqueOrThrow({where:{eventId:gpv.eventId}});
 await rejected('PV Ledger UPDATE rejected by DB',()=>tx.pvLedger.update({where:{eventId:gpv.eventId},data:{amount:999}}),'UCell append-only table pv_ledger does not allow UPDATE/DELETE');
 await rejected('PV Ledger DELETE rejected by DB',()=>tx.pvLedger.delete({where:{eventId:gpv.eventId}}),'UCell append-only table pv_ledger does not allow UPDATE/DELETE');
 check('PV Ledger entire original row survives rejected mutations',await tx.pvLedger.findUniqueOrThrow({where:{eventId:gpv.eventId}}),originalPv,{actual:'UNCHANGED',expected:'UNCHANGED'});
 const snapshot=await tx.historicalReplaySnapshot.findFirstOrThrow({where:{kind:'EPV',sourceId:{in:originalAwards.map(a=>a.sourceEventId)}}});
 await rejected('snapshot UPDATE rejected by DB',()=>tx.historicalReplaySnapshot.update({where:{snapshotId:snapshot.snapshotId},data:{hash:'invalid'}}),'APPEND_ONLY_REPLAY_EVIDENCE');
 await rejected('posting DELETE rejected by DB',()=>tx.entitlementReplayPosting.delete({where:{postingId:firstPost.postingId}}),'APPEND_ONLY_REPLAY_EVIDENCE');
 await rejected('posting cannot repeat previously clawed back delta',()=>tx.entitlementReplayPosting.create({data:{actionKey:'RETURN:INVALID',snapshotId:snapshot.snapshotId,entitlementKey:firstPost.entitlementKey,recipientQualificationId:self.qualificationId,originallyPosted:840,recalculatedEntitlement:0,delta:-840,stateHash:'invalid'}}),'REPLAY_DELTA_BASELINE_MISMATCH');
 await rejected('DB rejects recipient changed from historical evidence',()=>tx.entitlementReplayPosting.create({data:{actionKey:'RETURN:WRONG_RECIPIENT',snapshotId:snapshot.snapshotId,entitlementKey:firstPost.entitlementKey,recipientQualificationId:newSponsor.qualificationId,originallyPosted:840,recalculatedEntitlement:0,delta:0,stateHash:'invalid'}}),'HISTORICAL_RECIPIENT_MISMATCH');
 await rejected('DB rejects original baseline altered from historical evidence',()=>tx.entitlementReplayPosting.create({data:{actionKey:'RETURN:WRONG_BASELINE',snapshotId:snapshot.snapshotId,entitlementKey:firstPost.entitlementKey,recipientQualificationId:self.qualificationId,originallyPosted:10,recalculatedEntitlement:0,delta:830,stateHash:'invalid'}}),'REPLAY_ORIGINAL_BASELINE_CHANGED');
 const beforeMissing=await tx.pvLedger.count();
 await rejected('missing snapshot fails closed',()=>replay.verifyReplayEnvelope(null),'HISTORICAL_SNAPSHOT_MISSING');
 check('missing snapshot does not append money',await tx.pvLedger.count(),beforeMissing);
 // Original fixture capture precedes replay. TEST_ONLY parameters do not establish an operational calendar.
 const {captureParameters}=require('./packages/database/dist/parameter-snapshot.js');
 const historical=await captureParameters(tx,new Date('2020-01-03'),version);
 const pendingAward=await tx.bonusAward.create({data:{awardType:'REFERRAL',recipientQualificationId:self.qualificationId,theoryAmount:100,payableAmount:100,activeSnapshot:true,planLevelSnapshot:'LEADER',ruleVersionCode:version,parameterSnapshotHash:historical.hash,occurredAt:new Date('2020-01-03'),pendingUntil:new Date('2020-02-17'),calculationDetail:{testOnly:true}}});
 await tx.bonusAwardLifecycleEvent.createMany({data:[{bonusAwardId:pendingAward.bonusAwardId,status:'CALCULATED',occurredAt:new Date('2020-01-03')},{bonusAwardId:pendingAward.bonusAwardId,status:'PENDING_45D',occurredAt:new Date('2020-01-03T00:00:01Z')}]});
 const pendingEnvelope={format:'UCELL_HISTORICAL_REPLAY_V1',kind:'REFERRAL_K0',sourceId:randomUUID(),ruleVersionCode:version,at:'2020-01-03T00:00:00.000Z',parameters:historical,
  recipients:[{key:pendingAward.bonusAwardId,awardId:pendingAward.bonusAwardId,awardType:'REFERRAL',qualificationId:self.qualificationId,generation:1,active:true,eligible:true,theory:'100',posted:'100',pendingUntil:'2020-02-17T00:00:00.000Z',detail:{},qualification:{plan:{planCode:'LEADER'},status:{status:'EFFECTIVE'},activeIntervals:[{activeFrom:'2020-01-01T00:00:00.000Z',activeTo:null}]}}],evidence:{sources:[]},inputs:{}};
 const pendingSnapshot=await replay.storeReplaySnapshot(tx,pendingEnvelope);
 const pendingPosting=await replay.appendEntitlementDelta(tx,pendingSnapshot,pendingEnvelope.recipients[0],new Prisma.Decimal(0),'RETURN:PENDING_LIFECYCLE',replay.replayHash({pending:true}));
 check('PENDING_45D historical zero entitlement appends REVERSED lifecycle',(await tx.bonusAwardLifecycleEvent.findFirstOrThrow({where:{bonusAwardId:pendingAward.bonusAwardId},orderBy:[{occurredAt:'desc'},{createdAt:'desc'}]})).status,'REVERSED');
 check('PENDING_45D reversal creates no recovery',[pendingPosting.recoveryId,await tx.bonusRecoveryEvent.count({where:{bonusAwardId:pendingAward.bonusAwardId}})],[null,0]);
 const leftQ=await qualification(),rightQ=await qualification();
 for(const [index,q] of [leftQ,rightQ].entries())await tx.sponsorRelationship.create({data:{sponsorQualificationId:self.qualificationId,childQualificationId:q.qualificationId,sponsorSequenceNo:index+1,effectiveFrom:new Date('2020-01-01')}});
 await tx.binaryPlacement.create({data:{parentQualificationId:self.qualificationId,childQualificationId:leftQ.qualificationId,side:'LEFT',effectiveFrom:new Date('2020-01-01')}});
 await tx.binaryPlacement.create({data:{parentQualificationId:self.qualificationId,childQualificationId:rightQ.qualificationId,side:'RIGHT',effectiveFrom:new Date('2020-01-01')}});
 const economic=[];
 for(const q of [leftQ,rightQ]){const o=await tx.order.create({data:{qualificationId:q.qualificationId,purpose:'RETAIL',status:'PAID',grossAmount:1000,netAmount:1000,ruleVersionCode:version,paidAt:new Date('2020-01-03'),lines:{create:{productId:product.productId,skuSnapshot:product.sku,productNameSnapshot:'GPV TEST',quantity:2,unitPrice:500,lineAmount:1000,gpvRateSnapshot:1,gpvAmountSnapshot:1000,ruleProfileSnapshot:{testOnly:true}}}},include:{lines:true}});const event=await tx.pvLedger.create({data:{qualificationId:q.qualificationId,pvType:'GPV',amount:1000,eventType:'GPV_CREATED',sourceType:'ORDER',sourceId:o.orderId,sourceLineId:o.lines[0].orderLineId,ruleVersionCode:version,occurredAt:o.paidAt,correlationId:randomUUID()}});const row=await replay.sealGpvEvent(tx,event);economic.push({order:o,event,envelope:replay.verifyReplayEnvelope(row)});}
 const batch=await tx.settlementBatch.create({data:{settlementType:'REFERRAL_K0',periodStart:new Date('2020-01-01'),periodEnd:new Date('2020-01-08'),ruleVersionCode:version,status:'FINALIZED',parameterSnapshot:historical,totalGpv:2000,totalTheory:1100,poolRate:'.42',poolAvailable:840,kFactor:'.76363636'}});
 const originals=[];
 for(const [index,source] of economic.entries()){originals.push(await tx.bonusAward.create({data:{settlementBatchId:batch.settlementBatchId,awardType:'REFERRAL',generationNo:1,recipientQualificationId:self.qualificationId,sourceQualificationId:source.order.qualificationId,sourceEventId:source.event.eventId,theoryAmount:index===0?1000:100,payableAmount:index===0?'763.6364':'76.3636',kFactor:'.76363636',activeSnapshot:true,planLevelSnapshot:'LEADER',ruleVersionCode:version,occurredAt:source.event.occurredAt,pendingUntil:new Date('2020-02-17'),calculationDetail:{testOnly:true}}}));}
 await replay.sealSettlement(tx,batch);
 const saved=JSON.stringify([...originals].sort((a,b)=>a.bonusAwardId.localeCompare(b.bonusAwardId)));
 const outside=await qualification();
 const outsideOrder=await tx.order.create({data:{qualificationId:outside.qualificationId,purpose:'RETAIL',status:'PAID',grossAmount:1000,netAmount:1000,ruleVersionCode:version,paidAt:new Date('2020-01-09'),lines:{create:{productId:product.productId,skuSnapshot:product.sku,productNameSnapshot:'UNRELATED PERIOD POOL TEST',quantity:1,unitPrice:1000,lineAmount:1000,gpvRateSnapshot:1,gpvAmountSnapshot:1000,ruleProfileSnapshot:{testOnly:true}}}},include:{lines:true}});
 const outsideGpv=await tx.pvLedger.create({data:{qualificationId:outside.qualificationId,pvType:'GPV',amount:1000,eventType:'GPV_CREATED',sourceType:'ORDER',sourceId:outsideOrder.orderId,sourceLineId:outsideOrder.lines[0].orderLineId,ruleVersionCode:version,occurredAt:outsideOrder.paidAt,correlationId:randomUUID()}});await replay.sealGpvEvent(tx,outsideGpv);
 const chainOriginals=[];
 for(const [index,start,end,leftIn,rightIn,leftOut,rightOut,paired,totalGpv] of [[0,'2020-01-01','2020-01-08',200,0,1000,800,200,2000],[1,'2020-01-08','2020-01-10',1000,800,800,600,200,1000],[2,'2020-01-10','2020-01-17',0,800,0,800,0,0]]){
 const b=await tx.settlementBatch.create({data:{settlementType:'BINARY_K1',periodStart:new Date(start),periodEnd:new Date(end),ruleVersionCode:version,status:'FINALIZED',parameterSnapshot:historical,totalGpv,kFactor:1}});
  const zeroEvidence=index===0?await tx.bonusCalculationEvidence.create({data:{settlementBatchId:b.settlementBatchId,evidenceType:'BINARY_ELIGIBILITY',recipientQualificationId:inactive.qualificationId,reasonCode:'INACTIVE',theoreticalAmount:24,entitlementAmount:0,ruleVersionCode:version,parameterSnapshotHash:historical.hash,occurredAt:new Date(end),calculationDetail:{testOnly:true,pairedPv:'200',pairRate:'.12'}}}):null;
  if(zeroEvidence)await rejected('Binary zero-entitlement evidence UPDATE rejected by DB',()=>tx.bonusCalculationEvidence.update({where:{bonusCalculationEvidenceId:zeroEvidence.bonusCalculationEvidenceId},data:{reasonCode:'ALTERED'}}),'UCell append-only table bonus_calculation_evidence does not allow UPDATE/DELETE');
  const carry=await tx.binaryCarry.create({data:{qualificationId:self.qualificationId,periodEnd:new Date(end),ruleVersionCode:version,leftCarryIn:leftIn,rightCarryIn:rightIn,leftPeriodGpv:index===0?1000:0,rightPeriodGpv:index===0?1000:0,pairedPv:paired,leftCarryOut:leftOut,rightCarryOut:rightOut,weeklyCapSnapshot:200}});
  const theory=String(Number(paired)*.12);
  const award=await tx.bonusAward.create({data:{settlementBatchId:b.settlementBatchId,awardType:'BINARY',recipientQualificationId:self.qualificationId,theoryAmount:theory,payableAmount:theory,activeSnapshot:true,planLevelSnapshot:'LEADER',ruleVersionCode:version,occurredAt:new Date(end),pendingUntil:new Date('2020-03-01'),calculationDetail:{testOnly:true}}});const sealedBinary=await replay.sealSettlement(tx,b);
  if(zeroEvidence){const sealedEnvelope=replay.verifyReplayEnvelope(sealedBinary);check('sealed Binary snapshot retains inactive zero-entitlement reason',[sealedEnvelope.evidence.eligibilityEvidence[0].recipientQualificationId,sealedEnvelope.evidence.eligibilityEvidence[0].reasonCode,sealedEnvelope.evidence.eligibilityEvidence[0].entitlementAmount],[inactive.qualificationId,'INACTIVE','0'],{actual:[true,'INACTIVE','0'],expected:[true,'INACTIVE','0']});}
  const m=await tx.settlementBatch.create({data:{settlementType:'MATCHING_K2',periodStart:new Date(start),periodEnd:new Date(end),ruleVersionCode:version,status:'FINALIZED',parameterSnapshot:historical,totalGpv,kFactor:1}});
  const matchingTheory=String(Number(theory)*.1);
  const matching=await tx.bonusAward.create({data:{settlementBatchId:m.settlementBatchId,awardType:'MATCHING',recipientQualificationId:newSponsor.qualificationId,sourceAwardId:award.bonusAwardId,generationNo:1,theoryAmount:matchingTheory,payableAmount:matchingTheory,activeSnapshot:true,planLevelSnapshot:'LEADER',ruleVersionCode:version,occurredAt:new Date(end),pendingUntil:new Date('2020-03-01'),calculationDetail:{rate:'.1',unlockDepth:7,testOnly:true}}});await replay.sealSettlement(tx,m);
  chainOriginals.push({batch:b,matchingBatch:m,carry,award,matching});
 }
 const originalChainJson=JSON.stringify(chainOriginals);
 const refund=await tx.returnCase.create({data:{orderId:economic[0].order.orderId,status:'POSTED',reasonCode:'PERIOD_TEST',occurredAt:new Date('2020-01-10'),idempotencyKey:randomUUID(),correlationId:randomUUID(),lines:{create:{orderLineId:economic[0].order.lines[0].orderLineId,quantity:1,returnAmount:500,gpvReversalAmount:500}}}});
 await replay.processHistoricalReturn(tx,refund.returnCaseId);
 const gpvReversal=await tx.pvLedger.findFirstOrThrow({where:{sourceId:refund.returnCaseId,pvType:'GPV',eventType:'GPV_REVERSAL'}});
 const postedReturnLine=await tx.returnLine.findFirstOrThrow({where:{returnCaseId:refund.returnCaseId}});
 check('partial return creates proportional negative GPV event',[gpvReversal.amount.toString(),gpvReversal.qualificationId,gpvReversal.sourceLineId],['-500',economic[0].event.qualificationId,postedReturnLine.returnLineId],{actual:['-500',true,true],expected:['-500',true,true]});
 check('GPV reversal references original GPV event',gpvReversal.reversalOfEventId===economic[0].event.eventId,true);
 const postings=await tx.entitlementReplayPosting.findMany({where:{actionKey:'RETURN:'+refund.returnCaseId,entitlementKey:{in:originals.map(a=>a.bonusAwardId)}},orderBy:{entitlementKey:'asc'}});
 check('K0 complete period posts every original entitlement',postings.length,2);
 check('K0 cumulative effective source replay',postings.map(p=>p.recalculatedEntitlement.toNumber()).sort((a,b)=>a-b),[100,500]);
 check('unaffected K0 entitlement receives positive pool normalization delta',postings.find(p=>p.entitlementKey===originals[1].bonusAwardId).delta.toString(),'23.6364');
 const positive=postings.find(p=>p.entitlementKey===originals[1].bonusAwardId),negative=postings.find(p=>p.entitlementKey===originals[0].bonusAwardId);
 assert.ok(positive.correctionAwardId);assert.ok(negative.recoveryId);
 const correction=await tx.bonusAward.findUniqueOrThrow({where:{bonusAwardId:positive.correctionAwardId}});
 check('positive replay delta creates exact compensating award',[correction.sourceAwardId,correction.recipientQualificationId,correction.awardType,correction.theoryAmount.toString(),correction.payableAmount.toString()],[originals[1].bonusAwardId,self.qualificationId,'REFERRAL','23.6364','23.6364'],{actual:[true,true,'REFERRAL','23.6364','23.6364'],expected:[true,true,'REFERRAL','23.6364','23.6364']});
 check('positive replay compensating award retains historical evidence',[correction.parameterSnapshotHash,correction.ruleVersionCode,correction.pendingUntil.toISOString(),correction.calculationDetail.snapshotId,correction.calculationDetail.actionKey],[historical.hash,version,originals[1].pendingUntil.toISOString(),positive.snapshotId,'RETURN:'+refund.returnCaseId],{actual:[true,true,'2020-02-17T00:00:00.000Z',true,true],expected:[true,true,'2020-02-17T00:00:00.000Z',true,true]});
 check('positive replay compensating award has one historical replay lifecycle',await tx.bonusAwardLifecycleEvent.count({where:{bonusAwardId:correction.bonusAwardId,reasonCode:'HISTORICAL_REPLAY'}}),1);
 const recoveryRow=await tx.bonusRecoveryEvent.findUniqueOrThrow({where:{bonusRecoveryEventId:negative.recoveryId}});
 check('negative replay delta creates exact original award recovery',[negative.delta.toString(),recoveryRow.bonusAwardId,recoveryRow.returnCaseId,recoveryRow.recoveryAmount.toString(),recoveryRow.outstandingAmount.toString(),recoveryRow.status],['-263.6364',originals[0].bonusAwardId,refund.returnCaseId,'263.6364','263.6364','OPEN'],{actual:['-263.6364',true,true,'263.6364','263.6364','OPEN'],expected:['-263.6364',true,true,'263.6364','263.6364','OPEN']});
 check('replay delta uses exactly one correction direction',[positive.recoveryId,negative.correctionAwardId],[null,null]);
 const beforeReplay=[await tx.entitlementReplayPosting.count(),await tx.bonusAward.count(),await tx.bonusRecoveryEvent.count()];
 await replay.processHistoricalReturn(tx,refund.returnCaseId);
 check('duplicate return creates no second posting compensating award or recovery',[await tx.entitlementReplayPosting.count(),await tx.bonusAward.count(),await tx.bonusRecoveryEvent.count()],beforeReplay,{actual:{postingDelta:0,awardDelta:0,recoveryDelta:0},expected:{postingDelta:0,awardDelta:0,recoveryDelta:0}});
 check('K0 original award baseline preserved',JSON.stringify(await tx.bonusAward.findMany({where:{bonusAwardId:{in:originals.map(a=>a.bonusAwardId)}},orderBy:{bonusAwardId:'asc'}})),saved,{actual:'UNCHANGED',expected:'UNCHANGED'});
 const envelope={format:'UCELL_HISTORICAL_REPLAY_V1',kind:'BINARY_K1',sourceId:randomUUID(),ruleVersionCode:version,at:'2020-01-08T00:00:00.000Z',parameters:historical,recipients:[],evidence:{sources:economic.map(e=>e.envelope),carryRecipients:[{qualificationId:self.qualificationId,leftCarryIn:'200',rightCarryIn:'0',leftCarryOut:'0',rightCarryOut:'0',weeklyCapSnapshot:'200',active:true,qualification:{plan:{planCode:'LEADER'},status:{status:'EFFECTIVE'}}}]},inputs:{}};
 const effective=await replay.effectiveGpv(tx,envelope.evidence.sources);
 envelope.recipients=[{key:'binary-original',awardId:'binary-original',awardType:'BINARY',qualificationId:self.qualificationId,generation:0,active:true,eligible:true,theory:'100',posted:'100',pendingUntil:'2020-03-01T00:00:00.000Z',detail:{},qualification:{plan:{planCode:'LEADER'},status:{status:'EFFECTIVE'},activeIntervals:[]}}];
 const projected=replay.periodBinary(envelope,effective,new Map());
 check('DB effective subtree honors partial return',effective.get(economic[0].event.eventId).toString(),'500');
 check('later reversal belongs to original historical week',gpvReversal.occurredAt>=chainOriginals[0].batch.periodEnd&&economic[0].event.occurredAt>=chainOriginals[0].batch.periodStart&&economic[0].event.occurredAt<chainOriginals[0].batch.periodEnd,true);
 check('historical cap preserves nonzero left carry',projected.carryOut.get(self.qualificationId).left.toString(),'500');
 check('historical cap preserves nonzero right carry',projected.carryOut.get(self.qualificationId).right.toString(),'800');
 const next={...envelope,evidence:{...envelope.evidence,sources:[]}};
 const continuation=replay.periodBinary(next,new Map(),projected.carryOut);
 check('carry continuation derives next historical left carry',continuation.carryOut.get(self.qualificationId).left.toString(),'300');
 check('carry continuation derives next historical right carry',continuation.carryOut.get(self.qualificationId).right.toString(),'600');
 const {RpvService}=require('../backend/apps/api/dist/modules/rpv/rpv.service.js');
 const {SubscriptionCancellationService}=require('../backend/apps/api/dist/modules/subscription/subscription-cancellation.service.js');
 const plan=await tx.subscriptionPlan.create({data:{planCode:'PHASE2_'+randomUUID(),displayName:'PHASE2 TEST ONLY',durationMonths:2,prepaidAmount:4000,productBoxQty:2,monthlyRecognizedAmount:2000,monthlyRpv:1200}});
 const sub=await tx.subscription.create({data:{qualificationId:leftQ.qualificationId,subscriptionPlanId:plan.subscriptionPlanId,orderId:economic[0].order.orderId,status:'ACTIVE',startMonth:new Date('2020-01-01'),endMonth:new Date('2020-02-01'),ruleVersionCode:version}});
 const recognized=await tx.monthlyRecognitionSchedule.create({data:{subscriptionId:sub.subscriptionId,installmentNo:1,recognitionMonth:new Date('2020-01-01'),recognizedAmount:2000,rpvAmount:1200,dueAt:new Date('2020-01-03'),ruleVersionCode:version}});
 const future=await tx.monthlyRecognitionSchedule.create({data:{subscriptionId:sub.subscriptionId,installmentNo:2,recognitionMonth:new Date('2020-02-01'),recognizedAmount:2000,rpvAmount:1200,dueAt:new Date('2020-02-03'),ruleVersionCode:version}});
 await new RpvService(facade,{}).recognize(recognized.recognitionId);
 const recognizedSchedule=await tx.monthlyRecognitionSchedule.findUniqueOrThrow({where:{recognitionId:recognized.recognitionId}});
 const recognitionEvent=await tx.pvLedger.findUniqueOrThrow({where:{eventId:recognizedSchedule.pvLedgerEventId}});
 check('due RPV recognition seals exact original ledger identity',[recognitionEvent.amount.toString(),recognitionEvent.pvType,recognitionEvent.eventType,recognitionEvent.sourceId,recognitionEvent.sourceLineId,recognitionEvent.qualificationId,recognitionEvent.occurredAt.toISOString()],['1200','RPV','RPV_CREATED',sub.subscriptionId,recognized.recognitionId,leftQ.qualificationId,recognized.dueAt.toISOString()],{actual:['1200','RPV','RPV_CREATED',true,true,true,'2020-01-03T00:00:00.000Z'],expected:['1200','RPV','RPV_CREATED',true,true,true,'2020-01-03T00:00:00.000Z']});
 check('due RPV recognition updates original schedule identity',[recognizedSchedule.status,recognizedSchedule.pvLedgerEventId,recognizedSchedule.recognitionMonth.toISOString()],['RECOGNIZED',recognitionEvent.eventId,recognized.recognitionMonth.toISOString()],{actual:['RECOGNIZED',true,'2020-01-01T00:00:00.000Z'],expected:['RECOGNIZED',true,'2020-01-01T00:00:00.000Z']});
 const rpvSnapshot=await tx.historicalReplaySnapshot.findUniqueOrThrow({where:{kind_sourceId:{kind:'RPV',sourceId:recognized.recognitionId}}});
 const originalRecognitionAwards=await tx.rpvUplineAwardEvent.findMany({where:{recognitionId:recognized.recognitionId},orderBy:{rpvAwardEventId:'asc'}});
 const countBeforeDuplicate=await tx.pvLedger.count({where:{sourceLineId:recognized.recognitionId,pvType:'RPV'}});
 check('duplicate RPV recognition reports already recognized',(await new RpvService(facade,{}).recognize(recognized.recognitionId)).skipped,'ALREADY_RECOGNIZED');
 check('RPV duplicate recognition appends no original event',await tx.pvLedger.count({where:{sourceLineId:recognized.recognitionId,pvType:'RPV'}}),countBeforeDuplicate);
 check('duplicate RPV recognition preserves all original awards',await tx.rpvUplineAwardEvent.findMany({where:{recognitionId:recognized.recognitionId},orderBy:{rpvAwardEventId:'asc'}}),originalRecognitionAwards,{actual:'UNCHANGED',expected:'UNCHANGED'});
 check('duplicate RPV recognition preserves entire historical snapshot',await tx.historicalReplaySnapshot.findUniqueOrThrow({where:{kind_sourceId:{kind:'RPV',sourceId:recognized.recognitionId}}}),rpvSnapshot,{actual:'UNCHANGED',expected:'UNCHANGED'});
 const rpvSource=await qualification(),rpvInactiveG1=await qualification(false),rpvActiveG2=await qualification();
 await tx.binaryPlacement.create({data:{parentQualificationId:rpvInactiveG1.qualificationId,childQualificationId:rpvSource.qualificationId,side:'LEFT',effectiveFrom:new Date('2020-01-01')}});
 await tx.binaryPlacement.create({data:{parentQualificationId:rpvActiveG2.qualificationId,childQualificationId:rpvInactiveG1.qualificationId,side:'LEFT',effectiveFrom:new Date('2020-01-01')}});
 const traversalSub=await tx.subscription.create({data:{qualificationId:rpvSource.qualificationId,subscriptionPlanId:plan.subscriptionPlanId,orderId:economic[1].order.orderId,status:'ACTIVE',startMonth:new Date('2020-01-01'),endMonth:new Date('2020-01-01'),ruleVersionCode:version}});
 const traversalRecognition=await tx.monthlyRecognitionSchedule.create({data:{subscriptionId:traversalSub.subscriptionId,installmentNo:1,recognitionMonth:new Date('2020-01-01'),recognizedAmount:2000,rpvAmount:1200,dueAt:new Date('2020-01-03'),ruleVersionCode:version}});
 await new RpvService(facade,{}).recognize(traversalRecognition.recognitionId);
 const traversalAwards=await tx.rpvUplineAwardEvent.findMany({where:{recognitionId:traversalRecognition.recognitionId},orderBy:{binaryGeneration:'asc'}});
 check('inactive RPV upline receives zero without compression',[traversalAwards[0].recipientQualificationId,traversalAwards[0].binaryGeneration,traversalAwards[0].activeSnapshot,traversalAwards[0].payableAmount.toString()],[rpvInactiveG1.qualificationId,1,false,'0'],{actual:[true,1,false,'0'],expected:[true,1,false,'0']});
 check('higher RPV generation evaluated independently',[traversalAwards[1].recipientQualificationId,traversalAwards[1].binaryGeneration,traversalAwards[1].activeSnapshot,traversalAwards[1].payableAmount.toString()],[rpvActiveG2.qualificationId,2,true,'100'],{actual:[true,2,true,'100'],expected:[true,2,true,'100']});
 for(const field of ['recognitionMonth','recognitionPeriod','eventId']){
   const content=JSON.parse(JSON.stringify(rpvSnapshot.content));delete content.inputs[field];
   await rejected('RPV missing '+field+' fails closed',()=>replay.verifyReplayEnvelope({...rpvSnapshot,content,hash:replay.replayHash(content)}),'HISTORICAL_SNAPSHOT_MISSING');
 }
 const missingBinary=JSON.parse(JSON.stringify(rpvSnapshot.content));delete missingBinary.evidence.binary;
 await rejected('RPV missing Binary evidence fails closed',()=>replay.verifyReplayEnvelope({...rpvSnapshot,content:missingBinary,hash:replay.replayHash(missingBinary)}),'HISTORICAL_SNAPSHOT_MISSING');
 const missingTimezone=JSON.parse(JSON.stringify(rpvSnapshot.content));missingTimezone.parameters.parameters=missingTimezone.parameters.parameters.filter(p=>p.code!=='accounting.timezone');
 const {hash:ignoredTimezoneHash,...timezoneBody}=missingTimezone.parameters;missingTimezone.parameters.hash=replay.replayHash(timezoneBody);
 await rejected('RPV missing historical timezone fails closed',()=>replay.verifyReplayEnvelope({...rpvSnapshot,content:missingTimezone,hash:replay.replayHash(missingTimezone)}),'HISTORICAL_SNAPSHOT_MISSING');
 const changedRecipient=JSON.parse(JSON.stringify(rpvSnapshot.content));changedRecipient.recipients[0].qualificationId=newSponsor.qualificationId;
 await rejected('RPV changed sealed recipient rejected',()=>replay.verifyReplayEnvelope({...rpvSnapshot,content:changedRecipient,hash:replay.replayHash(changedRecipient)}),'HISTORICAL_SNAPSHOT_CORRUPT');
 const rpvAwards=JSON.stringify(await tx.rpvUplineAwardEvent.findMany({where:{recognitionId:recognized.recognitionId},orderBy:{rpvAwardEventId:'asc'}}));
 const originalPlacement=await tx.binaryPlacement.findUniqueOrThrow({where:{childQualificationId:leftQ.qualificationId}});
 await tx.binaryPlacement.update({where:{binaryPlacementId:originalPlacement.binaryPlacementId},data:{effectiveTo:new Date('2020-01-04')}});
 await tx.binaryPlacement.update({where:{binaryPlacementId:originalPlacement.binaryPlacementId},data:{parentQualificationId:newSponsor.qualificationId,effectiveFrom:new Date('2020-01-04'),effectiveTo:null}});
 const cancellation=await new SubscriptionCancellationService(facade).cancel(sub.subscriptionId,new Date('2020-01-02'),'PHASE2_TEST');
 check('subscription future rows cancelled',(await tx.monthlyRecognitionSchedule.findUniqueOrThrow({where:{recognitionId:future.recognitionId}})).status,'CANCELLED');
 check('recognized affected event queued exactly once',cancellation.queuedRpvReversalCount,1);
 const outbox=await tx.outboxEvent.findFirstOrThrow({where:{aggregateId:recognized.recognitionId,eventType:'RPV_REVERSAL_REQUIRED'}});
 const claim={outboxEventId:outbox.outboxEventId,processStatus:'PENDING',attemptCount:0};
 check('conditional outbox claim succeeds once',(await tx.outboxEvent.updateMany({where:claim,data:{processStatus:'PROCESSING',attemptCount:1,availableAt:new Date(Date.now()+120000)}})).count,1);
 check('duplicate outbox claim rejected',(await tx.outboxEvent.updateMany({where:claim,data:{processStatus:'PROCESSING',attemptCount:1}})).count,0);
 await replay.consumeReplayOutbox(tx,outbox.outboxEventId);
 check('production replay consumer marks success atomically',(await tx.outboxEvent.findUniqueOrThrow({where:{outboxEventId:outbox.outboxEventId}})).processStatus,'PROCESSED');
 check('RPV one negative historical reversal',await tx.pvLedger.count({where:{reversalOfEventId:(await tx.monthlyRecognitionSchedule.findUniqueOrThrow({where:{recognitionId:recognized.recognitionId}})).pvLedgerEventId,pvType:'RPV',amount:-1200}}),1);
 const rpvPost=await tx.entitlementReplayPosting.findFirstOrThrow({where:{actionKey:'RPV:'+recognized.recognitionId+':'+cancellation.cancellation.subscriptionCancellationId}});
 const rpvRecovery=await tx.bonusRecoveryEvent.findUniqueOrThrow({where:{bonusRecoveryEventId:rpvPost.recoveryId}});
 const rpvAnchor=await tx.bonusAward.findUniqueOrThrow({where:{bonusAwardId:rpvRecovery.bonusAwardId}});
 check('RPV recovery anchor uses original RPV type and historical recipient',[rpvAnchor.awardType,rpvAnchor.payableAmount.toString(),rpvAnchor.recipientQualificationId===self.qualificationId],['RPV','0',true]);
 check('RPV historical recipient recovery delta',rpvPost.delta.toString(),'-100');
 check('RPV replay retains original recipient after Binary change',rpvPost.recipientQualificationId===self.qualificationId,true);
 check('RPV current Binary parent receives no recovery',await tx.entitlementReplayPosting.count({where:{actionKey:rpvPost.actionKey,recipientQualificationId:newSponsor.qualificationId}}),0);
 check('original RPV award rows unchanged',JSON.stringify(await tx.rpvUplineAwardEvent.findMany({where:{recognitionId:recognized.recognitionId},orderBy:{rpvAwardEventId:'asc'}})),rpvAwards,{actual:'UNCHANGED',expected:'UNCHANGED'});
 await replay.consumeReplayOutbox(tx,outbox.outboxEventId);
 check('RPV duplicate processing creates no second posting',await tx.entitlementReplayPosting.count({where:{actionKey:'RPV:'+recognized.recognitionId+':'+cancellation.cancellation.subscriptionCancellationId}}),1);
 const refund2=await tx.returnCase.create({data:{orderId:economic[0].order.orderId,status:'POSTED',reasonCode:'DOWNSTREAM_TEST',occurredAt:new Date('2020-01-11'),idempotencyKey:randomUUID(),correlationId:randomUUID(),lines:{create:{orderLineId:economic[0].order.lines[0].orderLineId,quantity:1,returnAmount:500,gpvReversalAmount:500}}}});
 // A later finalized period deliberately has no replay snapshot. Convergence at the preceding
 // unchanged carry boundary must stop traversal before this period is read.
 await tx.settlementBatch.create({data:{settlementType:'BINARY_K1',periodStart:new Date('2020-01-17'),periodEnd:new Date('2020-01-24'),ruleVersionCode:version,status:'FINALIZED',parameterSnapshot:historical,totalGpv:0,kFactor:1}});
 const incomplete=await replay.replayReturnDependencies(tx,refund2.returnCaseId,1);
 check('maxWeeks returns explicit incomplete status',[incomplete.status,incomplete.code,incomplete.periods,incomplete.maxWeeks],['REPLAY_INCOMPLETE','REPLAY_INCOMPLETE',1,1]);
 const horizonRun=await tx.settlementReplayRun.findUniqueOrThrow({where:{sourceReturnCaseId:refund2.returnCaseId}});
 check('maxWeeks persists resumable non-monetary checkpoint',[horizonRun.status,horizonRun.processedWeeks,horizonRun.maxWeeks],['MAX_HORIZON',1,1]);
 check('incomplete replay appends no monetary entitlement',await tx.entitlementReplayPosting.count({where:{actionKey:'RETURN:'+refund2.returnCaseId}}),0);
 check('incomplete replay appends exactly one immutable period checkpoint',await tx.settlementReplayPeriod.count({where:{settlementReplayRunId:horizonRun.settlementReplayRunId}}),1);
 await replay.processHistoricalReturn(tx,refund2.returnCaseId);
 const completedRun=await tx.settlementReplayRun.findUniqueOrThrow({where:{sourceReturnCaseId:refund2.returnCaseId}});
 check('resume converges same replay run',[completedRun.settlementReplayRunId===horizonRun.settlementReplayRunId,completedRun.status,completedRun.processedWeeks],[true,'CONVERGED',3]);
 check('resume preserves and completes append-only period checkpoints',await tx.settlementReplayPeriod.count({where:{settlementReplayRunId:horizonRun.settlementReplayRunId}}),3);
 const completedPeriods=await tx.settlementReplayPeriod.findMany({where:{settlementReplayRunId:horizonRun.settlementReplayRunId},orderBy:{periodNo:'asc'}});
 check('period checkpoints capture complete K1 and K2 replay',completedPeriods.map(period=>[period.periodNo,period.originalK1.toString(),period.recomputedK1.toString(),period.originalK2?.toString(),period.recomputedK2?.toString()]),[[1,'1','1','1','1'],[2,'1','1','1','1'],[3,'1','1','1','1']]);
 check('propagation stops at first converged carry and award boundary',[completedRun.processedWeeks,completedPeriods[2].impactedQualifications],[3,[]]);
 await rejected('replay period checkpoint UPDATE rejected by DB',()=>tx.settlementReplayPeriod.update({where:{settlementReplayPeriodId:completedPeriods[0].settlementReplayPeriodId},data:{periodNo:99}}),'UCell append-only table settlement_replay_period does not allow UPDATE/DELETE');
 check('complete replay processes affected periods through convergence',(await tx.replayAction.findUniqueOrThrow({where:{actionKey:'RETURN:'+refund2.returnCaseId}})).result.periods,3);
 const correctedCarry=await tx.replayCarryProjection.findFirstOrThrow({where:{actionKey:'RETURN:'+refund2.returnCaseId,settlementBatchId:chainOriginals[1].batch.settlementBatchId}});
 check('multi-return continuation retains valid historical right carry',correctedCarry.carry[self.qualificationId].right,'800');
 check('multi-return continuation re-derives left carry',correctedCarry.carry[self.qualificationId].left,'0');
 check('downstream Binary award replay uses corrected incoming carry',(await tx.entitlementReplayPosting.findFirstOrThrow({where:{actionKey:'RETURN:'+refund2.returnCaseId,entitlementKey:chainOriginals[1].award.bonusAwardId}})).delta.toString(),'-24');
 check('downstream Matching uses exact recalculated Binary source',(await tx.entitlementReplayPosting.findFirstOrThrow({where:{actionKey:'RETURN:'+refund2.returnCaseId,entitlementKey:chainOriginals[1].matching.bonusAwardId}})).recalculatedEntitlement.toString(),'0');
 check('complete replay posts every Binary entitlement',await tx.entitlementReplayPosting.count({where:{actionKey:'RETURN:'+refund2.returnCaseId,entitlementKey:{in:chainOriginals.map(original=>original.award.bonusAwardId)}}}),chainOriginals.length);
 check('complete replay posts every Matching entitlement',await tx.entitlementReplayPosting.count({where:{actionKey:'RETURN:'+refund2.returnCaseId,entitlementKey:{in:chainOriginals.map(original=>original.matching.bonusAwardId)}}}),chainOriginals.length);
 for(const [index,original] of chainOriginals.entries()){check('original carry immutable period '+(index+1),JSON.stringify(await tx.binaryCarry.findUniqueOrThrow({where:{binaryCarryId:original.carry.binaryCarryId}})),JSON.stringify(original.carry),{actual:'UNCHANGED',expected:'UNCHANGED'});check('original Binary award immutable period '+(index+1),JSON.stringify(await tx.bonusAward.findUniqueOrThrow({where:{bonusAwardId:original.award.bonusAwardId}})),JSON.stringify(original.award),{actual:'UNCHANGED',expected:'UNCHANGED'});}
 check('all original Binary settlement batches unchanged',(await Promise.all(chainOriginals.map(async original=>JSON.stringify(await tx.settlementBatch.findUniqueOrThrow({where:{settlementBatchId:original.batch.settlementBatchId}}))===JSON.stringify(original.batch)))).every(Boolean),true);
 check('all original Binary carry rows unchanged',(await Promise.all(chainOriginals.map(async original=>JSON.stringify(await tx.binaryCarry.findUniqueOrThrow({where:{binaryCarryId:original.carry.binaryCarryId}}))===JSON.stringify(original.carry)))).every(Boolean),true);
 check('all original Binary award rows unchanged',(await Promise.all(chainOriginals.map(async original=>JSON.stringify(await tx.bonusAward.findUniqueOrThrow({where:{bonusAwardId:original.award.bonusAwardId}}))===JSON.stringify(original.award)))).every(Boolean),true);
 check('all original Matching settlement batches unchanged',(await Promise.all(chainOriginals.map(async original=>JSON.stringify(await tx.settlementBatch.findUniqueOrThrow({where:{settlementBatchId:original.matchingBatch.settlementBatchId}}))===JSON.stringify(original.matchingBatch)))).every(Boolean),true);
 check('all original Matching award rows unchanged',(await Promise.all(chainOriginals.map(async original=>JSON.stringify(await tx.bonusAward.findUniqueOrThrow({where:{bonusAwardId:original.matching.bonusAwardId}}))===JSON.stringify(original.matching)))).every(Boolean),true);
 check('cancelled future recognition row retained',await tx.monthlyRecognitionSchedule.count({where:{recognitionId:future.recognitionId,status:'CANCELLED'}}),1);

 check('return downstream does not repeat RPV clawback',await tx.entitlementReplayPosting.count({where:{actionKey:'RPV:'+recognized.recognitionId+':'+cancellation.cancellation.subscriptionCancellationId}}),1);
 const failOutbox=await tx.outboxEvent.create({data:{eventType:'RPV_REVERSAL_REQUIRED',aggregateType:'MONTHLY_RECOGNITION',aggregateId:randomUUID(),payload:{recognitionId:randomUUID(),subscriptionCancellationId:cancellation.cancellation.subscriptionCancellationId},processStatus:'PENDING',correlationId:randomUUID()}});
 await rejected('consumer missing historical evidence fails closed',()=>replay.consumeReplayOutbox(tx,failOutbox.outboxEventId),'HISTORICAL_SNAPSHOT_MISSING');
 check('failed consumer does not publish PROCESSED',(await tx.outboxEvent.findUniqueOrThrow({where:{outboxEventId:failOutbox.outboxEventId}})).processStatus,'PENDING');
 await rejected('return event idempotency key is DB unique',()=>tx.returnCase.create({data:{orderId:order.orderId,status:'POSTED',reasonCode:'DUPLICATE',occurredAt:new Date('2020-01-11'),idempotencyKey:first.idempotencyKey,correlationId:randomUUID()}}),'Unique constraint');
 const missingOrder=await tx.order.create({data:{qualificationId:self.qualificationId,purpose:'RETAIL',status:'PAID',grossAmount:1,netAmount:1,ruleVersionCode:version,paidAt:new Date('2020-01-12')}});
 const missingReturn=await tx.returnCase.create({data:{orderId:missingOrder.orderId,status:'POSTED',reasonCode:'MISSING_SOURCE',occurredAt:new Date('2020-01-13'),idempotencyKey:randomUUID(),correlationId:randomUUID()}});
 const missingEvent=await tx.outboxEvent.create({data:{eventType:'RETURN_CONFIRMED',aggregateType:'RETURN',aggregateId:missingReturn.returnCaseId,payload:{returnCaseId:missingReturn.returnCaseId},processStatus:'PENDING',correlationId:randomUUID()}});
 const ledgerCount=await tx.pvLedger.count(),postingCount=await tx.entitlementReplayPosting.count();
 await rejected('entire return consumer fails closed without original GPV',()=>replay.consumeReplayOutbox(tx,missingEvent.outboxEventId),'HISTORICAL_SNAPSHOT_MISSING');
 check('missing original return evidence appends no ledger',await tx.pvLedger.count(),ledgerCount);
 check('missing original return evidence appends no award posting',await tx.entitlementReplayPosting.count(),postingCount);
 check('missing original return evidence publishes no success action',await tx.replayAction.count({where:{actionKey:'RETURN:'+missingReturn.returnCaseId}}),0);
 check('missing original return evidence leaves outbox retryable',(await tx.outboxEvent.findUniqueOrThrow({where:{outboxEventId:missingEvent.outboxEventId}})).processStatus,'PENDING');
 const laterOrder=await tx.order.create({data:{qualificationId:self.qualificationId,purpose:'REPURCHASE',status:'PAID',grossAmount:4800,netAmount:4800,ruleVersionCode:version,paidAt:new Date('2020-01-12'),lines:{create:{productId:product.productId,skuSnapshot:product.sku,productNameSnapshot:'POST RETURN CONSUMPTION TEST',quantity:3,unitPrice:1600,lineAmount:4800,gpvRateSnapshot:0,gpvAmountSnapshot:0,ruleProfileSnapshot:{testOnly:true}}}},include:{lines:true}});
 const laterGpv=await tx.pvLedger.create({data:{qualificationId:self.qualificationId,pvType:'GPV',amount:0,eventType:'GPV_CREATED',sourceType:'ORDER',sourceId:laterOrder.orderId,sourceLineId:laterOrder.lines[0].orderLineId,ruleVersionCode:version,occurredAt:laterOrder.paidAt,correlationId:randomUUID()}});await replay.sealGpvEvent(tx,laterGpv);
 check('new recognition continues reconciled monthly effective baseline',(await service.recognizeOrder(laterOrder.orderId,version)).epv,'2640');
 const {ReturnService}=require('../backend/apps/api/dist/modules/return/return.service.js');
 const {IdempotencyService}=require('../backend/apps/api/dist/common/idempotency/idempotency.service.js');
 const {AuditService}=require('../backend/apps/api/dist/common/audit/audit.service.js');
 const {OutboxService}=require('../backend/apps/api/dist/common/outbox/outbox.service.js');
 const idempotency=new IdempotencyService({idempotencyRecord:tx.idempotencyRecord,$transaction:fn=>fn(tx)});
 const returns=new ReturnService(facade,idempotency,new AuditService(),new OutboxService());
 const returnKey=randomUUID(),dto={reasonCode:'FINAL_PARTIAL_TEST',occurredAt:'2020-01-14T00:00:00.000Z',lines:[{orderLineId:order.lines[0].orderLineId,quantity:1}]};
 await rejected('cumulative returned quantity cannot exceed original quantity',()=>returns.post(order.orderId,{...dto,lines:[{orderLineId:order.lines[0].orderLineId,quantity:2}]},randomUUID(),randomUUID()),'DOMAIN_RULE_VIOLATION');
 const posted=await returns.post(order.orderId,dto,returnKey,randomUUID());
 check('real ReturnService limits final return to original remaining amount',posted.value.lines[0].returnAmount.toString(),'1600');
 check('real multi-return reaches cumulative full return',(await tx.order.findUniqueOrThrow({where:{orderId:order.orderId}})).status,'RETURNED');
 check('posted return creates historical Binary and Matching recalculation requests',(await tx.settlementRecalculationRequest.findMany({where:{sourceReturnCaseId:posted.value.returnCaseId},orderBy:{settlementType:'asc'}})).map(request=>[request.settlementType,request.status,request.impactedQualificationId]),[['BINARY_K1','PENDING',self.qualificationId],['MATCHING_K2','PENDING',self.qualificationId]],{actual:[['BINARY_K1','PENDING',true],['MATCHING_K2','PENDING',true]],expected:[['BINARY_K1','PENDING',true],['MATCHING_K2','PENDING',true]]});
 check('same return idempotency request replays',(await returns.post(order.orderId,dto,returnKey,randomUUID())).replayed,true);
 check('idempotent return creates no duplicate recalculation requests',await tx.settlementRecalculationRequest.count({where:{sourceReturnCaseId:posted.value.returnCaseId}}),2);
 check('same return request publishes one transactional outbox',await tx.outboxEvent.count({where:{aggregateId:posted.value.returnCaseId,eventType:'RETURN_CONFIRMED'}}),1);
 const finalOutbox=await tx.outboxEvent.findFirstOrThrow({where:{aggregateId:posted.value.returnCaseId,eventType:'RETURN_CONFIRMED'}});await replay.consumeReplayOutbox(tx,finalOutbox.outboxEventId);
 check('successful historical replay processes recalculation requests',(await tx.settlementRecalculationRequest.findMany({where:{sourceReturnCaseId:posted.value.returnCaseId},orderBy:{settlementType:'asc'}})).map(request=>[request.settlementType,request.status,Boolean(request.processedAt)]),[['BINARY_K1','PROCESSED',true],['MATCHING_K2','PROCESSED',true]]);
 const ledgerBeforeDelivery=await tx.pvLedger.count(),postingBeforeDelivery=await tx.entitlementReplayPosting.count();
 await replay.consumeReplayOutbox(tx,finalOutbox.outboxEventId);
 check('duplicate RETURN_CONFIRMED appends no ledger',await tx.pvLedger.count(),ledgerBeforeDelivery);
 check('duplicate RETURN_CONFIRMED appends no entitlement posting',await tx.entitlementReplayPosting.count(),postingBeforeDelivery);
 const laterEvent=await tx.pvLedger.findFirstOrThrow({where:{sourceId:laterOrder.orderId,pvType:'EPV',eventType:'EPV_CREATED'}});
 const laterSponsorAward=await tx.bonusAward.findFirstOrThrow({where:{sourceEventId:laterEvent.eventId,recipientQualificationId:newSponsor.qualificationId}});
 check('cross-event recalculation uses later original earning recipient',(await tx.entitlementReplayPosting.findFirstOrThrow({where:{actionKey:'RETURN:'+posted.value.returnCaseId,entitlementKey:laterSponsorAward.bonusAwardId}})).delta.toString(),'-57.6');
 check('earlier historical recipient has no duplicate final clawback',(await tx.entitlementReplayPosting.findFirstOrThrow({where:{actionKey:'RETURN:'+posted.value.returnCaseId,recipientQualificationId:oldSponsor.qualificationId}})).delta.toString(),'0');
 check('later historical earning original ledger is immutable',(await tx.pvLedger.findUniqueOrThrow({where:{eventId:laterEvent.eventId}})).amount.toString(),'2640');

 await rejected('different request with same return key is rejected',()=>returns.post(order.orderId,{...dto,reasonCode:'CHANGED'},returnKey,randomUUID()),'IDEMPOTENCY_CONFLICT');
 const discounted=await tx.order.create({data:{qualificationId:self.qualificationId,purpose:'RETAIL',status:'PAID',grossAmount:200,discountAmount:50,netAmount:150,ruleVersionCode:version,paidAt:new Date('2020-01-12'),lines:{create:{productId:product.productId,skuSnapshot:product.sku,productNameSnapshot:'CAP TEST',quantity:2,unitPrice:100,lineAmount:200,gpvRateSnapshot:0,gpvAmountSnapshot:0,ruleProfileSnapshot:{testOnly:true}}}},include:{lines:true}});
 const capDto={reasonCode:'CAP_TEST',occurredAt:'2020-01-14T00:00:00.000Z',lines:[{orderLineId:discounted.lines[0].orderLineId,quantity:1}]};
 await returns.post(discounted.orderId,capDto,randomUUID(),randomUUID());
 await rejected('cumulative money cap rejects available quantity over net amount',()=>returns.post(discounted.orderId,capDto,randomUUID(),randomUUID()),'RETURN_AMOUNT_EXCEEDED');
 check('failed over-return preserves effective return baseline',(await tx.returnLine.aggregate({where:{returnCase:{orderId:discounted.orderId,status:'POSTED'}},_sum:{returnAmount:true}}))._sum.returnAmount.toString(),'100');
 const {SettlementCalendarService}=require('../backend/apps/api/dist/modules/settlement/settlement-calendar.service.js');
 const {snapshotDecimal}=require('../backend/apps/api/dist/modules/rules/parameter-snapshot.js');
 for(const [parameterCode,valueJson] of [['settlement.timezone','UTC'],['settlement.period',{unit:'WEEK',count:2,anchorLocal:'2020-01-01T00:00:00'}],['settlement.cut_off',{localTime:'13:15:00',daysAfterPeriodEnd:1,approvalReference:'TEST_ONLY_NOT_OPERATIONAL_APPROVAL'}]])await tx.runtimeRuleParameter.create({data:{ruleVersionCode:version,parameterCode,scopeKey:'BINARY_K1',valueJson,effectiveFrom:new Date('2019-01-01')}});
 const calendar=new SettlementCalendarService(facade),configured=await captureParameters(tx,new Date('2020-01-05'),version);
 const period=await calendar.periodFor(tx,new Date('2020-01-05'),configured,'BINARY_K1');
 check('explicit TEST calendar period bounds',[period.start.toISOString(),period.end.toISOString()],['2020-01-01T00:00:00.000Z','2020-01-15T00:00:00.000Z']);
 await tx.runtimeRuleParameter.updateMany({where:{ruleVersionCode:version,parameterCode:'binary.pair.rate',scopeKey:'*'},data:{effectiveTo:new Date('2020-01-16T13:15:00Z')}});
 await tx.runtimeRuleParameter.create({data:{ruleVersionCode:version,parameterCode:'binary.pair.rate',valueJson:'.2',effectiveFrom:new Date('2020-01-16T13:15:00Z')}});
 const atCutoff=await calendar.captureForPeriod(tx,period.start,period.end,'BINARY_K1',version);
 check('explicit TEST cutoff determines snapshot time',atCutoff.effectiveAt,'2020-01-16T13:15:00.000Z');
 check('parameter effective exactly at cutoff selected',snapshotDecimal(atCutoff,'binary.pair.rate').toString(),'0.2');
 check('earlier captured parameter remains historical',snapshotDecimal(historical,'binary.pair.rate').toString(),'0.12');
 const {RecoveryBalanceService}=require('../backend/apps/api/dist/modules/payout/recovery-balance.service.js');
 const {UnifiedPayableService}=require('../backend/apps/api/dist/modules/payout/unified-payable.service.js');
 const recovery=new RecoveryBalanceService(facade),payables=new UnifiedPayableService(facade,recovery);
 const priorOutstanding=(await tx.bonusRecoveryEvent.aggregate({where:{bonusAward:{recipientQualificationId:self.qualificationId}},_sum:{outstandingAmount:true}}))._sum.outstandingAmount;
 let firstLine;
 for(const capacity of [100,200]){
  const earned=await tx.bonusAward.create({data:{awardType:'REFERRAL',recipientQualificationId:self.qualificationId,sourceEventId:randomUUID(),theoryAmount:capacity,payableAmount:capacity,activeSnapshot:true,ruleVersionCode:version,occurredAt:new Date('2020-02-01'),pendingUntil:new Date('2020-03-17'),calculationDetail:{testOnly:true,subtype:'OFFSET_CAPACITY_INPUT_FIXTURE'}}});
  await tx.payableEntry.create({data:{qualificationId:self.qualificationId,sourceType:'BONUS_AWARD',sourceId:earned.bonusAwardId,awardType:'REFERRAL',grossAmount:capacity,availableAt:new Date('2020-03-17'),status:'OPEN',ruleVersionCode:version}});
  const payout=await payables.createPayoutBatch(new Date('2020-03-01'),new Date('2020-04-01'),version);
  const line=await tx.payoutLine.findFirstOrThrow({where:{payoutBatchId:payout.payoutBatchId,recipientQualificationId:self.qualificationId}});
  check('PAID clawback offset limited to new payout capacity '+capacity,line.recoveryOffset.toString(),String(capacity));check('PAID clawback offset preserves nonnegative net '+capacity,line.netAmount.toString(),'0');if(!firstLine)firstLine=line;
 }
 const beforeApplications=await tx.recoveryApplication.count({where:{payoutLineId:firstLine.payoutLineId}});
 check('same payout line offset replay is idempotent',(await recovery.apply(tx,{qualificationId:self.qualificationId,payoutLineId:firstLine.payoutLineId,maxAmount:new Prisma.Decimal(100)})).applied.toString(),'100');
 check('same payout line creates no duplicate offset application',await tx.recoveryApplication.count({where:{payoutLineId:firstLine.payoutLineId}}),beforeApplications);
 check('multi-batch clawback outstanding decreases only once per capacity',priorOutstanding.sub((await tx.bonusRecoveryEvent.aggregate({where:{bonusAward:{recipientQualificationId:self.qualificationId}},_sum:{outstandingAmount:true}}))._sum.outstandingAmount).toString(),'300');
 check('offset does not overwrite original PAID history',await tx.bonusAwardLifecycleEvent.findUniqueOrThrow({where:{lifecycleEventId:paidEvent.lifecycleEventId}}),paidEvent,{actual:'UNCHANGED',expected:'UNCHANGED'});
 throw rollback;
},{timeout:120000,isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}catch(error){if(error!==rollback)failure=error;}finally{await prisma.$disconnect();}
const out=new URL('../../governance/phase2-return-replay/final/',import.meta.url);fs.mkdirSync(out,{recursive:true});fs.writeFileSync(process.env.PHASE2_DB_EVIDENCE_PATH??new URL('db-regression.json',out),JSON.stringify({result:failure?'FAIL':'PASS',fixturesRolledBack:true,results,...(failure?{error:failure.stack}:{})},null,2)+'\n');
if(failure){console.error(failure);process.exitCode=1;}else console.log(`PASS ${results.length} real DB assertions; fixtures rolled back`);
