import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
import {readFileSync,writeFileSync} from 'node:fs';
const require=createRequire(new URL('../../member/package.json',import.meta.url));
const {chromium}=require('playwright');
const fixture=JSON.parse(readFileSync(new URL('../../governance/analytics/browser-fixture.json',import.meta.url),'utf8'));
const browser=await chromium.launch({headless:true,channel:'msedge'}),page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));const requests=[];let role='SUPER_ADMIN';
await page.addInitScript(()=>sessionStorage.setItem('ucell_admin_token','ANALYTICS_ISOLATED_UI_TEST'));
await page.route('**/api/v1/**',async route=>{
  const url=new URL(route.request().url()),path=url.pathname.replace('/api/v1','');requests.push(path);
  let data;
  if(path==='/auth/admin/me')data={role,subject:'ISOLATED TEST',provider:'TEST'};
  else if(path==='/admin/analytics/overview')data=fixture.overview;
  else if(path==='/admin/analytics/nasl/history')data=fixture.history;
  else if(path==='/admin/analytics/nasl/cohorts')data=fixture.cohorts;
  else if(path==='/admin/analytics/policy-versions')data=fixture.versions;
  else if(path==='/admin/analytics/refresh/status')data=fixture.refresh;
  else if(path===`/admin/analytics/sonar/sponsor/${fixture.root}/volumes`)data=fixture.volumeSponsor;
  else if(path===`/admin/analytics/sonar/binary/${fixture.root}/volumes`)data=fixture.volumeBinary;
  else if(path==='/admin/analytics/roots')data=fixture.roots;
  else if(path.endsWith('/contributors'))data=fixture.contributors;
  else if(path===`/admin/analytics/sonar/sponsor/${fixture.root}`)data=fixture.sponsor;
  else if(path===`/admin/analytics/sonar/binary/${fixture.root}`)data=fixture.binary;
  else if(path==='/admin/analytics/rebuild')data={snapshotId:'TEST_REBUILD',replayed:false};
  else return route.fulfill({status:404,json:{message:'Unexpected test route '+path}});
  await route.fulfill({json:{data}});
});
try{
  await page.goto('http://127.0.0.1:4191/analytics');await page.getByRole('heading',{name:'NASL／十二代組織健康雷達',exact:true}).waitFor();
  await page.getByLabel('組織起點（不包含起點本身）').selectOption(fixture.root);
  await page.getByRole('img',{name:/十二代活躍與重購比例雷達/}).waitFor();
  await page.getByLabel('業績量類型',{exact:true}).selectOption('EPV');
  await page.getByLabel('業績量類型',{exact:true}).selectOption('GPV');
  await page.getByRole('meter',{name:'第 1 代 GPV 淨量 80.1234',exact:true}).waitFor();
  await page.getByRole('region',{name:'同期群留存表，可水平捲動'}).waitFor();
  await page.getByLabel('留存指標',{exact:true}).selectOption('activeRetention');
  await page.getByLabel('歷史起日（含）').fill('2026-01-01');
  const filtered=page.waitForRequest(r=>r.url().includes('/nasl/cohorts?')&&r.url().includes('from=2026-01-01'));
  await page.getByRole('button',{name:'查詢歷史',exact:true}).click();await filtered;
  assert.equal(await page.locator('.nasl-heading h2').evaluate(el=>getComputedStyle(el).color),'rgb(238, 245, 252)','Dark-card heading remains readable under application styles');
  assert.equal(await page.getByRole('cell',{name:'第 12 代',exact:true}).count(),1);
  await page.screenshot({path:fileURLToPath(new URL('../../governance/analytics/desktop.png',import.meta.url)),fullPage:true});
  await page.getByLabel('組織關係').selectOption('binary');await page.getByRole('heading',{name:'雙軌組織 · 十二代雷達'}).waitFor();
  await page.getByText('已採最新重算修正',{exact:false}).waitFor();
  await page.getByRole('button',{name:'更新 NASL 與此組織雷達'}).click();assert.ok(requests.includes('/admin/analytics/rebuild'));
  await page.setViewportSize({width:390,height:844});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'No horizontal page overflow on mobile');
  await page.screenshot({path:fileURLToPath(new URL('../../governance/analytics/mobile.png',import.meta.url)),fullPage:true});
  role='FINANCE';await page.reload();await page.getByRole('heading',{name:'NASL／十二代組織健康雷達',exact:true}).waitFor();
  assert.equal(await page.getByRole('button',{name:/更新 NASL/}).count(),0,'Finance cannot rebuild');
  role='CUSTOMER_SERVICE';const before=requests.length;await page.reload();await page.getByRole('heading',{name:'無權存取此後台頁面'}).waitFor();
  assert.equal(requests.slice(before).filter(path=>path.startsWith('/admin/analytics')).length,0,'Unauthorized page does not issue analytics requests');
  assert.deepEqual(errors,[]);writeFileSync(new URL('../../governance/analytics/browser-results.json',import.meta.url),JSON.stringify({status:'PASS',fixture:fixture.label,viewports:[1440,390],checks:['12 generations','tree switch','rebuild wiring','mobile overflow','finance read only','customer-service denied before query','no page errors']},null,2));
  console.log('ANALYTICS_BROWSER_PASS');
}finally{await browser.close();}
