import {ConflictException,Injectable,NotFoundException,UnprocessableEntityException} from '@nestjs/common';
import {Prisma,PrismaService,appendMemberMessage} from '@ucell/database';
import {createHash,randomUUID} from 'node:crypto';
import {AuditService} from '../../common/audit/audit.service';
import {IdempotencyService} from '../../common/idempotency/idempotency.service';

type Lesson={title:string;contentType:'VIDEO_REFERENCE'|'DOCUMENT_REFERENCE'|'ARTICLE'|'EXTERNAL_LINK';contentReference:string;required?:boolean};
type CourseInput={courseCode:string;title:string;summary?:string;categoryCode:string;publishFrom?:string;publishTo?:string;lessons:Lesson[]};
const code=/^[A-Z][A-Z0-9_-]{2,39}$/;
@Injectable() export class LearningService{constructor(private db:PrismaService,private idempotency:IdempotencyService,private audit:AuditService){}
 async outreach(courseCode:string,memberNo:string,action:'ASSIGN'|'REMIND',reason:string,actor:string,key:string,requestId:string){
  if(!code.test(courseCode)||!/^\d{10}$/.test(memberNo)||!['ASSIGN','REMIND'].includes(action)||typeof reason!=='string'||!reason.trim()||reason.length>500)throw new UnprocessableEntityException('LEARNING_OUTREACH_INVALID');
  return (await this.execute(`admin:learning:outreach:${actor}`,key,{courseCode,memberNo,action,reason},async tx=>{
   await tx.$queryRaw(Prisma.sql`SELECT learning_course_id FROM learning.learning_course WHERE course_code=${courseCode} FOR UPDATE`);
   const c=await tx.learningCourse.findUnique({where:{courseCode},include:{versions:{where:{status:'PUBLISHED'},orderBy:{version:'desc'},take:1}}});
   await tx.$queryRaw(Prisma.sql`SELECT person_id FROM identity.person WHERE member_no=${memberNo} FOR UPDATE`);
   const person=await tx.person.findUnique({where:{memberNo},select:{personId:true,membershipState:true}});
   if(!c||!person||!['NETWORK_MEMBER','FORMAL_PENDING','FORMAL_MEMBER'].includes(person.membershipState??''))throw new NotFoundException('LEARNING_TARGET_NOT_AVAILABLE');
   let e=await tx.learningEnrollment.findUnique({where:{learningCourseId_personId:{learningCourseId:c.learningCourseId,personId:person.personId}},include:{courseVersion:true}});
   const v=e?.courseVersion??c.versions[0];if(!v||!this.open(c.status,v))throw new ConflictException('LEARNING_COURSE_NOT_OPEN');
   if(action==='ASSIGN'&&e)return {courseCode,memberNo,status:'ALREADY_ENROLLED',replayed:true};
   if(action==='REMIND'&&(!e||!['ENROLLED','STARTED'].includes(e.status)))throw new ConflictException('LEARNING_REMINDER_NOT_APPLICABLE');
   if(!e)e=await tx.learningEnrollment.create({data:{learningCourseId:c.learningCourseId,learningCourseVersionId:v.learningCourseVersionId,personId:person.personId,progressEvents:{create:{eventType:'COURSE_ENROLLED',idempotencyKey:`learning-enroll:${person.personId}:${c.learningCourseId}`,evidenceHash:createHash('sha256').update(`${person.personId}:${v.learningCourseVersionId}`).digest('hex')}}},include:{courseVersion:true}});
   const day=new Date(Date.now()+8*3600000).toISOString().slice(0,10),messageKey=action==='ASSIGN'?`learning:assigned:${e.learningEnrollmentId}`:`learning:reminder:${e.learningEnrollmentId}:${day}`;
   const existing=await tx.memberNotification.findUnique({where:{messageKey}});
   if(existing)return {courseCode,memberNo,status:'ALREADY_NOTIFIED',replayed:true};
   if(action==='ASSIGN')await tx.learningProgressEvent.create({data:{learningEnrollmentId:e.learningEnrollmentId,eventType:'COURSE_ASSIGNED',idempotencyKey:`learning-assign:${e.learningEnrollmentId}`,evidenceHash:createHash('sha256').update(JSON.stringify({actor,reason,version:v.learningCourseVersionId})).digest('hex')}});
   await appendMemberMessage(tx,{messageKey,personId:person.personId,category:'LEARNING',title:action==='ASSIGN'?'已為您指派課程':'課程學習提醒',body:action==='ASSIGN'?`已為您指派課程 ${courseCode}，請至教育訓練查看。`:`您加入的課程 ${courseCode} 尚未完成，請至教育訓練查看。`,sourceType:'LEARNING_COURSE',sourceReference:`COURSE:${courseCode}`,deepLink:`/learning?course=${courseCode}`,...(v.publishTo?{expiresAt:v.publishTo}:{})});
   await this.audit.write(tx,{actorType:'USER',actorId:actor,action:action==='ASSIGN'?'LEARNING_COURSE_ASSIGNED':'LEARNING_REMINDER_CREATED',entityType:'LearningEnrollment',entityId:e.learningEnrollmentId,afterData:{courseCode,memberNo,version:v.version,reason,channel:'UCELL_PERSONAL'},requestId,correlationId:randomUUID()});
   return {courseCode,memberNo,status:action==='ASSIGN'?'ASSIGNED':'REMINDER_CREATED',replayed:false};
  })).value;
 }
 private async execute<T>(scope:string,key:string,input:unknown,work:(tx:Prisma.TransactionClient)=>Promise<T>){for(let attempt=0;;attempt++){try{return await this.idempotency.execute(scope,key,input,work);}catch(error){if(attempt<3&&['P2034','P2002'].includes((error as any)?.code))continue;throw error;}}}
 private async lock(tx:Prisma.TransactionClient,courseId:string,versionId:string){await tx.$queryRaw(Prisma.sql`SELECT learning_course_id FROM learning.learning_course WHERE learning_course_id=${courseId}::uuid FOR UPDATE`);const c=await tx.learningCourse.findUniqueOrThrow({where:{learningCourseId:courseId}});const v=await tx.learningCourseVersion.findUniqueOrThrow({where:{learningCourseVersionId:versionId}});if(!this.open(c.status,v))throw new ConflictException('LEARNING_COURSE_NOT_OPEN');}
 async archive(courseCode:string,reason:string,actor:string,key:string,requestId:string){if(!code.test(courseCode)||typeof reason!=='string'||!reason.trim()||reason.length>500)throw new UnprocessableEntityException('LEARNING_ARCHIVE_INVALID');return (await this.execute(`admin:learning:archive:${courseCode}:${actor}`,key,{reason},async tx=>{await tx.$queryRaw(Prisma.sql`SELECT learning_course_id FROM learning.learning_course WHERE course_code=${courseCode} FOR UPDATE`);const c=await tx.learningCourse.findUnique({where:{courseCode}});if(!c)throw new NotFoundException('LEARNING_COURSE_NOT_FOUND');if(c.status==='ARCHIVED')return {courseCode,status:'ARCHIVED',replayed:true};await tx.learningCourse.update({where:{learningCourseId:c.learningCourseId},data:{status:'ARCHIVED'}});await tx.memberNotification.updateMany({where:{sourceReference:`COURSE:${courseCode}`,messageKey:{startsWith:'learning:reminder:'},retiredAt:null},data:{retiredAt:new Date()}});await this.audit.write(tx,{actorType:'USER',actorId:actor,action:'LEARNING_COURSE_ARCHIVED',entityType:'LearningCourse',entityId:c.learningCourseId,beforeData:{status:c.status},afterData:{courseCode,status:'ARCHIVED',reason},requestId,correlationId:randomUUID()});return {courseCode,status:'ARCHIVED',replayed:false};})).value;}
 private input(input:CourseInput){if(!code.test(input?.courseCode??'')||typeof input.title!=='string'||!input.title.trim()||!code.test(input.categoryCode??'')||!Array.isArray(input.lessons)||!input.lessons.length||input.lessons.length>100)throw new UnprocessableEntityException('LEARNING_COURSE_INVALID');const from=input.publishFrom?new Date(input.publishFrom):null,to=input.publishTo?new Date(input.publishTo):null;if(from&&(!Number.isFinite(from.getTime())||to&&to<=from)||to&&!Number.isFinite(to.getTime()))throw new UnprocessableEntityException('LEARNING_PUBLISH_WINDOW_INVALID');const lessons=input.lessons.map((x,i)=>{if(!x||typeof x.title!=='string'||!x.title.trim()||!['VIDEO_REFERENCE','DOCUMENT_REFERENCE','ARTICLE','EXTERNAL_LINK'].includes(x.contentType)||typeof x.contentReference!=='string'||!x.contentReference.trim())throw new UnprocessableEntityException('LEARNING_LESSON_INVALID');if(x.contentType!=='ARTICLE'){let u:URL;try{u=new URL(x.contentReference);}catch{throw new UnprocessableEntityException('LEARNING_CONTENT_REFERENCE_INVALID');}if(u.protocol!=='https:'||u.username||u.password)throw new UnprocessableEntityException('LEARNING_CONTENT_REFERENCE_INVALID');}return {sequenceNo:i+1,title:x.title.trim(),contentType:x.contentType,contentReference:x.contentReference.trim(),required:x.required!==false};});return {courseCode:input.courseCode,title:input.title.trim(),summary:input.summary?.trim()||null,categoryCode:input.categoryCode,publishFrom:from,publishTo:to,lessons};}
 async create(input:CourseInput,actor:string,key:string,requestId:string){const value=this.input(input);return (await this.execute(`admin:learning:create:${actor}`,key,input,async tx=>{const course=await tx.learningCourse.create({data:{courseCode:value.courseCode,createdByActor:actor}});const hash=createHash('sha256').update(JSON.stringify(value)).digest('hex');const version=await tx.learningCourseVersion.create({data:{learningCourseId:course.learningCourseId,version:1,title:value.title,summary:value.summary,categoryCode:value.categoryCode,publishFrom:value.publishFrom,publishTo:value.publishTo,contentHash:hash,lessons:{create:value.lessons}}});await this.audit.write(tx,{actorType:'USER',actorId:actor,action:'LEARNING_COURSE_CREATED',entityType:'LearningCourse',entityId:course.learningCourseId,afterData:{courseCode:value.courseCode,version:1,contentHash:hash},requestId,correlationId:randomUUID()});return {courseCode:value.courseCode,version:1,status:'DRAFT'};})).value;}
 async publish(courseCode:string,approvalReference:string,actor:string,key:string,requestId:string){if(!code.test(courseCode)||typeof approvalReference!=='string'||!approvalReference.trim())throw new UnprocessableEntityException('LEARNING_PUBLISH_INVALID');return (await this.execute(`admin:learning:publish:${courseCode}:${actor}`,key,{approvalReference},async tx=>{await tx.$queryRaw(Prisma.sql`SELECT learning_course_id FROM learning.learning_course WHERE course_code=${courseCode} FOR UPDATE`);const course=await tx.learningCourse.findUnique({where:{courseCode},include:{versions:{where:{status:'DRAFT'},orderBy:{version:'desc'},take:1}}});const version=course?.versions[0];if(!course||!version||course.status==='ARCHIVED')throw new ConflictException('LEARNING_VERSION_NOT_PUBLISHABLE');const now=new Date();await tx.learningCourseVersion.update({where:{learningCourseVersionId:version.learningCourseVersionId},data:{status:'PUBLISHED',approvalReference:approvalReference.trim(),approvedByActor:actor,approvedAt:now}});await tx.learningCourse.update({where:{learningCourseId:course.learningCourseId},data:{status:'PUBLISHED'}});await this.audit.write(tx,{actorType:'USER',actorId:actor,action:'LEARNING_COURSE_PUBLISHED',entityType:'LearningCourseVersion',entityId:version.learningCourseVersionId,afterData:{courseCode,version:version.version,contentHash:version.contentHash},requestId,correlationId:randomUUID()});return {courseCode,version:version.version,status:'PUBLISHED'};})).value;}
 async adminList(){const rows=await this.db.learningCourse.findMany({include:{versions:{include:{lessons:{orderBy:{sequenceNo:'asc'}}},orderBy:{version:'desc'}},_count:{select:{enrollments:true}}},orderBy:[{createdAt:'desc'},{courseCode:'asc'}],take:100});return rows.map(c=>({courseCode:c.courseCode,status:c.status,createdAt:c.createdAt.toISOString(),enrollmentCount:c._count.enrollments,versions:c.versions.map(v=>({version:v.version,title:v.title,summary:v.summary,categoryCode:v.categoryCode,audiencePolicy:v.audiencePolicy,status:v.status,publishFrom:v.publishFrom?.toISOString()??null,publishTo:v.publishTo?.toISOString()??null,approvedAt:v.approvedAt?.toISOString()??null,contentHash:v.contentHash,lessons:v.lessons.map(l=>({sequenceNo:l.sequenceNo,title:l.title,contentType:l.contentType,contentReference:l.contentReference,required:l.required}))}))}));}
 private async visible(courseCode:string,now=new Date()){const version=await this.db.learningCourseVersion.findFirst({where:{course:{courseCode,status:'PUBLISHED'},status:'PUBLISHED',audiencePolicy:'NETWORK_MEMBER',OR:[{publishFrom:null},{publishFrom:{lte:now}}],AND:[{OR:[{publishTo:null},{publishTo:{gt:now}}]}]},include:{course:true,lessons:{orderBy:{sequenceNo:'asc'}}},orderBy:{version:'desc'}});if(!version)throw new NotFoundException('LEARNING_COURSE_NOT_FOUND');return version;}
 private async memberAllowed(personId:string){const person=await this.db.person.findUnique({where:{personId},select:{membershipState:true}});if(!person||!['NETWORK_MEMBER','FORMAL_PENDING','FORMAL_MEMBER'].includes(person.membershipState??''))throw new NotFoundException('LEARNING_COURSE_NOT_FOUND');}
 async memberList(personId:string){try{await this.memberAllowed(personId);}catch(error){if(error instanceof NotFoundException)return [];throw error;}const rows=await this.db.learningCourse.findMany({where:{OR:[{status:'PUBLISHED'},{enrollments:{some:{personId}}}]},include:{versions:{where:{status:'PUBLISHED'},orderBy:{version:'desc'},take:1,include:{lessons:true}},enrollments:{where:{personId},take:1,include:{courseVersion:{include:{lessons:true}},progressEvents:{where:{eventType:'LESSON_COMPLETED'}}}}},orderBy:[{createdAt:'desc'},{courseCode:'asc'}],take:100});return rows.flatMap(c=>{const e=c.enrollments[0],v=e?.courseVersion??c.versions[0];if(!v)return [];const available=this.open(c.status,v);if(!e&&!available)return [];return [{courseCode:c.courseCode,title:v.title,summary:v.summary,categoryCode:v.categoryCode,version:v.version,lessonCount:v.lessons.length,status:e?.status??'AVAILABLE',courseStatus:c.status,available,completedLessonCount:e?.progressEvents.length??0,completedAt:e?.completedAt?.toISOString()??null}];});}
 async memberDetail(personId:string,courseCode:string){await this.memberAllowed(personId);return this.db.$transaction(async tx=>{const c=await tx.learningCourse.findUnique({where:{courseCode},include:{versions:{where:{status:'PUBLISHED'},orderBy:{version:'desc'},take:1,include:{lessons:{orderBy:{sequenceNo:'asc'}}}},enrollments:{where:{personId},take:1,include:{courseVersion:{include:{lessons:{orderBy:{sequenceNo:'asc'}}}},progressEvents:true}}}});if(!c)throw new NotFoundException('LEARNING_COURSE_NOT_FOUND');const e=c.enrollments[0],v=e?.courseVersion??c.versions[0];if(!v)throw new NotFoundException('LEARNING_COURSE_NOT_FOUND');const available=this.open(c.status,v);if(!e&&!available)throw new NotFoundException('LEARNING_COURSE_NOT_FOUND');const done=new Map(e?.progressEvents.filter(x=>x.eventType==='LESSON_COMPLETED').map(x=>[x.learningLessonId,x.occurredAt])??[]),required=v.lessons.filter(x=>x.required);return {courseCode,title:v.title,summary:v.summary,categoryCode:v.categoryCode,version:v.version,courseStatus:c.status,available,lessons:v.lessons.map(x=>({sequenceNo:x.sequenceNo,title:x.title,contentType:x.contentType,contentReference:x.contentReference,required:x.required,completedAt:done.get(x.learningLessonId)?.toISOString()??null})),status:e?.status??'AVAILABLE',startedAt:e?.startedAt?.toISOString()??null,completedAt:e?.completedAt?.toISOString()??null,requiredLessonCount:required.length,completedRequiredCount:required.filter(x=>done.has(x.learningLessonId)).length,canComplete:!!e&&['ENROLLED','STARTED'].includes(e.status)&&available&&required.every(x=>done.has(x.learningLessonId))};},{isolationLevel:Prisma.TransactionIsolationLevel.RepeatableRead});}
 private open(status:string,v:{status:string;audiencePolicy:string;publishFrom:Date|null;publishTo:Date|null}){const now=new Date();return status==='PUBLISHED'&&v.status==='PUBLISHED'&&v.audiencePolicy==='NETWORK_MEMBER'&&(!v.publishFrom||v.publishFrom<=now)&&(!v.publishTo||v.publishTo>now);}
 async enroll(personId:string,courseCode:string,key:string,requestId:string){await this.memberAllowed(personId);const v=await this.visible(courseCode);return (await this.execute(`member:learning:enroll:${personId}`,key,{courseCode},async tx=>{await this.lock(tx,v.learningCourseId,v.learningCourseVersionId);const existing=await tx.learningEnrollment.findUnique({where:{learningCourseId_personId:{learningCourseId:v.learningCourseId,personId}}});if(existing)return {courseCode,status:existing.status,replayed:true};const e=await tx.learningEnrollment.create({data:{learningCourseId:v.learningCourseId,learningCourseVersionId:v.learningCourseVersionId,personId,progressEvents:{create:{eventType:'COURSE_ENROLLED',idempotencyKey:`learning-enroll:${personId}:${v.learningCourseId}`,evidenceHash:createHash('sha256').update(`${personId}:${v.learningCourseVersionId}`).digest('hex')}}}});await appendMemberMessage(tx,{messageKey:`learning:enrolled:${e.learningEnrollmentId}`,personId,category:'LEARNING',title:'課程報名完成',body:`您已報名課程 ${courseCode}。`,sourceType:'LEARNING_COURSE',sourceReference:`COURSE:${courseCode}`,deepLink:`/learning?course=${courseCode}`});return {courseCode,status:e.status,replayed:false};})).value;}
 async lessonCompleted(personId:string,courseCode:string,sequenceNo:number,key:string){await this.memberAllowed(personId);const v=await this.visible(courseCode),e=await this.db.learningEnrollment.findUnique({where:{learningCourseId_personId:{learningCourseId:v.learningCourseId,personId}},include:{courseVersion:{include:{lessons:true}}}});if(!e)throw new ConflictException('LEARNING_ENROLLMENT_REQUIRED');const lesson=e.courseVersion.lessons.find(x=>x.sequenceNo===sequenceNo);if(!lesson)throw new NotFoundException('LEARNING_LESSON_NOT_FOUND');return (await this.execute(`member:learning:lesson:${personId}`,key,{courseCode,sequenceNo},async tx=>{await this.lock(tx,v.learningCourseId,e.learningCourseVersionId);const current=await tx.learningEnrollment.findUniqueOrThrow({where:{learningEnrollmentId:e.learningEnrollmentId}});if(current.status==='CANCELLED')throw new ConflictException('LEARNING_ENROLLMENT_CANCELLED');const prior=await tx.learningProgressEvent.findFirst({where:{learningEnrollmentId:e.learningEnrollmentId,learningLessonId:lesson.learningLessonId,eventType:'LESSON_COMPLETED'}});if(prior)return {courseCode,sequenceNo,status:current.status,replayed:true};const event=await tx.learningProgressEvent.create({data:{learningEnrollmentId:e.learningEnrollmentId,learningLessonId:lesson.learningLessonId,eventType:'LESSON_COMPLETED',idempotencyKey:`learning-lesson:${e.learningEnrollmentId}:${lesson.learningLessonId}`,evidenceHash:createHash('sha256').update(`${e.learningEnrollmentId}:${lesson.learningLessonId}`).digest('hex')}});if(current.status==='COMPLETED')throw new ConflictException('LEARNING_COURSE_ALREADY_COMPLETED');if(current.status==='ENROLLED'){await tx.learningProgressEvent.create({data:{learningEnrollmentId:e.learningEnrollmentId,eventType:'COURSE_STARTED',occurredAt:event.occurredAt,idempotencyKey:`learning-start:${e.learningEnrollmentId}`,evidenceHash:createHash('sha256').update(`learning-start:${e.learningEnrollmentId}`).digest('hex')}});await tx.learningEnrollment.update({where:{learningEnrollmentId:e.learningEnrollmentId},data:{status:'STARTED',startedAt:event.occurredAt}});}return {courseCode,sequenceNo,status:'STARTED',replayed:false};})).value;}
 async complete(personId:string,courseCode:string,key:string,requestId:string){await this.memberAllowed(personId);const v=await this.visible(courseCode),e=await this.db.learningEnrollment.findUnique({where:{learningCourseId_personId:{learningCourseId:v.learningCourseId,personId}},include:{courseVersion:{include:{lessons:true}}}});if(!e)throw new ConflictException('LEARNING_ENROLLMENT_REQUIRED');return (await this.execute(`member:learning:complete:${personId}`,key,{courseCode},async tx=>{await this.lock(tx,v.learningCourseId,e.learningCourseVersionId);const current=await tx.learningEnrollment.findUniqueOrThrow({where:{learningEnrollmentId:e.learningEnrollmentId}});if(current.status==='COMPLETED')return {courseCode,status:'COMPLETED',replayed:true};if(current.status==='CANCELLED')throw new ConflictException('LEARNING_ENROLLMENT_CANCELLED');const required=e.courseVersion.lessons.filter(x=>x.required).map(x=>x.learningLessonId);const done=await tx.learningProgressEvent.findMany({where:{learningEnrollmentId:e.learningEnrollmentId,eventType:'LESSON_COMPLETED'},select:{learningLessonId:true}});if(required.some(id=>!done.some(row=>row.learningLessonId===id)))throw new ConflictException('LEARNING_REQUIRED_LESSONS_INCOMPLETE');const now=new Date();if(!current.startedAt)await tx.learningProgressEvent.create({data:{learningEnrollmentId:e.learningEnrollmentId,eventType:'COURSE_STARTED',occurredAt:now,idempotencyKey:`learning-start:${e.learningEnrollmentId}`,evidenceHash:createHash('sha256').update(`learning-start:${e.learningEnrollmentId}`).digest('hex')}});await tx.learningProgressEvent.create({data:{learningEnrollmentId:e.learningEnrollmentId,eventType:'COURSE_COMPLETED',occurredAt:now,idempotencyKey:`learning-complete:${personId}:${e.learningEnrollmentId}`,evidenceHash:createHash('sha256').update(`${e.learningEnrollmentId}:${now.toISOString()}`).digest('hex')}});await tx.learningEnrollment.update({where:{learningEnrollmentId:e.learningEnrollmentId},data:{status:'COMPLETED',startedAt:current.startedAt??now,completedAt:now}});await tx.memberNotification.updateMany({where:{personId,messageKey:{startsWith:`learning:reminder:${e.learningEnrollmentId}:`},retiredAt:null},data:{retiredAt:now}});await appendMemberMessage(tx,{messageKey:`learning:completed:${e.learningEnrollmentId}`,personId,category:'LEARNING',title:'課程學習完成',body:`您已完成課程 ${courseCode}。`,sourceType:'LEARNING_COURSE',sourceReference:`COURSE:${courseCode}`,deepLink:`/learning?course=${courseCode}`});return {courseCode,status:'COMPLETED',replayed:false};})).value;}
}
