import {useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {command,get} from '../../lib/api';
import {Badge,Card,ErrorBox,Field,PageHeader} from '../../components/ui';
import {AdminTable} from '../../components/AdminTable';
import {useAuth} from '../auth/auth';

type Job={id:string;kind:string;periodStart:string;periodEnd:string;ruleVersionCode:string;approvalReference:string;createdAt:string;status:string;attemptCount:number;availableAt:string;lastError?:string|null;completedAt?:string|null;operational?:{jobReference:string;state:string;overdue:boolean|null;eligibleAt:string|null;maturesAt:string|null;waiting:{sourceEvents:number;recognitions:number;prerequisites:number};dependencies:{reference:string;kind:string;complete:boolean}[]}};
const labels:Record<string,string>={REFERRAL_K0:'推薦獎金',BINARY_K1:'雙軌獎金',MATCHING_K2:'對等獎金',GLOBAL:'全球分紅',WELFARE:'福利提撥',PAYABLE_PREPARATION:'應付準備',PENDING:'等待執行',PROCESSING:'執行中',PROCESSED:'已完成',DEAD:'執行失敗',READY:'可執行',RUNNING:'執行中',COMPLETED:'已完成',FAILED:'需要處理',EVIDENCE_INCONSISTENT:'完成證據不一致',WAITING_PREREQUISITE:'等待前置結算',WAITING_SOURCE_INPUTS:'等待來源處理',WAITING_RECOGNITION:'等待月認列',WAITING_MATURITY:'等待獎金成熟',LEASE_EXPIRED:'執行逾時，可重新排程',RETRY_SCHEDULED:'已排程重試'};
const tone=(status:string)=>status==='PROCESSED'?'ok':status==='DEAD'?'danger':status==='PROCESSING'?'warn':'neutral';
const when=(value?:string|null)=>value?new Date(value).toLocaleString('zh-TW'):'—';

export function SettlementJobsPage(){
 const {user}=useAuth(),client=useQueryClient();
 const [status,setStatus]=useState(''),[reason,setReason]=useState('人工確認來源已就緒，重新排程執行。');
 const [threshold,setThreshold]=useState('24'),[appliedThreshold,setAppliedThreshold]=useState<number|null>(null);
 const query=useQuery({queryKey:['settlement-jobs',status,appliedThreshold],queryFn:()=>get<{data:Job[]}>(`/admin/settlement-jobs?take=100${status?'&status='+status:''}${appliedThreshold?'&thresholdHours='+appliedThreshold:''}`),refetchInterval:15000});
 const retry=useMutation({mutationFn:(id:string)=>command(`/admin/settlement-jobs/${id}/retry`,{reason}),onSuccess:()=>client.invalidateQueries({queryKey:['settlement-jobs']})});
 const rows=query.data?.data??[],canRetry=['SUPER_ADMIN','FINANCE'].includes(user?.role??'');
 return <><PageHeader title="結算工作" subtitle="查看六類結算的等待原因與完成證據，處理需要重新排程的工作。" actions={<button onClick={()=>query.refetch()} disabled={query.isFetching}>重新整理</button>}/>
 <ErrorBox error={query.error??retry.error}/><Card title="篩選與重試"><div className="filter-grid"><Field label="執行狀態"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">全部</option>{['PENDING','PROCESSING','PROCESSED','DEAD'].map(x=><option key={x} value={x}>{labels[x]}</option>)}</select></Field><Field label="重試原因" hint="重新排程後仍會等待來源、前置結算與獎金成熟。"><input value={reason} minLength={3} maxLength={500} onChange={e=>setReason(e.target.value)}/></Field></div>
 <form onSubmit={e=>{e.preventDefault();const hours=Number(threshold);if(Number.isInteger(hours)&&hours>=1&&hours<=8760)setAppliedThreshold(hours);}}><Field label="營運逾時門檻（小時）" hint="從核准截止時間或獎金成熟時間中較晚者計算；供本次查詢使用。"><input required type="number" min="1" max="8760" value={threshold} onChange={e=>setThreshold(e.target.value)}/></Field><button type="submit">套用逾時門檻</button></form><p className="muted">{appliedThreshold?`目前以 ${appliedThreshold} 小時判定逾時。`:'尚未套用逾時門檻。'}</p></Card>
 <Card title={`近期工作（${rows.length}）`}>{query.isPending?<p>正在載入結算工作…</p>:rows.length===0?<p>目前沒有符合條件的結算工作。</p>:<div className="table-wrap"><AdminTable><thead><tr><th>種類／期間</th><th>規則／核准</th><th>狀態與等待原因</th><th>嘗試</th><th>預計可處理／完成</th><th>操作</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{labels[row.kind]??row.kind}</strong><br/><small>{when(row.periodStart)} → {when(row.periodEnd)}</small>{row.operational&&<><br/><small>{row.operational.jobReference}</small></>}</td><td>{row.ruleVersionCode}<br/><small>{row.approvalReference}</small></td><td><Badge tone={tone(row.status)}>{labels[row.operational?.state??row.status]??row.status}</Badge>{row.operational?.overdue&&<Badge tone="danger">已逾查詢門檻</Badge>}{row.lastError&&<p>上次執行失敗，請確認來源與稽核紀錄。</p>}{row.operational&&<><p className="muted">待處理來源 {row.operational.waiting.sourceEvents}／月認列 {row.operational.waiting.recognitions}／前置結算 {row.operational.waiting.prerequisites}</p>{row.operational.dependencies.length>0&&<details><summary>前置結算</summary>{row.operational.dependencies.map(parent=><p key={parent.reference}>{labels[parent.kind]??parent.kind}：{parent.complete?'已完成':'等待完成'} <small>{parent.reference}</small></p>)}</details>}</>}</td><td>{row.attemptCount}</td><td>{when(row.completedAt??row.operational?.maturesAt??row.availableAt)}</td><td><button disabled={!canRetry||retry.isPending||reason.trim().length<3||row.status==='PROCESSED'||row.operational?.state==='EVIDENCE_INCONSISTENT'||(row.status==='PROCESSING'&&new Date(row.availableAt)>new Date())} onClick={()=>retry.mutate(row.id)}>重新排程</button></td></tr>)}</tbody></AdminTable></div>}<p className="muted">稽核角色可唯讀；財務與系統管理員可重新排程。已完成的結算保留原始證據。</p></Card></>;
}
