import {randomUUID} from 'node:crypto';
import {PrismaService,Prisma,captureParameters,recognizeConsumption,sealGpvEvent,processHistoricalReturn} from '@ucell/database';
import {BinaryTreeService,TreePrincipal} from '../src/modules/binary-tree/binary-tree.service';
import {OrganizationService} from '../src/modules/organization/organization.service';
import {IdempotencyService} from '../src/common/idempotency/idempotency.service';
import {BonusQueryService} from '../src/modules/bonus/bonus-query.service';
import {EpvService} from '../src/modules/epv/epv.service';
import {EpvMonthService} from '../src/modules/epv/epv-month.service';
import {RpvService} from '../src/modules/rpv/rpv.service';
import {UnifiedPayableService} from '../src/modules/payout/unified-payable.service';
const url=process.env.PHASE2_TEST_DATABASE_URL;
if(!url||!/^ucell_jest_[a-f0-9]{32}$/.test(new URL(url).pathname.slice(1)))throw Error('ISOLATED_DATABASE_REQUIRED');
const db=new PrismaService();afterAll(()=>db.$disconnect());
it('Core EPV and RPV route Company finals to B; EPV return adds signed effects and duplicate recognition stays exactly once',async()=>{
 const person=await db.person.create({data:{legalName:'SYNTHETIC COMPANY VOLUMES'}}),subject=randomUUID();
 await db.identityLink.create({data:{personId:person.personId,provider:'ENTRA',providerSubject:subject}});
 await db.adminAccessGrant.create({data:{personId:person.personId,provider:'ENTRA',providerSubject:subject,roleCode:'SUPER_ADMIN',validFrom:new Date(Date.now()-1000)}});
 const session=await db.authSession.create({data:{personId:person.personId,provider:'ENTRA',subject,roleCode:'SUPER_ADMIN',tokenHash:randomUUID(),issuedAt:new Date(),expiresAt:new Date(Date.now()+3600000)}});
 const p:TreePrincipal={personId:person.personId,provider:'ENTRA',subject,role:'SUPER_ADMIN',sessionId:session.authSessionId},trees=new BinaryTreeService(db,new IdempotencyService(db),new OrganizationService(db));
 const tree=(await trees.create(p,{treeName:'Company EPV RPV Golden',reason:'Synthetic'},randomUUID())).value;
 await trees.change(p,tree.binaryTreeId,{status:'ACTIVE',expectedVersion:1,reason:'Synthetic'},randomUUID());
 const at=new Date(),q=await db.qualification.create({data:{currentHolderPersonId:person.personId,planLevelCode:'STARTER',status:'EFFECTIVE',effectiveAt:at}});
 await db.qualificationPlanHistory.create({data:{qualificationId:q.qualificationId,planCode:'STARTER',effectiveFrom:at,sourceType:'SYNTHETIC'}});
 await db.qualificationStatusHistory.create({data:{qualificationId:q.qualificationId,status:'EFFECTIVE',effectiveFrom:at,sourceType:'SYNTHETIC'}});
 await db.qualificationHolderHistory.create({data:{qualificationId:q.qualificationId,holderPersonId:person.personId,effectiveFrom:at,sourceType:'SYNTHETIC',sourceId:randomUUID()}});
 await trees.confirmCompanySponsor(p,tree.binaryTreeId,{qualificationId:q.qualificationId,reason:'Synthetic'},randomUUID());
 await trees.place(p,tree.binaryTreeId,{qualificationId:q.qualificationId,binaryParentQualificationId:tree.companyQualificationIds[1],side:'LEFT',expectedVersion:2,reason:'Synthetic'},randomUUID());
 const paidAt=new Date(),snapshot=await captureParameters(db as unknown as Prisma.TransactionClient,paidAt,'R1.0B');
 const product=await db.productReference.create({data:{sku:'COMPANY-VOLUME-'+randomUUID(),displayName:'Synthetic',currentPrice:2000}});
 const order=await db.order.create({data:{qualificationId:q.qualificationId,purpose:'REPURCHASE',status:'PAID',paidAt,grossAmount:10000,netAmount:10000,ruleVersionCode:'R1.0B',parameterSnapshotHash:snapshot.hash,lines:{create:{productId:product.productId,skuSnapshot:product.sku,productNameSnapshot:product.displayName,quantity:5,unitPrice:2000,lineAmount:10000,gpvRateSnapshot:1,gpvAmountSnapshot:10000,ruleProfileSnapshot:{synthetic:true}}}},include:{lines:true}});
 await db.$transaction(async tx=>{const r=await recognizeConsumption(tx,{qualificationId:q.qualificationId,sourceType:'ORDER',sourceId:order.orderId,sourceLineId:order.lines[0].orderLineId,amount:10000,eligible:true,concreteVolumeType:'GPV',productProfileVersion:'SYNTHETIC',ruleVersionCode:'R1.0B',parameterSnapshotHash:snapshot.hash,recognizedAt:paidAt,activeThreshold:'2000'});await sealGpvEvent(tx,r.volume!);},{timeout:30000});
 const epv=new EpvService(db,{} as any,new BonusQueryService(db),new EpvMonthService());
 const recognized=await epv.recognizeOrder(order.orderId);expect(recognized.eventId).toBeTruthy();
 const companyEpv=await db.awardEconomicDestination.findFirstOrThrow({where:{binaryTreeId:tree.binaryTreeId,awardType:'EPV'},include:{effects:true,sourceBonusAward:true}});
 expect(companyEpv.effects).toHaveLength(1);expect(companyEpv.effects[0].amountDelta.eq(companyEpv.sourceBonusAward!.payableAmount)).toBe(true);
 expect(companyEpv.sourceBonusAward!.planLevelSnapshot).toBe('LEADER');expect(companyEpv.effects[0].amountDelta.gt(0)).toBe(true);
 expect(await epv.recognizeOrder(order.orderId)).toMatchObject({skipped:'ALREADY_RECOGNIZED'});
 const ret=await db.returnCase.create({data:{orderId:order.orderId,status:'POSTED',postedAt:new Date(),occurredAt:new Date(),reasonCode:'SYNTHETIC',idempotencyKey:randomUUID(),correlationId:randomUUID(),lines:{create:{orderLineId:order.lines[0].orderLineId,quantity:1,returnAmount:2000,gpvReversalAmount:2000}}}});
 await db.$transaction(tx=>processHistoricalReturn(tx,ret.returnCaseId),{timeout:30000});
 const effects=await db.reservoirBEffect.findMany({where:{destinationId:companyEpv.destinationId}});
 expect(effects).toHaveLength(2);expect(effects.some(e=>e.amountDelta.lt(0))).toBe(true);
 const rate=(code:string,scope='*')=>new Prisma.Decimal(snapshot.parameters.find(p=>p.code===code&&p.scope===scope)!.value as string);
 const expectedEpv=new Prisma.Decimal(8000).sub(rate('epv.base_amount')).mul(rate('epv.rate'));
 expect(effects.reduce((n,e)=>n.add(e.amountDelta),new Prisma.Decimal(0)).eq(expectedEpv.mul(rate('epv.upline.rate','1')))).toBe(true);
 await db.$transaction(tx=>processHistoricalReturn(tx,ret.returnCaseId),{timeout:30000});expect(await db.reservoirBEffect.count({where:{destinationId:companyEpv.destinationId}})).toBe(2);
 const dueAt=new Date(),month=new Date(new Date(dueAt.getTime()+8*3600000).toISOString().slice(0,7)+'-01T00:00:00.000Z');
 const plan=await db.subscriptionPlan.create({data:{planCode:'SYNTHETIC-'+randomUUID(),displayName:'Synthetic RPV',durationMonths:1,prepaidAmount:2000,productBoxQty:1,monthlyRecognizedAmount:2000,monthlyRpv:2000}});
 const subscription=await db.subscription.create({data:{qualificationId:q.qualificationId,subscriptionPlanId:plan.subscriptionPlanId,status:'ACTIVE',startMonth:month,endMonth:month,ruleVersionCode:'R1.0B',parameterSnapshotHash:snapshot.hash,activatedAt:dueAt}});
 const schedule=await db.monthlyRecognitionSchedule.create({data:{subscriptionId:subscription.subscriptionId,installmentNo:1,recognitionMonth:month,recognizedAmount:plan.monthlyRecognizedAmount,rpvAmount:plan.monthlyRpv,dueAt,ruleVersionCode:'R1.0B',parameterSnapshotHash:snapshot.hash}});
 const rpv=new RpvService(db,{} as any);expect(await rpv.recognize(schedule.recognitionId)).toMatchObject({ancestorCount:2});
 const rpvDestinations=await db.awardEconomicDestination.findMany({where:{binaryTreeId:tree.binaryTreeId,awardType:'RPV'},include:{effects:true,sourceRpvAward:true}});
 expect(rpvDestinations).toHaveLength(2);
 for(const destination of rpvDestinations){expect(destination.effects).toHaveLength(1);expect(destination.effects[0].amountDelta.eq(destination.sourceRpvAward!.payableAmount)).toBe(true);expect(destination.sourceRpvAward!.activeSnapshot).toBe(true);expect(destination.bindingId).toBeTruthy();}
 expect(await rpv.recognize(schedule.recognitionId)).toMatchObject({skipped:'ALREADY_RECOGNIZED'});
 expect(await db.reservoirBEffect.count({where:{destination:{binaryTreeId:tree.binaryTreeId,awardType:'RPV'}}})).toBe(2);
 await new UnifiedPayableService(db,{} as any).materialize(new Date());
 expect(await db.payableEntry.count({where:{qualificationId:{in:tree.companyQualificationIds}}})).toBe(0);
 expect(await db.bonusRecoveryEvent.count({where:{bonusAward:{recipientQualificationId:{in:tree.companyQualificationIds}}}})).toBe(0);
},120000);
