import {BadRequestException} from '@nestjs/common';
import {Prisma} from '@prisma/client';
import {CompensationPeriodControlController} from '../src/modules/settlement-jobs/compensation-period-control.controller';
import {CompensationPeriodControlService} from '../src/modules/settlement-jobs/compensation-period-control.service';

const d=(value:string|number)=>new Prisma.Decimal(value),uuid='11111111-1111-4111-8111-111111111111';
function fixture(){
 const jobs=['REFERRAL_K0','BINARY_K1','MATCHING_K2','GLOBAL'].map((kind,index)=>({periodCloseJobId:`00000000-0000-4000-8000-00000000000${index}`,kind,outbox:{processStatus:'PROCESSED',attemptCount:1,lastError:null},receipt:{completedAt:new Date('2026-09-09T00:00:00Z')}}));
 const tx:any={periodCloseJob:{findMany:jest.fn().mockResolvedValue(jobs)},settlementBatch:{findMany:jest.fn().mockResolvedValue([{settlementBatchId:uuid,settlementType:'REFERRAL_K0',status:'FINALIZED',totalTheory:d(100),poolAvailable:d(80),kFactor:d('.8'),finalizedAt:new Date('2026-09-09Z')}])},bonusAward:{aggregate:jest.fn().mockResolvedValue({_count:2,_sum:{theoryAmount:d(100),payableAmount:d(80)}}),count:jest.fn().mockResolvedValue(0)},bonusRecoveryEvent:{aggregate:jest.fn().mockResolvedValue({_count:1,_sum:{recoveryAmount:d(10),recoveredAmount:d(10),outstandingAmount:d(0)}})},reservoirLedgerEffect:{aggregate:jest.fn().mockResolvedValue({_count:1,_sum:{amount:d(5)}})},payoutBatch:{findMany:jest.fn().mockResolvedValue([{payoutBatchId:uuid,status:'PAID',totalGross:d(80),totalRecovery:d(10),totalNet:d(70),createdAt:new Date(),approvals:[{stage:'FINANCE_REVIEW',decision:'APPROVED'}],exportArtifacts:[{exportReference:'BANK-1',revision:1,generatedAt:new Date()}],paymentResults:[{payoutLineId:uuid,resultStatus:'PAID',paidAmount:d(70),occurredAt:new Date()}]}])},fulfillmentErpHandoff:{count:jest.fn().mockResolvedValue(0)},$queryRaw:jest.fn().mockResolvedValue([{total:2n,open:0n,gross:d(80)}])};
 return {tx,db:{$transaction:jest.fn((work:any)=>work(tx))}};
}
describe('COMPENSATION_PERIOD_CONTROL',()=>{
 it('does not let a paid payout override a blocking close job',async()=>{
  const {db,tx}=fixture();tx.periodCloseJob.findMany.mockResolvedValue([{periodCloseJobId:uuid,kind:'REFERRAL_K0',outbox:{processStatus:'DEAD',attemptCount:10,lastError:'PERIOD_CLOSE_EXECUTION_FAILED'},receipt:null}]);
  expect((await new CompensationPeriodControlService(db as any).read({periodStart:'2026-09-01Z',periodEnd:'2026-09-08Z',ruleVersionCode:'R1.0B'})).lifecycle).toBe('BLOCKED');
 });
 it.each(['missingJobs','pendingAwards','openPayables'])('does not financially close paid payouts with %s',async condition=>{
  const {db,tx}=fixture();
  if(condition==='missingJobs')tx.periodCloseJob.findMany.mockResolvedValue([]);
  if(condition==='pendingAwards')tx.bonusAward.count.mockResolvedValue(1);
  if(condition==='openPayables')tx.$queryRaw.mockResolvedValue([{total:2n,open:1n,gross:d(80)}]);
  expect((await new CompensationPeriodControlService(db as any).read({periodStart:'2026-09-01Z',periodEnd:'2026-09-08Z',ruleVersionCode:'R1.0B'})).lifecycle).not.toBe('FINANCIALLY_RECONCILED');
 });
 it('counts cumulative payment confirmations once per line',async()=>{
  const {db,tx}=fixture(),rows=await tx.payoutBatch.findMany();
  rows[0].paymentResults=[{payoutLineId:uuid,resultStatus:'PAID',paidAmount:d(40),occurredAt:new Date('2026-09-10Z')},{payoutLineId:uuid,resultStatus:'PAID',paidAmount:d(70),occurredAt:new Date('2026-09-11Z')}];
  const result=await new CompensationPeriodControlService(db as any).read({periodStart:'2026-09-01Z',periodEnd:'2026-09-08Z',ruleVersionCode:'R1.0B'});
  expect(result.amountBridge.bankPaid).toBe('70.0000');
 });
 it.each([{paymentResults:[]},{paymentResults:[{payoutLineId:uuid,resultStatus:'PAID',paidAmount:d(40),occurredAt:new Date()}]}])('requires bank evidence matching net even when the batch is marked PAID',async({paymentResults})=>{
  const {db,tx}=fixture(),rows=await tx.payoutBatch.findMany();rows[0].paymentResults=paymentResults;
  expect((await new CompensationPeriodControlService(db as any).read({periodStart:'2026-09-01Z',periodEnd:'2026-09-08Z',ruleVersionCode:'R1.0B'})).lifecycle).toBe('BANK_RECONCILING');
 });
 it('allows only Finance and Compliance read roles',()=>{expect(Reflect.getMetadata('roles',CompensationPeriodControlController)).toEqual(['SUPER_ADMIN','FINANCE','COMPLIANCE_AUDIT']);});
 it('derives a member-economic lifecycle while keeping ERP accounting separate',async()=>{const {db}=fixture(),result=await new CompensationPeriodControlService(db as any).read({periodStart:'2026-09-01T00:00:00Z',periodEnd:'2026-09-08T00:00:00Z',ruleVersionCode:'R1.0B'}),serialized=JSON.stringify(result);expect(result.lifecycle).toBe('FINANCIALLY_RECONCILED');expect(result.amountBridge).toMatchObject({grossTheory:'100.0000',awardAfterEligibilityAndK:'80.0000',companyReservoirB:'5.0000',recoveryRequired:'10.0000',payoutNet:'70.0000',bankPaid:'70.0000',erpAccountingProjection:null});expect(result.checkpoints.find(row=>row.code==='ERP_ACCOUNTING')).toMatchObject({status:'BLOCKED_EXTERNAL'});expect(result.authority.hardClose).toBe('Not persisted by this read model');expect(serialized).not.toContain(uuid);});
 it('surfaces failed governed jobs as blocking without inventing a close',async()=>{const {db,tx}=fixture();tx.periodCloseJob.findMany.mockResolvedValue([{periodCloseJobId:uuid,kind:'REFERRAL_K0',outbox:{processStatus:'DEAD',attemptCount:10,lastError:'PERIOD_CLOSE_EXECUTION_FAILED'},receipt:null}]);tx.payoutBatch.findMany.mockResolvedValue([]);const result=await new CompensationPeriodControlService(db as any).read({periodStart:'2026-09-01T00:00:00Z',periodEnd:'2026-09-08T00:00:00Z',ruleVersionCode:'R1.0B'});expect(result.lifecycle).toBe('BLOCKED');expect(result.blockingExceptions[0]).toMatchObject({code:'PERIOD_CLOSE_EXECUTION_FAILED',status:'OPEN'});expect(result.blockingExceptions[0].reference).not.toContain(uuid);});
 it('does not expose raw Worker error text through the control read',async()=>{const {db,tx}=fixture();tx.periodCloseJob.findMany.mockResolvedValue([{periodCloseJobId:uuid,kind:'GLOBAL',outbox:{processStatus:'DEAD',attemptCount:2,lastError:'connection failed for member@example.test with token secret'},receipt:null}]);tx.payoutBatch.findMany.mockResolvedValue([]);const result=await new CompensationPeriodControlService(db as any).read({periodStart:'2026-09-01T00:00:00Z',periodEnd:'2026-09-08T00:00:00Z',ruleVersionCode:'R1.0B'});expect(result.jobs[0].blockingCode).toBe('PERIOD_CLOSE_FAILED');expect(result.blockingExceptions[0].code).toBe('PERIOD_CLOSE_FAILED');expect(JSON.stringify(result)).not.toContain('member@example.test');});
 it('derives Soft Close only from all four immutable unstarted requests',async()=>{const {db,tx}=fixture();tx.periodCloseJob.findMany.mockResolvedValue(['REFERRAL_K0','BINARY_K1','MATCHING_K2','GLOBAL'].map((kind,index)=>({periodCloseJobId:`00000000-0000-4000-8000-00000000000${index}`,kind,outbox:{processStatus:'PENDING',attemptCount:0,lastError:null},receipt:null})));tx.payoutBatch.findMany.mockResolvedValue([]);const result=await new CompensationPeriodControlService(db as any).read({periodStart:'2026-09-01T00:00:00Z',periodEnd:'2026-09-08T00:00:00Z',ruleVersionCode:'R1.0B'});expect(result.lifecycle).toBe('SOFT_CLOSED');expect(result.checkpoints.find(row=>row.code==='SOFT_CLOSE')).toMatchObject({status:'PASS'});expect(result.checkpoints.find(row=>row.code==='HISTORICAL_CORRECTION')).toMatchObject({status:'PASS'});});
 it('uses an explicit bounded operational threshold for aggregate aging evidence',async()=>{const db={$queryRaw:jest.fn().mockResolvedValue([{category:'RECOVERY_OUTSTANDING',item_count:2n,amount:d(45),oldest_at:new Date('2026-09-01T00:00:00Z')}])};const result=await new CompensationPeriodControlService(db as any).aging({thresholdHours:24,asOf:'2026-09-10T00:00:00Z'});expect(result.thresholdHours).toBe(24);expect(result.cutoff).toBe('2026-09-09T00:00:00.000Z');expect(result.items).toHaveLength(6);expect(result.items.find(row=>row.category==='RECOVERY_OUTSTANDING')).toEqual({category:'RECOVERY_OUTSTANDING',count:2,amount:'45.0000',oldestAt:'2026-09-01T00:00:00.000Z',status:'ATTENTION'});expect(result.items.find(row=>row.category==='BANK_TRANSFER_FAILED')?.status).toBe('CLEAR');expect(result.authority.threshold).toContain('Operator-supplied');});
 it('rejects missing, out-of-range or invalid aging controls',async()=>{const service=new CompensationPeriodControlService({} as any);await expect(service.aging({thresholdHours:0})).rejects.toBeInstanceOf(BadRequestException);await expect(service.aging({thresholdHours:8761})).rejects.toBeInstanceOf(BadRequestException);await expect(service.aging({thresholdHours:24,asOf:'invalid'})).rejects.toBeInstanceOf(BadRequestException);});
 it('fails closed for an invalid range or rule',async()=>{const service=new CompensationPeriodControlService({} as any);await expect(service.read({periodStart:'bad',periodEnd:'2026-09-08Z',ruleVersionCode:'R1'})).rejects.toBeInstanceOf(BadRequestException);await expect(service.read({periodStart:'2026-09-08Z',periodEnd:'2026-09-01Z',ruleVersionCode:'R1'})).rejects.toBeInstanceOf(BadRequestException);await expect(service.read({periodStart:'2026-09-01Z',periodEnd:'2026-09-08Z',ruleVersionCode:''})).rejects.toBeInstanceOf(BadRequestException);});
});
