import {PrismaClient} from '@prisma/client';
import {randomUUID} from 'node:crypto';
import {MemberEventsService} from '../src/modules/events/events.service';
import {IdempotencyService} from '../src/common/idempotency/idempotency.service';
import {AuditService} from '../src/common/audit/audit.service';
const url=process.env.PHASE2_TEST_DATABASE_URL;
(url?describe:describe.skip)('Member event authority',()=>{let db:PrismaClient,s:MemberEventsService;const actor=randomUUID();const event=()=>({eventCode:`EVENT-${randomUUID().replaceAll('-','').slice(0,12).toUpperCase()}`,title:'Synthetic event',eventType:'HYBRID' as const,startsAt:new Date(Date.now()+60_000).toISOString(),endsAt:new Date(Date.now()+3_600_000).toISOString(),locationReference:'Taipei synthetic venue',onlineJoinReference:'https://example.test/event',capacity:1});beforeAll(()=>{db=new PrismaClient({datasources:{db:{url}}});s=new MemberEventsService(db as any,new IdempotencyService(db as any),new AuditService());});afterAll(()=>db?.$disconnect());async function published(){const input=event();await s.create(input,actor,randomUUID(),randomUUID());await s.publish(input.eventCode,'SYNTHETIC-APPROVAL',actor,randomUUID(),randomUUID());return input;}
 it('publishes the versioned event and keeps ineligible members invisible',async()=>{const awards=await db.bonusAward.count(),payables=await db.payableEntry.count(),input=await published(),member=await db.person.create({data:{legalName:'Event member',membershipState:'NETWORK_MEMBER'}}),other=await db.person.create({data:{legalName:'Event ineligible'}});expect(await s.memberList(other.personId)).toEqual([]);await expect(s.memberDetail(other.personId,input.eventCode)).rejects.toMatchObject({status:404});expect(await s.memberList(member.personId)).toEqual([expect.objectContaining({eventCode:input.eventCode,status:'AVAILABLE',capacity:1})]);const row=await db.memberEvent.findUniqueOrThrow({where:{eventCode:input.eventCode},include:{versions:true}});expect(row.versions[0]).toMatchObject({status:'PUBLISHED',approvalReference:'SYNTHETIC-APPROVAL',eventType:'HYBRID'});expect(await db.bonusAward.count()).toBe(awards);expect(await db.payableEntry.count()).toBe(payables);});
 it('enforces capacity, cancels, re-registers, and idempotently checks in with an opaque credential',async()=>{const input=await published(),a=await db.person.create({data:{legalName:'Event a',membershipState:'NETWORK_MEMBER'}}),b=await db.person.create({data:{legalName:'Event b',membershipState:'NETWORK_MEMBER'}});const results=await Promise.allSettled([s.register(a.personId,input.eventCode,'a',randomUUID()),s.register(b.personId,input.eventCode,'b',randomUUID())]);const successes=results.filter((x):x is PromiseFulfilledResult<any>=>x.status==='fulfilled');expect(successes).toHaveLength(1);const winner=successes[0].value,person=results[0].status==='fulfilled'?a:b;expect(winner).toMatchObject({eventCode:input.eventCode,status:'REGISTERED',replayed:false});expect(winner.checkInToken).toMatch(/^[A-Za-z0-9_-]{40,}$/);const memberEvent=await db.memberEvent.findUniqueOrThrow({where:{eventCode:input.eventCode}});const saved=await db.memberEventRegistration.findUniqueOrThrow({where:{memberEventId_personId:{memberEventId:memberEvent.memberEventId,personId:person.personId}}});expect(saved.checkInTokenHash).toMatch(/^[a-f0-9]{64}$/);expect(saved.checkInTokenHash).not.toBe(winner.checkInToken);await s.cancel(person.personId,input.eventCode,'cancel',randomUUID());const renewed=await s.register(person.personId,input.eventCode,'renew',randomUUID());const token=renewed.checkInToken!;expect(renewed).toMatchObject({status:'REGISTERED',replayed:false});expect(token).not.toBe(winner.checkInToken);await db.memberEventVersion.update({where:{memberEventVersionId:saved.memberEventVersionId},data:{startsAt:new Date(Date.now()-1_000)}});expect(await s.checkIn(token,actor,'checkin-a',randomUUID())).toMatchObject({eventCode:input.eventCode,status:'CHECKED_IN',replayed:false});expect(await s.checkIn(token,actor,'checkin-b',randomUUID())).toMatchObject({eventCode:input.eventCode,status:'CHECKED_IN',replayed:true});expect(await s.adminRegistrations(input.eventCode)).toMatchObject({eventCode:input.eventCode,registrations:[{memberNo:person.memberNo,status:'CHECKED_IN'}]});});
});
