import {PrismaClient} from '@prisma/client';
import {randomUUID} from 'node:crypto';
import {MemberEventsService} from '../src/modules/events/events.service';
import {IdempotencyService} from '../src/common/idempotency/idempotency.service';
import {AuditService} from '../src/common/audit/audit.service';
const url=process.env.PHASE2_TEST_DATABASE_URL;
(url?describe:describe.skip)('Event lifecycle and participation evidence',()=>{
 let db:PrismaClient,s:MemberEventsService;const actor=randomUUID();
 beforeAll(()=>{db=new PrismaClient({datasources:{db:{url}}});s=new MemberEventsService(db as any,new IdempotencyService(db as any),new AuditService());});afterEach(()=>jest.restoreAllMocks());afterAll(()=>db.$disconnect());
 async function fixture(){const eventCode=`EV-${randomUUID().slice(0,8).toUpperCase()}`,person=await db.person.create({data:{legalName:'Private event participant',membershipState:'NETWORK_MEMBER'}}),startsAt=new Date(Date.now()+3600000),endsAt=new Date(Date.now()+7200000);await s.create({eventCode,title:'Event',eventType:'HYBRID',startsAt:startsAt.toISOString(),endsAt:endsAt.toISOString(),locationReference:'Venue',onlineJoinReference:'https://example.test/private-room',capacity:1},actor,randomUUID(),randomUUID());await s.publish(eventCode,'APPROVED-EVENT',actor,randomUUID(),randomUUID());return {eventCode,person,startsAt,endsAt};}
 it('retains both registration cycles and records check-in/attendance exactly once under concurrent keys',async()=>{
  const f=await fixture(),register=()=>s.register(f.person.personId,f.eventCode,randomUUID(),randomUUID());await Promise.all([register(),register()]);const cancel=()=>s.cancel(f.person.personId,f.eventCode,randomUUID(),randomUUID());await Promise.all([cancel(),cancel()]);const renewed=await register();
  await expect(s.attend(f.eventCode,f.person.memberNo,actor,randomUUID(),randomUUID())).rejects.toMatchObject({status:409});jest.spyOn(s as any,'now').mockReturnValue(new Date(f.startsAt.getTime()+1000));const check=()=>s.checkIn(renewed.checkInToken!,actor,randomUUID(),randomUUID());await Promise.all([check(),check()]);const attend=()=>s.attend(f.eventCode,f.person.memberNo,actor,randomUUID(),randomUUID());await Promise.all([attend(),attend()]);
  const r=await db.memberEventRegistration.findFirstOrThrow({where:{personId:f.person.personId},include:{participationEvidence:{orderBy:{occurredAt:'asc'}}}});expect(r.status).toBe('ATTENDED');expect(r.participationEvidence).toHaveLength(5);expect(new Set(r.participationEvidence.map(x=>x.registrationCycleId)).size).toBe(2);expect(await db.auditEvent.count({where:{action:'MEMBER_EVENT_ATTENDED',entityId:r.memberEventRegistrationId}})).toBe(1);expect(await db.memberNotification.count({where:{personId:f.person.personId}})).toBe(5);
  const detail=await s.memberDetail(f.person.personId,f.eventCode);expect(detail.history).toHaveLength(5);expect(detail.canIssueCredential).toBe(false);expect(JSON.stringify(detail)).not.toContain(r.checkInTokenHash);expect(JSON.stringify(detail)).not.toContain(r.registrationCycleId);
  await expect(db.memberEventParticipationEvidence.delete({where:{participationEvidenceId:r.participationEvidence[0].participationEvidenceId}})).rejects.toThrow();await expect(db.memberEventRegistration.update({where:{memberEventRegistrationId:r.memberEventRegistrationId},data:{status:'REGISTERED'}})).rejects.toThrow();
 });
 it('lets only the owner rotate an opaque credential, invalidates stale credentials and keeps rotation out of participation counts',async()=>{
  const f=await fixture(),other=await db.person.create({data:{legalName:'Other',membershipState:'NETWORK_MEMBER'}});expect((await s.memberDetail(other.personId,f.eventCode)).onlineJoinReference).toBeNull();const first=await s.register(f.person.personId,f.eventCode,randomUUID(),randomUUID()),key=randomUUID(),second=await s.credential(f.person.personId,f.eventCode,key,randomUUID());expect(second.checkInToken).not.toBe(first.checkInToken);expect(await s.credential(f.person.personId,f.eventCode,key,randomUUID())).toEqual(second);await expect(s.credential(other.personId,f.eventCode,randomUUID(),randomUUID())).rejects.toMatchObject({status:404});
  const third=await s.credential(f.person.personId,f.eventCode,randomUUID(),randomUUID());await expect(s.credential(f.person.personId,f.eventCode,key,randomUUID())).rejects.toMatchObject({status:409});jest.spyOn(s as any,'now').mockReturnValue(new Date(f.startsAt.getTime()+1000));await expect(s.checkIn(second.checkInToken,actor,randomUUID(),randomUUID())).rejects.toMatchObject({status:404});await s.checkIn(third.checkInToken,actor,randomUUID(),randomUUID());expect(await db.memberEventParticipationEvidence.count({where:{registration:{personId:f.person.personId}}})).toBe(2);
 });
 it('retains ongoing/past member detail and archived history without exposing joining information to strangers',async()=>{
  const f=await fixture();await s.register(f.person.personId,f.eventCode,randomUUID(),randomUUID());const clock=jest.spyOn(s as any,'now').mockReturnValue(new Date(f.startsAt.getTime()+1000));expect((await s.memberDetail(f.person.personId,f.eventCode)).onlineJoinReference).toBe('https://example.test/private-room');expect(await s.memberList(f.person.personId)).toEqual(expect.arrayContaining([expect.objectContaining({eventCode:f.eventCode,status:'REGISTERED'})]));clock.mockReturnValue(new Date(f.endsAt.getTime()+1000));expect((await s.memberDetail(f.person.personId,f.eventCode)).onlineJoinReference).toBeNull();await expect(s.credential(f.person.personId,f.eventCode,randomUUID(),randomUUID())).rejects.toMatchObject({status:409});
  await s.archive(f.eventCode,'Event closed',actor,randomUUID(),randomUUID());expect(await s.memberDetail(f.person.personId,f.eventCode)).toMatchObject({eventStatus:'ARCHIVED',canRegister:false,canIssueCredential:false,history:[{eventType:'EVENT_REGISTERED'}]});const r=await db.memberEventRegistration.findFirstOrThrow({where:{personId:f.person.personId}});await expect(db.memberEventVersion.update({where:{memberEventVersionId:r.memberEventVersionId},data:{title:'Changed'}})).rejects.toThrow();expect(JSON.stringify(await s.adminList())).not.toContain(r.memberEventVersionId);
 });
});
