import {PrismaClient} from '@prisma/client';
import {randomUUID} from 'node:crypto';
import {LearningService} from '../src/modules/learning/learning.service';
import {IdempotencyService} from '../src/common/idempotency/idempotency.service';
import {AuditService} from '../src/common/audit/audit.service';
const url=process.env.PHASE2_TEST_DATABASE_URL;
(url?describe:describe.skip)('Learning course authority',()=>{
 let db:PrismaClient,s:LearningService;const actor=randomUUID();const course=()=>({courseCode:`LEARN-${randomUUID().replaceAll('-','').slice(0,12).toUpperCase()}`,title:'Synthetic course',categoryCode:'ONBOARDING',lessons:[{title:'Read this',contentType:'ARTICLE' as const,contentReference:'safe article'},{title:'Watch this',contentType:'VIDEO_REFERENCE' as const,contentReference:'https://example.test/video'}]});
 beforeAll(()=>{db=new PrismaClient({datasources:{db:{url}}});s=new LearningService(db as any,new IdempotencyService(db as any),new AuditService());});afterAll(()=>db?.$disconnect());
 async function published(){const input=course();await s.create(input,actor,randomUUID(),randomUUID());await s.publish(input.courseCode,'SYNTHETIC-APPROVAL',actor,randomUUID(),randomUUID());return {person:await db.person.create({data:{legalName:'Learning member',membershipState:'NETWORK_MEMBER'}}),input};}
 it('publishes a versioned course without creating economic facts',async()=>{const awards=await db.bonusAward.count(),payables=await db.payableEntry.count();const {person,input}=await published();const list=await s.memberList(person.personId);expect(list).toEqual([expect.objectContaining({courseCode:input.courseCode,lessonCount:2,status:'AVAILABLE'})]);expect(await db.bonusAward.count()).toBe(awards);expect(await db.payableEntry.count()).toBe(payables);const row=await db.learningCourse.findUniqueOrThrow({where:{courseCode:input.courseCode},include:{versions:{include:{lessons:true}}}});expect(row.versions[0]).toMatchObject({status:'PUBLISHED',version:1,approvalReference:'SYNTHETIC-APPROVAL'});expect(row.versions[0].lessons).toHaveLength(2);});
 it('requires an eligible member and records one traceable completion chain',async()=>{const {person,input}=await published(),other=await db.person.create({data:{legalName:'Ineligible learning person'}});await expect(s.memberDetail(other.personId,input.courseCode)).rejects.toMatchObject({status:404});expect((await s.enroll(person.personId,input.courseCode,'enroll-a',randomUUID()))).toMatchObject({status:'ENROLLED',replayed:false});await expect(s.complete(person.personId,input.courseCode,'complete-too-early',randomUUID())).rejects.toMatchObject({status:409});await s.lessonCompleted(person.personId,input.courseCode,1,'lesson-a');await s.lessonCompleted(person.personId,input.courseCode,2,'lesson-b');expect((await s.complete(person.personId,input.courseCode,'complete-a',randomUUID()))).toMatchObject({status:'COMPLETED',replayed:false});expect((await s.complete(person.personId,input.courseCode,'complete-b',randomUUID()))).toMatchObject({status:'COMPLETED',replayed:true});const events=await db.learningProgressEvent.findMany({where:{enrollment:{personId:person.personId}},orderBy:{occurredAt:'asc'}});expect(events.map(x=>x.eventType).sort()).toEqual(['COURSE_COMPLETED','COURSE_ENROLLED','LESSON_COMPLETED','LESSON_COMPLETED'].sort());expect(events.every(x=>/^[a-f0-9]{64}$/.test(x.evidenceHash))).toBe(true);});
 it('replays repeated enrollment and lesson completion without duplicate evidence',async()=>{const {person,input}=await published();await s.enroll(person.personId,input.courseCode,'enroll-a',randomUUID());expect((await s.enroll(person.personId,input.courseCode,'enroll-b',randomUUID()))).toMatchObject({replayed:true});await s.lessonCompleted(person.personId,input.courseCode,1,'lesson-a');expect((await s.lessonCompleted(person.personId,input.courseCode,1,'lesson-b'))).toMatchObject({replayed:true});expect(await db.learningEnrollment.count({where:{personId:person.personId}})).toBe(1);expect(await db.learningProgressEvent.count({where:{enrollment:{personId:person.personId},eventType:'LESSON_COMPLETED'}})).toBe(1);});
});
