import {PrismaClient} from '@prisma/client';
import {randomUUID} from 'node:crypto';
import {MemberGrowthService} from '../src/modules/member/member-growth.service';
const url=process.env.PHASE2_TEST_DATABASE_URL;
(url?describe:describe.skip)('Growth exact participation counts',()=>{
 let db:PrismaClient;beforeAll(()=>db=new PrismaClient({datasources:{db:{url}}}));afterAll(()=>db.$disconnect());
 it('uses owned qualification, effective Active intervals, historical ranks and current sponsor relationships without exposing children',async()=>{
  const person=await db.person.create({data:{legalName:'Owner'}}),other=await db.person.create({data:{legalName:'PRIVATE CHILD'}}),now=new Date(),past=new Date(now.getTime()-3600000),future=new Date(now.getTime()+3600000),q=await db.qualification.create({data:{currentHolderPersonId:person.personId,planLevelCode:'ELITE',activeFlag:false}}),inactive=await db.qualification.create({data:{currentHolderPersonId:person.personId,planLevelCode:'STARTER',activeFlag:true}}),child=await db.qualification.create({data:{currentHolderPersonId:other.personId,planLevelCode:'LEADER'}}),expired=await db.qualification.create({data:{currentHolderPersonId:other.personId,planLevelCode:'STARTER'}});
  await db.activePeriod.createMany({data:[{qualificationId:q.qualificationId,activeFrom:past,activeTo:future,sourceType:'TEST',ruleVersionCode:'R1.0B'},{qualificationId:inactive.qualificationId,activeFrom:new Date(past.getTime()-3600000),activeTo:past,sourceType:'TEST',ruleVersionCode:'R1.0B'}]});await db.qualificationGlobalRankHistory.create({data:{qualificationId:q.qualificationId,rankCode:'NEW_STAR',achievedAt:past,sourcePeriodEnd:past,ruleVersionCode:'R1.0B'}});await db.sponsorRelationship.createMany({data:[{sponsorQualificationId:q.qualificationId,childQualificationId:child.qualificationId,sponsorSequenceNo:1,effectiveFrom:past},{sponsorQualificationId:q.qualificationId,childQualificationId:expired.qualificationId,sponsorSequenceNo:2,effectiveFrom:new Date(past.getTime()-3600000),effectiveTo:past}]});
  const view=await new MemberGrowthService(db as any).read(person.personId);expect(view.dimensions.qualification.items.map(x=>x.qualificationNo)).toEqual([q.qualificationNo.toString(),inactive.qualificationNo.toString()]);expect(view.dimensions.active).toMatchObject({activeQualificationCount:1,totalQualificationCount:2});expect(view.dimensions.active.items.find(x=>x.qualificationNo===q.qualificationNo.toString())).toMatchObject({active:true,activeFrom:past.toISOString(),activeTo:future.toISOString()});expect(view.dimensions.globalRank.achieved).toEqual([{qualificationNo:q.qualificationNo.toString(),rankCode:'NEW_STAR',achievedAt:past.toISOString(),sourcePeriodEnd:past.toISOString()}]);expect(view.dimensions.organization.directQualifiedCount).toBe(1);expect(JSON.stringify(view)).not.toContain('"qualificationNo":"'+child.qualificationNo+'"');
  for(const hidden of [person.personId,other.personId,q.qualificationId,child.qualificationId,'PRIVATE CHILD'])expect(JSON.stringify(view)).not.toContain(hidden);
 });
 it('counts all 101 completions/attendances independently of the 100-row preview and separates check-in from attendance',async()=>{
  const p=await db.person.create({data:{legalName:'PRIVATE GROWTH OWNER',membershipState:'NETWORK_MEMBER'}}),other=await db.person.create({data:{legalName:'Other growth owner'}}),now=new Date(),past=new Date(now.getTime()-3600000),future=new Date(now.getTime()+3600000),prefix=randomUUID().slice(0,8).toUpperCase();
  const courses=Array.from({length:101},(_,i)=>({learningCourseId:randomUUID(),courseCode:`GROWTH-${prefix}-${i}`,status:'PUBLISHED' as const,createdByActor:'TEST'}));await db.learningCourse.createMany({data:courses});const versions=courses.map(c=>({learningCourseVersionId:randomUUID(),learningCourseId:c.learningCourseId,version:1,title:'Synthetic course',categoryCode:'ONBOARDING',status:'PUBLISHED' as const,contentHash:'a'.repeat(64)}));await db.learningCourseVersion.createMany({data:versions});await db.learningEnrollment.createMany({data:versions.map(v=>({learningCourseId:v.learningCourseId,learningCourseVersionId:v.learningCourseVersionId,personId:p.personId,status:'COMPLETED' as const,enrolledAt:past,startedAt:past,completedAt:now}))});
  const events=Array.from({length:104},(_,i)=>({memberEventId:randomUUID(),eventCode:`GROWTH-${prefix}-EV-${i}`,status:i===103?'ARCHIVED' as const:'PUBLISHED' as const,createdByActor:'TEST'}));await db.memberEvent.createMany({data:events});const ev=events.map((e,i)=>({memberEventVersionId:randomUUID(),memberEventId:e.memberEventId,version:1,title:'Synthetic activity',eventType:'OFFLINE' as const,status:'PUBLISHED' as const,startsAt:i>=102?future:past,endsAt:new Date(future.getTime()+3600000),locationReference:'Venue',contentHash:'b'.repeat(64)}));await db.memberEventVersion.createMany({data:ev});await db.memberEventRegistration.createMany({data:ev.map((v,i)=>({memberEventId:v.memberEventId,memberEventVersionId:v.memberEventVersionId,personId:p.personId,status:i<101?'ATTENDED' as const:i===101?'CHECKED_IN' as const:'REGISTERED' as const,checkInTokenHash:randomUUID().replaceAll('-','').repeat(2),registeredAt:past,checkedInAt:i<102?past:null,attendedAt:i<101?now:null}))});
  const service=new MemberGrowthService(db as any),view=await service.read(p.personId);expect(view.dimensions.learning).toMatchObject({enrolledCount:101,completedCount:101});expect(view.dimensions.learning.items).toHaveLength(100);expect(view.dimensions.events).toMatchObject({attendedCount:101,checkedInCount:1,upcomingRegisteredCount:1});expect(view.dimensions.events.items).toHaveLength(100);expect(view.coverage.counts).toBe('ALL_PERSON_RECORDS');expect(view.milestones).toHaveLength(20);expect(view.milestones.every(x=>x.link.startsWith('/events?event=GROWTH-'))).toBe(true);
  expect((await service.read(other.personId)).dimensions.events).toMatchObject({attendedCount:0,checkedInCount:0,upcomingRegisteredCount:0});const json=JSON.stringify(view);for(const hidden of [p.personId,other.personId,events[0].memberEventId,ev[0].memberEventVersionId,'PRIVATE GROWTH OWNER'])expect(json).not.toContain(hidden);
 });
});
