import {QualificationPlacementService} from '../src/modules/qualification/qualification-placement.service';
describe('pending reference placement',()=>{
 it('resolves a qualification without a Ball number and returns the newly assigned number',async()=>{
  const findUnique=jest.fn().mockResolvedValueOnce({qualificationId:'pending-q',ballNo:null}).mockResolvedValueOnce({qualificationId:'parent-q',ballNo:'TREE-AX000002'});
  const db:any={qualification:{findUnique,findUniqueOrThrow:jest.fn().mockResolvedValue({ballNo:'TREE-A000001'})}};
  const service=new QualificationPlacementService(db,{} as any,{} as any,{} as any);
  const place=jest.spyOn(service as any,'place').mockResolvedValue({value:{side:'LEFT',placedAt:'2026-09-25T00:00:00Z',evidenceHash:'a'.repeat(64)}});
  expect(await service.placeBySponsorOwnerReference('owner',{placementReference:'P42',binaryParentBallNo:'TREE-AX000002',side:'LEFT'},'key','request')).toMatchObject({ballNo:'TREE-A000001',binaryParentBallNo:'TREE-AX000002'});
  expect(findUnique).toHaveBeenCalledWith({where:{qualificationNo:42n},select:{qualificationId:true,ballNo:true}});
  expect(place).toHaveBeenCalledWith('owner','SPONSOR_OWNER',{qualificationId:'pending-q',binaryParentQualificationId:'parent-q',side:'LEFT'},'key','request');
 });
 it('rejects out-of-range references before querying the database',async()=>{
  const findUnique=jest.fn(),service=new QualificationPlacementService({qualification:{findUnique}} as any,{} as any,{} as any,{} as any);
  for(const placementReference of ['P0','P9223372036854775808','P'+'9'.repeat(20)])await expect(service.placeBySponsorOwnerReference('owner',{placementReference,binaryParentBallNo:'A000001',side:'LEFT'},'key','request')).rejects.toMatchObject({response:{code:'PLACEMENT_REFERENCE_INVALID'}});
  expect(findUnique).not.toHaveBeenCalled();
 });
});
describe('pending placement member-safe read model',()=>{it('returns memberNo and Ball numbers without internal UUIDs',async()=>{const db:any={qualification:{findMany:jest.fn().mockResolvedValueOnce([{qualificationId:'sponsor-q'}]).mockResolvedValueOnce([{qualificationId:'pending-q',qualificationNo:42n,ballNo:null},{qualificationId:'sponsor-q',ballNo:'A000004'}])},qualificationSetup:{findMany:jest.fn().mockResolvedValue([{qualificationId:'pending-q',ownerPersonId:'owner-p',finalSponsorQualificationId:'sponsor-q',packageType:'STARTER',setupStatus:'PLACEMENT_PENDING',placementRequestedAt:new Date('2026-01-01T00:00:00Z'),placementDueAt:new Date('2026-01-04T00:00:00Z'),placedAt:null,setupPolicyVersion:'V1'}])},person:{findMany:jest.fn().mockResolvedValue([{personId:'owner-p',memberNo:'2609000001'}])}};const service=new QualificationPlacementService(db,{} as any,{} as any,{} as any);const rows=await service.pendingForSponsorOwner('owner-p',new Date('2026-01-02T00:00:00Z'));expect(rows[0]).toMatchObject({pendingBallNo:null,placementReference:'P42',pendingMemberNo:'2609000001',sponsorBallNo:'A000004',packageType:'STARTER',paymentState:'CONFIRMED'});expect(rows[0]).not.toHaveProperty('qualificationId');expect(rows[0]).not.toHaveProperty('ownerPersonId');expect(rows[0]).not.toHaveProperty('sponsorQualificationId');});it('rejects a UUID before it can be used as a public Ball number',async()=>{const findUnique=jest.fn(),service=new QualificationPlacementService({qualification:{findUnique}} as any,{} as any,{} as any,{} as any);await expect(service.placeBySponsorOwnerReference('person',{placementReference:'11111111-1111-4111-8111-111111111111',binaryParentBallNo:'A000004',side:'LEFT'},'key','request')).rejects.toMatchObject({response:{code:'PLACEMENT_REFERENCE_INVALID'}});expect(findUnique).not.toHaveBeenCalled();});});
