import {PeriodProjectionService} from '../src/modules/analytics/period-projection.service';
import {randomUUID} from 'node:crypto';
import {PrismaService} from '@ucell/database';
import {BinaryTreeService,TreePrincipal} from '../src/modules/binary-tree/binary-tree.service';
import {OrganizationService} from '../src/modules/organization/organization.service';
import {IdempotencyService} from '../src/common/idempotency/idempotency.service';
const url=process.env.PHASE2_TEST_DATABASE_URL;
if(!url||!/^ucell_jest_[a-f0-9]{32}$/.test(new URL(url).pathname.slice(1)))throw Error('ISOLATED_DATABASE_REQUIRED');
const db=new PrismaService(),service=new PeriodProjectionService(db);
let p:TreePrincipal,query:any;
beforeAll(async()=>{
 const person=await db.person.create({data:{legalName:'SYNTHETIC PERIOD PROJECTION'}}),subject=randomUUID();
 await db.identityLink.create({data:{personId:person.personId,provider:'ENTRA',providerSubject:subject}});
 await db.adminAccessGrant.create({data:{personId:person.personId,provider:'ENTRA',providerSubject:subject,roleCode:'SUPER_ADMIN',validFrom:new Date(Date.now()-1000)}});
 const session=await db.authSession.create({data:{personId:person.personId,provider:'ENTRA',subject,roleCode:'SUPER_ADMIN',tokenHash:randomUUID(),issuedAt:new Date(),expiresAt:new Date(Date.now()+3600000)}});
 p={personId:person.personId,provider:'ENTRA',subject,role:'SUPER_ADMIN',sessionId:session.authSessionId};
 const trees=new BinaryTreeService(db,new IdempotencyService(db),new OrganizationService(db));
 const tree=(await trees.create(p,{treeName:'Projection fixture',reason:'Synthetic'},randomUUID())).value;
 await new Promise(r=>setTimeout(r,5));
 const now=new Date().toISOString();
 query={metrics:['tree.monthly_new_balls'],dimensions:['binaryTreeId'],groupBy:['binaryTreeId'],filters:{binaryTreeId:tree.binaryTreeId},limit:50,time:{timezone:'Asia/Taipei',periodStart:'2026-01-01T00:00:00.000Z',periodEnd:'2099-01-01T00:00:00.000Z',asOf:now,knowledgeCutoff:now}};
});
afterAll(()=>db.$disconnect());
it('dry-run never publishes; rebuild atomically publishes an immutable generation and reconcile agrees',async()=>{
 const dry=await service.request(p,query,'DRY_RUN',randomUUID());
 expect(await service.runOne()).toMatchObject({jobId:dry.jobId,status:'COMPLETED'});
 expect((await service.read(p,query)).status).toBe('UNAVAILABLE');
 const key=randomUUID(),rebuild=await service.request(p,query,'REBUILD',key);
 expect(await service.request(p,query,'REBUILD',key)).toMatchObject({jobId:rebuild.jobId,replayed:true});
 await expect(service.request(p,query,'DRY_RUN',key)).rejects.toMatchObject({status:409});
 expect(await service.runOne()).toMatchObject({jobId:rebuild.jobId,status:'COMPLETED'});
 const read=await service.read(p,query);
 expect(read).toMatchObject({status:'AVAILABLE',projectionStatus:'CURRENT',result:[{measures:{balls:'3',monthlyNewBalls:'3'}}]});
 const snapshot=read.snapshot!;
 await expect(db.$executeRaw`UPDATE integration.period_aggregate_generation SET source_hash='bad' WHERE generation_id=${snapshot}::uuid`).rejects.toThrow();
 const reconcile=await service.request(p,query,'RECONCILE',randomUUID());
 expect(await service.runOne()).toMatchObject({jobId:reconcile.jobId,status:'COMPLETED'});
 expect((await service.status(p,reconcile.jobId)).result.reconciles).toBe(true);
 expect((await service.read(p,query,snapshot)).snapshot).toBe(snapshot);
 await expect(service.read(p,{...query,time:{...query.time,periodStart:'2026-02-01T00:00:00.000Z'}},snapshot)).rejects.toMatchObject({status:409});
 await expect(service.read(p,query,undefined,'cursor')).rejects.toMatchObject({status:409});
});
it('rejects SQL-shaped and unsupported queries and denies non-finance and another actor jobs',async()=>{
 await expect(service.request(p,{...query,sql:'select * from identity.person'},'REBUILD',randomUUID())).rejects.toMatchObject({status:422});
 await expect(service.request(p,{...query,metrics:['recovery.amount']},'REBUILD',randomUUID())).rejects.toMatchObject({status:422});
 await expect(service.request({...p,role:'ORDER_OPS'},query,'REBUILD',randomUUID())).rejects.toMatchObject({status:403});
 await expect(service.status(p,randomUUID())).rejects.toMatchObject({status:404});
});
it('exports the same generation as CSV, preserves provenance, and rejects expired/private downloads',async()=>{
 const {PeriodExportService}=await import('../src/modules/analytics/period-export.service');
 const exporter=new PeriodExportService(db,service),read=await service.read(p,query),snapshot=read.snapshot!;
 const key=randomUUID(),job=await exporter.request(p,query,snapshot,key);
 expect(await exporter.request(p,query,snapshot,key)).toMatchObject({exportId:job.exportId,replayed:true});
 expect(await exporter.runOne()).toMatchObject({exportId:job.exportId,status:'COMPLETED'});
 const state=await exporter.status(p,job.exportId);expect(state.row_count).toBe(1);expect(state.chunk_count).toBe(1);
 let csv='';for await(const chunk of exporter.download(p,job.exportId))csv+=chunk.toString();
 expect(csv).toContain('generatedAt,dataThrough,definitionVersion');expect(csv).toContain(snapshot);expect(csv).toContain('monthlyNewBalls');
 await expect(exporter.status({...p,role:'ORDER_OPS'},job.exportId)).rejects.toMatchObject({status:403});
 await expect(exporter.status(p,randomUUID())).rejects.toMatchObject({status:404});
 await db.$executeRaw`UPDATE integration.analytics_export_job SET expires_at=now()-interval '1 second' WHERE export_id=${job.exportId}::uuid`;
 expect((await exporter.status(p,job.exportId)).status).toBe('EXPIRED');
 await expect(exporter.download(p,job.exportId).next()).rejects.toMatchObject({status:410});
});
it('a superseded rebuild cannot publish over the newest requested generation',async()=>{
 const older=await service.request(p,query,'REBUILD',randomUUID());
 const newer=await service.request(p,query,'REBUILD',randomUUID());
 expect(await service.runOne()).toMatchObject({jobId:older.jobId,status:'COMPLETED'});
 expect(await service.read(p,query)).toMatchObject({status:'UNAVAILABLE',projectionStatus:'REBUILDING'});
 expect(await service.runOne()).toMatchObject({jobId:newer.jobId,status:'COMPLETED'});
 const latest=await service.status(p,newer.jobId);
 expect((await service.read(p,query)).snapshot).toBe(latest.result.generation);
});
it('concurrent workers and expired-lease retry publish one generation and one complete export',async()=>{
 const job=await service.request(p,query,'REBUILD',randomUUID());
 await expect(db.$executeRaw`UPDATE integration.period_projection_job SET query_hash='tampered' WHERE job_id=${job.jobId}::uuid`).rejects.toThrow('PROJECTION_JOB_IDENTITY_IMMUTABLE');
 await db.$executeRaw`UPDATE integration.period_projection_job SET status='RUNNING',lease_token=${randomUUID()}::uuid,lease_until=now()-interval '1 second' WHERE job_id=${job.jobId}::uuid`;
 const outcomes=await Promise.all([service.runOne(),new PeriodProjectionService(db).runOne()]);
 expect(outcomes.filter(Boolean)).toEqual([{jobId:job.jobId,status:'COMPLETED'}]);
 const [count]=await db.$queryRaw<any[]>`SELECT count(*)::text n FROM integration.period_aggregate_generation WHERE job_id=${job.jobId}::uuid`;expect(count.n).toBe('1');
 const read=await service.read(p,query),{PeriodExportService}=await import('../src/modules/analytics/period-export.service');
 const exporter=new PeriodExportService(db,service),request=await exporter.request(p,query,read.snapshot!,randomUUID());
 await expect(db.$executeRaw`UPDATE integration.analytics_export_job SET actor_id=${randomUUID()}::uuid WHERE export_id=${request.exportId}::uuid`).rejects.toThrow('EXPORT_JOB_IDENTITY_IMMUTABLE');
 await db.$executeRaw`UPDATE integration.analytics_export_job SET status='RUNNING',lease_token=${randomUUID()}::uuid,lease_until=now()-interval '1 second' WHERE export_id=${request.exportId}::uuid`;
 const exported=await Promise.all([exporter.runOne(),new PeriodExportService(db,service).runOne()]);
 expect(exported.filter(Boolean)).toEqual([{exportId:request.exportId,status:'COMPLETED'}]);
 expect(await exporter.runOne()).toBeNull();
 const status=await exporter.status(p,request.exportId);expect(status).toMatchObject({row_count:1,chunk_count:1});
 const [chunks]=await db.$queryRaw<any[]>`SELECT count(*)::text n FROM integration.analytics_export_chunk WHERE export_id=${request.exportId}::uuid`;expect(chunks.n).toBe('1');
});
it('revocation before worker execution fails without publishing a generation',async()=>{
 const job=await service.request(p,query,'REBUILD',randomUUID());
 await db.authSession.update({where:{authSessionId:p.sessionId},data:{revokedAt:new Date()}});
 expect(await service.runOne()).toMatchObject({jobId:job.jobId,status:'FAILED'});
 const [row]=await db.$queryRaw<any[]>`SELECT count(*)::text n FROM integration.period_aggregate_generation WHERE job_id=${job.jobId}::uuid`;
 expect(row.n).toBe('0');
 await expect(service.read(p,query)).rejects.toMatchObject({status:403});
});
