import { Body, Controller, Get, Headers, Param, Post, Query, Req, UseGuards } from '@nestjs/common';
import { ApiBearerAuth, ApiHeader, ApiOperation, ApiTags } from '@nestjs/swagger';
import { IsString, IsUUID, Matches, MaxLength, MinLength } from 'class-validator';
import { IdempotencyGuard } from '../../common/guards/idempotency.guard';
import { Roles } from './roles.decorator';
import { ExistingMemberLineLinkService } from './existing-member-line-link.service';
class RequestDto { @Matches(/^\d{10}$/) memberNo!:string; @IsString() @MinLength(8) @MaxLength(160) verificationReference!:string; @IsString() @MinLength(1) @MaxLength(16384) idToken!:string; }
class CompleteDto { @IsUUID() requestId!:string; @IsString() @MinLength(20) @MaxLength(200) completionToken!:string; @IsString() @MinLength(1) @MaxLength(16384) idToken!:string; }
@ApiTags('Existing Member LINE Link') @Controller('existing-member-line-links')
export class ExistingMemberLineLinkController { constructor(private readonly service:ExistingMemberLineLinkService){} @Post('requests') @UseGuards(IdempotencyGuard) @ApiHeader({name:'Idempotency-Key',required:true}) @ApiOperation({operationId:'requestExistingMemberLineLink',description:'A verified LINE subject requests an existing-member link. memberNo alone is insufficient; Support must review the verification reference.'}) request(@Body() body:RequestDto,@Headers('idempotency-key') key:string,@Req() req:any){return this.service.request({...body,key,requestId:req.requestId}).then(r=>({data:r.value,meta:{replayed:r.replayed}}));} @Post('complete') @ApiOperation({operationId:'completeExistingMemberLineLink',description:'Consumes one approved short-lived token only for the requesting verified LINE subject. It never creates a Person, Ball, Sponsor, placement or economic effect.'}) complete(@Body() body:CompleteDto){return this.service.complete(body);} }
@ApiTags('Admin - Existing Member LINE Link') @ApiBearerAuth('adminBearer') @Roles('SUPER_ADMIN','MEMBERSHIP_OPS','CUSTOMER_SERVICE') @Controller('admin/existing-member-line-links')
export class AdminExistingMemberLineLinkController { constructor(private readonly service:ExistingMemberLineLinkService){} @Get() @ApiOperation({operationId:'adminListExistingMemberLineLinks',description:'Authorized queue for existing-member LINE link requests. Tokens and raw LINE credentials are never returned.'}) list(@Query('status') status?:'PENDING'|'APPROVED'|'COMPLETED'){return this.service.list(status);}
 @Post(':id/approve') @UseGuards(IdempotencyGuard) @ApiHeader({name:'Idempotency-Key',required:true}) @ApiOperation({operationId:'approveExistingMemberLineLink',description:'Authorized admin approves a pending request and receives a token only for approved out-of-band delivery.'}) approve(@Param('id') id:string,@Req() req:any){return this.service.approve(id,req.user?.personId,req.requestId);} }
