import { ConflictException, Injectable, NotFoundException, UnauthorizedException } from '@nestjs/common';
import { Prisma, PrismaService } from '@ucell/database';
import { createHash, randomBytes, randomUUID } from 'crypto';
import { AuditService } from '../../common/audit/audit.service';
import { IdempotencyService } from '../../common/idempotency/idempotency.service';
import { IdentityTokenService } from './identity-token.service';
import { LineTokenVerifierService } from './line-token-verifier.service';
const hash=(value:string)=>createHash('sha256').update(value).digest('hex');
@Injectable()
export class ExistingMemberLineLinkService {
 constructor(private readonly db:PrismaService,private readonly verifier:LineTokenVerifierService,private readonly idempotency:IdempotencyService,private readonly audit:AuditService){}
 async request(input:{memberNo:string;verificationReference:string;idToken:string;key:string;requestId:string}){const line=await this.verifier.verify(input.idToken);return this.idempotency.execute(`existing-member-line-link:${line.subject}`,input.key,{memberNo:input.memberNo,verificationReference:input.verificationReference},async tx=>{const person=await tx.person.findUnique({where:{memberNo:input.memberNo}});if(!person||person.status!=='EFFECTIVE')throw new NotFoundException({code:'EXISTING_MEMBER_NOT_FOUND'});if(await tx.identityLink.findUnique({where:{provider_providerSubject:{provider:'LINE',providerSubject:line.subject}}}))throw new ConflictException({code:'LINE_SUBJECT_ALREADY_BOUND'});if(await tx.identityLink.findFirst({where:{personId:person.personId,provider:'LINE',status:'ACTIVE'}}))throw new ConflictException({code:'EXISTING_MEMBER_LINE_REBIND_REQUIRED'});const request=await tx.accountRecoveryRequest.create({data:{personId:person.personId,type:'EXISTING_MEMBER_LINE_LINK',requestedProviderSubject:line.subject,verificationEvidence:{reference:input.verificationReference,channel:'LINE_VERIFIED'},idempotencyKey:`existing-member-line-link:${line.subject}:${input.key}`}});await this.audit.write(tx,{actorType:'LINE_VERIFIED',action:'EXISTING_MEMBER_LINE_LINK_REQUESTED',entityType:'AccountRecoveryRequest',entityId:request.accountRecoveryRequestId,afterData:{personId:person.personId,status:'PENDING'},requestId:input.requestId,correlationId:randomUUID()});return {requestId:request.accountRecoveryRequestId,status:'PENDING'};});}
 async list(status?:'PENDING'|'APPROVED'|'COMPLETED'){const rows=await this.db.accountRecoveryRequest.findMany({where:{type:'EXISTING_MEMBER_LINE_LINK',...(status?{status}: {})},include:{person:{select:{memberNo:true,legalName:true}}},orderBy:{createdAt:'desc'},take:100});return rows.map(row=>({requestId:row.accountRecoveryRequestId,status:row.status,memberNo:row.person.memberNo,memberName:row.person.legalName,verificationReference:(row.verificationEvidence as any)?.reference??null,createdAt:row.createdAt.toISOString(),expiresAt:row.completionTokenExpiresAt?.toISOString()??null}));} async approve(requestId:string,actorId:string,requestIdForAudit:string){return this.db.$transaction(async tx=>{const request=await tx.accountRecoveryRequest.findUnique({where:{accountRecoveryRequestId:requestId}});if(!request||request.type!=='EXISTING_MEMBER_LINE_LINK'||request.status!=='PENDING')throw new ConflictException({code:'EXISTING_MEMBER_LINK_NOT_PENDING'});const raw=randomBytes(32).toString('base64url'),now=new Date(),approved=await tx.accountRecoveryRequest.update({where:{accountRecoveryRequestId:requestId},data:{status:'APPROVED',approverActorId:actorId,approvedAt:now,completionTokenHash:hash(raw),completionTokenExpiresAt:new Date(now.getTime()+1800000)}});await this.audit.write(tx,{actorType:'ADMIN',actorId,action:'EXISTING_MEMBER_LINE_LINK_APPROVED',entityType:'AccountRecoveryRequest',entityId:requestId,afterData:{personId:request.personId,status:approved.status},requestId:requestIdForAudit,correlationId:randomUUID()});return {requestId,completionToken:raw,expiresAt:approved.completionTokenExpiresAt};},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
 async complete(input:{requestId:string;completionToken:string;idToken:string}){const line=await this.verifier.verify(input.idToken);return this.db.$transaction(async tx=>{const request=await tx.accountRecoveryRequest.findUnique({where:{accountRecoveryRequestId:input.requestId}}),now=new Date();if(!request||request.type!=='EXISTING_MEMBER_LINE_LINK'||request.status!=='APPROVED'||!request.completionTokenHash||request.completionTokenHash!==hash(input.completionToken)||request.completionTokenUsedAt||!request.completionTokenExpiresAt||request.completionTokenExpiresAt<=now||request.requestedProviderSubject!==line.subject)throw new UnauthorizedException({code:'EXISTING_MEMBER_LINK_TOKEN_INVALID'});const person=await tx.person.findUnique({where:{personId:request.personId}});if(!person||person.securityStatus!=='NORMAL')throw new ConflictException({code:'EXISTING_MEMBER_LINK_PERSON_UNAVAILABLE'});if(await tx.identityLink.findFirst({where:{personId:person.personId,provider:'LINE',status:'ACTIVE'}}))throw new ConflictException({code:'EXISTING_MEMBER_LINE_REBIND_REQUIRED'});if(await tx.identityLink.findUnique({where:{provider_providerSubject:{provider:'LINE',providerSubject:line.subject}}}))throw new ConflictException({code:'LINE_SUBJECT_ALREADY_BOUND'});const binding=await tx.identityLink.create({data:{personId:person.personId,provider:'LINE',providerSubject:line.subject,status:'ACTIVE'}});await tx.accountRecoveryRequest.update({where:{accountRecoveryRequestId:request.accountRecoveryRequestId},data:{status:'COMPLETED',completionTokenUsedAt:now,completedAt:now}});await this.audit.write(tx,{actorType:'LINE_VERIFIED',action:'LINE_BINDING_CREATED',entityType:'IdentityLink',entityId:binding.identityLinkId,afterData:{personId:person.personId,source:'EXISTING_MEMBER_LINE_LINK'},requestId:`existing-member-link:${request.accountRecoveryRequestId}`,correlationId:randomUUID()});const ttl=Math.min(3600,line.expiresAt-Math.floor(Date.now()/1000));if(ttl<=0)throw new UnauthorizedException({code:'LINE_TOKEN_EXPIRED'});const session=await new IdentityTokenService(tx as any).issue({provider:'LINE',subject:line.subject,personId:person.personId,ttlSeconds:ttl});return {...session,memberNo:person.memberNo};},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
}
