import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {useState} from 'react';
import {command,get,qs} from '../../lib/api';
import {Card,ErrorBox,Field,PageHeader} from '../../components/ui';
import {EmptyState,ErrorState,LoadingState,StatusBadge} from '@ucell/design-system';
import {SearchOption,SearchSelect} from '../../components/SearchSelect';

export function PaperIntakePage(){
 const [status,setStatus]=useState(''),qc=useQueryClient();
 const [newLegalName,setNewLegalName]=useState(''),[newCountry,setNewCountry]=useState(''),[newType,setNewType]=useState(''),[newDocumentNo,setNewDocumentNo]=useState('');
 const [person,setPerson]=useState<SearchOption|null>(null),[paperApplicationNo,setPaperApplicationNo]=useState(''),[receivedAt,setReceivedAt]=useState(''),[evidenceDocumentRef,setEvidenceDocumentRef]=useState('');
 const [orderApplicationNo,setOrderApplicationNo]=useState(''),[packageVersionId,setPackageVersionId]=useState(''),[sponsorCode,setSponsorCode]=useState(''),[quantities,setQuantities]=useState<Record<string,number>>({});
 const [receiptOrderNo,setReceiptOrderNo]=useState(''),[receiptReference,setReceiptReference]=useState(''),[paymentChannel,setPaymentChannel]=useState('BANK'),[paymentNamespace,setPaymentNamespace]=useState('UCELL'),[receiptAmount,setReceiptAmount]=useState(''),[receiptReceivedAt,setReceiptReceivedAt]=useState(''),[receiptNote,setReceiptNote]=useState('');
 const [approvalReference,setApprovalReference]=useState(''),[approvalChannel,setApprovalChannel]=useState('BANK'),[approvalNamespace,setApprovalNamespace]=useState('UCELL');
 const query=useQuery({queryKey:['paper-applications',status],queryFn:()=>get<any>('/admin/paper-applications'+qs({status:status||undefined,take:100}))});
 const packages=useQuery({queryKey:['packages'],queryFn:()=>get<any>('/admin/packages')});
 const products=useQuery({queryKey:['products'],queryFn:()=>get<any>('/admin/products')});
 const create=useMutation({mutationFn:()=>command<any>('/admin/paper-applications',{personId:person!.id,paperApplicationNo,receivedAt:new Date(receivedAt).toISOString(),evidenceDocumentRef:evidenceDocumentRef||undefined}),onSuccess:()=>{setPaperApplicationNo('');setEvidenceDocumentRef('');setReceivedAt('');void qc.invalidateQueries({queryKey:['paper-applications']});}});
 const createNewPerson=useMutation({mutationFn:()=>command<any>('/admin/paper-applications/new-person',{paperApplicationNo,legalName:newLegalName,documentCountry:newCountry,documentType:newType,documentNo:newDocumentNo,receivedAt:new Date(receivedAt).toISOString(),evidenceDocumentRef:evidenceDocumentRef||undefined}),onSuccess:()=>{setNewDocumentNo('');void qc.invalidateQueries({queryKey:['paper-applications']});}});
 const rows=query.data?.data??[];
 const activeVersions=(packages.data?.data??[]).filter((profile:any)=>profile.packageClass==='QUALIFICATION').flatMap((profile:any)=>profile.versions.filter((version:any)=>version.status==='ACTIVE').map((version:any)=>({...version,stableCode:profile.stableCode})));
 const selectedVersion=activeVersions.find((version:any)=>version.packageProfileVersionId===packageVersionId);
 const productName=(id:string)=>{const product=(products.data?.data??[]).find((row:any)=>(row.ruleProfiles??[]).some((rule:any)=>rule.productRuleProfileId===id));return product?`${product.sku} · ${product.displayName}`:'受控商品規則';};
 const selectionTotal=selectedVersion?.selectableProducts.reduce((sum:number,row:any)=>sum+(quantities[row.productRuleProfileId]??0),0)??0;
 const createOrder=useMutation({mutationFn:()=>command<any>('/admin/paper-applications/qualification-orders',{paperApplicationNo:orderApplicationNo,packageVersionId,sponsorCode:sponsorCode||undefined,selections:selectedVersion.selectableProducts.filter((row:any)=>(quantities[row.productRuleProfileId]??0)>0).map((row:any)=>({productRuleProfileId:row.productRuleProfileId,quantity:quantities[row.productRuleProfileId]}))}),onSuccess:()=>{setOrderApplicationNo('');setSponsorCode('');setPackageVersionId('');setQuantities({});void qc.invalidateQueries({queryKey:['paper-applications']});}});
 const enterReceipt=useMutation({mutationFn:()=>command<any>('/admin/paper-receipts',{orderNo:receiptOrderNo,receiptReference,paymentChannel,paymentNamespace,amount:receiptAmount,currency:'TWD',receivedAt:new Date(receiptReceivedAt).toISOString(),note:receiptNote||undefined}),onSuccess:()=>{setReceiptReference('');setReceiptAmount('');setReceiptNote('');void qc.invalidateQueries({queryKey:['paper-applications']});}});
 const approveReceipt=useMutation({mutationFn:()=>command<any>('/admin/paper-receipts/approve',{receiptReference:approvalReference,paymentChannel:approvalChannel,paymentNamespace:approvalNamespace}),onSuccess:()=>{setApprovalReference('');void qc.invalidateQueries({queryKey:['paper-applications']});}});
 async function searchPerson(q:string){const response:any=await get('/admin/persons'+qs({q,take:20}));return (response.data??[]).map((x:any)=>({id:x.personId,primary:x.memberNo,secondary:x.legalName??undefined}));}
 return <><PageHeader title="紙本申請 Intake" subtitle="受控證件指紋安全比對 Person；紙本證件原文與敏感身分資料不會顯示於此頁。"/>
 <Card title="建立新 Person 紙本申請"><div className="form"><Field label="法定姓名"><input value={newLegalName} onChange={e=>setNewLegalName(e.target.value)} maxLength={160}/></Field><Field label="證件國別"><input value={newCountry} onChange={e=>setNewCountry(e.target.value.toUpperCase())} maxLength={8}/></Field><Field label="證件類型"><input value={newType} onChange={e=>setNewType(e.target.value.toUpperCase())} maxLength={64}/></Field><Field label="證件號碼"><input value={newDocumentNo} onChange={e=>setNewDocumentNo(e.target.value)} maxLength={128}/></Field><small className="muted">證件號碼只在送出時用於受控 HMAC 比對，不會回傳、顯示或寫入一般稽核紀錄。未設定的國別／證件類型會安全拒絕。</small><button className="primary" disabled={!paperApplicationNo.trim()||!receivedAt||!newLegalName.trim()||!newCountry||!newType||!newDocumentNo||createNewPerson.isPending} onClick={()=>createNewPerson.mutate()}>安全比對並建立／重用 Person</button><ErrorBox error={createNewPerson.error}/>{createNewPerson.isSuccess&&<p role="status">已完成安全比對；如有可能重複身分，已送交審查。</p>}</div></Card>
 <Card title="建立紙本申請"><div className="form"><SearchSelect label="既有會員" value={person} onChange={setPerson} search={searchPerson} placeholder="輸入會員編號、姓名或聯絡資料"/><Field label="紙本申請編號"><input value={paperApplicationNo} onChange={e=>setPaperApplicationNo(e.target.value)} maxLength={80}/></Field><Field label="收件時間"><input type="datetime-local" value={receivedAt} onChange={e=>setReceivedAt(e.target.value)}/></Field><Field label="受控文件參照（選填）"><input value={evidenceDocumentRef} onChange={e=>setEvidenceDocumentRef(e.target.value)} maxLength={500}/></Field><small className="muted">找不到既有會員時，請依正式 duplicate-review 流程處理；此頁不建立新 Person。</small><button className="primary" disabled={!person||!paperApplicationNo.trim()||!receivedAt||create.isPending} onClick={()=>create.mutate()}>建立紙本申請</button><ErrorBox error={create.error}/>{create.isSuccess&&<p role="status">紙本申請已建立。</p>}</div></Card>
 <Card title="建立紙本資格套組訂單"><div className="form"><Field label="紙本申請編號"><input value={orderApplicationNo} onChange={e=>setOrderApplicationNo(e.target.value)} maxLength={80}/></Field><Field label="有效資格套組"><select value={packageVersionId} onChange={e=>{setPackageVersionId(e.target.value);setQuantities({});}}><option value="">請選擇</option>{activeVersions.map((version:any)=><option key={version.packageProfileVersionId} value={version.packageProfileVersionId}>{version.stableCode} · {version.displayName} · {version.currency} {version.priceAmount}</option>)}</select></Field>{selectedVersion&&<><p className="muted">此套組需要精確選擇 {selectedVersion.selectableProductQuantity} 件商品。價格與資格效果由後端版本快照決定。</p>{selectedVersion.selectableProducts.map((row:any)=><Field key={row.productRuleProfileId} label={`${productName(row.productRuleProfileId)}（${row.minQty??0}–${row.maxQty??'—'}）`}><input type="number" min={row.minQty??0} max={row.maxQty??undefined} value={quantities[row.productRuleProfileId]??0} onChange={e=>setQuantities(values=>({...values,[row.productRuleProfileId]:Number(e.target.value)}))}/></Field>)}</>}<Field label="推薦碼（選填）"><input value={sponsorCode} onChange={e=>setSponsorCode(e.target.value.toUpperCase())} maxLength={80}/></Field><button className="primary" disabled={!orderApplicationNo.trim()||!selectedVersion||selectionTotal!==selectedVersion.selectableProductQuantity||createOrder.isPending} onClick={()=>createOrder.mutate()}>建立紙本資格套組訂單</button><ErrorBox error={createOrder.error}/>{createOrder.isSuccess&&<p role="status">訂單已建立，請繼續以紙本收據流程確認付款。</p>}</div></Card>
 <Card title="登錄紙本收據"><div className="form"><Field label="訂單編號"><input value={receiptOrderNo} onChange={e=>setReceiptOrderNo(e.target.value.replace(/\D/g,''))} inputMode="numeric"/></Field><Field label="收據參考編號"><input value={receiptReference} onChange={e=>setReceiptReference(e.target.value)} maxLength={100}/></Field><Field label="收款管道"><input value={paymentChannel} onChange={e=>setPaymentChannel(e.target.value)} maxLength={40}/></Field><Field label="收款命名空間"><input value={paymentNamespace} onChange={e=>setPaymentNamespace(e.target.value)} maxLength={80}/></Field><Field label="收款金額"><input value={receiptAmount} onChange={e=>setReceiptAmount(e.target.value)} inputMode="decimal"/></Field><Field label="實際收件時間"><input type="datetime-local" value={receiptReceivedAt} onChange={e=>setReceiptReceivedAt(e.target.value)}/></Field><Field label="備註（選填）"><input value={receiptNote} onChange={e=>setReceiptNote(e.target.value)} maxLength={500}/></Field><small className="muted">登錄者不可覆核 Qualification 收款；請由另一位具權限人員在受控流程覆核。</small><button className="primary" disabled={!receiptOrderNo||!receiptReference.trim()||!paymentChannel.trim()||!paymentNamespace.trim()||!/^\d+(\.\d{1,2})?$/.test(receiptAmount)||!receiptReceivedAt||enterReceipt.isPending} onClick={()=>enterReceipt.mutate()}>登錄收據</button><ErrorBox error={enterReceipt.error}/>{enterReceipt.isSuccess&&<p role="status">收據已登錄，尚未確認付款。</p>}</div></Card>
 <Card title="覆核紙本收據"><div className="form"><Field label="收據參考編號"><input value={approvalReference} onChange={e=>setApprovalReference(e.target.value)} maxLength={100}/></Field><Field label="收款管道"><input value={approvalChannel} onChange={e=>setApprovalChannel(e.target.value)} maxLength={40}/></Field><Field label="收款命名空間"><input value={approvalNamespace} onChange={e=>setApprovalNamespace(e.target.value)} maxLength={80}/></Field><small className="muted">僅具覆核權限的角色可確認。若為資格套組且登錄者與覆核者相同，後端會拒絕操作。</small><button className="primary" disabled={!approvalReference.trim()||!approvalChannel.trim()||!approvalNamespace.trim()||approveReceipt.isPending} onClick={()=>approveReceipt.mutate()}>覆核並確認付款</button><ErrorBox error={approveReceipt.error}/>{approveReceipt.isSuccess&&<p role="status">付款確認已送交核心流程。</p>}</div></Card>
 <Card title="紙本申請與訂單"><label>狀態 <select value={status} onChange={e=>setStatus(e.target.value)}><option value="">全部</option><option>OPEN</option><option>ORDER_CREATED</option></select></label>
 {query.isPending?<LoadingState label="正在載入紙本申請…"/>:query.error?<ErrorState message={String(query.error)} retry={()=>void query.refetch()}/>:!rows.length?<EmptyState title="目前沒有紙本申請"/>:<div className="table-wrap"><table><thead><tr><th>紙本申請編號</th><th>會員編號</th><th>收件時間</th><th>狀態</th><th>訂單</th><th>付款</th></tr></thead><tbody>{rows.map((row:any)=><tr key={row.paperApplicationNo}><td>{row.paperApplicationNo}</td><td>{row.memberNo}</td><td>{row.receivedAt}</td><td><StatusBadge status={row.status}/></td><td>{row.order?`#${row.order.orderNo} · ${row.order.purpose}`:'—'}</td><td>{row.order?.status??'—'}</td></tr>)}</tbody></table></div>}
 </Card></>;
}
