import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Badge,Card,Field,Metric,PageHeader} from '../../components/ui';
import {QueryFeedback} from '../../components/QueryFeedback';
import {get,qs} from '../../lib/api';

type Checkpoint={code:string;label:string;status:string;evidence:string};
type Data={erpAccounting?:{projectionReference:string|null;status:string;state:string;memberPayableGross:string|null;currency:string|null;sourceChanged:boolean};reconciliationScope?:{periodReference:string;sharedPayoutLines:number;missingPayables:number;unpaidPayables:number;bankIncompleteLines:number};period:{periodStart:string;periodEnd:string;ruleVersionCode:string};lifecycle:string;dataThrough:string;elapsedSeconds?:number;checkpoints:Checkpoint[];jobs:{jobReference:string;kind:string;status:string;periodStart?:string;periodEnd?:string;attemptCount:number;completedAt:string|null;blockingCode:string|null}[];settlements:{kind:string;status:string;totalTheory:string;poolAvailable:string;kFactor:string;finalizedAt:string|null}[];amountBridge:Record<string,string|null>;payouts:{payoutReference:string;status:string;totalGross:string;totalRecovery:string;totalNet:string;paymentResults:{paid:number;failed:number}}[];blockingExceptions:{reference:string;code:string;status:string}[];freshness:{status:string;dataThrough:string};authority:{ucell:string;erp:string;hardClose:string}};
type Aging={asOf:string;thresholdHours:number;cutoff:string;items:{category:string;count:number;amount:string|null;oldestAt:string|null;status:string}[];authority:{threshold:string;facts:string;action:string}};
const tone=(status:string)=>['PASS','RECORDED','CURRENT','SOFT_CLOSED','FINANCIALLY_RECONCILED'].includes(status)?'ok':['FAILED','BLOCKED','ATTENTION'].includes(status)?'danger':['PENDING','RUNNING','READY','BLOCKED_EXTERNAL','NOT_AVAILABLE'].includes(status)?'warn':'neutral';
const money=(value:string|null|undefined)=>value===undefined?'尚無資料':value===null?'未建立 ERP 會計投影':Number(value).toLocaleString('zh-TW',{minimumFractionDigits:2,maximumFractionDigits:4});
const labels:Record<string,string>={OPEN:'尚未開始',PRECHECK:'前置檢查中',READY_TO_CLOSE:'可開始封存',SOFT_CLOSED:'輸入已封存',SETTLING:'結算中',RECONCILING:'對帳中',AWARD_FINALIZED:'獎金已定案',MATURING:'等待獎金成熟',PAYABLE_READY:'應付已備妥',PAYMENT_REVIEW:'付款審核中',EXPORTED:'已匯出',BANK_RECONCILING:'銀行結果對帳中',FINANCIALLY_RECONCILED:'會員經濟已對帳',BLOCKED:'有阻擋項目',PASS:'通過',FAILED:'失敗',PENDING:'等待處理',RUNNING:'處理中',PROCESSING:'執行中',PROCESSED:'已完成',DEAD:'執行失敗',CURRENT:'目前資料',RECORDED:'已有紀錄',ATTENTION:'需要處理',BLOCKED_EXTERNAL:'等待外部條件',NOT_AVAILABLE:'證據未齊',NOT_APPLICABLE:'本期不適用',NO_EFFECT_RECORDED:'本期無紀錄',READY:'已備妥',CLEAR:'無待辦',PAID:'已付款',PARTIALLY_PAID:'部分付款',REFERRAL_K0:'推薦獎金 K0',BINARY_K1:'雙軌獎金 K1',MATCHING_K2:'對等獎金 K2',GLOBAL:'全球分紅',WELFARE:'福利提撥',PAYABLE_PREPARATION:'應付準備',MATURED_AWARD_NOT_PAYABLE:'已成熟但未建應付',PAYABLE_NOT_BATCHED:'應付尚未分批',PAYOUT_EXPORTED_UNRESOLVED:'已匯出但結果未齊',BANK_TRANSFER_FAILED:'銀行失敗紀錄',RECOVERY_OUTSTANDING:'尚待回收',ERP_BRIDGE_ATTENTION:'ERP 對接待處理'};
const label=(value:string)=>labels[value]??value;
const problems:Record<string,string>={COMPENSATION_PAYABLE_SOURCE_MISMATCH:'應付與原始獎金不一致',COMPENSATION_RECOVERY_BALANCE_MISMATCH:'回收餘額與實際抵扣不一致',COMPENSATION_PAYOUT_TOTAL_MISMATCH:'付款批次合計不一致',COMPENSATION_PAYOUT_LINE_MISMATCH:'付款明細與應付或抵扣不一致',COMPENSATION_PAYOUT_SOURCE_UNATTRIBUTED:'付款缺少本期獎金來源連結',COMPENSATION_BANK_EVIDENCE_MISMATCH:'已付款狀態缺少完整銀行回覆',COMPENSATION_PAYOUT_APPROVAL_EVIDENCE_MISSING:'缺少獨立財務及稽核覆核證據',COMPENSATION_PAYOUT_EXPORT_EVIDENCE_INVALID:'付款匯出證據缺漏或不一致',COMPENSATION_BLOCKING_OPERATIONAL_EXCEPTION:'尚有未解決的重大營運例外',COMPENSATION_APPROVED_CALENDAR_UNAVAILABLE:'缺少完整的核准日曆設定',COMPENSATION_PREPARATION_COHORT_MISMATCH:'應付準備與核准來源期間不一致',COMPENSATION_RECEIPT_STATUS_MISMATCH:'完成憑證與執行狀態不一致',COMPENSATION_SEALED_RESULT_INVALID:'結算憑證缺少可驗證的封存證據',COMPENSATION_VOLUME_EVIDENCE_INVALID:'原始認列證據缺漏或晚於封存',PERIOD_CLOSE_EXECUTION_FAILED:'結算執行失敗',PERIOD_CLOSE_FAILED:'結算工作需要處理'};
export function CompensationPeriodControlPage(){
 const [draft,setDraft]=useState({periodStart:'',periodEnd:'',ruleVersionCode:'R1.0B',thresholdHours:'24'}),[selection,setSelection]=useState<typeof draft|null>(null);
 const query=useQuery({queryKey:['compensation-period-control',selection],queryFn:()=>get<{data:Data}>('/admin/compensation-period-control'+qs({periodStart:new Date(selection!.periodStart).toISOString(),periodEnd:new Date(selection!.periodEnd).toISOString(),ruleVersionCode:selection!.ruleVersionCode})),enabled:!!selection,refetchInterval:60_000});
 const aging=useQuery({queryKey:['compensation-aging-control',selection],queryFn:()=>get<{data:Aging}>('/admin/compensation-period-control/aging'+qs({thresholdHours:selection!.thresholdHours})),enabled:!!selection,refetchInterval:60_000});
 const data=query.data?.data,bridge=data?.amountBridge;
 return <><PageHeader title="獎金與會員經濟營運控制中心" subtitle="控制 UCell 獎金週期；不代表 ERP／法定會計月結。" actions={<button disabled={!selection||query.isFetching} onClick={()=>void query.refetch()}>重新整理</button>}/>
  <Card title="選擇獎金週期"><form onSubmit={event=>{event.preventDefault();setSelection({...draft,ruleVersionCode:draft.ruleVersionCode.trim()})}}><div className="filter-grid"><Field label="期間開始"><input required type="datetime-local" value={draft.periodStart} onChange={event=>setDraft(value=>({...value,periodStart:event.target.value}))}/></Field><Field label="期間結束"><input required type="datetime-local" value={draft.periodEnd} onChange={event=>setDraft(value=>({...value,periodEnd:event.target.value}))}/></Field><Field label="Rule Version"><input required maxLength={100} value={draft.ruleVersionCode} onChange={event=>setDraft(value=>({...value,ruleVersionCode:event.target.value}))}/></Field><Field label="營運逾時門檻（小時）"><input required type="number" min="1" max="8760" value={draft.thresholdHours} onChange={event=>setDraft(value=>({...value,thresholdHours:event.target.value}))}/></Field></div><button className="primary" type="submit">載入控制狀態</button></form></Card>
  {!selection&&<Card><p>選擇獎金週期後，系統以同一資料庫快照讀取結算、Award、Recovery、Payable 與付款證據。</p></Card>}<QueryFeedback query={query}/>
  {data&&<><Card title="週期狀態"><div className="status-strip"><Badge tone={tone(data.lifecycle)}>{label(data.lifecycle)}</Badge><span>資料截點：{new Date(data.dataThrough).toLocaleString('zh-TW')}</span>{data.elapsedSeconds!==undefined&&<span>期末後經過 {(data.elapsedSeconds/3600).toLocaleString('zh-TW',{maximumFractionDigits:1})} 小時</span>}</div><p className="muted">會員經濟已對帳只表示 UCell 證據通過對帳；ERP 會計投影狀態另列。</p></Card>
   <Card title="阻擋與警示">{data.blockingExceptions.length?<ul>{data.blockingExceptions.map((row,index)=><li key={`${row.reference}:${row.code}:${index}`}><strong>{problems[row.code]??'需要確認的營運證據'}</strong> · {row.reference} · {row.status==='OPEN'?'待處理':label(row.status)}</li>)}</ul>:<p>目前沒有已列出的阻擋項目；請一併檢查下方尚未通過的檢查點。</p>}</Card>
   {bridge&&<div className="metrics"><Metric label="已記錄理論獎金（不含全球分紅）" value={money(bridge.grossTheory)}/><Metric label="全球分紅分配" value={money(bridge.globalAllocated)}/><Metric label="核定獎金" value={money(bridge.awardAfterEligibilityAndK)}/><Metric label="水庫 B" value={money(bridge.companyReservoirB)}/><Metric label="尚待回收" value={money(bridge.recoveryOutstanding)}/><Metric label="已建應付" value={money(bridge.payableMaterialized)}/><Metric label="相關付款明細淨額" value={money(bridge.payoutNet)}/><Metric label="相關付款明細銀行已付" value={money(bridge.bankPaid)}/><Metric label="ERP 封存應付毛額" value={money(bridge.erpAccountingProjection)}/></div>}
   {data.erpAccounting&&<Card title="ERP 獨立對帳狀態"><Badge tone={tone(data.erpAccounting.status)}>{label(data.erpAccounting.status)}</Badge><p>{data.erpAccounting.state==='NOT_CREATED'?'尚未建立聚合投影。':data.erpAccounting.sourceChanged?'核准後來源數字已改變，需補充投影及對帳；原快照保持不變。':data.erpAccounting.state==='SEALED_MAPPING_REQUIRED'?'財務聚合已封存，仍等待核准會計科目映射。':'請查閱 ERP 受理與對帳證據。'}</p><p>封存應付毛額：{money(data.erpAccounting.memberPayableGross)} {data.erpAccounting.currency}；不代表 ERP 已過帳。</p><a href={'/erp-reconciliation?stream=COMPENSATION'+(data.erpAccounting.projectionReference?'&projection='+encodeURIComponent(data.erpAccounting.projectionReference):'')}>查看獎金聚合與來源明細</a></Card>}
   {data.reconciliationScope&&<Card title="金額對帳範圍"><p>獎金與應付依本期來源計算。付款及銀行金額列出相關付款明細的完整金額，可能包含其他週期；尚未分攤至單一獎金週期。</p><p>跨期共用付款明細：{data.reconciliationScope.sharedPayoutLines} 筆；已成熟但缺少應付：{data.reconciliationScope.missingPayables} 筆；尚未付清應付：{data.reconciliationScope.unpaidPayables} 筆；銀行證據未齊明細：{data.reconciliationScope.bankIncompleteLines} 筆。</p></Card>}
   <Card title="控制檢查點"><div className="table-wrap"><table><thead><tr><th>檢查點</th><th>狀態</th><th>權威證據</th></tr></thead><tbody>{data.checkpoints.map(row=><tr key={row.code}><td>{labels[row.code]??row.label}</td><td><Badge tone={tone(row.status)}>{label(row.status)}</Badge></td><td>{row.evidence}</td></tr>)}</tbody></table></div></Card>
   <Card title="結算工作"><ul>{data.jobs.map(row=><li key={row.jobReference}><strong>{label(row.kind)}</strong> · <Badge tone={tone(row.status)}>{label(row.status)}</Badge> · 已嘗試 {row.attemptCount} 次{row.periodStart&&row.periodEnd&&<p>{new Date(row.periodStart).toLocaleString('zh-TW')} → {new Date(row.periodEnd).toLocaleString('zh-TW')}</p>}<small>{row.jobReference}</small>{row.blockingCode&&<p>{problems[row.blockingCode]??'請查閱結算工作的待處理證據'}</p>}</li>)}</ul>{!data.jobs.length&&<p>尚無受治理的結算工作。</p>}</Card>
   <QueryFeedback query={aging}/>{aging.data?.data&&<Card title={`目前全域未結項（${aging.data.data.thresholdHours} 小時門檻）`}><div className="table-wrap"><table><thead><tr><th>類別</th><th>狀態</th><th>筆數</th><th>金額</th><th>最早證據</th></tr></thead><tbody>{aging.data.data.items.map(row=><tr key={row.category}><td>{label(row.category)}</td><td><Badge tone={tone(row.status)}>{label(row.status)}</Badge></td><td>{row.count}</td><td>{row.amount===null?'不適用':money(row.amount)}</td><td>{row.oldestAt?new Date(row.oldestAt).toLocaleString('zh-TW'):'—'}</td></tr>)}</tbody></table></div><p className="muted">截至 {new Date(aging.data.data.asOf).toLocaleString('zh-TW')} 的全域待處理項目。門檻由本次查詢提供；處理仍須透過結算、付款、回收或 ERP 對帳流程。</p></Card>}
   <Card title="對帳範圍"><p><strong>UCell：</strong>會員獎金、應付、回收與銀行結果。</p><p><strong>ERP：</strong>公司會計、庫存與憑證的對接結果另行對帳。UCell 已付款不代表 ERP 已入帳。</p></Card></>}
 </>;
}
