import {act,create} from 'react-test-renderer';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {describe,expect,it,vi} from 'vitest';
import {CompensationPeriodControlPage} from './CompensationPeriodControlPage';
import * as api from '../../lib/api';
vi.mock('../../lib/api');
vi.mock('./CompensationPeriodSources',()=>({CompensationPeriodSources:()=>null}));
it('preserves the exact linked period in Taipei fields without inventing an aging threshold',async()=>{
 const start='2026-09-09T16:00:00.000Z',end='2026-09-24T16:00:00.000Z';vi.stubGlobal('window',{location:{search:'?'+new URLSearchParams({periodStart:start,periodEnd:end,ruleVersionCode:'R1.0B'})}});vi.mocked(api.get).mockReset().mockResolvedValue({data:{lifecycle:'OPEN',dataThrough:end,checkpoints:[],jobs:[],settlements:[],payouts:[],blockingExceptions:[],freshness:{},authority:{}}} as any);vi.mocked(api.qs).mockImplementation(values=>'?'+new URLSearchParams(Object.entries(values).filter(([,value])=>value!=null).map(([key,value])=>[key,String(value)])).toString());
 let tree:any;try{await act(async()=>{tree=create(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><CompensationPeriodControlPage/></QueryClientProvider>);await new Promise(resolve=>setTimeout(resolve,80));});expect(api.get).toHaveBeenCalledWith('/admin/compensation-period-control?'+new URLSearchParams({periodStart:start,periodEnd:end,ruleVersionCode:'R1.0B'}));expect(vi.mocked(api.get).mock.calls.some(([url])=>url.includes('/aging'))).toBe(false);expect(tree.root.findAllByType('input')[0].props.value).toBe('2026-09-10T00:00:00.000');}
 finally{if(tree)await act(async()=>tree.unmount());vi.unstubAllGlobals();}
});
describe('CompensationPeriodControlPage',()=>{it('labels UCell and ERP authority independently and shows parameterized aging without internal ids',async()=>{vi.mocked(api.get).mockImplementation(async url=>url.includes('/aging')?{data:{asOf:'2026-09-08Z',thresholdHours:24,cutoff:'2026-09-07Z',items:[{category:'RECOVERY_OUTSTANDING',count:2,amount:'45.0000',oldestAt:'2026-09-01Z',status:'ATTENTION'}],authority:{threshold:'Operator-supplied operational parameter',facts:'Stored facts',action:'Read-only'}}}:{data:{period:{periodStart:'2026-09-01Z',periodEnd:'2026-09-08Z',ruleVersionCode:'R1.0B'},reconciliationScope:{periodReference:'COMPENSATION-PERIOD-abc',sharedPayoutLines:1,missingPayables:0,unpaidPayables:0,bankIncompleteLines:0},lifecycle:'BLOCKED',elapsedSeconds:7200,dataThrough:'2026-09-29T00:00:00Z',checkpoints:[{code:'ERP_ACCOUNTING',label:'ERP accounting projection',status:'BLOCKED_EXTERNAL',evidence:'ERP_ACCOUNT_MAPPING_REQUIRED'}],jobs:[{jobReference:'PERIOD-JOB-abc',kind:'REFERRAL_K0',status:'PROCESSED',attemptCount:1,completedAt:'2026-09-29Z',blockingCode:null}],settlements:[],amountBridge:{grossTheory:'100.0000',awardAfterEligibilityAndK:'80.0000',companyReservoirB:'10.0000',recoveryOutstanding:'0.0000',payoutNet:'70.0000',bankPaid:'70.0000',erpAccountingProjection:null},payouts:[],blockingExceptions:[{reference:'PERIOD-RECOGNITION',code:'COMPENSATION_VOLUME_EVIDENCE_INVALID',status:'OPEN'}],freshness:{status:'CURRENT',dataThrough:'2026-09-29Z'},authority:{ucell:'Member compensation/economic control only',erp:'Corporate accounting projection remains independent',hardClose:'Not persisted by this read model'}}} as any);let tree:any;await act(async()=>{tree=create(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><CompensationPeriodControlPage/></QueryClientProvider>)});const inputs=tree.root.findAllByType('input');await act(async()=>{inputs[0].props.onChange({target:{value:'2026-09-01T00:00'}});inputs[1].props.onChange({target:{value:'2026-09-08T00:00'}});});await act(async()=>{tree.root.findByType('form').props.onSubmit({preventDefault(){}});await new Promise(resolve=>setTimeout(resolve,100));});const text=JSON.stringify(tree.toJSON());expect(text).toContain('有阻擋項目');expect(text).toContain('原始認列證據缺漏或晚於封存');expect(text).toContain('期末後經過');expect(text).toContain('等待外部條件');expect(text).toContain('尚待回收');expect(text).toContain('跨期共用付款明細');expect(text).toContain('尚未分攤至單一獎金週期');expect(text).toContain('相關付款明細銀行已付');expect(text).toContain('24 小時門檻');expect(text).toContain('不代表 ERP／法定會計月結');expect(text).not.toMatch(/[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}/i);});});
