import {useRef,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Card,Field,PageHeader} from '../../components/ui';
import {QueryFeedback} from '../../components/QueryFeedback';
import {get,post} from '../../lib/api';
type Lesson={title:string;contentType:string;contentReference:string;required:boolean};
type Course={courseCode:string;status:string;enrollmentCount:number;versions:{version:number;title:string;summary:string|null;categoryCode:string;status:string;publishFrom:string|null;publishTo:string|null;lessons:(Lesson&{sequenceNo:number})[]}[]};
const emptyLesson=():Lesson=>({title:'',contentType:'ARTICLE',contentReference:'',required:true});
const state=(value:string)=>({DRAFT:'草稿',PUBLISHED:'已發布',ARCHIVED:'已封存'}[value]??'狀態待確認');
const types:Record<string,string>={ARTICLE:'文章',VIDEO_REFERENCE:'影片連結',DOCUMENT_REFERENCE:'文件／PDF 連結',EXTERNAL_LINK:'外部教材連結'};
export function LearningPage(){
 const query=useQuery({queryKey:['learning-admin'],queryFn:()=>get<{data:Course[]}>('/admin/learning/courses')});
 const [courseCode,setCode]=useState(''),[title,setTitle]=useState(''),[summary,setSummary]=useState(''),[categoryCode,setCategory]=useState('ONBOARDING'),[lessons,setLessons]=useState<Lesson[]>([emptyLesson()]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const keys=useRef(new Map<string,string>()),flight=useRef(false);
 async function command(path:string,body:unknown){if(flight.current)return false;flight.current=true;setBusy(true);setError('');setNotice('');const signature=path+JSON.stringify(body),key=keys.current.get(signature)??crypto.randomUUID();keys.current.set(signature,key);try{await post(path,body,{idempotencyKey:key});keys.current.delete(signature);setNotice('課程資料已保存。');await query.refetch();return true;}catch(e){setError(e instanceof Error?e.message:'操作失敗，請重試。');return false;}finally{flight.current=false;setBusy(false);}}
 function change(index:number,patch:Partial<Lesson>){setLessons(rows=>rows.map((row,i)=>i===index?{...row,...patch}:row));}
 return <><PageHeader title="教育訓練管理" subtitle="建立教材草稿、核准發布及封存；學習完成不會改變會員資格或獎金。"/>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<Card title="建立課程草稿"><form onSubmit={async event=>{event.preventDefault();if(await command('/admin/learning/courses',{courseCode,title,summary,categoryCode,lessons})){setCode('');setTitle('');setSummary('');setLessons([emptyLesson()]);}}}><fieldset disabled={busy}><div className="filter-grid"><Field label="課程代碼"><input required pattern="[A-Z][A-Z0-9_-]{2,39}" value={courseCode} onChange={e=>setCode(e.target.value.toUpperCase())}/></Field><Field label="課程名稱"><input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="分類代碼"><input required pattern="[A-Z][A-Z0-9_-]{2,39}" value={categoryCode} onChange={e=>setCategory(e.target.value.toUpperCase())}/></Field></div><Field label="課程說明"><textarea value={summary} maxLength={4000} onChange={e=>setSummary(e.target.value)}/></Field><p>對象：網路會員及正式會員。教材連結在發布前須完成內容審核。</p>{lessons.map((lesson,index)=><fieldset key={index}><legend>第 {index+1} 課</legend><Field label="單元名稱"><input required value={lesson.title} maxLength={160} onChange={e=>change(index,{title:e.target.value})}/></Field><Field label="教材形式"><select value={lesson.contentType} onChange={e=>change(index,{contentType:e.target.value})}>{Object.entries(types).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><Field label={lesson.contentType==='ARTICLE'?'文章內容':'已審核的 HTTPS 教材網址'}><textarea required maxLength={20000} value={lesson.contentReference} onChange={e=>change(index,{contentReference:e.target.value})}/></Field><label className="checkbox"><input type="checkbox" checked={lesson.required} onChange={e=>change(index,{required:e.target.checked})}/>必修</label>{lessons.length>1&&<button type="button" onClick={()=>setLessons(rows=>rows.filter((_,i)=>i!==index))}>移除第 {index+1} 課</button>}</fieldset>)}<button type="button" disabled={lessons.length>=100} onClick={()=>setLessons(rows=>[...rows,emptyLesson()])}>新增單元</button> <button type="submit">保存草稿</button></fieldset></form></Card><QueryFeedback query={query} empty={query.data?.data.length===0}/><p>最多顯示最近 100 門課程，以下數量不是全系統統計。</p>{query.data?.data.map(course=><CourseCard key={course.courseCode} course={course} busy={busy} command={command}/>)}</>;
}
function CourseCard({course,busy,command}:{course:Course;busy:boolean;command:(path:string,body:unknown)=>Promise<boolean>}){
 const [approval,setApproval]=useState(''),[reason,setReason]=useState(''),v=course.versions[0],path=`/admin/learning/courses/${encodeURIComponent(course.courseCode)}`;
 return <Card title={v?.title??course.courseCode}><p>{course.courseCode} · {state(course.status)} · {course.enrollmentCount} 筆報名</p><p>{v?.summary}</p>{course.versions.map(version=><details key={version.version}><summary>第 {version.version} 版 · {state(version.status)} · {version.lessons.length} 課</summary><p>分類：{version.categoryCode}</p>{version.lessons.map(lesson=><section key={lesson.sequenceNo}><h4>{lesson.sequenceNo}. {lesson.title}（{lesson.required?'必修':'選修'}）</h4><p>{types[lesson.contentType]??'教材'}</p><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{lesson.contentReference}</p></section>)}</details>)}{course.status!=='ARCHIVED'&&v?.status==='DRAFT'&&<form onSubmit={e=>{e.preventDefault();void command(`${path}/publish`,{approvalReference:approval});}}><Field label="發布核准依據"><input required maxLength={200} disabled={busy} value={approval} onChange={e=>setApproval(e.target.value)}/></Field><button disabled={busy||!approval.trim()}>核准發布</button></form>}{course.status!=='ARCHIVED'&&<form onSubmit={e=>{e.preventDefault();void command(`${path}/archive`,{reason});}}><p>封存後停止新增學習進度，既有報名及完成證據會保留。</p><Field label="封存原因"><input required maxLength={500} disabled={busy} value={reason} onChange={e=>setReason(e.target.value)}/></Field><button disabled={busy||!reason.trim()}>封存課程</button></form>}</Card>;
}
