import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Badge,Card,Field,Metric,PageHeader} from '../../components/ui';
import {QueryFeedback} from '../../components/QueryFeedback';
import {get,qs} from '../../lib/api';
type Item={reference:string;stream:string;state:string;orderNo:string|null;fulfillmentKey:string|null;requestedAt:string;acknowledgedAt:string|null;reconciledAt:string|null;elapsedHours:number;thresholdHours:number|null;exceptionReferences:string[];blockedReason:string|null;link:string;candidate:{code:string;severity:string;evidenceHash:string}|null};
type Page={items:Item[];counts:Record<string,number>;observed:number;candidateCount:number;latestSuccessfulReconciliation:string|null;nextCursor:string|null;asOf:string;dataThrough:string;coverage:string};
const labels:Record<string,string>={SALES:'銷售',RETURN:'退貨',COMPENSATION:'獎金／付款會計',FULFILLMENT:'履約交付',READY:'已準備',QUEUED:'等待處理',SENT:'傳送中',ACKNOWLEDGED:'ERP 已受理',RECONCILED:'ERP 已對帳',MISMATCH:'ERP 有差異',FAILED:'處理失敗',BLOCKED_EXTERNAL:'等待外部條件',ERP_TRANSPORT_FAILED:'ERP 傳送失敗',ERP_RESULT_MISMATCH:'ERP 回報與封存資料不符',ERP_OPEN_EXCEPTION:'仍有未結案例外',ERP_RECONCILIATION_OVERDUE:'已受理但對帳等待超過門檻',ERP_HANDOFF_OVERDUE:'交付等待超過門檻'};
const time=(value:string|null)=>value?new Date(value).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'}):'尚無';
export function OperationsControlPage(){
 const [stream,setStream]=useState('SALES'),[draft,setDraft]=useState(''),[threshold,setThreshold]=useState<number|undefined>(),[cursor,setCursor]=useState<string|undefined>(),[asOf,setAsOf]=useState<string|undefined>();
 const query=useQuery({queryKey:['operations-erp-health',stream,threshold,cursor,asOf],queryFn:()=>get<{data:Page}>('/admin/operations/control/erp-health'+qs({stream,thresholdHours:threshold,cursor,asOf,take:25})),refetchInterval:60_000});
 const data=query.data?.data,reset=()=>{setCursor(undefined);setAsOf(undefined);};
 return <><PageHeader title="營運控制中心" subtitle="從目前證據追蹤 ERP 健康、差異與待處理事項。ERP、付款與會員經濟狀態各自保留。"/><Card title="ERP 分流健康"><form onSubmit={event=>{event.preventDefault();setThreshold(draft===''?undefined:Number(draft));reset();}}><div className="filter-grid"><Field label="ERP 資料流"><select value={stream} onChange={event=>{setStream(event.target.value);reset();}}>{['SALES','FULFILLMENT','COMPENSATION','RETURN'].map(value=><option key={value} value={value}>{labels[value]}</option>)}</select></Field><Field label="作業等待門檻（小時，可留白）"><input type="number" min="1" max="8760" step="1" value={draft} onChange={event=>setDraft(event.target.value)}/></Field></div><button type="submit">套用等待門檻</button> <button type="button" onClick={()=>void query.refetch()} disabled={query.isFetching}>重新讀取目前狀態</button></form><p>留白時僅列出失敗、差異與未結案例外，不推定逾期。門檻是作業檢查參數。</p></Card>
 <QueryFeedback query={query} empty={!!data&&!data.items.length}/>{data&&<><Card title="本頁觀察範圍"><p>以下數量只涵蓋本頁 {data.observed} 筆；請翻頁檢查其餘資料，不代表全系統總量。</p><div className="metric-grid"><Metric label="待處理候選" value={data.candidateCount}/>{Object.entries(data.counts).map(([key,count])=><Metric key={key} label={labels[key]??key} value={count}/>)}</div><p>本頁最近成功 ERP 對帳：{time(data.latestSuccessfulReconciliation)}</p><p>資料建立範圍截至：{time(data.asOf)} · 狀態讀取時間：{time(data.dataThrough)}</p></Card><Card title="具體證據與處理入口"><div className="table-wrap"><table><thead><tr><th>來源</th><th>ERP 狀態</th><th>建立／受理後經過</th><th>需處理事項</th><th>證據入口</th></tr></thead><tbody>{data.items.map(row=><tr key={row.reference}><td>{row.orderNo?'訂單 '+row.orderNo:labels[row.stream]}{row.fulfillmentKey&&<><br/>{row.fulfillmentKey}</>}</td><td><Badge tone={row.candidate?'danger':row.state==='RECONCILED'?'ok':'warn'}>{labels[row.state]??row.state}</Badge>{row.blockedReason&&<p>{row.blockedReason==='ERP_ACCOUNT_MAPPING_REQUIRED'?'尚待核准會計映射':'尚待核准實際傳輸條件'}</p>}</td><td>{row.elapsedHours} 小時{row.thresholdHours!==null&&<>／門檻 {row.thresholdHours} 小時</>}</td><td>{row.candidate?labels[row.candidate.code]??row.candidate.code:'本頁檢查未發現候選'}{row.exceptionReferences.length>0&&<p>尚有待處理例外；對帳相符不會自動結案。</p>}</td><td><a href={row.link}>查看來源及對帳證據</a><details><summary>檢查依據</summary><p>{row.reference}</p><p>建立：{time(row.requestedAt)}</p><p>ERP 受理：{time(row.acknowledgedAt)}</p><p>ERP 對帳：{time(row.reconciledAt)}</p>{row.candidate&&<p>{row.candidate.evidenceHash}</p>}</details></td></tr>)}</tbody></table></div>{data.nextCursor&&<button onClick={()=>{setCursor(data.nextCursor!);setAsOf(data.asOf);}}>下一頁</button>}{cursor&&<button onClick={reset}>返回第一頁</button>}</Card></>}
 <Card title="其他權威證據"><a href="/compensation-period-control">獎金週期控制</a> · <a href="/settlement-jobs">結算工作</a> · <a href="/payouts">付款批次與銀行對帳</a> · <a href="/admin/finance/reservoirs">Company／Reservoir 證據</a></Card></>;
}
