import {CandidateTaskForm} from './OperationsWorkItems';
import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Card,Field,Metric} from '../../components/ui';
import {QueryFeedback} from '../../components/QueryFeedback';
import {get,qs} from '../../lib/api';
type Item={reference:string;scope:string;status:string;createdAt:string;evidence:Record<string,string|number|boolean|null>;actionLink:string|null;candidates:{code:string;evidenceHash:string}[]};
type Page={items:Item[];observed:number;counts:{attention:number;bankFailedLines:number;bankUnreconciledLines:number};recoveryOutstanding:string;nextCursor:string|null;asOf:string;dataThrough:string};
const labels:Record<string,string>={PAYOUT:'付款批次／銀行對帳',PAYABLE:'可付款項來源',RECOVERY:'追回餘額',PAYOUT_BATCH_TOTAL_MISMATCH:'付款批次與明細總額不符',PAYOUT_LINE_SOURCE_MISMATCH:'付款明細與應付／抵扣來源不符',BANK_RESULT_FAILED:'銀行回報失敗，尚未確認完整付款',BANK_RESULT_INCOMPLETE:'銀行付款尚未完整確認',BANK_PAID_EVIDENCE_MISSING:'已付款狀態缺少完整銀行證據',PAYABLE_SOURCE_MISSING:'找不到可付款項的獎金來源',PAYABLE_SOURCE_TYPE_UNSUPPORTED:'可付款項來源類別待確認',PAYABLE_SOURCE_MISMATCH:'可付款項與獎金來源不符',PAYABLE_MATURITY_EVIDENCE_MISSING:'缺少獎金生效或到期證據',PAYABLE_PAYOUT_LINK_MISMATCH:'可付款項與付款明細連結不符',RECOVERY_BALANCE_MISMATCH:'追回餘額與抵扣紀錄不符',RECOVERY_OUTSTANDING:'尚有待追回款項'};
const states:Record<string,string>={DRAFT:'草稿',READY:'待覆核',REVIEWED:'待獨立核准',APPROVED:'已核准',EXPORTED:'已匯出',PROCESSING:'對帳中',PARTIALLY_PAID:'部分付款',FAILED:'付款失敗',PAID:'已付款',VOIDED:'已作廢',OPEN:'待處理',BATCHED:'已納入批次',PARTIALLY_RECOVERED:'部分追回',RECOVERED:'已追回',CLOSED:'已結清'};
const fields:Record<string,string>={periodStart:'付款期間起',periodEnd:'付款期間迄',totalGross:'整批應付總額',totalRecovery:'整批追回抵扣',totalNet:'整批淨額',lineGross:'明細應付合計',lineRecovery:'明細抵扣合計',lineNet:'明細淨額合計',bankConfirmed:'整批累計銀行確認',lineCount:'明細筆數',bankFailedLines:'銀行失敗明細',bankUnreconciledLines:'銀行未完整確認明細',bankStage:'已進入匯出／銀行階段',brokenLineCount:'來源異常明細',amountScope:'金額範圍',sourceType:'獎金來源類別',sourceReference:'來源參考碼',grossAmount:'可付款金額',sourceAmount:'獎金來源金額',ruleVersionCode:'可付款規則版本',sourceRuleVersionCode:'來源規則版本',availableAt:'可付款時間',sourceExists:'來源存在',companyDestination:'Company 去向',payoutReference:'付款批次參考碼',recoveryRequired:'應追回',recoveryApplied:'已抵扣',recoveryOutstanding:'待追回',applicationCount:'抵扣筆數',occurredAt:'發生時間'};
function initial(){const params=typeof window==='undefined'?new URLSearchParams():new URLSearchParams(window.location.search),scope=params.get('scope')??'PAYOUT',reference=params.get('reference');return {scope:['PAYOUT','PAYABLE','RECOVERY'].includes(scope)?scope:'PAYOUT',reference:reference&&new RegExp(`^${scope}-[a-f0-9]{40}$`).test(reference)?reference:undefined};}
export function OperationsFinancialHealth(){
 const [filter,setFilter]=useState(initial),[cursor,setCursor]=useState<string>(),[asOf,setAsOf]=useState<string>();
 const reset=()=>{setCursor(undefined);setAsOf(undefined);};
 const query=useQuery({queryKey:['operations-financial-health',filter.scope,filter.reference,cursor,asOf],queryFn:()=>get<{data:Page}>('/admin/operations/control/financial-health'+qs({...filter,take:25,cursor,asOf})),refetchInterval:60_000}),data=query.data?.data;
 return <section id="financial-source-health"><Card title="財務來源與銀行健康"><Field label="財務證據類別"><select value={filter.scope} onChange={event=>{setFilter({scope:event.target.value,reference:undefined});reset();}}>{['PAYOUT','PAYABLE','RECOVERY'].map(scope=><option key={scope} value={scope}>{labels[scope]}</option>)}</select></Field>{filter.reference&&<p>目前只檢查指定商業參考碼。<button onClick={()=>{setFilter({...filter,reference:undefined});reset();}}>查看完整佇列</button></p>}<button disabled={query.isFetching} onClick={()=>void query.refetch()}>重新讀取財務證據</button><p>每頁最多 25 筆。數量及金額只涵蓋本頁，不代表全系統。銀行金額採各明細最高累計確認值；整批數值不分攤至獎金期間。</p><QueryFeedback query={query} empty={!!data&&!data.items.length}/>{data&&!query.error&&<><div className="metric-grid"><Metric label="本頁待處理來源" value={data.counts.attention}/>{filter.scope==='PAYOUT'&&<><Metric label="本頁銀行失敗明細" value={data.counts.bankFailedLines}/><Metric label="本頁銀行未完整確認明細" value={data.counts.bankUnreconciledLines}/></>}{filter.scope==='RECOVERY'&&<Metric label="本頁待追回金額" value={data.recoveryOutstanding}/>}</div><p>建立範圍截至 {new Date(data.asOf).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'})}；狀態讀取時間 {new Date(data.dataThrough).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'})}。</p>{data.items.map(item=><section key={item.reference}><h3>{labels[item.scope]} · {item.reference}</h3><p>來源狀態：{states[item.status]??'待核對'}</p>{item.candidates.length?<ul>{item.candidates.map(candidate=><li key={candidate.code}>{labels[candidate.code]??candidate.code}<CandidateTaskForm candidate={{stream:item.scope,reference:item.reference,code:candidate.code,evidenceHash:candidate.evidenceHash,asOf:data.asOf}}/><details><summary>檢查依據</summary><code>{candidate.evidenceHash}</code></details></li>)}</ul>:<p>本次檢查未發現異常，不代表整個來源流程已完成。</p>}{item.actionLink&&<a href={item.actionLink}>開啟付款批次並處理對帳</a>}<details><summary>查看具體來源證據</summary><dl>{Object.entries(item.evidence).map(([key,value])=><div key={key}><dt>{fields[key]??key}</dt><dd>{typeof value==='boolean'?value?'是':'否':value==='WHOLE_PAYOUT_BATCH'?'整個付款批次':value??'尚無'}</dd></div>)}</dl></details></section>)}{data.nextCursor&&<button onClick={()=>{setCursor(data.nextCursor!);setAsOf(data.asOf);}}>財務證據下一頁</button>}{cursor&&<button onClick={reset}>財務證據第一頁</button>}</>}</Card></section>;
}
