import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Card,Field,Metric} from '../../components/ui';
import {QueryFeedback} from '../../components/QueryFeedback';
import {get,qs} from '../../lib/api';
import {CandidateTaskForm} from './OperationsWorkItems';
type Item={reference:string;scope:string;evidence:{qualificationNo:string|null;awardType:string;historicalCompany:boolean;occurredAt:string;sourceAmount:string;ruleVersionCode:string;destinationReference:string|null;destination:string|null;periodStart:string|null;periodEnd:string|null;originalEntitlement:string|null;originalCredit:string;originalEffectCount:number;replayAdjustment:string;replayEffectCount:number;recordedBalance:string};candidates:{code:string;evidenceHash:string;detail:Record<string,unknown>}[]};
type Page={items:Item[];observed:number;attention:number;nextCursor:string|null;asOf:string;dataThrough:string};
const labels:Record<string,string>={COMPANY_BONUS:'一般獎金來源',COMPANY_RPV:'RPV 獎金來源',COMPANY_GLOBAL:'全球分紅來源',COMPANY_AWARD_DESTINATION_MISSING:'Company 權益尚未記錄 Reservoir B 去向',RESERVOIR_B_ENTITLEMENT_MISMATCH:'原始權益與原始入帳不一致',RESERVOIR_B_REPLAY_MISMATCH:'Replay 更正與調整分錄不一致',RESERVOIR_B_MEMBER_PAYABLE_CONFLICT:'Company 權益同時出現會員應付'};
const when=(value:string|null)=>value?new Date(value).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'}):'尚無';
function initial(){const params=typeof window==='undefined'?new URLSearchParams():new URLSearchParams(window.location.search),value=params.get('company'),scope=value&&['COMPANY_BONUS','COMPANY_RPV','COMPANY_GLOBAL'].includes(value)?value:'COMPANY_BONUS',reference=params.get('reference');return {scope,reference:reference&&new RegExp('^'+scope.replace('_','-')+'-[a-f0-9]{40}$').test(reference)?reference:undefined};}
export function OperationsCompanyHealth(){
 const [filter,setFilter]=useState(initial),[cursor,setCursor]=useState<string>(),[asOf,setAsOf]=useState<string>();const reset=()=>{setCursor(undefined);setAsOf(undefined);};
 const query=useQuery({queryKey:['operations-company-health',filter,cursor,asOf],queryFn:()=>get<{data:Page}>('/admin/operations/control/company-health'+qs({...filter,take:25,cursor,asOf})),refetchInterval:60_000}),data=query.data?.data;
 return <Card title="Company／Reservoir B 對帳"><Field label="Company 檢查來源"><select value={filter.scope} onChange={event=>{setFilter({scope:event.target.value,reference:undefined});reset();}}>{['COMPANY_BONUS','COMPANY_RPV','COMPANY_GLOBAL'].map(scope=><option key={scope} value={scope}>{labels[scope]}</option>)}</select></Field><button disabled={query.isFetching} onClick={()=>void query.refetch()}>重新讀取 Company 證據</button>{filter.reference&&<button onClick={()=>{setFilter({...filter,reference:undefined});reset();}}>查看完整 Company 佇列</button>}<p>按獎金發生時的歷史所有權檢查，保留健康及會員來源以免分頁漏查。原始權益與後續正負調整分開列示；以下僅涵蓋本頁，不代表全部水庫餘額。</p><QueryFeedback query={query} empty={!!data&&!data.items.length}/>{data&&!query.error&&<><div className="metric-grid"><Metric label="本頁來源" value={data.observed}/><Metric label="本頁需對帳" value={data.attention}/></div><p>建立範圍截至 {when(data.asOf)}；狀態讀取時間 {when(data.dataThrough)}。</p>{data.items.map(item=><section key={item.reference}><h3>資格 {item.evidence.qualificationNo??'待核對'} · {item.evidence.awardType}</h3><p>{item.evidence.historicalCompany?'獎金發生時屬 Company':'獎金發生時不屬 Company'}；來源金額 {item.evidence.sourceAmount}；規則 {item.evidence.ruleVersionCode}。</p><p>來源發生：{when(item.evidence.occurredAt)}；Reservoir B 去向：{item.evidence.destination?'已記錄':'尚未記錄'}。</p>{item.evidence.destination&&<dl><dt>原始權益</dt><dd>{item.evidence.originalEntitlement}</dd><dt>原始入帳／筆數</dt><dd>{item.evidence.originalCredit}／{item.evidence.originalEffectCount}</dd><dt>Replay 正負調整／筆數</dt><dd>{item.evidence.replayAdjustment}／{item.evidence.replayEffectCount}</dd><dt>此來源已記錄餘額</dt><dd>{item.evidence.recordedBalance}</dd><dt>權益來源期間</dt><dd>{when(item.evidence.periodStart)} → {when(item.evidence.periodEnd)}</dd></dl>}{!item.candidates.length&&<p>本次檢查未發現不一致。</p>}{item.candidates.map(candidate=><div key={candidate.code}><p>{labels[candidate.code]??candidate.code}</p><CandidateTaskForm candidate={{stream:item.scope,reference:item.reference,code:candidate.code,evidenceHash:candidate.evidenceHash,asOf:data.asOf}}/><details><summary>差異依據</summary><p>{candidate.evidenceHash}</p></details></div>)}<details><summary>商業參考碼</summary><p>{item.reference}</p><p>{item.evidence.destinationReference}</p></details></section>)}{data.nextCursor&&<button onClick={()=>{setCursor(data.nextCursor!);setAsOf(data.asOf);}}>Company 證據下一頁</button>}{cursor&&<button onClick={reset}>Company 證據第一頁</button>}</>}</Card>;
}
