import {useQuery} from '@tanstack/react-query';
import {useState} from 'react';
import {get,qs} from '../../lib/api';
import {Qualification} from '../../types/domain';
import {Badge,Card,ErrorBox,Field,Metric,PageHeader,JsonResult} from '../../components/ui';
import {SearchOption,SearchSelect} from '../../components/SearchSelect';
import {dateTime,money} from '../../lib/format';
import {DetailDrawer,StatusBadge} from '@ucell/design-system';

export function BonusesPage(){
  const [qualification,setQualification]=useState<SearchOption|null>(null);const [selectedAward,setSelectedAward]=useState<string|null>(null);const [settlementType,setSettlementType]=useState('');
  const summary=useQuery({queryKey:['comp-summary'],queryFn:()=>get<any>('/admin/observability/compensation/summary'),refetchInterval:30_000});
  const settlements=useQuery({queryKey:['settlements',settlementType],queryFn:()=>get<any>('/admin/observability/settlements'+qs({type:settlementType||undefined,take:100}))});
  const pools=useQuery({queryKey:['pools'],queryFn:()=>get<any>('/admin/observability/pools'+qs({take:24}))});
  const ops=useQuery({queryKey:['qualification-ops',qualification?.id],queryFn:()=>get<any>(`/admin/observability/qualifications/${qualification!.id}/operations`),enabled:!!qualification});
  const award=useQuery({queryKey:['award-detail',selectedAward],queryFn:()=>get<any>(`/admin/observability/awards/${selectedAward}`),enabled:!!selectedAward});
  async function qualSearch(q:string){const r:any=await get('/admin/qualifications'+qs({q,status:'EFFECTIVE',take:20}));return (r.data as Qualification[]).map(x=>({id:x.qualificationId,primary:`Q#${x.qualificationNo??'—'} · ${x.currentHolder?.legalName??'—'}`,secondary:`${x.planLevelCode} · ${x.qualificationId}`}))}
  const s=summary.data?.data;const rows=settlements.data?.data??[];const p=pools.data?.data;const o=ops.data?.data;
  return <><PageHeader title="獎金／結算營運" subtitle="Theory、K0/K1/K2、45D生命週期、Carry、Recovery與Pool均只讀Backend結果。"/>
  <Card title="Bonus Engine Pipeline"><ol className="uc-lifecycle" aria-label="結算流程">{['Data Frozen','Active Snapshot','K0','K1','K2','Global Pool','Welfare','45D','Payable'].map(stage=><li key={stage}>{stage} <StatusBadge status="UNAVAILABLE" label="執行狀態待提供"/></li>)}</ol><p className="muted">此圖為流程導覽，不代表本期已執行。各階段 snapshot／hash／exceptions／Executed At 需由正式 Read Model 提供。</p></Card>
  <ErrorBox error={summary.error}/><div className="metrics"><Metric label="PENDING_45D" value={s?.awards?.pending45d??'—'} helper="Awards"/><Metric label="EFFECTIVE" value={s?.awards?.effective??'—'} helper="Awards"/><Metric label="Open Recovery" value={s?.recoveries?.openCount??'—'} helper={s?money(s.recoveries.outstanding):'—'}/><Metric label="Rule" value="R1.0B" helper="FROZEN"/></div>
  <div className="grid two"><Card title="Settlement History"><Field label="Settlement Type"><select value={settlementType} onChange={e=>setSettlementType(e.target.value)}><option value="">全部</option><option>REFERRAL_K0</option><option>BINARY_K1</option><option>MATCHING_K2</option></select></Field><div className="table-wrap"><table><thead><tr><th>Type</th><th>Period End</th><th>Pool</th><th>Theory</th><th>K</th><th>Awards</th></tr></thead><tbody>{rows.map((x:any)=><tr key={x.settlementBatchId}><td>{x.settlementType}</td><td>{dateTime(x.periodEnd)}</td><td>{money(x.poolAvailable)}</td><td>{money(x.totalTheory)}</td><td>{Number(x.kFactor).toFixed(4)}</td><td>{x._count?.awards??0}</td></tr>)}</tbody></table></div></Card>
  <Card title="Global / Welfare Pool"><h3>Global 5%</h3><div className="table-wrap"><table><thead><tr><th>Period</th><th>Available</th><th>Distributed</th><th>Awards</th></tr></thead><tbody>{(p?.global??[]).map((x:any)=><tr key={x.globalPoolSettlementId}><td>{dateTime(x.periodEnd)}</td><td>{money(x.poolAvailable)}</td><td>{money(x.distributedAmount)}</td><td>{x._count?.awards??0}</td></tr>)}</tbody></table></div><h3>Welfare 2% Accrual</h3><div className="table-wrap"><table><thead><tr><th>Period</th><th>Accrued</th></tr></thead><tbody>{(p?.welfare??[]).map((x:any)=><tr key={x.welfarePoolAccrualId}><td>{dateTime(x.periodEnd)}</td><td>{money(x.accruedAmount)}</td></tr>)}</tbody></table></div></Card></div>
  <Card title="Qualification Compensation Drill-down"><SearchSelect label="Qualification" value={qualification} onChange={x=>{setQualification(x);setSelectedAward(null)}} search={qualSearch}/>{!o?<p className="muted">選擇Qualification查看Active、PV、Carry與Award。</p>:<>
    <div className="grid two"><div><h3>PV Balances</h3><div className="table-wrap"><table><thead><tr><th>Type</th><th>Balance</th></tr></thead><tbody>{(o.balances??[]).map((x:any)=><tr key={x.pvType}><td>{x.pvType}</td><td>{x._sum?.amount??0}</td></tr>)}</tbody></table></div><h3>Active Timeline</h3><div className="timeline-list">{(o.qualification?.activePeriods??[]).map((x:any)=><div className="timeline-item" key={x.activePeriodId}><strong>{dateTime(x.activeFrom)}</strong><span>→ {dateTime(x.activeTo)}</span><small>{x.sourceType}</small></div>)}</div></div>
    <div><h3>Binary Carry</h3><div className="table-wrap"><table><thead><tr><th>Period</th><th>L In</th><th>R In</th><th>Pair</th><th>L Out</th><th>R Out</th></tr></thead><tbody>{(o.carry??[]).map((x:any)=><tr key={x.binaryCarryId}><td>{dateTime(x.periodEnd)}</td><td>{x.leftCarryIn}</td><td>{x.rightCarryIn}</td><td>{x.pairedPv}</td><td>{x.leftCarryOut}</td><td>{x.rightCarryOut}</td></tr>)}</tbody></table></div></div></div>
    <h3>Awards</h3><div className="table-wrap"><table><thead><tr><th>Type</th><th>Occurred</th><th>Theory</th><th>K</th><th>Payable</th><th>Lifecycle</th></tr></thead><tbody>{(o.awards??[]).map((x:any)=><tr key={x.bonusAwardId} onClick={()=>setSelectedAward(x.bonusAwardId)} className="click-row"><td>{x.awardType}</td><td>{dateTime(x.occurredAt)}</td><td>{money(x.theoryAmount)}</td><td>{Number(x.kFactor).toFixed(4)}</td><td>{money(x.payableAmount)}</td><td>{x.lifecycleEvents?.map((e:any)=>e.status).join(' → ')}</td></tr>)}</tbody></table></div>
  </>}</Card>
  <DetailDrawer open={!!selectedAward} title="Award Drill-down" onClose={()=>setSelectedAward(null)}><ErrorBox error={award.error}/>{award.data?.data?<AwardDetail a={award.data.data}/>:<p role="status">讀取中…</p>}</DetailDrawer></>
}
function AwardDetail({a}:{a:any}){return <div className="grid two"><dl className="detail-grid"><dt>Award ID</dt><dd className="mono">{a.bonusAwardId}</dd><dt>Type</dt><dd>{a.awardType}</dd><dt>Recipient</dt><dd>{a.recipient?.currentHolder?.legalName}<br/><span className="mono">{a.recipientQualificationId}</span></dd><dt>Source</dt><dd>{a.sourceQualification?.currentHolder?.legalName??'—'}<br/><span className="mono">{a.sourceQualificationId??'—'}</span></dd><dt>Theory</dt><dd>{money(a.theoryAmount)}</dd><dt>K Factor</dt><dd>{a.kFactor}</dd><dt>Payable</dt><dd>{money(a.payableAmount)}</dd><dt>Active Snapshot</dt><dd>{String(a.activeSnapshot)}</dd><dt>Plan Snapshot</dt><dd>{a.planLevelSnapshot??'—'}</dd><dt>Pending Until</dt><dd>{dateTime(a.pendingUntil)}</dd></dl><div><h3>Calculation Detail</h3><JsonResult value={a.calculationDetail}/><h3>Lifecycle</h3>{(a.lifecycleEvents??[]).map((e:any)=><p key={e.bonusAwardLifecycleEventId}><Badge tone={e.status==='EFFECTIVE'?'ok':'neutral'}>{e.status}</Badge> {dateTime(e.occurredAt)} · {e.reasonCode}</p>)}<h3>Recovery</h3>{(a.recoveryEvents??[]).length===0?<p className="muted">無Recovery</p>:(a.recoveryEvents??[]).map((r:any)=><p key={r.bonusRecoveryEventId}>{r.status} · outstanding {money(r.outstandingAmount)}</p>)}</div></div>}
