import {useState,type ReactNode} from 'react';
import {UCellButton,EmptyState,FilterBar} from '@ucell/design-system';
export type GridColumn<T>={key:string;label:string;value:(row:T)=>string;render?:(row:T)=>ReactNode};
/** Client view of an explicitly bounded API result; never claims server-wide pagination. */
export function AdminDataGrid<T>({rows,columns,rowId,label,toolbar,searchable=false,rowProps}:{rows:T[];columns:GridColumn<T>[];rowId:(row:T)=>string;label:string;toolbar?:ReactNode;searchable?:boolean;rowProps?:(row:T)=>{onClick?:()=>void;className?:string}}){
 const [search,setSearch]=useState(''); const [sort,setSort]=useState<{key:string;descending:boolean}|null>(null);const [page,setPage]=useState(0);const [hidden,setHidden]=useState<string[]>([]);const size=20;
 const filtered=search?rows.filter(r=>columns.some(c=>c.value(r).toLocaleLowerCase().includes(search.toLocaleLowerCase()))):rows;const ordered=[...filtered];const column=columns.find(c=>c.key===sort?.key);if(column)ordered.sort((a,b)=>column.value(a).localeCompare(column.value(b),'zh-TW',{numeric:true})*(sort?.descending?-1:1));const visible=columns.filter(c=>!hidden.includes(c.key));const last=Math.max(0,Math.ceil(filtered.length/size)-1);const current=Math.min(page,last);
 return <section aria-label={label}>{searchable&&<FilterBar><label>搜尋已載入資料<input value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}}/></label></FilterBar>}{toolbar&&<FilterBar>{toolbar}</FilterBar>}<details><summary>顯示欄位</summary>{columns.map(c=><label key={c.key} className="checkbox"><input type="checkbox" checked={!hidden.includes(c.key)} onChange={()=>setHidden(h=>h.includes(c.key)?h.filter(k=>k!==c.key):h.length<columns.length-1?[...h,c.key]:h)}/>{c.label}</label>)}</details>{!filtered.length?<EmptyState title="目前沒有資料"/>:<div className="table-wrap"><table><caption className="uc-sr-only">{label}；僅對本次 API 回傳資料排序與分頁</caption><thead><tr>{visible.map(c=><th key={c.key} aria-sort={sort?.key===c.key?(sort.descending?'descending':'ascending'):'none'}><UCellButton onClick={()=>{setSort({key:c.key,descending:sort?.key===c.key?!sort.descending:false});setPage(0)}}>{c.label}</UCellButton></th>)}</tr></thead><tbody>{ordered.slice(current*size,(current+1)*size).map(row=><tr key={rowId(row)} {...rowProps?.(row)}>{visible.map(c=><td key={c.key}>{c.render?c.render(row):c.value(row)}</td>)}</tr>)}</tbody></table></div>}<div className="button-row"><UCellButton disabled={current===0} onClick={()=>setPage(current-1)}>上一頁</UCellButton><span aria-live="polite">第 {current+1}／{last+1} 頁 · 本次載入 {rows.length} 筆</span><UCellButton disabled={current===last} onClick={()=>setPage(current+1)}>下一頁</UCellButton></div><small className="muted">搜尋條件由頁面送至 Backend；不將已載入資料視為完整名冊。Export／Saved View／Bulk Action 尚未啟用。</small></section>
}
