import {ConflictException,Injectable,NotFoundException,UnprocessableEntityException} from '@nestjs/common';
import {Prisma,PrismaService} from '@ucell/database';
import {createHash,randomBytes,randomUUID} from 'node:crypto';
import {AuditService} from '../../common/audit/audit.service';
import {IdempotencyService} from '../../common/idempotency/idempotency.service';
type EventInput={eventCode:string;title:string;description?:string;eventType:'ONLINE'|'OFFLINE'|'HYBRID';startsAt:string;endsAt:string;locationReference?:string;onlineJoinReference?:string;capacity?:number};
const code=/^[A-Z][A-Z0-9_-]{2,39}$/;
const active=['REGISTERED','CHECKED_IN','ATTENDED'] as const;
@Injectable() export class MemberEventsService{constructor(private db:PrismaService,private idempotency:IdempotencyService,private audit:AuditService){}
 private input(input:EventInput){if(!code.test(input?.eventCode??'')||typeof input.title!=='string'||!input.title.trim()||!['ONLINE','OFFLINE','HYBRID'].includes(input.eventType))throw new UnprocessableEntityException('EVENT_INVALID');const startsAt=new Date(input.startsAt),endsAt=new Date(input.endsAt);if(!Number.isFinite(startsAt.getTime())||!Number.isFinite(endsAt.getTime())||endsAt<=startsAt||!Number.isInteger(input.capacity??0)||(input.capacity??0)<0)throw new UnprocessableEntityException('EVENT_WINDOW_OR_CAPACITY_INVALID');const locationReference=input.locationReference?.trim()||null,onlineJoinReference=input.onlineJoinReference?.trim()||null;if((input.eventType==='OFFLINE'&&!locationReference)||(input.eventType==='ONLINE'&&!onlineJoinReference)||(input.eventType==='HYBRID'&&(!locationReference||!onlineJoinReference)))throw new UnprocessableEntityException('EVENT_LOCATION_INVALID');if(onlineJoinReference){try{if(new URL(onlineJoinReference).protocol!=='https:')throw 0;}catch{throw new UnprocessableEntityException('EVENT_ONLINE_REFERENCE_INVALID');}}return {eventCode:input.eventCode,title:input.title.trim(),description:input.description?.trim()||null,eventType:input.eventType,startsAt,endsAt,locationReference,onlineJoinReference,capacity:input.capacity??null};}
 async create(input:EventInput,actor:string,key:string,requestId:string){const value=this.input(input);return (await this.idempotency.execute(`admin:event:create:${actor}`,key,input,async tx=>{const {eventCode,...versionData}=value;const event=await tx.memberEvent.create({data:{eventCode,createdByActor:actor}});const hash=createHash('sha256').update(JSON.stringify(value)).digest('hex');await tx.memberEventVersion.create({data:{memberEventId:event.memberEventId,version:1,...versionData,contentHash:hash}});await this.audit.write(tx,{actorType:'USER',actorId:actor,action:'MEMBER_EVENT_CREATED',entityType:'MemberEvent',entityId:event.memberEventId,afterData:{eventCode,version:1,contentHash:hash},requestId,correlationId:randomUUID()});return {eventCode,version:1,status:'DRAFT'};})).value;}
 async publish(eventCode:string,approvalReference:string,actor:string,key:string,requestId:string){if(!code.test(eventCode)||!approvalReference?.trim())throw new UnprocessableEntityException('EVENT_PUBLISH_INVALID');return (await this.idempotency.execute(`admin:event:publish:${eventCode}:${actor}`,key,{approvalReference},async tx=>{const event=await tx.memberEvent.findUnique({where:{eventCode},include:{versions:{where:{status:'DRAFT'},orderBy:{version:'desc'},take:1}}});const version=event?.versions[0];if(!event||!version)throw new ConflictException('EVENT_NOT_PUBLISHABLE');const now=new Date();await tx.memberEventVersion.update({where:{memberEventVersionId:version.memberEventVersionId},data:{status:'PUBLISHED',approvalReference:approvalReference.trim(),approvedByActor:actor,approvedAt:now}});await tx.memberEvent.update({where:{memberEventId:event.memberEventId},data:{status:'PUBLISHED'}});await this.audit.write(tx,{actorType:'USER',actorId:actor,action:'MEMBER_EVENT_PUBLISHED',entityType:'MemberEventVersion',entityId:version.memberEventVersionId,afterData:{eventCode,version:version.version,contentHash:version.contentHash},requestId,correlationId:randomUUID()});return {eventCode,version:version.version,status:'PUBLISHED'};})).value;}
 async adminList(){return this.db.memberEvent.findMany({include:{versions:{orderBy:{version:'desc'}}},orderBy:{createdAt:'desc'},take:100});}
 async adminRegistrations(eventCode:string){if(!code.test(eventCode))throw new NotFoundException('EVENT_NOT_FOUND');const event=await this.db.memberEvent.findUnique({where:{eventCode},select:{memberEventId:true,eventCode:true}});if(!event)throw new NotFoundException('EVENT_NOT_FOUND');const rows=await this.db.memberEventRegistration.findMany({where:{memberEventId:event.memberEventId},include:{person:{select:{memberNo:true}},eventVersion:{select:{title:true}}},orderBy:{registeredAt:'asc'},take:500});return {eventCode:event.eventCode,registrations:rows.map(row=>({memberNo:row.person.memberNo,status:row.status,registeredAt:row.registeredAt.toISOString(),cancelledAt:row.cancelledAt?.toISOString()??null,checkedInAt:row.checkedInAt?.toISOString()??null,attendedAt:row.attendedAt?.toISOString()??null,eventTitle:row.eventVersion.title}))};}
 private async allowed(personId:string){const p=await this.db.person.findUnique({where:{personId},select:{membershipState:true}});return !!p&&['NETWORK_MEMBER','FORMAL_PENDING','FORMAL_MEMBER'].includes(p.membershipState??'');}
 private async visible(eventCode:string,now=new Date()){const version=await this.db.memberEventVersion.findFirst({where:{event:{eventCode,status:'PUBLISHED'},status:'PUBLISHED',audiencePolicy:'NETWORK_MEMBER',startsAt:{gt:now}},include:{event:true},orderBy:{version:'desc'}});if(!version)throw new NotFoundException('EVENT_NOT_FOUND');return version;}
 async memberList(personId:string){if(!await this.allowed(personId))return [];const now=new Date(),rows=await this.db.memberEventVersion.findMany({where:{status:'PUBLISHED',audiencePolicy:'NETWORK_MEMBER',startsAt:{gt:now},event:{status:'PUBLISHED'}},include:{event:true,registrationEvidence:{where:{personId},take:1}},orderBy:{startsAt:'asc'},take:100});const seen=new Set<string>();return rows.filter(x=>!seen.has(x.memberEventId)&&!!seen.add(x.memberEventId)).map(x=>({eventCode:x.event.eventCode,title:x.title,description:x.description,eventType:x.eventType,startsAt:x.startsAt.toISOString(),endsAt:x.endsAt.toISOString(),capacity:x.capacity,status:x.registrationEvidence[0]?.status??'AVAILABLE'}));}
 async memberDetail(personId:string,eventCode:string){if(!await this.allowed(personId))throw new NotFoundException('EVENT_NOT_FOUND');const v=await this.visible(eventCode);const registration=await this.db.memberEventRegistration.findUnique({where:{memberEventId_personId:{memberEventId:v.memberEventId,personId}}});return {eventCode,title:v.title,description:v.description,eventType:v.eventType,startsAt:v.startsAt.toISOString(),endsAt:v.endsAt.toISOString(),locationReference:v.locationReference,onlineJoinReference:v.onlineJoinReference,capacity:v.capacity,status:registration?.status??'AVAILABLE'};}
 async register(personId:string,eventCode:string,key:string,requestId:string){if(!await this.allowed(personId))throw new NotFoundException('EVENT_NOT_FOUND');const visible=await this.visible(eventCode);return (await this.idempotency.execute(`member:event:register:${personId}`,key,{eventCode},async tx=>{await tx.$executeRaw(Prisma.sql`SELECT member_event_id FROM learning.member_event WHERE member_event_id=${visible.memberEventId}::uuid FOR UPDATE`);const v=await tx.memberEventVersion.findUniqueOrThrow({where:{memberEventVersionId:visible.memberEventVersionId},include:{event:true}});const now=new Date();if(v.status!=='PUBLISHED'||v.event.status!=='PUBLISHED'||v.startsAt<=now)throw new NotFoundException('EVENT_NOT_FOUND');const existing=await tx.memberEventRegistration.findUnique({where:{memberEventId_personId:{memberEventId:v.memberEventId,personId}}});if(existing&&existing.status!=='CANCELLED')return {eventCode,status:existing.status,replayed:true};const count=await tx.memberEventRegistration.count({where:{memberEventId:v.memberEventId,status:{in:[...active]}}});if(v.capacity!==null&&count>=v.capacity)throw new ConflictException('EVENT_CAPACITY_FULL');const token=randomBytes(32).toString('base64url'),hash=createHash('sha256').update(token).digest('hex');if(existing)await tx.memberEventRegistration.update({where:{memberEventRegistrationId:existing.memberEventRegistrationId},data:{memberEventVersionId:v.memberEventVersionId,status:'REGISTERED',checkInTokenHash:hash,registeredAt:now,cancelledAt:null,checkedInAt:null,attendedAt:null}});else await tx.memberEventRegistration.create({data:{memberEventId:v.memberEventId,memberEventVersionId:v.memberEventVersionId,personId,checkInTokenHash:hash}});await this.audit.write(tx,{actorType:'MEMBER',actorId:personId,action:'MEMBER_EVENT_REGISTERED',entityType:'MemberEventRegistration',afterData:{eventCode,status:'REGISTERED'},requestId,correlationId:randomUUID()});return {eventCode,status:'REGISTERED',checkInToken:token,replayed:false};})).value;}
 async cancel(personId:string,eventCode:string,key:string,requestId:string){if(!await this.allowed(personId))throw new NotFoundException('EVENT_NOT_FOUND');const v=await this.visible(eventCode);return (await this.idempotency.execute(`member:event:cancel:${personId}`,key,{eventCode},async tx=>{const r=await tx.memberEventRegistration.findUnique({where:{memberEventId_personId:{memberEventId:v.memberEventId,personId}}});if(!r)throw new ConflictException('EVENT_REGISTRATION_REQUIRED');if(r.status==='CANCELLED')return {eventCode,status:'CANCELLED',replayed:true};if(r.status!=='REGISTERED')throw new ConflictException('EVENT_REGISTRATION_NOT_CANCELLABLE');await tx.memberEventRegistration.update({where:{memberEventRegistrationId:r.memberEventRegistrationId},data:{status:'CANCELLED',cancelledAt:new Date()}});await this.audit.write(tx,{actorType:'MEMBER',actorId:personId,action:'MEMBER_EVENT_CANCELLED',entityType:'MemberEventRegistration',afterData:{eventCode,status:'CANCELLED'},requestId,correlationId:randomUUID()});return {eventCode,status:'CANCELLED',replayed:false};})).value;}
 async checkIn(token:string,actor:string,key:string,requestId:string){if(typeof token!=='string'||token.length<32)throw new NotFoundException('EVENT_CHECKIN_NOT_FOUND');const hash=createHash('sha256').update(token).digest('hex');return (await this.idempotency.execute(`admin:event:checkin:${actor}`,key,{tokenHash:hash},async tx=>{const r=await tx.memberEventRegistration.findUnique({where:{checkInTokenHash:hash},include:{event:true,eventVersion:true}});if(!r)throw new NotFoundException('EVENT_CHECKIN_NOT_FOUND');const now=new Date();if(r.eventVersion.startsAt>now||r.eventVersion.endsAt<now)throw new ConflictException('EVENT_CHECKIN_OUTSIDE_WINDOW');if(['CHECKED_IN','ATTENDED'].includes(r.status))return {eventCode:r.event.eventCode,status:r.status,replayed:true};if(r.status!=='REGISTERED')throw new ConflictException('EVENT_REGISTRATION_NOT_CHECKINABLE');await tx.memberEventRegistration.update({where:{memberEventRegistrationId:r.memberEventRegistrationId},data:{status:'CHECKED_IN',checkedInAt:now}});await this.audit.write(tx,{actorType:'USER',actorId:actor,action:'MEMBER_EVENT_CHECKED_IN',entityType:'MemberEventRegistration',afterData:{eventCode:r.event.eventCode,status:'CHECKED_IN'},requestId,correlationId:randomUUID()});return {eventCode:r.event.eventCode,status:'CHECKED_IN',replayed:false};})).value;}
}
