import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {useState} from 'react';
import {AdminTable} from '../../components/AdminTable';
import {Badge,Card,ErrorBox,Field,PageHeader} from '../../components/ui';
import {QueryFeedback} from '../../components/QueryFeedback';
import {command,get,putCommand} from '../../lib/api';
import {useAuth} from '../auth/auth';
import type {ProductReference} from '../../types/domain';

type ProductRule={productRuleProfileId:string;minQty:number|null;maxQty:number|null;selectionIncrement:number;sortOrder:number;status:string};
type PackageVersion={packageProfileVersionId:string;version:number;displayName:string;currency:string;priceAmount:string;selectableProductQuantity:number;selectionMode:string;membershipEffect:string;qualificationEffect:string;targetQualificationRequired:boolean;status:'DRAFT'|'APPROVED'|'SCHEDULED'|'ACTIVE'|'RETIRED';effectiveFrom:string|null;effectiveTo:string|null;salesFrom:string|null;salesTo:string|null;approvalReference:string|null;configHash:string;selectableProducts:ProductRule[]};
type PackageProfile={packageProfileId:string;stableCode:string;packageClass:'QUALIFICATION'|'ACTIVE_DURATION'|'FUTURE';status:string;versions:PackageVersion[]};
const tone=(status:PackageVersion['status'])=>status==='ACTIVE'?'ok':status==='DRAFT'?'warn':'neutral';

export function PackagesPage(){
 const {user}=useAuth(),qc=useQueryClient(),canManage=user?.role==='SUPER_ADMIN'||user?.role==='PACKAGE_CONFIG_MANAGE';
 const query=useQuery({queryKey:['packages'],queryFn:()=>get<{data:PackageProfile[]}>('/admin/packages')});
 const products=useQuery({queryKey:['products'],queryFn:()=>get<{data:ProductReference[]}>('/admin/products'),enabled:canManage});
 const rows=query.error?[]:query.data?.data??[];
 const [profile,setProfile]=useState({stableCode:'',packageClass:'QUALIFICATION' as PackageProfile['packageClass']}),[target,setTarget]=useState(''),[poolTarget,setPoolTarget]=useState(''),[pool,setPool]=useState<Array<{productRuleProfileId:string;minQty:number;maxQty:number;selectionIncrement:number}>>([]),[version,setVersion]=useState({displayName:'',currency:'TWD',priceAmount:'',selectableProductQuantity:1,membershipEffect:'',qualificationEffect:'',activeDurationUnit:'',activeDurationValue:'',memberEligibilityPolicyRef:'',recognitionConfigRef:'',targetQualificationRequired:false}),[error,setError]=useState<unknown>(null);
 const refresh=()=>qc.invalidateQueries({queryKey:['packages']});
 const createProfile=useMutation({mutationFn:()=>command('/admin/packages',{stableCode:profile.stableCode.trim().toUpperCase(),packageClass:profile.packageClass}),onSuccess:()=>{setProfile({...profile,stableCode:''});setError(null);refresh()},onError:setError});
 const createVersion=useMutation({mutationFn:()=>command(`/admin/packages/${encodeURIComponent(target)}/versions`,{displayName:version.displayName.trim(),currency:version.currency.trim().toUpperCase(),priceAmount:version.priceAmount,selectableProductQuantity:version.selectableProductQuantity,membershipEffect:version.membershipEffect.trim(),qualificationEffect:version.qualificationEffect.trim(),targetQualificationRequired:version.targetQualificationRequired,...(version.activeDurationUnit.trim()?{activeDurationUnit:version.activeDurationUnit.trim(),activeDurationValue:Number(version.activeDurationValue)}:{}),...(version.memberEligibilityPolicyRef.trim()?{memberEligibilityPolicyRef:version.memberEligibilityPolicyRef.trim()}:{}),recognitionConfigRef:version.recognitionConfigRef.trim()}),onSuccess:()=>{setVersion({...version,displayName:'',priceAmount:'',membershipEffect:'',qualificationEffect:'',activeDurationUnit:'',activeDurationValue:'',memberEligibilityPolicyRef:'',recognitionConfigRef:''});setError(null);refresh()},onError:setError});
 const savePool=useMutation({mutationFn:()=>putCommand(`/admin/packages/versions/${encodeURIComponent(poolTarget)}/selectable-products`,{products:pool.map((item,sortOrder)=>({...item,sortOrder}))}),onSuccess:()=>{setPool([]);setError(null);refresh()},onError:setError});
 const available=(products.data?.data??[]).flatMap(product=>(product.ruleProfiles??[]).map(rule=>({id:rule.productRuleProfileId,label:`${product.sku} · ${product.displayName} · ${rule.ruleVersionCode}`})));
 function addRule(id:string){if(!id||pool.some(item=>item.productRuleProfileId===id))return;setPool(items=>[...items,{productRuleProfileId:id,minQty:0,maxQty:1,selectionIncrement:1}]);}
 return <><PageHeader title="套組與資格商品" subtitle="Core 套組版本、正式價格與可選商品池的版本化營運管理。"/>
  <div className="callout info"><strong>Core authoritative：</strong>前台只提交套組版本及商品數量。價格、資格效果、認列與訂單金額均由 Backend 依已核准版本處理。</div>
  <ErrorBox error={error}/>
  {canManage&&<div className="grid two"><Card title="建立套組主檔"><div className="form"><Field label="穩定代碼"><input value={profile.stableCode} maxLength={80} onChange={event=>setProfile(value=>({...value,stableCode:event.target.value}))}/></Field><Field label="套組類別"><select value={profile.packageClass} onChange={event=>setProfile(value=>({...value,packageClass:event.target.value as PackageProfile['packageClass']}))}><option value="QUALIFICATION">取得資格</option><option value="ACTIVE_DURATION">資格有效期</option><option value="FUTURE">未來保留</option></select></Field><button className="primary" disabled={!/^[A-Z0-9_]{2,80}$/.test(profile.stableCode.trim().toUpperCase())||createProfile.isPending} onClick={()=>createProfile.mutate()}>{createProfile.isPending?'建立中…':'建立套組主檔'}</button></div></Card>
  <Card title="新增不可變版本"><div className="form"><Field label="套組主檔"><select value={target} onChange={event=>setTarget(event.target.value)}><option value="">請選擇</option>{rows.map(row=><option value={row.packageProfileId} key={row.packageProfileId}>{row.stableCode} · {row.packageClass}</option>)}</select></Field><Field label="顯示名稱"><input value={version.displayName} maxLength={120} onChange={event=>setVersion(value=>({...value,displayName:event.target.value}))}/></Field><Field label="幣別"><input value={version.currency} maxLength={3} onChange={event=>setVersion(value=>({...value,currency:event.target.value}))}/></Field><Field label="正式價格"><input inputMode="decimal" value={version.priceAmount} onChange={event=>setVersion(value=>({...value,priceAmount:event.target.value}))}/></Field><Field label="精確選品件數"><input type="number" min={1} max={10000} value={version.selectableProductQuantity} onChange={event=>setVersion(value=>({...value,selectableProductQuantity:Number(event.target.value)}))}/></Field><Field label="Membership Effect"><input value={version.membershipEffect} onChange={event=>setVersion(value=>({...value,membershipEffect:event.target.value}))}/></Field><Field label="Qualification Effect"><input value={version.qualificationEffect} onChange={event=>setVersion(value=>({...value,qualificationEffect:event.target.value}))}/></Field><Field label="Recognition Config Reference"><input value={version.recognitionConfigRef} onChange={event=>setVersion(value=>({...value,recognitionConfigRef:event.target.value}))}/></Field><Field label="Member Eligibility Policy（選填）"><input value={version.memberEligibilityPolicyRef} onChange={event=>setVersion(value=>({...value,memberEligibilityPolicyRef:event.target.value}))}/></Field><Field label="有效期單位（選填，須與數值同時提供）"><input value={version.activeDurationUnit} onChange={event=>setVersion(value=>({...value,activeDurationUnit:event.target.value}))}/></Field><Field label="有效期數值"><input type="number" min={1} max={1200} value={version.activeDurationValue} onChange={event=>setVersion(value=>({...value,activeDurationValue:event.target.value}))}/></Field><label><input type="checkbox" checked={version.targetQualificationRequired} onChange={event=>setVersion(value=>({...value,targetQualificationRequired:event.target.checked}))}/> 需要指定既有資格</label><button className="primary" disabled={!target||!version.displayName.trim()||!/^[A-Z]{3}$/.test(version.currency.trim().toUpperCase())||!/^\d{1,16}(\.\d{1,2})?$/.test(version.priceAmount)||version.selectableProductQuantity<1||!version.membershipEffect.trim()||!version.qualificationEffect.trim()||!version.recognitionConfigRef.trim()||Boolean(version.activeDurationUnit.trim())!==Boolean(version.activeDurationValue)||createVersion.isPending} onClick={()=>createVersion.mutate()}>{createVersion.isPending?'建立中…':'新增版本草稿'}</button></div></Card></div>}
  {canManage&&<Card title="設定版本可選商品池"><div className="form"><Field label="DRAFT 套組版本"><select value={poolTarget} onChange={event=>{setPoolTarget(event.target.value);setPool([])}}><option value="">請選擇</option>{rows.flatMap(profile=>profile.versions.filter(item=>item.status==='DRAFT').map(item=><option key={item.packageProfileVersionId} value={item.packageProfileVersionId}>{profile.stableCode} · v{item.version} · {item.displayName}</option>))}</select></Field><Field label="加入 Product Rule Profile"><select value="" disabled={!poolTarget||products.isLoading} onChange={event=>addRule(event.target.value)}><option value="">請選擇商品規則</option>{available.filter(item=>!pool.some(row=>row.productRuleProfileId===item.id)).map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></Field>{pool.map((item,index)=><div className="card" key={item.productRuleProfileId}><strong>{available.find(rule=>rule.id===item.productRuleProfileId)?.label??item.productRuleProfileId}</strong><div className="grid two"><Field label="最少數量"><input type="number" min={0} value={item.minQty} onChange={event=>setPool(rows=>rows.map((row,i)=>i===index?{...row,minQty:Number(event.target.value)}:row))}/></Field><Field label="最多數量"><input type="number" min={1} value={item.maxQty} onChange={event=>setPool(rows=>rows.map((row,i)=>i===index?{...row,maxQty:Number(event.target.value)}:row))}/></Field><Field label="選擇增量"><input type="number" min={1} value={item.selectionIncrement} onChange={event=>setPool(rows=>rows.map((row,i)=>i===index?{...row,selectionIncrement:Number(event.target.value)}:row))}/></Field></div><button onClick={()=>setPool(rows=>rows.filter((_,i)=>i!==index))}>移除商品規則</button></div>)}<p>儲存會以目前清單完整取代此 DRAFT 版本的商品池；既有已核准版本不可修改。</p><button className="primary" disabled={!poolTarget||!pool.length||pool.some(item=>item.minQty<0||item.maxQty<1||item.minQty>item.maxQty||item.selectionIncrement<1)||savePool.isPending} onClick={()=>savePool.mutate()}>{savePool.isPending?'儲存中…':'儲存完整商品池'}</button></div></Card>}
  <QueryFeedback query={query} empty={!rows.length}/>
  <Card title="套組版本清單"><div className="table-wrap"><AdminTable><thead><tr><th>套組</th><th>版本／狀態</th><th>正式價格</th><th>選品規則</th><th>期間</th><th>核准與雜湊</th></tr></thead><tbody>{rows.flatMap(profile=>profile.versions.map(version=><tr key={version.packageProfileVersionId}><td><strong>{version.displayName}</strong><br/><small>{profile.stableCode} · {profile.packageClass}</small></td><td>v{version.version}<br/><Badge tone={tone(version.status)}>{version.status}</Badge></td><td>{version.currency} {version.priceAmount}</td><td>{version.selectionMode} · {version.selectableProductQuantity} 件<br/><small>{version.selectableProducts.length} 個可選 Product Rule Profile</small></td><td>{version.salesFrom??version.effectiveFrom??'尚未排程'}<br/>{version.salesTo??version.effectiveTo?`至 ${version.salesTo??version.effectiveTo}`:'無截止'}</td><td>{version.approvalReference??'尚未核准'}<br/><small className="mono" title={version.configHash}>{version.configHash.slice(0,12)}…</small></td></tr>))}</tbody></AdminTable></div>{!rows.length&&!query.isLoading&&<p>尚無套組設定。</p>}</Card>
  <Card title="治理界線"><p>此頁不在瀏覽器計算 PV、BV、資格效果或應付金額。DRAFT、APPROVED、SCHEDULED、ACTIVE、RETIRED 狀態均直接讀取 Core；Production 排程值仍須正式核准。</p></Card></>;
}
