import {it,expect,vi,beforeEach} from 'vitest';
import {create,act} from 'react-test-renderer';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {QualificationDetail} from './QualificationDetail';
import {get} from '../../lib/api';
vi.mock('../../lib/api',()=>({get:vi.fn(),qs:()=>'?entityType=QUALIFICATION&entityId=ball-a&take=50'}));
vi.mock('../auth/auth',()=>({useAuth:()=>({user:{role:'MEMBERSHIP_OPS'}})}));
beforeEach(()=>{vi.mocked(get).mockReset();vi.mocked(get).mockImplementation(async(path:string)=>({data:path.includes('/operations')?{qualification:{qualificationId:'ball-a'},pv:[],balances:[],awards:[]}: {qualificationId:'ball-a',ballNo:'A000001',kind:'MEMBER_ORIGIN',currentHolder:{memberNo:'2609000001'},currentHolderPersonId:'person-a',planLevelCode:'STALE_PLAN_SHOULD_NOT_RENDER',status:'EFFECTIVE',activeFlag:true,activePeriods:[],orders:[],admin360:{organization:{status:'AVAILABLE',treeCode:'TREE-A',binaryPositionNo:'4',binaryPath:'RLL',canonicalSide:'LEFT'},owner:{status:'AVAILABLE',ownerType:'MEMBER',memberNo:'2609000001'},plan:{status:'AVAILABLE',planCode:'STARTER',source:'QUALIFICATION_PLAN_HISTORY'},globalRank:{status:'AVAILABLE',scope:'GLOBAL_CUMULATIVE',highestRank:'DIAMOND'}}}}) as any)});
async function waitForText(tree:ReturnType<typeof create>,text:string){await vi.waitFor(()=>expect(JSON.stringify(tree.toJSON())).toContain(text))}
async function render(){let tree:ReturnType<typeof create>;await act(async()=>{tree=create(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><QualificationDetail id="ball-a"/></QueryClientProvider>)});await waitForText(tree!,'Ball Number');return tree!}
it('shows public Ball and Member identifiers instead of the technical qualification key',async()=>{const tree=await render(),output=JSON.stringify(tree.toJSON());expect(output).toContain('A000001');expect(output).toContain('2609000001');expect(output).toContain('TREE-A');expect(output).toContain('RLL');expect(output).toContain('DIAMOND');expect(output).toContain('STARTER');expect(output).not.toContain('STALE_PLAN_SHOULD_NOT_RENDER');expect(output).not.toContain('Qualification ID');act(()=>tree.unmount())});
it('never calls Audit for a Membership Ops user and retains all ten tabs',async()=>{const tree=await render();expect(tree.root.findAllByProps({role:'tab'})).toHaveLength(10);await act(async()=>{tree.root.findAllByProps({role:'tab'}).find(t=>t.children.join('')==='Audit')!.props.onClick()});await waitForText(tree,'此角色無 Audit 讀取權限');expect(vi.mocked(get).mock.calls.every(([p])=>!String(p).includes('audit-events'))).toBe(true);act(()=>tree.unmount())});
it('fails closed for operations belonging to another Qualification',async()=>{vi.mocked(get).mockImplementation(async(path:string)=>({data:path.includes('/operations')?{qualification:{qualificationId:'outsider'},balances:[{pvType:'PV',_sum:{amount:'999999'}}]}:{qualificationId:'ball-a',planLevelCode:'LEADER'}}) as any);const tree=await render();await act(async()=>{tree.root.findAllByProps({role:'tab'}).find(t=>t.children.join('')==='PV/RPV/EPV')!.props.onClick()});await waitForText(tree,'evidence 不一致');expect(JSON.stringify(tree.toJSON())).not.toContain('999999');act(()=>tree.unmount())});
it('shows Company LEADER and Always Active only from complete bootstrap and owner evidence',async()=>{
 vi.mocked(get).mockResolvedValue({data:{qualificationId:'ball-a',kind:'COMPANY_BOOTSTRAP',currentHolderPersonId:null,currentCompanyPrincipalId:'company-principal',planLevelCode:null,status:'EFFECTIVE',activeFlag:false,activePeriods:[],orders:[],admin360:{organization:{status:'AVAILABLE'},owner:{status:'AVAILABLE',ownerType:'COMPANY',companyCode:'UCELL_COMPANY'},plan:{status:'AVAILABLE',planCode:'LEADER',source:'COMPANY_BOOTSTRAP_PROFILE_BINDING',profileVersion:'COMPANY_BOOTSTRAP_PROFILE_V1',effectiveFrom:'2026-09-01T00:00:00.000Z',effectiveTo:null},globalRank:{status:'AVAILABLE',highestRank:null}}}});
 const tree=await render();let output=JSON.stringify(tree.toJSON());expect(output).toContain('方案 LEADER');expect(output).toContain('Always Active (Company Rule)');expect(output).toContain('已核准 Company Bootstrap LEADER Binding');
 await act(async()=>{tree.root.findAllByProps({role:'tab'}).find(t=>t.children.join('')==='Active')!.props.onClick()});
 output=JSON.stringify(tree.toJSON());expect(output).toContain('公司持有期間適用');expect(output).not.toContain('2,000');expect(output).not.toContain('尚無 Active history');act(()=>tree.unmount());
});
it('retains the Member-origin plan when authoritative owner evidence says Company',async()=>{
 vi.mocked(get).mockResolvedValue({data:{qualificationId:'ball-a',ballNo:'AX000001',kind:'MEMBER_ORIGIN',currentCompanyPrincipalId:'company-principal',planLevelCode:'LEADER',status:'EFFECTIVE',activeFlag:false,activePeriods:[],orders:[],admin360:{organization:{status:'AVAILABLE'},owner:{status:'AVAILABLE',ownerType:'COMPANY',companyCode:'UCELL_COMPANY'},plan:{status:'AVAILABLE',planCode:'STARTER',source:'QUALIFICATION_PLAN_HISTORY',profileVersion:null,effectiveFrom:'2026-09-01T00:00:00.000Z',effectiveTo:null},globalRank:{status:'AVAILABLE',highestRank:null}}}});
 const tree=await render();const output=JSON.stringify(tree.toJSON());expect(output).toContain('方案 STARTER');expect(output).toContain('Always Active (Company Rule)');expect(output).not.toContain('方案 LEADER');expect(output).not.toContain('已核准 Company Bootstrap LEADER Binding');act(()=>tree.unmount());
});
it('fails closed when the authoritative 360 plan or owner evidence is unavailable',async()=>{
 vi.mocked(get).mockResolvedValue({data:{qualificationId:'ball-a',ballNo:'AX000001',kind:'COMPANY_BOOTSTRAP',currentCompanyPrincipalId:'company-principal',planLevelCode:'LEADER',status:'EFFECTIVE',activeFlag:false,activePeriods:[],orders:[],admin360:{organization:{status:'UNAVAILABLE'},owner:{status:'UNAVAILABLE',ownerType:null},plan:{status:'UNAVAILABLE',planCode:null,source:null},globalRank:{status:'UNAVAILABLE',highestRank:null}}}});
 const tree=await render();let output=JSON.stringify(tree.toJSON());expect(output).toContain('方案資料未提供');expect(output).toContain('持有證據未提供');expect(output).not.toContain('方案 LEADER');
 await act(async()=>{tree.root.findAllByProps({role:'tab'}).find(t=>t.children.join('')==='Active')!.props.onClick()});
 output=JSON.stringify(tree.toJSON());expect(output).not.toContain('Always Active (Company Rule)');act(()=>tree.unmount());
});
it('does not promote an incomplete Company profile into LEADER while preserving verified Company Active status',async()=>{
 vi.mocked(get).mockResolvedValue({data:{qualificationId:'ball-a',ballNo:'AX000001',kind:'COMPANY_BOOTSTRAP',currentCompanyPrincipalId:'company-principal',planLevelCode:'LEADER',status:'EFFECTIVE',activeFlag:false,activePeriods:[],orders:[],admin360:{organization:{status:'AVAILABLE'},owner:{status:'AVAILABLE',ownerType:'COMPANY',companyCode:'UCELL_COMPANY'},plan:{status:'AVAILABLE',planCode:'LEADER',source:'COMPANY_BOOTSTRAP_PROFILE_BINDING',profileVersion:null,effectiveFrom:null,effectiveTo:null},globalRank:{status:'AVAILABLE',highestRank:null}}}});
 const tree=await render();const output=JSON.stringify(tree.toJSON());expect(output).toContain('方案資料未提供');expect(output).toContain('Always Active (Company Rule)');expect(output).not.toContain('方案 LEADER');expect(output).not.toContain('已核准 Company Bootstrap LEADER Binding');act(()=>tree.unmount());
});
