CREATE TABLE commerce.package_profile (package_profile_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),stable_code text NOT NULL UNIQUE,package_class text NOT NULL CHECK(package_class IN ('QUALIFICATION','ACTIVE_DURATION','FUTURE')),status text NOT NULL DEFAULT 'ACTIVE',created_at timestamptz(6) NOT NULL DEFAULT now());
CREATE INDEX package_profile_class_status_idx ON commerce.package_profile(package_class,status);
CREATE TABLE commerce.package_profile_version (package_profile_version_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),package_profile_id uuid NOT NULL REFERENCES commerce.package_profile(package_profile_id),version integer NOT NULL CHECK(version>0),display_name text NOT NULL,currency text NOT NULL,price_amount numeric(18,2) NOT NULL CHECK(price_amount>0),selectable_product_quantity integer NOT NULL CHECK(selectable_product_quantity>0),selection_mode text NOT NULL DEFAULT 'EXACT_QUANTITY' CHECK(selection_mode='EXACT_QUANTITY'),membership_effect text NOT NULL,qualification_effect text NOT NULL,active_duration_unit text,active_duration_value integer,target_qualification_required boolean NOT NULL DEFAULT false,member_eligibility_policy_ref text,sales_from timestamptz(6),sales_to timestamptz(6),effective_from timestamptz(6),effective_to timestamptz(6),status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN ('DRAFT','APPROVED','SCHEDULED','ACTIVE','RETIRED')),recognition_config_ref text,config_hash text NOT NULL,approval_reference text,created_by_actor text NOT NULL,approved_by_actor text,approved_at timestamptz(6),created_at timestamptz(6) NOT NULL DEFAULT now(),updated_at timestamptz(6) NOT NULL DEFAULT now(),UNIQUE(package_profile_id,version),CHECK(sales_to IS NULL OR sales_from IS NOT NULL AND sales_to>sales_from),CHECK(effective_to IS NULL OR effective_from IS NOT NULL AND effective_to>effective_from),CHECK((active_duration_unit IS NULL)=(active_duration_value IS NULL)),CHECK(active_duration_value IS NULL OR active_duration_value>0));
CREATE INDEX package_version_sellable_idx ON commerce.package_profile_version(status,effective_from,effective_to,sales_from,sales_to);
CREATE TABLE commerce.package_selectable_product (package_selectable_product_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),package_profile_version_id uuid NOT NULL REFERENCES commerce.package_profile_version(package_profile_version_id),product_rule_profile_id uuid NOT NULL REFERENCES commerce.product_rule_profile(product_rule_profile_id),enabled_from timestamptz(6) NOT NULL,enabled_to timestamptz(6),min_qty integer,max_qty integer,selection_increment integer NOT NULL DEFAULT 1,sort_order integer NOT NULL DEFAULT 0,status text NOT NULL DEFAULT 'ACTIVE',created_at timestamptz(6) NOT NULL DEFAULT now(),UNIQUE(package_profile_version_id,product_rule_profile_id),CHECK(enabled_to IS NULL OR enabled_to>enabled_from),CHECK(min_qty IS NULL OR min_qty>=0),CHECK(max_qty IS NULL OR max_qty>0),CHECK(min_qty IS NULL OR max_qty IS NULL OR max_qty>=min_qty),CHECK(selection_increment>0));
CREATE INDEX package_selectable_version_status_idx ON commerce.package_selectable_product(package_profile_version_id,status,enabled_from,enabled_to);
CREATE TABLE commerce.package_purchase_snapshot (package_purchase_snapshot_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),order_id uuid NOT NULL UNIQUE REFERENCES commerce."order"(order_id),person_id uuid NOT NULL REFERENCES identity.person(person_id),target_qualification_id uuid REFERENCES membership.qualification(qualification_id),package_profile_version_id uuid NOT NULL REFERENCES commerce.package_profile_version(package_profile_version_id),package_code text NOT NULL,package_name text NOT NULL,package_class text NOT NULL,currency text NOT NULL,price_amount numeric(18,2) NOT NULL,selectable_product_quantity integer NOT NULL,membership_effect text NOT NULL,qualification_effect text NOT NULL,active_duration_unit text,active_duration_value integer,recognition_config_ref text NOT NULL,package_config_hash text NOT NULL,purchased_at timestamptz(6) NOT NULL,created_at timestamptz(6) NOT NULL DEFAULT now());
CREATE INDEX package_purchase_person_time_idx ON commerce.package_purchase_snapshot(person_id,purchased_at);CREATE INDEX package_purchase_target_time_idx ON commerce.package_purchase_snapshot(target_qualification_id,purchased_at);
CREATE TABLE commerce.package_purchase_selection (package_purchase_selection_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),package_purchase_snapshot_id uuid NOT NULL REFERENCES commerce.package_purchase_snapshot(package_purchase_snapshot_id),product_rule_profile_id uuid NOT NULL REFERENCES commerce.product_rule_profile(product_rule_profile_id),product_id uuid NOT NULL REFERENCES commerce.product_reference(product_id),sku_snapshot text NOT NULL,product_display_snapshot text NOT NULL,quantity integer NOT NULL CHECK(quantity>0),product_config_hash text NOT NULL,created_at timestamptz(6) NOT NULL DEFAULT now(),UNIQUE(package_purchase_snapshot_id,product_rule_profile_id));
CREATE TABLE membership.qualification_active_entitlement_evidence (qualification_active_entitlement_evidence_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),qualification_id uuid NOT NULL REFERENCES membership.qualification(qualification_id),package_purchase_snapshot_id uuid NOT NULL UNIQUE REFERENCES commerce.package_purchase_snapshot(package_purchase_snapshot_id),entitlement_type text NOT NULL,period_start timestamptz(6) NOT NULL,period_end timestamptz(6) NOT NULL,policy_version text NOT NULL,evidence_hash text NOT NULL,status text NOT NULL,created_at timestamptz(6) NOT NULL DEFAULT now(),CHECK(period_end>period_start));
CREATE INDEX active_entitlement_qualification_period_idx ON membership.qualification_active_entitlement_evidence(qualification_id,period_start,period_end);

CREATE FUNCTION commerce.ucell_package_version_guard() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD.status<>'DRAFT' AND (NEW.display_name,NEW.currency,NEW.price_amount,NEW.selectable_product_quantity,NEW.selection_mode,NEW.membership_effect,NEW.qualification_effect,NEW.active_duration_unit,NEW.active_duration_value,NEW.target_qualification_required,NEW.member_eligibility_policy_ref,NEW.recognition_config_ref,NEW.config_hash) IS DISTINCT FROM (OLD.display_name,OLD.currency,OLD.price_amount,OLD.selectable_product_quantity,OLD.selection_mode,OLD.membership_effect,OLD.qualification_effect,OLD.active_duration_unit,OLD.active_duration_value,OLD.target_qualification_required,OLD.member_eligibility_policy_ref,OLD.recognition_config_ref,OLD.config_hash) THEN RAISE EXCEPTION 'published package configuration is immutable'; END IF; RETURN NEW; END $$;
CREATE TRIGGER package_version_immutable_guard BEFORE UPDATE ON commerce.package_profile_version FOR EACH ROW EXECUTE FUNCTION commerce.ucell_package_version_guard();
CREATE FUNCTION commerce.ucell_package_product_guard() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE s text; BEGIN SELECT status INTO s FROM commerce.package_profile_version WHERE package_profile_version_id=COALESCE(NEW.package_profile_version_id,OLD.package_profile_version_id);IF s<>'DRAFT' THEN RAISE EXCEPTION 'published package product pool is immutable';END IF;RETURN COALESCE(NEW,OLD);END $$;
CREATE TRIGGER package_product_immutable_guard BEFORE INSERT OR UPDATE OR DELETE ON commerce.package_selectable_product FOR EACH ROW EXECUTE FUNCTION commerce.ucell_package_product_guard();
CREATE TRIGGER package_purchase_snapshot_append_only BEFORE UPDATE OR DELETE ON commerce.package_purchase_snapshot FOR EACH ROW EXECUTE FUNCTION public.ucell_prevent_mutation();
CREATE TRIGGER package_purchase_selection_append_only BEFORE UPDATE OR DELETE ON commerce.package_purchase_selection FOR EACH ROW EXECUTE FUNCTION public.ucell_prevent_mutation();
CREATE TRIGGER qualification_active_entitlement_append_only BEFORE UPDATE OR DELETE ON membership.qualification_active_entitlement_evidence FOR EACH ROW EXECUTE FUNCTION public.ucell_prevent_mutation();

WITH seed(stable_code,package_class,display_name,price_amount,qty,membership_effect,qualification_effect,duration_unit,duration_value,target_required) AS (VALUES ('STARTER','QUALIFICATION','啟航',14400,3,'FORMAL_ELIGIBILITY','CREATE_QUALIFICATION',NULL,NULL,false),('ELITE','QUALIFICATION','菁英',43200,9,'FORMAL_ELIGIBILITY','CREATE_QUALIFICATION',NULL,NULL,false),('LEADER','QUALIFICATION','領袖',72000,15,'FORMAL_ELIGIBILITY','CREATE_QUALIFICATION',NULL,NULL,false),('ACTIVE_QUARTER','ACTIVE_DURATION','季活躍',6000,2,'NONE','ACTIVE_ENTITLEMENT','MONTH',3,true),('ACTIVE_HALF_YEAR','ACTIVE_DURATION','半年活躍',12000,4,'NONE','ACTIVE_ENTITLEMENT','MONTH',6,true),('ACTIVE_YEAR','ACTIVE_DURATION','年活躍',24000,8,'NONE','ACTIVE_ENTITLEMENT','YEAR',1,true)),profiles AS (INSERT INTO commerce.package_profile(stable_code,package_class) SELECT stable_code,package_class FROM seed RETURNING package_profile_id,stable_code) INSERT INTO commerce.package_profile_version(package_profile_id,version,display_name,currency,price_amount,selectable_product_quantity,membership_effect,qualification_effect,active_duration_unit,active_duration_value,target_qualification_required,status,config_hash,approval_reference,created_by_actor) SELECT p.package_profile_id,1,s.display_name,'TWD',s.price_amount,s.qty,s.membership_effect,s.qualification_effect,s.duration_unit,s.duration_value,s.target_required,'DRAFT',encode(digest(concat_ws('|',s.stable_code,s.display_name,s.price_amount,s.qty),'sha256'),'hex'),'BATCH4_APPROVED_INITIAL_PARAMETERS','GOVERNANCE_SEED' FROM seed s JOIN profiles p USING(stable_code);
