import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {ErrorBox,Field} from '../../components/ui';
import {QueryFeedback} from '../../components/QueryFeedback';
import {get,post,qs} from '../../lib/api';
import {erpMetricLabel} from './ErpCompensationProjectionForm';
type Entry={groupReference:string;treatment:'MAP'|'REPORT_ONLY';mappingCode:string|null};
type Preview={mappingReference:string;revision:number;reviewHash:string;request:{aggregates:(Entry&{metric:string;economicCategory:string;amount:string})[]}};
type Mapping={mappingReference:string;revision:number;approvedAt:string;requestHash:string;request:{configuration:{policyReference:string;policyVersion:number};aggregates:(Entry&{metric:string;economicCategory:string;amount:string})[]}};
export function ErpAccountingMappingForm({reference,groups,canApprove,pinned,previousMappingReference,onApproved}:{reference:string;groups:{groupReference:string;metric:string;economicCategory:string;amount:string}[];canApprove:boolean;pinned:boolean;previousMappingReference:string|null;onApproved:()=>void}){
 const [connection,setConnection]=useState(''),[policy,setPolicy]=useState(''),[version,setVersion]=useState(''),[values,setValues]=useState<Record<string,{treatment:string;mappingCode:string}>>({}),[preview,setPreview]=useState<Preview|null>(null),[approval,setApproval]=useState(''),[error,setError]=useState<unknown>(),[busy,setBusy]=useState(false),[before,setBefore]=useState<number|undefined>();
 const connections=useQuery({queryKey:['erp-mapping-connections'],queryFn:()=>get<{data:{items:{connectionKey:string;version:number;provider:string;environment:string}[];truncated:boolean}}>('/admin/erp-accounting-mappings/connections'),enabled:canApprove&&!pinned});
 const history=useQuery({queryKey:['erp-mapping-history',reference,before,previousMappingReference],queryFn:()=>get<{data:{items:Mapping[];nextBefore:number|null}}>(`/admin/erp-accounting-mappings/${reference}`+qs({before}))});
 const invalidate=()=>{setPreview(null);setApproval('');setError(undefined);};
 const change=(ref:string,patch:Partial<{treatment:string;mappingCode:string}>)=>{invalidate();setValues(current=>({...current,[ref]:{...(current[ref]??{treatment:'',mappingCode:''}),...patch}}));};
 const body=()=>{const selected=connections.data?.data.items.find(row=>JSON.stringify([row.connectionKey,row.version])===connection);return {connectionKey:selected?.connectionKey,connectionVersion:selected?.version,policyReference:policy,policyVersion:Number(version),previousMappingReference,entries:groups.map(group=>({groupReference:group.groupReference,treatment:values[group.groupReference]?.treatment,mappingCode:values[group.groupReference]?.treatment==='REPORT_ONLY'?null:values[group.groupReference]?.mappingCode}))};};
 return <section aria-label="ERP 會計映射"><h3>會計映射核准</h3><p>逐項填入核准的 ERP 映射代碼，或明確指定僅供報表。各金額分別核對，不加總成會計分錄。</p><ErrorBox error={error}/><QueryFeedback query={history}/>{history.data?.data.items.map(item=><details key={item.mappingReference}><summary>映射第 {item.revision} 版 · {new Date(item.approvedAt).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'})}</summary><p>政策依據：{item.request.configuration.policyReference} · 政策版本 {item.request.configuration.policyVersion}</p><MappingTable rows={item.request.aggregates}/><p>{item.mappingReference}</p><p>傳送證據：{item.requestHash}</p></details>)}{history.data?.data.nextBefore&&<button onClick={()=>setBefore(history.data!.data.nextBefore!)}>較早映射版本</button>}{before&&<button onClick={()=>setBefore(undefined)}>最新映射版本</button>}
 {pinned?<p>此投影已固定傳送版本，映射不可再變更；核准歷史持續保留。</p>:!canApprove?<p>目前為稽核唯讀；映射核准需財務權限。</p>:<><QueryFeedback query={connections}/>{connections.data&&!connections.data.data.items.length&&<p>尚無有效的已核准 ERP 連線版本，請先完成連線設定。</p>}{connections.data?.data.truncated&&<p>連線清單僅顯示前 100 筆，請先由連線管理確認目標版本。</p>}<form onSubmit={async event=>{event.preventDefault();setBusy(true);setError(undefined);setPreview(null);try{setPreview((await post<{data:Preview}>(`/admin/erp-accounting-mappings/${reference}/preview`,body())).data);}catch(value){setError(value);}finally{setBusy(false);}}}><fieldset disabled={busy}><Field label="ERP 連線版本"><select required value={connection} onChange={event=>{invalidate();setConnection(event.target.value);}}><option value="">請選擇</option>{connections.data?.data.items.map(row=><option key={JSON.stringify([row.connectionKey,row.version,row.provider])} value={JSON.stringify([row.connectionKey,row.version])}>{row.connectionKey} · {row.provider} · 第 {row.version} 版 · {row.environment==='TEST'?'測試':row.environment==='STAGE'?'驗收':'正式'}</option>)}</select></Field><Field label="核准映射政策單號"><input required pattern="[A-Za-z0-9][A-Za-z0-9._:/-]{7,99}" value={policy} onChange={event=>{invalidate();setPolicy(event.target.value);}}/></Field><Field label="映射政策版本"><input required type="number" min="1" max="2147483647" step="1" value={version} onChange={event=>{invalidate();setVersion(event.target.value);}}/></Field>
 {groups.map((group,index)=><fieldset key={group.groupReference}><legend>項目 {index+1}：{erpMetricLabel[group.metric]??group.metric} · {group.economicCategory} · {group.amount}</legend><Field label={`項目 ${index+1} 處理方式`}><select required value={values[group.groupReference]?.treatment??''} onChange={event=>change(group.groupReference,{treatment:event.target.value,mappingCode:''})}><option value="">請明確選擇</option><option value="MAP">使用核准映射</option><option value="REPORT_ONLY">僅供報表</option></select></Field>{values[group.groupReference]?.treatment==='MAP'&&<Field label={`項目 ${index+1} 映射代碼`}><input required pattern="[A-Za-z0-9][A-Za-z0-9._:/-]{0,99}" value={values[group.groupReference].mappingCode} onChange={event=>change(group.groupReference,{mappingCode:event.target.value})}/></Field>}</fieldset>)}<button type="submit" disabled={!groups.length}>預覽映射版本</button></fieldset></form>
 {preview&&<><h4>待核准映射第 {preview.revision} 版</h4><MappingTable rows={preview.request.aggregates}/><details><summary>審閱證據</summary><p>{preview.reviewHash}</p></details><form onSubmit={async event=>{event.preventDefault();setBusy(true);setError(undefined);try{await post(`/admin/erp-accounting-mappings/${reference}/approve`,{...body(),reviewHash:preview.reviewHash,approvalReference:approval});setPreview(null);setApproval('');setBefore(undefined);await history.refetch();onApproved();}catch(value){setError(value);}finally{setBusy(false);}}}><fieldset disabled={busy}><Field label="映射財務核准單號"><input required pattern="[A-Za-z0-9][A-Za-z0-9._:/-]{7,99}" value={approval} onChange={event=>setApproval(event.target.value)}/></Field><button type="submit">核准並封存映射</button></fieldset></form></>}
 </>}
 </section>;
}
function MappingTable({rows}:{rows:(Entry&{metric:string;economicCategory:string;amount:string})[]}){return <div className="table-wrap"><table><thead><tr><th>數值項目</th><th>類別</th><th>金額</th><th>映射決策</th></tr></thead><tbody>{rows.map(row=><tr key={row.groupReference}><td>{erpMetricLabel[row.metric]??row.metric}</td><td>{row.economicCategory}</td><td>{row.amount}</td><td>{row.treatment==='REPORT_ONLY'?'僅供報表':row.mappingCode}</td></tr>)}</tbody></table></div>;}
