import {act,create} from 'react-test-renderer';
import {beforeEach,describe,expect,it,vi} from 'vitest';
import {ErpAccountingSupplementForm} from './ErpAccountingSupplementForm';
import * as api from '../../lib/api';
vi.mock('../../lib/api',async()=>({...await vi.importActual('../../lib/api'),post:vi.fn()}));
const reference='ERP-PROJECTION-'+'a'.repeat(40),next='ERP-PROJECTION-'+'b'.repeat(40),preview={projectionReference:next,revision:2,reviewHash:'a'.repeat(64),drillbackHash:'b'.repeat(64),previous:{projectionReference:reference,revision:1,totals:{bankPaid:'40.0000'}},expected:{totals:{bankPaid:'100.0000'}}};
describe('Append-only accounting supplement approval',()=>{
 beforeEach(()=>{vi.mocked(api.post).mockReset();vi.mocked(api.post).mockImplementation(async(path)=>({data:path.endsWith('preview')?preview:{projectionReference:next}} as any));});
 it('shows old and current values and binds a separate approval to the parent and review hash',async()=>{let tree:any;const onCreated=vi.fn();await act(async()=>{tree=create(<ErpAccountingSupplementForm reference={reference} configuration={{accountingDate:'2026-09-30',currency:'TWD'}} payment onCreated={onCreated}/>);});await act(async()=>tree.root.findAllByType('form')[0].props.onSubmit({preventDefault(){}}));expect(JSON.stringify(tree.toJSON())).toContain('40.0000');expect(JSON.stringify(tree.toJSON())).toContain('100.0000');await act(async()=>{const inputs=tree.root.findAllByType('form')[1].findAllByType('input');inputs[0].props.onChange({target:{value:'BANK-CHANGE-001'}});inputs[1].props.onChange({target:{value:'FINANCE-APPROVAL-002'}});});await act(async()=>tree.root.findAllByType('form')[1].props.onSubmit({preventDefault(){}}));expect(api.post).toHaveBeenLastCalledWith('/admin/erp-projections/payment/supplement-approve',expect.objectContaining({previousProjectionReference:reference,reviewHash:preview.reviewHash,reasonReference:'BANK-CHANGE-001',approvalReference:'FINANCE-APPROVAL-002'}));expect(onCreated).toHaveBeenCalledWith(next);await act(async()=>tree.unmount());});
 it('invalidates review when the supplemental accounting date changes',async()=>{let tree:any;await act(async()=>{tree=create(<ErpAccountingSupplementForm reference={reference} configuration={{accountingDate:'2026-09-30'}} payment={false} onCreated={vi.fn()}/>);});await act(async()=>tree.root.findAllByType('form')[0].props.onSubmit({preventDefault(){}}));await act(async()=>tree.root.findByProps({type:'date'}).props.onChange({target:{value:'2026-10-01'}}));expect(tree.root.findAllByType('form')).toHaveLength(1);expect(api.post).toHaveBeenCalledWith('/admin/erp-projections/compensation/supplement-preview',expect.objectContaining({previousProjectionReference:reference}));await act(async()=>tree.unmount());});
});
