import {useState} from 'react';
import {ErrorBox,Field} from '../../components/ui';
import {post} from '../../lib/api';
type Preview={projectionReference:string;revision:number;reviewHash:string;drillbackHash:string;previous:{projectionReference:string;revision:number;totals:Record<string,string>};expected:{totals:Record<string,string>}};
const labels:Record<string,string>={memberPayableGross:'會員應付毛額',recoveryRequired:'應回收',recoveryApplied:'已回收',recoveryOutstanding:'待回收',payoutRecoveryOffset:'整批回收抵扣',payoutNet:'整批付款淨額',bankPaid:'銀行累計已付'};
export function ErpAccountingSupplementForm({reference,configuration,payment,onCreated}:{reference:string;configuration:Record<string,unknown>;payment:boolean;onCreated:(reference:string)=>void}){
 const [accountingDate,setAccountingDate]=useState(String(configuration.accountingDate??'')),[preview,setPreview]=useState<Preview|null>(null),[reason,setReason]=useState(''),[approval,setApproval]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>();
 const base='/admin/erp-projections/'+(payment?'payment':'compensation'),body=()=>({...configuration,accountingDate,previousProjectionReference:reference});
 return <section><h3>建立補充快照</h3><p>重新核對目前來源，保留前版投影與受理證據。補充快照也需另行取得 ERP 映射及受理結果。</p><ErrorBox error={error}/><form onSubmit={async event=>{event.preventDefault();setBusy(true);setError(undefined);setPreview(null);try{setPreview((await post<{data:Preview}>(base+'/supplement-preview',body())).data);}catch(value){setError(value);}finally{setBusy(false);}}}><fieldset disabled={busy}><Field label="補充快照會計日期"><input required type="date" value={accountingDate} onChange={event=>{setAccountingDate(event.target.value);setPreview(null);setReason('');setApproval('');}}/></Field><button type="submit">比較目前資料與此版本</button></fieldset></form>
  {preview&&<><p>第 {preview.previous.revision} 版 → 第 {preview.revision} 版。各數值分別對帳，不將差額自行轉成會計分錄。</p><div className="table-wrap"><table><thead><tr><th>數值項目</th><th>前版</th><th>補充快照</th></tr></thead><tbody>{Object.entries(preview.expected.totals).map(([key,value])=><tr key={key}><td>{labels[key]??key}</td><td>{preview.previous.totals[key]??'尚無'}</td><td>{value}</td></tr>)}</tbody></table></div><details><summary>補充審閱證據</summary><p>前版：{preview.previous.projectionReference}</p><p>審閱 hash：{preview.reviewHash}</p><p>來源 hash：{preview.drillbackHash}</p></details><form onSubmit={async event=>{event.preventDefault();setBusy(true);setError(undefined);try{const result=await post<{data:{projectionReference:string}}>(base+'/supplement-approve',{...body(),reviewHash:preview.reviewHash,reasonReference:reason,approvalReference:approval});setPreview(null);onCreated(result.data.projectionReference);}catch(value){setError(value);}finally{setBusy(false);}}}><Field label="補充原因依據單號"><input required pattern="[A-Za-z0-9][A-Za-z0-9._:/-]{7,99}" value={reason} onChange={event=>setReason(event.target.value)}/></Field><Field label="補充財務核准單號"><input required pattern="[A-Za-z0-9][A-Za-z0-9._:/-]{7,99}" value={approval} onChange={event=>setApproval(event.target.value)}/></Field><button type="submit" disabled={busy}>核准並新增補充版本</button></form></>}
 </section>;
}
