import {act,create} from 'react-test-renderer';
import {beforeEach,describe,expect,it,vi} from 'vitest';
import {ErpAccountingMappingForm} from './ErpAccountingMappingForm';
import * as api from '../../lib/api';
vi.mock('../../lib/api',async()=>({...await vi.importActual('../../lib/api'),post:vi.fn()}));
vi.mock('@tanstack/react-query',()=>({useQuery:({queryKey}:any)=>({data:{data:queryKey[0]==='erp-mapping-connections'?{items:[{connectionKey:'TEST-ERP',version:1,provider:'EZTOOL',environment:'TEST'}],truncated:false}:{items:[],nextBefore:null}},refetch:vi.fn(),isPending:false,isError:false,isFetching:false})}));
const reference='ERP-PROJECTION-'+'a'.repeat(40),groupReference='COMPENSATION-GROUP-'+'b'.repeat(40),groups=[{groupReference,metric:'MEMBER_PAYABLE_GROSS',economicCategory:'BINARY',amount:'100.0000'}],preview={mappingReference:'ERP-MAPPING-'+'c'.repeat(40),revision:1,reviewHash:'d'.repeat(64),request:{aggregates:[{...groups[0],treatment:'REPORT_ONLY',mappingCode:null}]}};
describe('ERP explicit mapping approval',()=>{
 beforeEach(()=>{vi.mocked(api.post).mockReset();vi.mocked(api.post).mockImplementation(async path=>({data:path.endsWith('/preview')?preview:{mappingReference:preview.mappingReference}} as any));});
 async function render(canApprove=true,pinned=false){let tree:any;const done=vi.fn();await act(async()=>{tree=create(<ErpAccountingMappingForm reference={reference} groups={groups} canApprove={canApprove} pinned={pinned} previousMappingReference={null} onApproved={done}/>);});return {tree,done};}
 async function configure(tree:any){await act(async()=>{const selects=tree.root.findAllByType('select');selects[0].props.onChange({target:{value:JSON.stringify(['TEST-ERP',1])}});selects[1].props.onChange({target:{value:'REPORT_ONLY'}});const inputs=tree.root.findAllByType('input');inputs[0].props.onChange({target:{value:'APPROVED-POLICY'}});inputs[1].props.onChange({target:{value:'1'}});});await act(async()=>tree.root.findAllByType('form')[0].props.onSubmit({preventDefault(){}}));}
 it('requires an explicit per-group choice and separate hash-bound approval',async()=>{const {tree,done}=await render();expect(tree.root.findAllByType('select')[1].props.value).toBe('');await configure(tree);expect(api.post).toHaveBeenCalledWith(`/admin/erp-accounting-mappings/${reference}/preview`,expect.objectContaining({entries:[{groupReference,treatment:'REPORT_ONLY',mappingCode:null}],previousMappingReference:null}));await act(async()=>tree.root.findAllByType('form')[1].findByType('input').props.onChange({target:{value:'FINANCE-APPROVED-001'}}));await act(async()=>tree.root.findAllByType('form')[1].props.onSubmit({preventDefault(){}}));expect(api.post).toHaveBeenLastCalledWith(`/admin/erp-accounting-mappings/${reference}/approve`,expect.objectContaining({reviewHash:preview.reviewHash,approvalReference:'FINANCE-APPROVED-001'}));expect(done).toHaveBeenCalledTimes(1);await act(async()=>tree.unmount());});
 it('invalidates preview when configuration changes',async()=>{const {tree}=await render();await configure(tree);expect(tree.root.findAllByType('form')).toHaveLength(2);await act(async()=>tree.root.findByProps({type:'number'}).props.onChange({target:{value:'2'}}));expect(tree.root.findAllByType('form')).toHaveLength(1);await act(async()=>tree.unmount());});
 it('keeps audit and dispatched projections read only',async()=>{for(const [canApprove,pinned] of [[false,false],[true,true]]){const {tree}=await render(canApprove,pinned);expect(tree.root.findAllByType('form')).toHaveLength(0);await act(async()=>tree.unmount());}expect(api.post).not.toHaveBeenCalled();});
});
