import {useState} from 'react';
import {Field} from '../../components/ui';
import {erpMetricLabel,categoryLabels} from './ErpCompensationProjectionForm';
export type AccountingGroup={groupReference:string;metric:string;economicCategory:string;amount:string;treatment:string;mappingCode:string|null};
export function ErpAccountingResultForm({groups,actual,providerReference,requestHash,canRecord,disabled,submit}:{groups:AccountingGroup[];actual?:{groupReference:string;amount:string}[];providerReference:string;requestHash:string;canRecord:boolean;disabled:boolean;submit:(body:unknown)=>Promise<boolean>}){
 const [resultKey,setResultKey]=useState(()=>crypto.randomUUID()),[currency,setCurrency]=useState(''),[occurredAt,setOccurredAt]=useState(''),[values,setValues]=useState<Record<string,{included:boolean;amount:string}>>({});
 const required=groups.filter(group=>group.treatment==='MAP');
 return <section aria-label="ERP 聚合結果對帳"><h3>ERP 聚合金額對帳</h3><p>僅核對核准映射的項目；僅供報表項目不列入應過帳金額。每項獨立比較，不將重疊的毛額、抵扣與淨額相加。</p><div className="table-wrap"><table><thead><tr><th>數值項目／類別</th><th>映射代碼</th><th>UCell 封存值</th><th>ERP 回報值</th></tr></thead><tbody>{required.map(group=><tr key={group.groupReference}><td>{erpMetricLabel[group.metric]??group.metric} · {categoryLabels[group.economicCategory]??group.economicCategory}</td><td>{group.mappingCode}</td><td>{group.amount}</td><td>{actual?.find(row=>row.groupReference===group.groupReference)?.amount??'尚無'}</td></tr>)}{actual?.filter(row=>!required.some(group=>group.groupReference===row.groupReference)).map(row=><tr key={row.groupReference}><td>{row.groupReference}</td><td>不在核准對帳項目內</td><td>不適用</td><td>{row.amount}</td></tr>)}</tbody></table></div>{!required.length&&<p>此版本全部為僅供報表；可記錄已受理單據的幣別與證據，不代表存在會計分錄。</p>}
 {canRecord&&<form onSubmit={async event=>{event.preventDefault();const ok=await submit({resultKey,providerReference,requestHash,currency,occurredAt:new Date(occurredAt+'+08:00').toISOString(),groups:required.filter(group=>values[group.groupReference]?.included).map(group=>({groupReference:group.groupReference,amount:values[group.groupReference].amount}))});if(ok){setResultKey(crypto.randomUUID());setCurrency('');setOccurredAt('');setValues({});}}}><fieldset disabled={disabled}><Field label="ERP 聚合單據時間（台北時間）"><input required type="datetime-local" value={occurredAt} onChange={event=>setOccurredAt(event.target.value)}/></Field><Field label="ERP 聚合幣別"><input required pattern="[A-Z]{3}" value={currency} onChange={event=>setCurrency(event.target.value.toUpperCase())}/></Field>{required.map((group,index)=><fieldset key={group.groupReference}><legend>項目 {index+1}：{erpMetricLabel[group.metric]??group.metric} · {categoryLabels[group.economicCategory]??group.economicCategory}</legend><label><input type="checkbox" checked={values[group.groupReference]?.included??false} onChange={event=>setValues(current=>({...current,[group.groupReference]:{amount:current[group.groupReference]?.amount??'',included:event.target.checked}}))}/>ERP 本次回報此項目</label>{values[group.groupReference]?.included&&<Field label={`項目 ${index+1} ERP 實際金額`}><input required inputMode="decimal" pattern="[0-9]+(\.[0-9]{1,4})?" value={values[group.groupReference].amount} onChange={event=>setValues(current=>({...current,[group.groupReference]:{...current[group.groupReference],amount:event.target.value}}))}/></Field>}</fieldset>)}<button type="submit">核對並保存 ERP 聚合結果</button></fieldset></form>}
 </section>;
}
