import {act,create} from 'react-test-renderer';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {beforeEach,describe,expect,it,vi} from 'vitest';
import {ErpBusinessProjectionPanel} from './ErpBusinessProjectionPanel';
import * as api from '../../lib/api';
const auth=vi.hoisted(()=>({role:'FINANCE'}));
vi.mock('../auth/auth',()=>({useAuth:()=>({user:auth})}));
vi.mock('../../lib/api',async()=>({...await vi.importActual('../../lib/api'),get:vi.fn(),post:vi.fn()}));
const reference='ERP-PROJECTION-'+'a'.repeat(40),lineReference='ORDER-LINE-'+'b'.repeat(40);
const row={projectionReference:reference,stream:'SALES',status:'ACKNOWLEDGED',providerReference:'ERP-10001',payloadHash:'a'.repeat(64),drillbackHash:'b'.repeat(64),expected:{orderNo:'10001',currency:'TWD',netAmount:'190',lines:[{lineReference,sku:'SKU-1',quantity:'2',amount:'200'}]},actual:null,attemptCount:1,requestedAt:'2026-09-30T00:00:00Z',acknowledgedAt:'2026-09-30T00:01:00Z',reconciledAt:null,blockedReason:null,mismatchCode:null,drillback:{verified:true},exceptions:[{reference:'ERP-EXCEPTION-'+'c'.repeat(40),code:'ERP_PROJECTION_RESULT_MISMATCH',status:'OPEN'}]};
async function mount(){let tree:any;await act(async()=>{tree=create(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><ErpBusinessProjectionPanel/></QueryClientProvider>);await new Promise(resolve=>setTimeout(resolve,30));});await act(async()=>{tree.root.findAllByType('button').find((button:any)=>button.children.join('')==='查看投影與對帳').props.onClick();await new Promise(resolve=>setTimeout(resolve,30));});return tree;}
describe('ERP business projection controls',()=>{
 beforeEach(()=>{auth.role='FINANCE';vi.mocked(api.post).mockReset();vi.mocked(api.get).mockImplementation(async(path)=>({data:path===`/admin/erp-projections/${reference}`?row:{items:[row],nextCursor:null,asOf:'2026-09-30T00:00:00Z',dataThrough:'2026-09-30T00:02:00Z'}} as any));});
 it('leaves actual ERP values blank and keeps open exceptions visible',async()=>{const tree=await mount(),text=JSON.stringify(tree.toJSON());expect(text).toContain('仍有 ');expect(text).toContain('未解決例外');expect(text).toContain('來源封存已通過 hash 驗證');const form=tree.root.findAllByType('form').at(-1);expect(form.findAllByType('input').filter((input:any)=>input.props.type!=='checkbox').every((input:any)=>input.props.value==='')).toBe(true);expect(form.findByProps({type:'checkbox'}).props.checked).toBe(false);expect(api.post).not.toHaveBeenCalled();await act(async()=>tree.unmount());});
 it('does not expose result-entry controls to compliance readers',async()=>{auth.role='COMPLIANCE_AUDIT';const tree=await mount();expect(JSON.stringify(tree.toJSON())).toContain('稽核唯讀');expect(tree.root.findAllByProps({type:'datetime-local'})).toHaveLength(0);expect(api.post).not.toHaveBeenCalled();await act(async()=>tree.unmount());});
 it('requires a case reference to retry failed delivery without changing the sealed projection',async()=>{vi.mocked(api.get).mockImplementation(async(path)=>({data:path===`/admin/erp-projections/${reference}`?{...row,status:'FAILED',providerReference:null}:{items:[row],nextCursor:null}} as any));vi.mocked(api.post).mockResolvedValue({data:{projectionReference:reference,replayed:false}} as any);const tree=await mount(),form=tree.root.findAllByType('form').at(-1);expect(form.findByType('input').props.value).toBe('');expect(form.findByType('input').props.required).toBe(true);await act(async()=>form.findByType('input').props.onChange({target:{value:'CASE-ERP-2026'}}));await act(async()=>tree.root.findAllByType('form').at(-1).props.onSubmit({preventDefault(){}}));expect(api.post).toHaveBeenCalledWith(`/admin/erp-projections/${reference}/retry`,{retryKey:expect.any(String),reasonReference:'CASE-ERP-2026'});expect(JSON.stringify(tree.toJSON())).toContain('已保存重試請求');await act(async()=>tree.unmount());});
 it('submits only explicitly entered actual values and selected ERP lines',async()=>{const tree=await mount();vi.mocked(api.post).mockResolvedValue({data:{outcome:'PARTIAL'}} as any);const form=()=>tree.root.findAllByType('form').at(-1);await act(async()=>{const inputs=form().findAllByType('input');inputs[0].props.onChange({target:{value:'2026-09-30T08:30'}});inputs[1].props.onChange({target:{value:'twd'}});inputs[2].props.onChange({target:{value:'95'}});inputs[3].props.onChange({target:{checked:true}});});await act(async()=>{const inputs=form().findAllByType('input');inputs[4].props.onChange({target:{value:'1'}});inputs[5].props.onChange({target:{value:'100'}});});await act(async()=>form().props.onSubmit({preventDefault(){}}));expect(api.post).toHaveBeenCalledWith(`/admin/erp-projections/${reference}/results`,expect.objectContaining({providerReference:'ERP-10001',currency:'TWD',amount:'95',lines:[{lineReference,quantity:'1',amount:'100'}]}));expect(form().findAllByType('input')[2].props.value).toBe('');await act(async()=>tree.unmount());});
});
