import {ErpPaymentProjectionForm} from './ErpPaymentProjectionForm';
import {ErpCompensationProjectionForm,CompensationAggregateTable,CompensationSourceTable} from './ErpCompensationProjectionForm';
import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Badge,Card,ErrorBox,Field} from '../../components/ui';
import {get,post,qs} from '../../lib/api';
import {QueryFeedback} from '../../components/QueryFeedback';
import {useAuth} from '../auth/auth';

type Line={lineReference:string;sku:string;quantity:string;amount:string};
type Projection={projectionReference:string;stream:string;status:string;payloadHash:string;drillbackHash:string;providerReference:string|null;attemptCount:number;blockedReason:string|null;mismatchCode:string|null;expected:{orderNo?:string;currency?:string;netAmount?:string;amount?:string;periodReference?:string;payoutReference?:string;projectionPurpose?:string;paymentEvidence?:{confirmedLines:number;pendingLines:number};aggregates?:{metric:string;economicCategory:string;payoutReference:string|null;amount:string;sourceCount:number}[];lines?:Line[]};actual:{amount:string;currency:string;occurredAt:string;lines:{lineReference:string;quantity:string;amount:string}[]}|null;requestedAt:string;acknowledgedAt:string|null;reconciledAt:string|null;exceptions?:{reference:string;code:string;status:string}[];drillback?:{verified:boolean;hash:string;orderNo:string|null};dataThrough?:string};
type Sources={orderNo:string;status:string;returns:{returnReference:string;status:string;occurredAt:string}[]};
const label:Record<string,string>={SALES:'銷售',RETURN:'退貨',COMPENSATION:'獎金會計投影',BLOCKED_EXTERNAL:'等待外部條件',QUEUED:'等待處理',ACKNOWLEDGED:'ERP 已受理',RECONCILED:'ERP 金額與數量已對帳',MISMATCH:'ERP 有差異',FAILED:'受理失敗',PAID:'已付款',FULFILLED:'已履行',PARTIAL_RETURN:'部分退貨',RETURNED:'已退貨',POSTED:'已入帳',DRAFT:'草稿',CONFIRMED:'已確認'};
const initialQuery=(key:string)=>typeof window==='undefined'?'':new URLSearchParams(window.location.search).get(key)??'';
const when=(value:string|null)=>value?new Date(value).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'}):'尚無';
const tone=(value:string)=>value==='RECONCILED'?'ok':['FAILED','MISMATCH'].includes(value)?'danger':'warn';
export function ErpBusinessProjectionPanel(){
 const {user}=useAuth(),client=useQueryClient(),canWrite=['SUPER_ADMIN','ORDER_OPS','FINANCE'].includes(user?.role??'');
 const [stream,setStream]=useState(()=>['SALES','RETURN','COMPENSATION'].includes(initialQuery('stream'))?initialQuery('stream'):'SALES'),[cursor,setCursor]=useState<string|undefined>(),[asOf,setAsOf]=useState<string|undefined>(),[draftOrder,setDraftOrder]=useState(''),[orderNo,setOrderNo]=useState(''),[selected,setSelected]=useState(()=>/^ERP-PROJECTION-[a-f0-9]{40}$/.test(initialQuery('projection'))?initialQuery('projection'):''),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(),[notice,setNotice]=useState(''),[retryReason,setRetryReason]=useState(''),[retryKey,setRetryKey]=useState(()=>crypto.randomUUID());
 const list=useQuery({queryKey:['erp-business-projections',stream,cursor,asOf],queryFn:()=>get<{data:{items:Projection[];nextCursor:string|null;asOf:string;dataThrough:string}}>('/admin/erp-projections'+qs({stream,cursor,asOf,take:25})),refetchInterval:60_000});
 const sources=useQuery({queryKey:['erp-business-sources',orderNo],queryFn:()=>get<{data:Sources}>(`/admin/erp-projections/orders/${orderNo}/sources`),enabled:!!orderNo});
 const detail=useQuery({queryKey:['erp-business-detail',selected],queryFn:()=>get<{data:Projection}>(`/admin/erp-projections/${selected}`),enabled:!!selected});
 async function command(path:string,body:unknown={}){setBusy(true);setError(undefined);setNotice('');try{const result=await post<{data:{projectionReference?:string;outcome?:string;replayed?:boolean}}>(path,body);if(result.data.projectionReference)setSelected(result.data.projectionReference);setNotice(path.endsWith('/retry')?'已保存重試請求；沿用原投影與 ERP 冪等鍵，尚待實際受理。':result.data.outcome==='MATCHED'?'ERP 金額與數量相符；來源交易及待處理例外仍各自管理。':result.data.outcome?'已記錄 ERP 差異，請處理相關例外。':result.data.replayed?'已載入原有投影。':'已保存投影與交付請求。');await client.invalidateQueries({queryKey:['erp-business-projections']});await client.invalidateQueries({queryKey:['erp-business-detail']});return true;}catch(value){setError(value);return false;}finally{setBusy(false);}}
 const row=detail.data?.data;
 return <>
  <Card title="銷售／退貨／獎金會計投影"><p>UCell 保留交易與會員經濟明細；此處追蹤送交 ERP 的封存版本及對帳結果。ERP 已受理仍須核對金額和數量。</p><Field label="投影類型"><select value={stream} onChange={event=>{setStream(event.target.value);setCursor(undefined);setAsOf(undefined);setSelected('');}}>{(user?.role==='ORDER_OPS'?['SALES','RETURN']:['SALES','RETURN','COMPENSATION']).map(value=><option key={value} value={value}>{label[value]}</option>)}</select></Field><button onClick={()=>void list.refetch()} disabled={list.isFetching}>重新讀取投影</button></Card>
  <ErrorBox error={error}/>{notice&&<p role="status">{notice}</p>}
  {stream!=='COMPENSATION'&&<Card title="從訂單建立投影"><form onSubmit={event=>{event.preventDefault();setOrderNo(draftOrder);}}><Field label="訂單號"><input required inputMode="numeric" pattern="[0-9]{1,19}" value={draftOrder} onChange={event=>setDraftOrder(event.target.value)}/></Field><button type="submit">載入訂單來源</button></form><QueryFeedback query={sources}/>{sources.data&&<><p>訂單 {sources.data.data.orderNo} · {label[sources.data.data.status]??sources.data.data.status}</p>{stream==='SALES'?<button disabled={!canWrite||busy||!['PAID','FULFILLED','PARTIAL_RETURN','RETURNED'].includes(sources.data.data.status)} onClick={()=>void command(`/admin/erp-projections/orders/${orderNo}/sales`)}>封存銷售投影</button>:<ul>{sources.data.data.returns.map(item=><li key={item.returnReference}>{when(item.occurredAt)} · {label[item.status]??item.status} <button disabled={!canWrite||busy||item.status!=='POSTED'} onClick={()=>void command(`/admin/erp-projections/orders/${orderNo}/returns/${item.returnReference}`)}>封存此筆退貨投影</button></li>)}</ul>}</>}{!canWrite&&<p>目前為稽核唯讀；建立投影及登錄對帳需財務或訂單作業權限。</p>}</Card>}
  {stream==='COMPENSATION'&&<ErpCompensationProjectionForm canApprove={['SUPER_ADMIN','FINANCE'].includes(user?.role??'')} onCreated={reference=>{setSelected(reference);void client.invalidateQueries({queryKey:['erp-business-projections']});}}/>}
  {stream==='COMPENSATION'&&['SUPER_ADMIN','FINANCE'].includes(user?.role??'')&&<ErpPaymentProjectionForm onCreated={reference=>{setSelected(reference);void client.invalidateQueries({queryKey:['erp-business-projections']});}}/>}
  <QueryFeedback query={list} empty={!!list.data&&!list.data.data.items.length}/>
  {list.data&&<Card title="投影紀錄"><div className="table-wrap"><table><thead><tr><th>來源／類型</th><th>ERP 狀態</th><th>嘗試次數</th><th>建立時間</th><th>證據</th></tr></thead><tbody>{list.data.data.items.map(item=><tr key={item.projectionReference}><td>{item.expected.orderNo?`訂單 ${item.expected.orderNo}`:item.expected.payoutReference?'付款批次 '+item.expected.payoutReference:'獎金週期'} · {label[item.stream]}</td><td><Badge tone={tone(item.status)}>{label[item.status]??item.status}</Badge></td><td>{item.attemptCount}</td><td>{when(item.requestedAt)}</td><td><button onClick={()=>setSelected(item.projectionReference)}>查看投影與對帳</button></td></tr>)}</tbody></table></div><p>狀態讀取時間：{when(list.data.data.dataThrough)}</p>{list.data.data.nextCursor&&<button onClick={()=>{setCursor(list.data!.data.nextCursor!);setAsOf(list.data!.data.asOf);}}>下一頁</button>}</Card>}
  <QueryFeedback query={detail}/>{row&&<Card title="投影明細與來源追溯"><p><Badge tone={tone(row.status)}>{label[row.status]??row.status}</Badge> · {row.projectionReference}</p>{row.blockedReason&&<p>{row.blockedReason==='ERP_ACCOUNT_MAPPING_REQUIRED'?'尚缺核准會計科目映射；UCell 會員經濟狀態另行管理。':'實際 ERP 傳輸尚待核准介面及連線條件。'}</p>}<p>ERP 單號：{row.providerReference??'尚未受理'} · ERP 受理：{when(row.acknowledgedAt)} · ERP 對帳：{when(row.reconciledAt)}</p><p>UCell 預期金額：{row.expected.netAmount??row.expected.amount??'依聚合項目'} {row.expected.currency}；ERP 回報金額：{row.actual?.amount??'尚無'} {row.actual?.currency??''}</p>{!!row.exceptions?.length&&<p role="alert">仍有 {row.exceptions.length} 筆未解決例外；ERP 金額相符不會自動結案例外。</p>}<div className="table-wrap"><table><thead><tr><th>商品</th><th>UCell 數量</th><th>UCell 明細金額</th><th>ERP 數量</th><th>ERP 明細金額</th></tr></thead><tbody>{(row.expected.lines??[]).map(line=>{const actual=row.actual?.lines.find(item=>item.lineReference===line.lineReference);return <tr key={line.lineReference}><td>{line.sku}</td><td>{line.quantity}</td><td>{line.amount}</td><td>{actual?.quantity??'尚無'}</td><td>{actual?.amount??'尚無'}</td></tr>;})}</tbody></table></div>{row.expected.paymentEvidence&&<p>銀行完整確認 {row.expected.paymentEvidence.confirmedLines} 筆；尚待完整確認 {row.expected.paymentEvidence.pendingLines} 筆。</p>}{row.expected.aggregates&&<CompensationAggregateTable rows={row.expected.aggregates}/>}{row.stream==='COMPENSATION'&&<CompensationSourceTable key={row.projectionReference} reference={row.projectionReference} payment={row.expected.projectionPurpose==='PAYOUT_ACCOUNTING_REVIEW'}/>}{row.mismatchCode&&<p role="alert">ERP 回報與原始投影尚未完全一致，請核對來源明細與例外處理紀錄。</p>}<details><summary>封存與追溯證據</summary><p>投影 hash：{row.payloadHash}</p><p>來源追溯 hash：{row.drillbackHash}</p><p>{row.drillback?.verified?'來源封存已通過 hash 驗證。':'來源封存待驗證。'}</p></details>{canWrite&&row.status==='FAILED'&&<form onSubmit={async event=>{event.preventDefault();if(await command('/admin/erp-projections/'+row.projectionReference+'/retry',{retryKey,reasonReference:retryReason})){setRetryKey(crypto.randomUUID());setRetryReason('');}}}><Field label="重試依據單號"><input required minLength={8} maxLength={100} pattern="[A-Za-z0-9][A-Za-z0-9._:/-]{7,99}" value={retryReason} onChange={event=>setRetryReason(event.target.value)}/></Field><button type="submit" disabled={busy}>重新排入 ERP 處理</button><p>原投影、歷次嘗試及未解決例外均保留。</p></form>}{canWrite&&row.providerReference&&row.stream!=='COMPENSATION'&&['ACKNOWLEDGED','MISMATCH','RECONCILED'].includes(row.status)&&<ResultForm key={row.projectionReference} row={row} disabled={busy} submit={body=>command(`/admin/erp-projections/${row.projectionReference}/results`,body)}/>}</Card>}
 </>;
}
function ResultForm({row,disabled,submit}:{row:Projection;disabled:boolean;submit:(body:unknown)=>Promise<boolean>}){
 const [resultKey,setResultKey]=useState(()=>crypto.randomUUID()),[amount,setAmount]=useState(''),[currency,setCurrency]=useState(''),[occurredAt,setOccurredAt]=useState(''),[values,setValues]=useState<Record<string,{included:boolean;amount:string;quantity:string}>>({});
 const set=(key:string,change:Partial<{included:boolean;amount:string;quantity:string}>)=>setValues(current=>({...current,[key]:{...(current[key]??{included:false,amount:'',quantity:''}),...change}}));
 return <form onSubmit={async event=>{event.preventDefault();const ok=await submit({resultKey,providerReference:row.providerReference,occurredAt:new Date(occurredAt).toISOString(),currency,amount,lines:(row.expected.lines??[]).filter(line=>values[line.lineReference]?.included).map(line=>({lineReference:line.lineReference,amount:values[line.lineReference].amount,quantity:values[line.lineReference].quantity}))});if(ok){setResultKey(crypto.randomUUID());setAmount('');setCurrency('');setOccurredAt('');setValues({});}}}><h3>登錄實際 ERP 對帳結果</h3><p>依 ERP 單據填入實際值。此操作不變更付款、退貨回收或物流事實。</p><div className="filter-grid"><Field label="ERP 單據時間"><input required type="datetime-local" value={occurredAt} onChange={event=>setOccurredAt(event.target.value)}/></Field><Field label="ERP 幣別"><input required pattern="[A-Z]{3}" maxLength={3} value={currency} onChange={event=>setCurrency(event.target.value.toUpperCase())}/></Field><Field label="ERP 單據總額"><input required inputMode="decimal" pattern="[0-9]+(\.[0-9]{1,4})?" value={amount} onChange={event=>setAmount(event.target.value)}/></Field></div>{(row.expected.lines??[]).map(line=><fieldset key={line.lineReference}><legend>{line.sku}</legend><label><input type="checkbox" checked={values[line.lineReference]?.included??false} onChange={event=>set(line.lineReference,{included:event.target.checked})}/>ERP 本次有此明細</label>{values[line.lineReference]?.included&&<div className="filter-grid"><Field label={`${line.sku} ERP 數量`}><input required inputMode="decimal" pattern="[0-9]+(\.[0-9]{1,4})?" value={values[line.lineReference].quantity} onChange={event=>set(line.lineReference,{quantity:event.target.value})}/></Field><Field label={`${line.sku} ERP 明細金額`}><input required inputMode="decimal" pattern="[0-9]+(\.[0-9]{1,4})?" value={values[line.lineReference].amount} onChange={event=>set(line.lineReference,{amount:event.target.value})}/></Field></div>}</fieldset>)}<button type="submit" disabled={disabled}>核對並保存 ERP 結果</button></form>;
}
