import {act,create} from 'react-test-renderer';
import {beforeEach,describe,expect,it,vi} from 'vitest';
import {ErpCompensationProjectionForm} from './ErpCompensationProjectionForm';
import * as api from '../../lib/api';
vi.mock('../../lib/api',async()=>({...await vi.importActual('../../lib/api'),post:vi.fn()}));
const preview={projectionReference:'ERP-PROJECTION-'+'a'.repeat(40),reviewHash:'a'.repeat(64),drillbackHash:'b'.repeat(64),expected:{currency:'TWD',totals:{memberPayableGross:'10.0000'},aggregates:[{metric:'MEMBER_PAYABLE_GROSS',economicCategory:'EPV',payoutReference:null,amount:'10.0000',sourceCount:2}]}};
async function mount(){let tree:any;const onCreated=vi.fn();await act(async()=>{tree=create(<ErpCompensationProjectionForm canApprove onCreated={onCreated}/>);});return {tree,onCreated};}
async function review(tree:any){const values=['2026-09-10T00:00','2026-09-25T00:00','R1.0B','2026-09-26','TWD','FINANCE-TWD'];await act(async()=>{tree.root.findAllByType('input').filter((input:any)=>input.props.type!=='checkbox').forEach((input:any,index:number)=>input.props.onChange({target:{value:values[index]}}));});await act(async()=>tree.root.findAllByType('form')[0].props.onSubmit({preventDefault(){}}));}
describe('Compensation projection approval',()=>{
 beforeEach(()=>{vi.mocked(api.post).mockReset();vi.mocked(api.post).mockImplementation(async(path)=>({data:path.endsWith('/preview')?preview:{projectionReference:preview.projectionReference}} as any));});
 it('requires explicit configuration and a returned review hash before approval',async()=>{const {tree,onCreated}=await mount();expect(tree.root.findAllByType('form')).toHaveLength(1);expect(tree.root.findAllByType('input').filter((input:any)=>input.props.type!=='checkbox').every((input:any)=>input.props.value==='')).toBe(true);await review(tree);expect(tree.root.findAllByType('form')).toHaveLength(2);const approval=tree.root.findAllByType('form')[1];await act(async()=>approval.findByType('input').props.onChange({target:{value:'FINANCE-APPROVAL-01'}}));await act(async()=>tree.root.findAllByType('form')[1].props.onSubmit({preventDefault(){}}));expect(api.post).toHaveBeenLastCalledWith('/admin/erp-projections/compensation/approve',expect.objectContaining({reviewHash:preview.reviewHash,approvalReference:'FINANCE-APPROVAL-01',currencyBasisReference:'FINANCE-TWD',groupByPayoutBatch:false}));expect(onCreated).toHaveBeenCalledWith(preview.projectionReference);await act(async()=>tree.unmount());});
 it('removes approval controls when a reviewed dimension changes',async()=>{const {tree}=await mount();await review(tree);expect(tree.root.findAllByType('form')).toHaveLength(2);await act(async()=>tree.root.findByProps({type:'checkbox'}).props.onChange({target:{checked:true}}));expect(tree.root.findAllByType('form')).toHaveLength(1);expect(api.post).toHaveBeenCalledTimes(1);await act(async()=>tree.unmount());});
 it('leaves Order Operations and Compliance readers without approval commands',async()=>{let tree:any;await act(async()=>{tree=create(<ErpCompensationProjectionForm canApprove={false} onCreated={vi.fn()}/>);});expect(tree.root.findAllByType('form')).toHaveLength(0);expect(api.post).not.toHaveBeenCalled();await act(async()=>tree.unmount());});
});
