import {act,create} from 'react-test-renderer';
import {beforeEach,describe,expect,it,vi} from 'vitest';
import {ErpPaymentProjectionForm} from './ErpPaymentProjectionForm';
import * as api from '../../lib/api';
vi.mock('../../lib/api',async()=>({...await vi.importActual('../../lib/api'),get:vi.fn(),post:vi.fn()}));
const payoutReference='PAYOUT-'+'a'.repeat(40),projectionReference='ERP-PROJECTION-'+'b'.repeat(40),preview={reviewHash:'a'.repeat(64),drillbackHash:'b'.repeat(64),expected:{aggregates:[{metric:'PAYOUT_NET',economicCategory:'ALL',payoutReference,amount:'130',sourceCount:1}],totals:{memberPayableGross:'150',payoutRecoveryOffset:'20',payoutNet:'130',bankPaid:'130'}}};
async function mount(){let tree:any;const onCreated=vi.fn();await act(async()=>{tree=create(<ErpPaymentProjectionForm onCreated={onCreated}/>);});await act(async()=>{const inputs=tree.root.findAllByType('input');inputs[0].props.onChange({target:{value:'2026-09-10T00:00'}});inputs[1].props.onChange({target:{value:'2026-09-25T00:00'}});});await act(async()=>tree.root.findAllByType('form')[0].props.onSubmit({preventDefault(){}}));await act(async()=>{const form=tree.root.findAllByType('form')[1];form.findByType('select').props.onChange({target:{value:payoutReference}});const inputs=form.findAllByType('input');inputs[0].props.onChange({target:{value:'2026-09-26'}});inputs[1].props.onChange({target:{value:'twd'}});inputs[2].props.onChange({target:{value:'TEST-LEDGER-TWD'}});});await act(async()=>tree.root.findAllByType('form')[1].props.onSubmit({preventDefault(){}}));return {tree,onCreated};}
describe('Whole-batch ERP payment approval',()=>{
 beforeEach(()=>{vi.mocked(api.get).mockReset();vi.mocked(api.post).mockReset();vi.mocked(api.get).mockResolvedValue({data:{items:[{payoutReference,status:'PAID',gross:'150',recovery:'20',net:'130'}],nextCursor:null}} as any);vi.mocked(api.post).mockImplementation(async(path)=>({data:path.endsWith('/preview')?preview:{projectionReference}} as any));});
 it('loads business batch references and binds approval to the reviewed full-batch values',async()=>{const {tree,onCreated}=await mount();expect(JSON.stringify(tree.toJSON())).toContain('整批付款淨額');const approval=tree.root.findAllByType('form')[2];await act(async()=>approval.findByType('input').props.onChange({target:{value:'FINANCE-PAYMENT-01'}}));await act(async()=>tree.root.findAllByType('form')[2].props.onSubmit({preventDefault(){}}));expect(api.post).toHaveBeenLastCalledWith('/admin/erp-projections/payment/approve',expect.objectContaining({payoutReference,reviewHash:preview.reviewHash,currency:'TWD',approvalReference:'FINANCE-PAYMENT-01'}));expect(onCreated).toHaveBeenCalledWith(projectionReference);await act(async()=>tree.unmount());});
 it('discards review after batch-period changes',async()=>{const {tree}=await mount();expect(tree.root.findAllByType('form')).toHaveLength(3);await act(async()=>tree.root.findAllByType('input')[0].props.onChange({target:{value:'2026-09-11T00:00'}}));expect(tree.root.findAllByType('form')).toHaveLength(1);expect(api.post).toHaveBeenCalledTimes(1);await act(async()=>tree.unmount());});
});
