import {useState} from 'react';
import {Card,ErrorBox,Field} from '../../components/ui';
import {get,post,qs} from '../../lib/api';
import {CompensationAggregateTable} from './ErpCompensationProjectionForm';
type Batch={payoutReference:string;status:string;gross:string;recovery:string;net:string};
type Preview={existingProjectionReference?:string|null;reviewHash:string;drillbackHash:string;expected:{paymentEvidence?:{confirmedLines:number;pendingLines:number};aggregates:{metric:string;economicCategory:string;payoutReference:string|null;amount:string;sourceCount:number}[];totals:{memberPayableGross:string;payoutRecoveryOffset:string;payoutNet:string;bankPaid:string}}};
export function ErpPaymentProjectionForm({onCreated}:{onCreated:(reference:string)=>void}){
 const [input,setInput]=useState({periodStart:'',periodEnd:'',payoutReference:'',accountingDate:'',currency:'',currencyBasisReference:'',groupByEconomicCategory:true}),[batches,setBatches]=useState<Batch[]>([]),[loaded,setLoaded]=useState(false),[nextCursor,setNextCursor]=useState<string|null>(null),[preview,setPreview]=useState<Preview|null>(null),[approval,setApproval]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>();
 const range=()=>({periodStart:new Date(input.periodStart).toISOString(),periodEnd:new Date(input.periodEnd).toISOString()});
 const body=()=>({...input,...range()});
 function change(key:keyof typeof input,value:string|boolean){setInput(current=>({...current,[key]:value}));setPreview(null);setApproval('');if(key==='periodStart'||key==='periodEnd'){setBatches([]);setLoaded(false);setNextCursor(null);setInput(current=>({...current,payoutReference:''}));}}
 async function load(cursor?:string){setBusy(true);setError(undefined);try{const result=await get<{data:{items:Batch[];nextCursor:string|null}}>('/admin/erp-projections/payment/batches'+qs({...range(),cursor,take:25}));setBatches(current=>cursor?[...current,...result.data.items]:result.data.items);setNextCursor(result.data.nextCursor);setLoaded(true);}catch(value){setError(value);}finally{setBusy(false);}}
 return <Card title="整批付款會計投影"><p>以付款批次完整金額對帳。毛額可依獎金類別彙總；回收抵扣、淨額及銀行已付不分攤到獎金週期或個別獎金類別。</p><ErrorBox error={error}/>
  <form onSubmit={event=>{event.preventDefault();void load();}}><fieldset disabled={busy}><div className="filter-grid"><Field label="付款批次期間開始（本機時區）"><input required type="datetime-local" value={input.periodStart} onChange={event=>change('periodStart',event.target.value)}/></Field><Field label="付款批次期間結束（本機時區）"><input required type="datetime-local" value={input.periodEnd} onChange={event=>change('periodEnd',event.target.value)}/></Field></div><button type="submit">載入付款批次</button></fieldset></form>
  {loaded&&!batches.length&&<p>此付款批次期間尚無批次。</p>}
  {!!batches.length&&<form onSubmit={async event=>{event.preventDefault();setBusy(true);setError(undefined);setPreview(null);try{setPreview((await post<{data:Preview}>('/admin/erp-projections/payment/preview',body())).data);}catch(value){setError(value);}finally{setBusy(false);}}}><fieldset disabled={busy}><Field label="付款批次"><select required value={input.payoutReference} onChange={event=>change('payoutReference',event.target.value)}><option value="">選擇批次</option>{batches.map(batch=><option key={batch.payoutReference} value={batch.payoutReference}>{batch.payoutReference} · 毛額 {batch.gross}／抵扣 {batch.recovery}／淨額 {batch.net}</option>)}</select></Field>{nextCursor&&<button type="button" onClick={()=>void load(nextCursor)}>載入更多批次</button>}<div className="filter-grid"><Field label="付款投影會計日期"><input required type="date" value={input.accountingDate} onChange={event=>change('accountingDate',event.target.value)}/></Field><Field label="付款投影帳務幣別"><input required pattern="[A-Z]{3}" maxLength={3} value={input.currency} onChange={event=>change('currency',event.target.value.toUpperCase())}/></Field><Field label="付款帳務幣別核准依據"><input required pattern="[A-Za-z0-9][A-Za-z0-9._:/-]{7,99}" value={input.currencyBasisReference} onChange={event=>change('currencyBasisReference',event.target.value)}/></Field></div><label><input type="checkbox" checked={input.groupByEconomicCategory} onChange={event=>change('groupByEconomicCategory',event.target.checked)}/>毛額依獎金類別分組</label><button type="submit">預覽完整付款批次</button><p>須有獨立財務與稽核核准，以及可驗證的原始匯出證據。此處不換匯或發起付款。</p></fieldset></form>}
  {preview&&<>{preview.existingProjectionReference&&<p>已有封存版本；後續變更請建立補充快照。<button type="button" onClick={()=>onCreated(preview.existingProjectionReference!)}>查看最新封存版本</button></p>}<h3>付款投影審閱</h3>{preview.expected.paymentEvidence&&<p>銀行完整確認 {preview.expected.paymentEvidence.confirmedLines} 筆；尚待完整確認 {preview.expected.paymentEvidence.pendingLines} 筆。沒有回覆不等於已確認零元。</p>}<CompensationAggregateTable rows={preview.expected.aggregates}/><p>審閱 hash：{preview.reviewHash}</p><p>來源 hash：{preview.drillbackHash}</p>{!preview.existingProjectionReference&&<form onSubmit={async event=>{event.preventDefault();setBusy(true);setError(undefined);try{const result=await post<{data:{projectionReference:string}}>('/admin/erp-projections/payment/approve',{...body(),reviewHash:preview.reviewHash,approvalReference:approval});setPreview(null);setApproval('');onCreated(result.data.projectionReference);}catch(value){setError(value);}finally{setBusy(false);}}}><Field label="付款投影核准單號"><input required pattern="[A-Za-z0-9][A-Za-z0-9._:/-]{7,99}" value={approval} onChange={event=>setApproval(event.target.value)}/></Field><button type="submit" disabled={busy}>核准並封存付款投影</button><p>封存不代表 ERP 已過帳；銀行回覆變更會使尚未核准的預覽失效。</p></form>}</>}
 </Card>;
}
