import {Link,NavLink,Route,Routes} from 'react-router-dom';
import {useEffect,useState} from 'react';
import {useQualification} from './QualificationContext';
import {displayRank,getDashboard} from './memberData';
import type {Dashboard} from './api';

function ContextBar(){const {qualifications,current,select}=useQualification();return <section className="context"><span>目前資格</span><select value={current?.id||''} onChange={e=>select(e.target.value)}>{qualifications.map(q=><option key={q.id} value={q.id}>{q.code}｜{displayRank(q.rank)}｜{q.ballLabel}</option>)}</select><small>組織、業績與獎金依此資格獨立顯示</small></section>}
function Home(){const {current}=useQualification();const [d,setD]=useState<Dashboard|null>(null);useEffect(()=>{if(current)getDashboard(current).then(setD)},[current]);if(!d)return <p className="loading">資料載入中…</p>;return <><ContextBar/><section className="hero"><h2>您好，{d.memberName}</h2><p>{d.memberNo} · {displayRank(d.qualification.rank)}</p></section><section className="grid"><article><span>本月重購</span><strong>{d.monthlyRepurchaseStatus==='ACTIVE'?'已啟用':'未啟用'}</strong></article><article><span>PV</span><strong>{d.pv??'—'}</strong></article><article><span>RPV</span><strong>{d.rpv??'—'}</strong></article><article><span>EPV</span><strong>{d.epv??'—'}</strong></article></section><section className="card"><span>本期獎金</span><h2>{d.bonusAmount===null?'結算中':`NT$ ${d.bonusAmount.toLocaleString()}`}</h2><small>{d.bonusStatus} · 未完成正式結算時不顯示假 NT$0</small></section><h3>快速服務</h3><section className="actions"><Link to="/organization">我的組織</Link><Link to="/performance">我的業績</Link><Link to="/bonuses">獎金明細</Link><Link to="/shop">商品商城</Link><Link to="/orders">我的訂單</Link><Link to="/me">會員資料</Link></section></>}
const Page=({title,children}:{title:string;children:string})=><><ContextBar/><section className="page card"><h2>{title}</h2><p>{children}</p></section></>;
export default function App(){const {loading}=useQualification();if(loading)return <main className="loading">資格資料載入中…</main>;return <div className="app"><header><div><b>UCell</b><small>會員中心</small></div><span className="badge">R1.0B</span></header><main><Routes><Route path="/" element={<Home/>}/><Route path="/organization" element={<Page title="我的組織">Sponsor Tree 與 Binary Tree 將分頁呈現，禁止混用組織語意。</Page>}/><Route path="/performance" element={<Page title="我的業績">顯示目前資格的 PV、RPV、EPV 與結算週期，不跨球合併。</Page>}/><Route path="/bonuses" element={<Page title="獎金明細">僅顯示核心獎金引擎回傳之正式狀態與金額，前端不自行計算。</Page>}/><Route path="/shop" element={<Page title="商品商城">商品、價格與訂單入口；庫存與會計責任未來由 ERP 邊界承接。</Page>}/><Route path="/orders" element={<Page title="我的訂單">訂單、付款、履約與退貨狀態將依 API 事件呈現。</Page>}/><Route path="/me" element={<Page title="我的">Person 層級會員資料與 1:N 資格清單。</Page>}/></Routes></main><nav><NavLink to="/">首頁</NavLink><NavLink to="/organization">組織</NavLink><NavLink to="/shop">商城</NavLink><NavLink to="/bonuses">獎金</NavLink><NavLink to="/me">我的</NavLink></nav></div>}
