import {useRef,useState,type FormEvent} from 'react';
import {updateDeliveryProfile,type DeliveryProfile} from './memberData';

export default function DeliveryProfileEditor({profile,refresh}:{profile:DeliveryProfile;refresh:()=>void}){
 const [recipientName,setRecipientName]=useState(profile.recipientName??''),[phone,setPhone]=useState(profile.phone??''),[countryCode,setCountryCode]=useState(profile.countryCode??'TW'),[postalCode,setPostalCode]=useState(profile.postalCode??''),[region,setRegion]=useState(profile.region??''),[city,setCity]=useState(profile.city??''),[address,setAddress]=useState(profile.address??''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const pending=useRef<{body:string;key:string}|null>(null),flight=useRef(false);
 async function submit(event:FormEvent){event.preventDefault();if(flight.current)return;const input={recipientName:recipientName.trim(),phone:phone.trim(),countryCode:countryCode.trim().toUpperCase(),...(postalCode.trim()?{postalCode:postalCode.trim()}:{}),region:region.trim(),city:city.trim(),address:address.trim()};if(!input.recipientName||!/^\+?[0-9 ()-]{6,32}$/.test(input.phone)||!/[0-9]/.test(input.phone)||!/^[A-Z]{2}$/.test(input.countryCode)||!input.region||!input.city||input.address.length<5){setError('請完整填寫收件人、電話與配送地址');return;}const body=JSON.stringify(input);if(pending.current?.body!==body)pending.current={body,key:crypto.randomUUID()};flight.current=true;setBusy(true);setError('');try{await updateDeliveryProfile(input,pending.current.key);pending.current=null;refresh();}catch(reason){setError(reason instanceof Error?reason.message:'配送資料更新失敗，請保留資料重試');}finally{flight.current=false;setBusy(false);}}
 return <form className="card" onSubmit={submit}><h3>{profile.complete?'更新配送資料':'結帳前請完成配送資料'}</h3><p>配送資料與正式會員升級分開處理；完成地址不會建立或變更經營資格。</p><label>收件人姓名<input value={recipientName} maxLength={80} autoComplete="name" onChange={e=>setRecipientName(e.target.value)} disabled={busy}/></label><label>聯絡電話<input value={phone} type="tel" maxLength={32} autoComplete="tel" onChange={e=>setPhone(e.target.value)} disabled={busy}/></label><label>國家代碼<input value={countryCode} maxLength={2} onChange={e=>setCountryCode(e.target.value)} disabled={busy}/></label><label>郵遞區號<input value={postalCode} maxLength={16} autoComplete="postal-code" onChange={e=>setPostalCode(e.target.value)} disabled={busy}/></label><label>縣市／區域<input value={region} maxLength={80} onChange={e=>setRegion(e.target.value)} disabled={busy}/></label><label>城市／鄉鎮<input value={city} maxLength={80} onChange={e=>setCity(e.target.value)} disabled={busy}/></label><label>配送地址<textarea value={address} maxLength={300} autoComplete="street-address" onChange={e=>setAddress(e.target.value)} disabled={busy}/></label>{error&&<p role="alert">{error}</p>}<button disabled={busy}>{busy?'儲存中…':'儲存配送資料'}</button></form>;
}
