import {useRef,useState} from 'react';
import {useSearchParams} from 'react-router-dom';
import {MemberPageHeader} from './MemberPageHeader';
import {getEvents} from './memberData';
import {memberApi as api} from './memberApi';
import {useResource} from './useResource';
import {safeLearningUrl} from './LearningCenter';
import {ErrorState,LoadingState,EmptyState} from '@ucell/design-system';
const state=(value:string)=>({AVAILABLE:'可查看',REGISTERED:'已報名',CANCELLED:'已取消',CHECKED_IN:'已報到',ATTENDED:'已確認出席',EVENT_REGISTERED:'完成報名',EVENT_REGISTRATION_CANCELLED:'取消報名',EVENT_CHECKED_IN:'完成報到',EVENT_ATTENDED:'確認出席'}[value]??'狀態待確認');
const format=(value:string)=>new Date(value).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'});
const type=(value:string)=>({ONLINE:'線上活動',OFFLINE:'實體活動',HYBRID:'線上及實體活動'}[value]??'活動');
type Detail={eventCode:string;title:string;description:string|null;eventType:string;eventStatus:string;version:number;startsAt:string;endsAt:string;locationReference:string|null;onlineJoinReference:string|null;capacity:number|null;status:string;canRegister:boolean;canCancel:boolean;canIssueCredential:boolean;history:{eventType:string;occurredAt:string;version:number;origin:string}[]};
export default function EventCenter(){const [params,setParams]=useSearchParams(),selected=params.get('event'),s=useResource('events',getEvents);if(selected)return <EventDetail key={selected} code={selected} back={()=>setParams({})}/>;return <><MemberPageHeader title="活動中心"/><p className="uc-page-intro">查看活動、管理報名及取得私人報到憑證。日期皆以臺北時間顯示。</p>{s.error?<ErrorState message={s.error} retry={s.retry}/>:!s.data?<LoadingState/>:s.data.length?s.data.map(e=><article className="card" key={e.eventCode}><h3>{e.title}</h3><p>{e.description??'活動說明尚未提供'}</p><p>{type(e.eventType)} · {format(e.startsAt)} · {state(e.status)}</p><button onClick={()=>setParams({event:e.eventCode})}>查看活動</button></article>):<EmptyState title="目前沒有可參加的活動"/>}</>}
function EventDetail({code,back}:{code:string;back:()=>void}){
 const valid=/^[A-Z][A-Z0-9_-]{2,39}$/.test(code),path=`/member/events/${encodeURIComponent(code)}`,s=useResource(`event:${code}`,signal=>api<Detail>(path,{signal}),valid);
 const [token,setToken]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),keys=useRef(new Map<string,string>()),flight=useRef(false);
 async function command(action:string){if(flight.current)return;flight.current=true;setBusy(true);setError('');setNotice('');const key=keys.current.get(action)??crypto.randomUUID();keys.current.set(action,key);try{const result=await api<{checkInToken?:string}>(`${path}/${action}`,{method:'POST',headers:{'Idempotency-Key':key}});keys.current.delete(action);setToken(result.checkInToken&&/^[A-Za-z0-9_-]{43}$/.test(result.checkInToken)?result.checkInToken:'');setNotice(action==='cancel'?'已取消報名。':action==='credential'?'已更新報到憑證，舊憑證已失效。':'活動報名已完成。');s.retry();}catch(e){if((e as {status?:number}).status===409)keys.current.delete(action);setError(e instanceof Error?e.message:'操作失敗，請重試。');}finally{flight.current=false;setBusy(false);}}
 const d=s.data,join=d?.onlineJoinReference?safeLearningUrl(d.onlineJoinReference):null;
 return <><button onClick={back}>返回活動列表</button>{!valid?<ErrorState message="活動代碼格式不正確"/>:s.error?<ErrorState message={s.error} retry={s.retry}/>:!d?<LoadingState/>:<><MemberPageHeader title={d.title}/><p>{d.description}</p><p>{d.eventCode} · 第 {d.version} 版 · {type(d.eventType)} · {state(d.status)}</p><p>{format(d.startsAt)} 至 {format(d.endsAt)}（臺北時間）</p><p>名額：{d.capacity??'未設人數上限'}</p>{d.locationReference&&<p>地點：{d.locationReference}</p>}{join&&<a href={join} target="_blank" rel="noopener noreferrer">進入線上活動（另開視窗）</a>}{d.eventStatus==='ARCHIVED'&&<p>活動已封存，保留您的參與紀錄。</p>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{d.canRegister&&<button disabled={busy} onClick={()=>void command('register')}>報名活動</button>}{d.canCancel&&<button disabled={busy} onClick={()=>void command('cancel')}>取消報名</button>}{d.canIssueCredential&&<section className="card"><h3>私人報到憑證</h3><p>請向活動工作人員出示。憑證只顯示於目前頁面，離開後可重新取得；重新取得會讓舊憑證失效。</p>{token&&<output aria-label="報到憑證" style={{display:'block',overflowWrap:'anywhere'}}>{token}</output>}<button disabled={busy} onClick={()=>void command('credential')}>{token?'更新報到憑證':'取得報到憑證'}</button></section>}<h3>我的參與紀錄</h3>{d.history.length?<ol>{d.history.map((h,i)=><li key={i}>{state(h.eventType)} · {format(h.occurredAt)} · 第 {h.version} 版{h.origin==='LEGACY_SNAPSHOT'?'（既有紀錄）':''}</li>)}</ol>:<p>尚無報名紀錄。</p>}</>}</>;
}
