import {useRef,useState} from 'react';
import {ErrorState,LoadingState} from '@ucell/design-system';
import {consentFormalContract,getFormalRequiredContracts,saveFormalDraft} from './memberData';
import {useResource} from './useResource';

export default function FormalUpgrade(){
 const contracts=useResource('formal-contracts',getFormalRequiredContracts),[accepted,setAccepted]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState<{version:number;nationalIdMasked:string;bankAccountMasked:string}|null>(null),key=useRef(crypto.randomUUID());
 const [form,setForm]=useState({legalName:'',gender:'',birthDate:'',nationalId:'',communicationAddress:'',phone:'',email:'',bankCode:'',bankAccount:'',accountHolder:''});
 if(contracts.error)return <ErrorState message={contracts.error} retry={contracts.retry}/>;if(!contracts.data)return <LoadingState/>;const contract=contracts.data[0];if(!contract)return <section className="card"><h3>升級正式會員</h3><p>正式會員合約與隱私告知尚未完成正式配置，因此目前無法建立申請草稿。</p></section>;
 const set=(name:keyof typeof form,value:string)=>setForm(current=>({...current,[name]:value}));
 async function submit(event:React.FormEvent){event.preventDefault();if(!accepted||busy)return;setBusy(true);setError('');try{if(!contract.acceptedAt)await consentFormalContract(contract.id,key.current);const result=await saveFormalDraft({formalContractVersionId:contract.id,...form},key.current);setSaved(result);key.current=crypto.randomUUID();contracts.retry();}catch(reason){setError(reason instanceof Error?reason.message:'草稿儲存失敗');}finally{setBusy(false);}}
 return <form className="card" onSubmit={submit}><h3>升級正式會員：加密草稿</h3><p>目前只保存加密草稿，不會送審、核准、建立球位或改變會員狀態。身分證與存摺檔案須等待私有儲存及掃毒政策完成。</p><details><summary>{contract.title}（{contract.version}）</summary><p>{contract.content}</p><small>內容雜湊：{contract.contentHash}</small></details><label><input type="checkbox" checked={accepted||!!contract.acceptedAt} disabled={!!contract.acceptedAt||busy} onChange={e=>setAccepted(e.target.checked)}/> 我已閱讀並同意上述正式會員合約與隱私告知</label>
 <label>姓名<input required maxLength={120} autoComplete="name" value={form.legalName} onChange={e=>set('legalName',e.target.value)}/></label><label>性別<input required maxLength={32} value={form.gender} onChange={e=>set('gender',e.target.value)}/></label><label>出生年月日<input required type="date" value={form.birthDate} onChange={e=>set('birthDate',e.target.value)}/></label><label>身分證號<input required maxLength={32} autoComplete="off" value={form.nationalId} onChange={e=>set('nationalId',e.target.value)}/></label><label>通訊地址<textarea required maxLength={500} autoComplete="street-address" value={form.communicationAddress} onChange={e=>set('communicationAddress',e.target.value)}/></label><label>電話<input required maxLength={32} autoComplete="tel" value={form.phone} onChange={e=>set('phone',e.target.value)}/></label><label>Email<input required type="email" maxLength={254} autoComplete="email" value={form.email} onChange={e=>set('email',e.target.value)}/></label><label>銀行別／代碼<input required maxLength={16} value={form.bankCode} onChange={e=>set('bankCode',e.target.value)}/></label><label>銀行帳號<input required maxLength={34} autoComplete="off" value={form.bankAccount} onChange={e=>set('bankAccount',e.target.value)}/></label><label>帳戶名<input required maxLength={120} value={form.accountHolder} onChange={e=>set('accountHolder',e.target.value)}/></label>
 <button className="primary" disabled={busy||!(accepted||!!contract.acceptedAt)}>{busy?'加密儲存中…':'儲存加密草稿'}</button>{saved&&<p role="status">已保存第 {saved.version} 版草稿；身分證 {saved.nationalIdMasked}，帳號 {saved.bankAccountMasked}。</p>}{error&&<p role="alert">{error}</p>}</form>;
}