import {Link} from 'react-router-dom';
import {MemberPageHeader} from './MemberPageHeader';
import {getGrowth} from './memberData';
import {useResource} from './useResource';
import {ErrorState,LoadingState,MetricCard} from '@ucell/design-system';
const rank=(code:string)=>({NEW_STAR:'新星',EXCELLENCE:'卓越',GLORY:'榮耀',DIAMOND:'鑽石',CROWN:'皇冠'}[code]??'階級待確認');
const state=(code:string)=>({DRAFT:'草稿',PENDING:'待啟用',EFFECTIVE:'已生效',ACTIVE:'有效',INACTIVE:'未啟用',SUSPENDED:'已暫停',TERMINATED:'已終止',NONE:'尚無有效訂閱',ENROLLED:'已報名',STARTED:'學習中',COMPLETED:'已完成',CANCELLED:'已取消',REGISTERED:'已報名',CHECKED_IN:'已報到',ATTENDED:'已確認出席',COURSE_ENROLLED:'加入課程',COURSE_STARTED:'開始學習',COURSE_COMPLETED:'完成課程',ASSESSMENT_COMPLETED:'完成評量',EVENT_REGISTERED:'活動報名',EVENT_REGISTRATION_CANCELLED:'取消活動報名',EVENT_CHECKED_IN:'活動報到',EVENT_ATTENDED:'活動出席確認'}[code]??'狀態待確認');
const plan=(code:string)=>({MEMBER:'會員',STARTER:'啟航',ELITE:'菁英',LEADER:'領袖'}[code]??'方案待確認');
const time=(value:string|null)=>value?new Date(value).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'}):'尚無';
export default function GrowthCenter(){
 const s=useResource('my-growth',getGrowth);if(s.error)return <ErrorState message={s.error} retry={s.retry}/>;if(!s.data)return <LoadingState/>;const d=s.data.dimensions;
 return <><MemberPageHeader title="我的成長"/><p className="uc-page-intro">每個面向取自伺服器紀錄，分開呈現。資料時間：{time(s.data.asOf)}。</p><section className="uc-metric-grid"><MetricCard label="目前 Active 資格" value={d.active.activeQualificationCount}/><MetricCard label="直推資格" value={d.organization.directQualifiedCount}/><MetricCard label="完成課程" value={d.learning.completedCount}/><MetricCard label="已確認出席活動" value={d.events.attendedCount}/></section>
 <section className="card"><h3>我的資格</h3>{d.qualification.items.length?<ul>{d.qualification.items.map(q=><li key={q.qualificationNo}>{q.ballNo??q.qualificationNo} · {plan(q.planLevelCode)} · {state(q.status)}</li>)}</ul>:<p>尚無經營資格；仍可查看本人符合資格的課程與活動。</p>}<Link to="/me">查看會員資料</Link></section>
 <section className="card"><h3>Active 有效區間</h3><p>目前 {d.active.activeQualificationCount}／{d.active.totalQualificationCount} 個資格處於 Active 區間。</p>{d.active.items.map(q=><p key={q.qualificationNo}>資格 {q.qualificationNo}：{q.active?'目前 Active':'目前非 Active'}{q.active&&<>，自 {time(q.activeFrom)} 至 {q.activeTo?time(q.activeTo):'未設定到期時間'}</>}</p>)}<p>狀態依伺服器的有效區間判斷，到期時間不包含在區間內。</p></section>
 <section className="card"><h3>全球階級與組織</h3>{d.globalRank.achieved.length?<ul>{d.globalRank.achieved.map((r,index)=><li key={index}>資格 {r.qualificationNo} · {rank(r.rankCode)} · 達成於 {time(r.achievedAt)}</li>)}</ul>:<p>尚無已達成的全球階級紀錄。</p>}<p>下一階：{d.globalRank.nextAchievement.reason}</p><p>目前有效直推資格：{d.organization.directQualifiedCount}。此數量不代表其他會員的業績或私人資料。</p></section>
 <section className="card"><h3>重購訂閱</h3>{d.repurchase.items.length?d.repurchase.items.map(q=><p key={q.qualificationNo}>資格 {q.qualificationNo}：{state(q.status)}{q.endMonth&&<>，訂閱迄月 {new Date(q.endMonth).toISOString().slice(0,7)}</>}</p>):<p>尚無資格的訂閱資料。</p>}<p>訂閱狀態不等同每期已完成認列。</p>{d.qualification.items.length>0&&<Link to="/orders">查看我的訂單</Link>}</section>
 <section className="card"><h3>學習成長</h3><p>本人全部紀錄：{d.learning.enrolledCount} 門已加入，{d.learning.completedCount} 門已完成。</p><p>下列最多顯示最近 {s.data.coverage.itemLimit} 筆。</p><ul>{d.learning.items.map(c=><li key={c.courseCode}><Link to={'/learning?course='+encodeURIComponent(c.courseCode)}>{c.title}</Link> · {state(c.status)}{c.completedAt&&<> · 完成於 {time(c.completedAt)}</>}</li>)}</ul><Link to="/learning">前往教育訓練</Link></section>
 <section className="card"><h3>活動參與</h3><p>本人全部紀錄：{d.events.upcomingRegisteredCount} 場即將參加，{d.events.checkedInCount} 場已報到尚未確認出席，{d.events.attendedCount} 場已確認出席。</p><p>已報到不會計入已確認出席；已封存活動不列入即將參加。下列最多顯示最近 {s.data.coverage.itemLimit} 筆。</p><ul>{d.events.items.map(e=><li key={e.eventCode}><Link to={'/events?event='+encodeURIComponent(e.eventCode)}>{e.title}</Link> · {state(e.status)} · {time(e.startsAt)}</li>)}</ul><Link to="/events">前往活動中心</Link></section>
 <section className="card"><h3>最近成長紀錄</h3>{s.data.milestones.length?<ol>{s.data.milestones.map((m,index)=><li key={index}>{state(m.type)} · {m.title} · {time(m.occurredAt)} {/^\/(learning\?course|events\?event)=[A-Z][A-Z0-9_-]{2,39}$/.test(m.link)&&<Link to={m.link}>查看紀錄</Link>}</li>)}</ol>:<p>尚無學習或活動里程碑。</p>}<p>最多顯示最近 {s.data.coverage.milestoneLimit} 筆已保存的紀錄。</p></section></>;
}
