import {EmptyState,ErrorState,LoadingState} from '@ucell/design-system';
import {useRef,useState} from 'react';
import DeliveryProfileEditor from './DeliveryProfileEditor';
import {createPackageOrder,getDeliveryProfile,getPackageProducts,getQualificationPackages,getRepresentedLegalEntities,resolveSponsorCandidate,getFormalEnrollment,payEnrollmentPackage,payStageCommerceOrder,type PackageOffer} from './memberData';
import {useResource} from './useResource';
import {pendingSponsorCandidate} from './liff';

export default function QualificationPackageShop({onCreated}:{onCreated:()=>void}){
 const packages=useResource('qualification-packages',getQualificationPackages);
 const legalEntities=useResource('represented-legal-entities',getRepresentedLegalEntities);
 const [selected,setSelected]=useState<PackageOffer|null>(null),[legalEntityId,setLegalEntityId]=useState('');
 if(selected)return <PackageSelection offer={selected} legalEntityId={legalEntityId||undefined} onCancel={()=>setSelected(null)} onCreated={onCreated}/>;
 return <><h2>會員資格套組</h2><p>選擇套組 → 選滿主商品 → 完成配送資料與付款 → 填寫正式會員申請。</p><p>可混選或重複選購五項主商品；啟航 3 盒、菁英 9 盒、領袖 15 盒。套組金額以目前上架價格為準。</p>
 {legalEntities.error?<ErrorState message={legalEntities.error} retry={legalEntities.retry}/>:!legalEntities.data?<LoadingState label="法人代表權載入中…"/>:<section className="card"><h3>購買資格主體</h3><label>以何者名義取得新球<select value={legalEntityId} onChange={e=>setLegalEntityId(e.target.value)}><option value="">本人</option>{legalEntities.data.map(entity=><option key={entity.legalEntityId} value={entity.legalEntityId}>{entity.registeredName} · {entity.memberNo}</option>)}</select></label>{legalEntityId&&<p className="muted">此球與後續組織權利將屬於所選法人；您是目前授權代表人，不是法人球位的個人持有人。</p>}</section>}
 {packages.error?<ErrorState message={packages.error} retry={packages.retry}/>:!packages.data?<LoadingState label="套組載入中…"/>:!packages.data.length?<EmptyState title="目前沒有可申請的正式會員套組"/>:<div className="mall-offer-grid">{packages.data.map(item=><article className="card" key={item.packageVersionId}><h3>{item.displayName}</h3><p>套組價格：{item.currency} {item.priceAmount}</p><p>可選 {item.selectableProductQuantity} 盒主商品</p><button disabled={!legalEntities.data||!!legalEntities.error} onClick={()=>setSelected(item)}>選擇套組商品</button></article>)}</div>}
 </>;
}

export function PackageSelection({offer,onCancel,onCreated,targetQualificationId,legalEntityId}:{offer:PackageOffer;onCancel:()=>void;onCreated:()=>void;targetQualificationId?:string;legalEntityId?:string}){
 const enrollment=useResource('package-enrollment-payment',getFormalEnrollment);
 const delivery=useResource('delivery-profile',getDeliveryProfile);
 const pool=useResource(`qualification-package:${offer.packageVersionId}`,signal=>getPackageProducts(offer.packageVersionId,signal));
 const [quantities,setQuantities]=useState<Record<string,number>>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[receipt,setReceipt]=useState<{id:string;qualificationId:string;total:string;paid:boolean}|null>(null);
 const [sponsorCode,setSponsorCode]=useState(()=>pendingSponsorCandidate()??'');
 const validSponsor=/^[A-Z][A-Z0-9_-]{1,39}$/.test(sponsorCode),sponsor=useResource(`sponsor-candidate:${sponsorCode}`,signal=>resolveSponsorCandidate(sponsorCode,signal),Boolean(sponsorCode)&&validSponsor);
 const pending=useRef<{body:string;key:string}|null>(null),flight=useRef(false);
 const count=Object.values(quantities).reduce((sum,value)=>sum+value,0);
 function change(id:string,next:number,min:number|null,max:number|null,increment:number){if(flight.current)return;const floor=min??0,ceiling=max??offer.selectableProductQuantity,current=quantities[id]??0;let value=next<=0||current>0&&next<floor?0:next;if(value>0&&value<floor)value=Math.ceil(floor/increment)*increment;if(value>ceiling||value%increment!==0)return;setQuantities(previous=>({...previous,[id]:value}));pending.current=null;setError('');setReceipt(null);}
 async function submit(){const selections=Object.entries(quantities).filter(([,quantity])=>quantity>0).sort(([a],[b])=>a.localeCompare(b)).map(([productRuleProfileId,quantity])=>({productRuleProfileId,quantity}));if(flight.current||receipt||count!==offer.selectableProductQuantity||!delivery.data?.complete||sponsorCode&&!sponsor.data)return;const body=JSON.stringify({packageVersionId:offer.packageVersionId,targetQualificationId,legalEntityId,sponsorCode,selections});if(pending.current?.body!==body)pending.current={body,key:crypto.randomUUID()};flight.current=true;setBusy(true);setError('');try{const paymentState=!legalEntityId?await getFormalEnrollment():null;const order=await createPackageOrder(offer.packageVersionId,selections,pending.current.key,targetQualificationId,legalEntityId,sponsorCode||undefined);if(paymentState?.stagePaymentEnabled){if(offer.membershipEffect==='FORMAL_ELIGIBILITY'&&!targetQualificationId)await payEnrollmentPackage(order.id,pending.current.key);else if(offer.packageClass==='ACTIVE_DURATION')await payStageCommerceOrder(order.id,pending.current.key);}setReceipt({id:order.id,qualificationId:order.qualificationId,total:order.total,paid:!!paymentState?.stagePaymentEnabled&&(offer.membershipEffect==='FORMAL_ELIGIBILITY'&&!targetQualificationId||offer.packageClass==='ACTIVE_DURATION')});pending.current=null;onCreated();}catch(e){setError(e instanceof Error?e.message:'建立套組訂單失敗，請保留選擇後重試');}finally{flight.current=false;setBusy(false);}}
 if(pool.error)return <section className="card"><ErrorState message={pool.error} retry={pool.retry}/><button onClick={onCancel}>返回套組清單</button></section>;
 if(!pool.data)return <LoadingState label="套組商品載入中…"/>;
 return <section className="card"><h3>{offer.displayName} · 商品選擇</h3><p role="status" aria-live="polite">已選 {count}／{offer.selectableProductQuantity} 盒主商品</p><p>可混選不同商品，也可重複選同一商品。{count<offer.selectableProductQuantity?`還需選擇 ${offer.selectableProductQuantity-count} 盒。`:"已選滿，請確認配送資料後結帳。"}</p><label>推薦碼（選填）<input value={sponsorCode} maxLength={40} onChange={event=>{setSponsorCode(event.target.value.trim().toUpperCase());pending.current=null;}} placeholder="例如 A001286"/></label>{sponsorCode&&!validSponsor&&<p role="alert">推薦碼格式不正確。</p>}{sponsorCode&&validSponsor&&!sponsor.data&&!sponsor.error&&<p>正在核驗推薦碼…</p>}{sponsor.error&&<p role="alert">{sponsor.error}</p>}{sponsor.data&&<p>{sponsor.data.kind==='COMPANY_ALIAS'?`已核准推薦：${sponsor.data.displayLabel}`:`已核准推薦球：${sponsor.data.sponsorBallNo}（${sponsor.data.planLevelCode}）`}。建立訂單時仍會重新驗證並封存；不顯示推薦人個資。</p>}<div className="mall-offer-grid">{pool.data.products.map(product=>{const quantity=quantities[product.productRuleProfileId]??0,increment=product.selectionIncrement;return <article className="card" key={product.productRuleProfileId}><h4>{product.displayName}</h4>{/^TIP-(363|580|696|777|999)$/.test(product.sku)&&<img className="mall-product-cover" src={`/products/${product.sku.toLowerCase()}.png`} alt={product.displayName+" 商品圖"} loading="lazy"/>}<p>{product.available?'可選購':'目前不可選購'}</p><div className="quantity"><button disabled={busy||quantity<=0} onClick={()=>change(product.productRuleProfileId,quantity-increment,product.minQty,product.maxQty,increment)}>減少</button><output>{quantity}</output><button disabled={busy||!product.available||count+increment>offer.selectableProductQuantity||(product.maxQty!==null&&quantity+increment>product.maxQty)} onClick={()=>change(product.productRuleProfileId,quantity+increment,product.minQty,product.maxQty,increment)}>增加</button></div></article>;})}</div>{delivery.error?<ErrorState message={delivery.error} retry={delivery.retry}/>:!delivery.data?<LoadingState label="配送資料載入中…"/>:<DeliveryProfileEditor profile={delivery.data} refresh={delivery.retry}/>}<p>應付金額將由伺服器建立訂單後確認；建立訂單不代表付款、資格生效或業績認列。</p><button disabled={busy||!!receipt||count!==offer.selectableProductQuantity||!delivery.data?.complete||Boolean(sponsorCode)&&!sponsor.data} onClick={submit}>{busy?'處理中…':enrollment.data?.stagePaymentEnabled&&!targetQualificationId&&!legalEntityId&&offer.membershipEffect==='FORMAL_ELIGIBILITY'?'選購套組並完成 Stage 付款':'建立待付款套組訂單'}</button><button disabled={busy} onClick={onCancel}>返回套組清單</button>{error&&<p role="alert">{error}</p>}{receipt&&<section role="status"><h3>{receipt.paid?'Stage 套組付款已通過':'待付款套組訂單已建立'}</h3><p>NT$ {receipt.total}</p><p>{targetQualificationId?'目標資格':'新資格'}已由伺服器確認。{legalEntityId?' 本資格由所選法人持有。':''}</p></section>}</section>;
}
