import {Body,Controller,Get,Param,ParseUUIDPipe,Post,Put,Query,Req,UseGuards} from '@nestjs/common';
import {ApiBearerAuth,ApiOperation,ApiProperty,ApiPropertyOptional,ApiTags} from '@nestjs/swagger';
import {Type} from 'class-transformer';
import {ArrayMaxSize,ArrayMinSize,IsArray,IsBoolean,IsEnum,IsISO8601,IsInt,IsOptional,IsString,IsUUID,Matches,Max,MaxLength,Min,MinLength,ValidateNested} from 'class-validator';
import {MemberAuthenticationGuard} from '../auth/member-authentication.guard';
import {Roles} from '../auth/roles.decorator';
import {PackageConfigService,PackageVersionInput} from './package-config.service';
class CreatePackageProfileDto {@Matches(/^[A-Z0-9_]{2,80}$/) stableCode!:string;@IsEnum(['QUALIFICATION','ACTIVE_DURATION','FUTURE']) packageClass!:'QUALIFICATION'|'ACTIVE_DURATION'|'FUTURE';}
class PackageVersionDto implements PackageVersionInput {@IsString() @MinLength(1) @MaxLength(120) displayName!:string;@Matches(/^[A-Z]{3}$/) currency!:string;@Matches(/^\d{1,16}(\.\d{1,2})?$/) priceAmount!:string;@IsInt() @Min(1) @Max(10000) selectableProductQuantity!:number;@IsString() @MinLength(1) @MaxLength(80) membershipEffect!:string;@IsString() @MinLength(1) @MaxLength(80) qualificationEffect!:string;@IsOptional() @IsString() @MaxLength(40) activeDurationUnit?:string;@IsOptional() @IsInt() @Min(1) @Max(1200) activeDurationValue?:number;@IsBoolean() targetQualificationRequired!:boolean;@IsOptional() @IsString() @MaxLength(200) memberEligibilityPolicyRef?:string;@IsOptional() @IsString() @MaxLength(200) recognitionConfigRef?:string;}
class SelectableProductDto {@ApiProperty({format:'uuid'}) @IsUUID() productRuleProfileId!:string;@ApiPropertyOptional() @IsOptional() @IsInt() @Min(0) minQty?:number;@ApiPropertyOptional() @IsOptional() @IsInt() @Min(1) maxQty?:number;@ApiPropertyOptional() @IsOptional() @IsInt() @Min(1) selectionIncrement?:number;@ApiPropertyOptional() @IsOptional() @IsInt() @Min(0) sortOrder?:number;}
class ProductPoolDto {@ApiProperty({type:[SelectableProductDto]}) @IsArray() @ArrayMinSize(1) @ArrayMaxSize(200) @ValidateNested({each:true}) @Type(()=>SelectableProductDto) products!:SelectableProductDto[];}
class ApprovalDto {@IsString() @MinLength(1) @MaxLength(200) approvalReference!:string;}
class ScheduleDto {@IsISO8601() effectiveFrom!:string;@IsOptional() @IsISO8601() effectiveTo?:string;@IsOptional() @IsISO8601() salesFrom?:string;@IsOptional() @IsISO8601() salesTo?:string;}
class MemberSelectionDto {@IsUUID() productRuleProfileId!:string;@IsInt() @Min(1) @Max(10000) quantity!:number;}
class ValidateSelectionDto {@IsUUID() packageVersionId!:string;@IsOptional() @IsUUID() targetQualificationId?:string;@IsArray() @ArrayMinSize(1) @ArrayMaxSize(200) @ValidateNested({each:true}) @Type(()=>MemberSelectionDto) selections!:MemberSelectionDto[];}
@ApiTags('Admin - Package Configuration') @ApiBearerAuth('adminBearer') @Roles('SUPER_ADMIN','ORDER_OPS','COMPLIANCE_AUDIT','PACKAGE_CONFIG_MANAGE','PACKAGE_CONFIG_APPROVE') @Controller('admin/packages')
export class AdminPackageConfigController {constructor(private readonly service:PackageConfigService){}@Get() list(){return this.service.adminList();}@Post() @Roles('SUPER_ADMIN','PACKAGE_CONFIG_MANAGE') create(@Body() b:CreatePackageProfileDto,@Req() r:any){return this.service.createProfile(b,r.user?.personId??r.user?.subject);}@Post(':id/versions') @Roles('SUPER_ADMIN','PACKAGE_CONFIG_MANAGE') add(@Param('id',new ParseUUIDPipe()) id:string,@Body() b:PackageVersionDto,@Req() r:any){return this.service.addVersion(id,b,r.user?.personId??r.user?.subject);}@Put('versions/:id/selectable-products') @Roles('SUPER_ADMIN','PACKAGE_CONFIG_MANAGE') products(@Param('id',new ParseUUIDPipe()) id:string,@Body() b:ProductPoolDto){return this.service.setProducts(id,b.products);}@Post('versions/:id/approve') @Roles('SUPER_ADMIN','PACKAGE_CONFIG_APPROVE') approve(@Param('id',new ParseUUIDPipe()) id:string,@Body() b:ApprovalDto,@Req() r:any){return this.service.approve(id,b.approvalReference,r.user?.personId??r.user?.subject);}@Post('versions/:id/schedule') @Roles('SUPER_ADMIN','PACKAGE_CONFIG_APPROVE') schedule(@Param('id',new ParseUUIDPipe()) id:string,@Body() b:ScheduleDto){return this.service.schedule(id,b);}@Post('versions/:id/activate') @Roles('SUPER_ADMIN','PACKAGE_CONFIG_APPROVE') activate(@Param('id',new ParseUUIDPipe()) id:string){return this.service.activate(id);}@Post('versions/:id/retire') @Roles('SUPER_ADMIN','PACKAGE_CONFIG_APPROVE') retire(@Param('id',new ParseUUIDPipe()) id:string){return this.service.retire(id);}}
@ApiTags('Member - Packages') @ApiBearerAuth('memberBearer') @UseGuards(MemberAuthenticationGuard) @Controller('member')
export class MemberPackageController {constructor(private readonly service:PackageConfigService){}@Get('packages') @ApiOperation({operationId:'memberPackages'}) list(@Query('class') packageClass?:string){return this.service.memberList(packageClass);}@Get('packages/:id/products') products(@Param('id',new ParseUUIDPipe()) id:string){return this.service.memberProducts(id);}@Post('package-selections/validate') validate(@Req() r:any,@Body() b:ValidateSelectionDto){return this.service.validateSelection(r.user.personId,b);}}
